### ISSUE TITLE
osc chroot should mount things like /proc /dev and so on

### ISSUE THREAD

**Issue by darix** [openSUSE/osc#100]
similar to issue #95 .... maybe use the build script to drop us into the chroot and let it handle all the mounting and stuff.

especially for debugging the missing /proc and /dev is really annoying.

**Comment by nickbroon** [comment]
This appears to be duplicate of the now resolved #288

**Comment by lethliel** [comment]
This was fixed in https://github.com/openSUSE/osc/pull/291/commits/5726c6633570db89f11e80824acd563c9509de75
