### ISSUE TITLE
0.177.0: osc build fails for url-encoded URLs

### ISSUE THREAD

**Issue by susnux** [openSUSE/osc#1039]
Starting with 0.177 the build of packages fails if the project contains special characters like `c++`.

Error:
```
  File "/usr/lib/python3.8/site-packages/osc/build.py", line 307, in makeurls
    self.urllist.append(url % self.mp)
ValueError: unsupported format character 'B' (0x42) at index 66
```

It happens for e.g. the following URL: `https://download.opensuse.org/repositories/devel:/libraries:/c_c%2B%2B/openSUSE_Factory/`

**Comment by dmach** [comment]
This seems to be fixed based on the previous comment.
Closing.
