### ISSUE TITLE
osc branch in git-based workflow

### ISSUE THREAD

**Issue by mcepl** [openSUSE/osc#1054]
**Is your feature request related to a problem? Please describe.**
When I get SR normal way in OBS (e.g., https://build.opensuse.org/request/show/978673) I see the results of the experimental build in the submitter’s branch. How will it work in the new git-based world? I dimly remember there was some possible way how to use OBS as CI for GitLab requests, wasn’t there? Could I get the results of the OBS run on the GitLab merge request?

**Describe the solution you'd like**
When the submitter has also a package setup with `scmsync`, the branch command could take care of:
* creating new `scmsync` element in the child repository configuration
* setting up the OBS-as-CI for the particular repository.

It would be easier if the repository hosting was some platform with well defined API (one point for GitLab), where the user could have defined in her personal configuration file the namespace where new repositories should be created, and then `osc branch` could create it automatically and setup that CI workflow for merge request.

**Comment by hennevogel** [comment]
Guess you are looking for the [SCM/CI integration](https://openbuildservice.org/help/manuals/obs-user-guide/cha.obs.scm_ci_workflow_integration.html). It supports `obs_scm` service and also `scmsync` attribute.

**Comment by hennevogel** [comment]
@dmach ?

**Comment by adrianschroeter** [comment]
any source operation won't happen in OBS anymore when using scmsync. The given design goal is work package centric, that means you work inside of gitea (or alternative) and OBS is configured just to follow it (possibly in multiple places).

Therefore there won't be any support neither in osc nor in the api to do source modifications.

In the long run, the target project will be managed with git also (see the ALP project). That means a submission is also a merge request in $gitea.

osc will only support tasks for dealing with git repos in context of build setups, like results, buildlogs and alike.

**Comment by mcepl** [comment]
Well, frankly, my dear, I don't give a damn whether we use `osc` or some specialized git-only tool, but currently it seems nothing is working. `osc` doesn’t support it and when following [directions using plain git](https://github.com/openSUSE/scm-staging/pull/24), the result is apparently not correct.

So, what should I do?

**Comment by mcepl** [comment]
In the spirit of [DoTheSimplestThingThatCouldPossiblyWork](https://wiki.c2.com/?DoTheSimplestThingThatCouldPossiblyWork) I have made this hack [which temporarily creates `.osc/`](https://git.sr.ht/~mcepl/gosc/tree/master/item/goinit).
