### ISSUE TITLE
The `get_password` methods of password managers return values of different types

### ISSUE THREAD

**Issue by crazyscientist** [openSUSE/osc#1073]
**Describe the bug**
The `get_password` methods of implemented credential managers in `osc/credentials.py` return values of different types, e.g.

* `PlaintextConfigFileCredentialsManager` and `ObfuscatedConfigFileCredentialsManager` return a `str`
* all other credential mangers return an instance of `_LazyPassword`

**Versions**
- Operating system: Does not matter
- Packages: 0.180.0

**Expected behavior**
All the implementations return values of the same type.

**Additional context**
Not strictly a bug, but somebody who is not aware of this difference might look at weird errors due to that.

**Comment by dmach** [comment]
This is how it was designed and how it works :/
We currently have different priorities than fixing this, but let's keep it in the backlog as a reminder that the credentials managers need rework.
