### ISSUE TITLE
osc AppImage crashes on Rocky 9

### ISSUE THREAD

**Issue by rafaelorafaelo** [openSUSE/osc#1075]
**Describe the bug**
When I start the AppImage of osc on a fresh Rocky 9 box, it crashes with a Python error.

**Versions**
- Operating system: `(source /etc/os-release; echo $PRETTY_NAME)`
Rocky Linux 9.0 (Blue Onyx)
- Packages: `rpm -q osc`
none

**To Reproduce**
1. Download osc from https://download.opensuse.org/repositories/openSUSE:/Tools/AppImage/ I used osc-0.180.0-lp152.331.1.Build331.1.glibc2.26-x86_64.AppImage
2. chmod 755 and run the file

**Expected behavior**
osc runs like on Rocky 8

**Screenshots, console outputs**
[ralf@localhost ~]$ ./osc-0.180.0-lp152.331.1.Build331.1.glibc2.26-x86_64.AppImage
```
Python path configuration:
  PYTHONHOME = '/tmp/.mount_osc-0.f0Vnbn/usr/'
  PYTHONPATH = '/tmp/.mount_osc-0.f0Vnbn/usr/share/pyshared/:'
  program name = '/usr/bin/python3'
  isolated = 0
  environment = 1
  user site = 1
  import site = 1
  sys._base_executable = '/usr/bin/python3'
  sys.base_prefix = '/tmp/.mount_osc-0.f0Vnbn/usr'
  sys.base_exec_prefix = '/tmp/.mount_osc-0.f0Vnbn/usr'
  sys.platlibdir = 'lib64'
  sys.executable = '/usr/bin/python3'
  sys.prefix = '/tmp/.mount_osc-0.f0Vnbn/usr'
  sys.exec_prefix = '/tmp/.mount_osc-0.f0Vnbn/usr'
  sys.path = [
    '/tmp/.mount_osc-0.f0Vnbn/usr/share/pyshared/',
    '',
    '/tmp/.mount_osc-0.f0Vnbn/usr/lib64/python39.zip',
    '/tmp/.mount_osc-0.f0Vnbn/usr/lib64/python3.9',
    '/tmp/.mount_osc-0.f0Vnbn/usr/lib64/python3.9/lib-dynload',
  ]
Fatal Python error: init_fs_encoding: failed to get the Python codec of the filesystem encoding
Python runtime state: core initialized
ModuleNotFoundError: No module named 'encodings'

Current thread 0x00007f0c47c4fb80 (most recent call first):
<no Python frame>
```

**Comment by dmach** [comment]
It seems that the appimage contains only runtime for python 2.7 and 3.6.
I currently don't know any details about how the appimage gets build, but I'll definitely take a look.

**Comment by dmach** [comment]
Fixed: https://build.opensuse.org/request/show/1088528
The problem was in using the system python interpreter with libs from the appimage.
Changing shebang fixed the problem.
