### ISSUE TITLE
osc 1.0.0b tarball contains an outdated setup.py requiring m2crypto and chardet

### ISSUE THREAD

**Issue by dcermak** [openSUSE/osc#1094]
**Describe the bug**

The tarball https://github.com/openSUSE/osc/archive/refs/tags/1.0.0b0.tar.gz appears to have an outdated `setup.py` which still contains the old requirements for chardet & m2crypto.

**To Reproduce**
1. Download 1.0.0b0.tar.gz & extract it
2. grep for `install_requires` in `setup.py`: `install_requires=['M2Crypto', 'chardet'],`

**Expected behavior**

`setup.py` should have `install_requires=['cryptography', 'urllib3'],`

**Comment by dmach** [comment]
tag `1.0.0b0` corresponds with 69f75a0278cb57c3769cf065bc04ed317e422875
It is only a version bump that opens 1.0 development, allowing us to do git builds for example: `1.0.0b0.43.g43337afd`
I'll tag `1.0.0b1` later today to have a proper release.

**Comment by dmach** [comment]
tarball associated with tag 1.0.0b1 works fine: https://github.com/openSUSE/osc/releases/tag/1.0.0b1
If you're looking for a spec that works with the new release, you can find it here: https://build.opensuse.org/package/show/OBS:Server:Unstable/osc
