### ISSUE TITLE
osc up on project level with scmsync package fails 2nd time

### ISSUE THREAD

**Issue by lnussel** [openSUSE/osc#1096]
````
$ osc up
checking out new package dummy
A    dummy
$ osc up
can't add package 'dummy': Object already exists
$ rpm -q osc
osc-0.181.0-1.1.noarch
$ head -2 /etc/os-release 
NAME="openSUSE Tumbleweed"
# VERSION="20220718"
```

**Comment by dmach** [comment]
@lnussel could you try patch from #1115? Does it fix the problem for you?
Please note that the latest osc (that includes PR #1115) is 1.0.0 beta that quite differs from 0.181.0 you have installed so the patch will probably not apply directly. But it was reproducible with the latest master as well.
