### ISSUE TITLE
Need a better way to extract GIT_VERSION

### ISSUE THREAD

**Issue by chenrui333** [openSUSE/osc#1101]
**Describe the bug**
With [this PR](https://github.com/openSUSE/osc/pull/1037), the `osc --version` is broken on the homebrew regression test.

I have to introduce such patch (which is the same one used by [freebsd](https://cgit.freebsd.org/ports/commit/?id=0f1e7823c4246d1c8781c6d78bf188fe2d89701a)). 

```
diff --git a/osc/util/git_version.py b/osc/util/git_version.py
index 69022cf..67a12e4 100644
--- a/osc/util/git_version.py
+++ b/osc/util/git_version.py
@@ -3,6 +3,7 @@ import subprocess


 def get_git_archive_version():
+    return None
     """
     Return version that is set by git during `git archive`.
     The returned format is equal to what `git describe --tags` returns.
@@ -18,6 +19,7 @@ def get_git_archive_version():


 def get_git_version():
+    return None
     """
     Determine version from git repo by calling `git describe --tags`.
     """
```

**Versions**
- Operating system: macOS
- Packages: homebrew

**To Reproduce**
1. Run command `osc --version`
2. See error

```
/opt/homebrew/Library/Taps/homebrew/homebrew-core on bump-osc-0.181.0 [!$]
$ /opt/homebrew/Cellar/osc/0.181.0/bin/osc --version
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/osc/0.181.0/bin/osc", line 10, in <module>
    from osc import commandline, babysitter
  File "/opt/homebrew/Cellar/osc/0.181.0/libexec/lib/python3.10/site-packages/osc/commandline.py", line 28, in <module>
    from .core import *
  File "/opt/homebrew/Cellar/osc/0.181.0/libexec/lib/python3.10/site-packages/osc/core.py", line 10, in <module>
    __version__ = git_version.get_version('0.181.0')
  File "/opt/homebrew/Cellar/osc/0.181.0/libexec/lib/python3.10/site-packages/osc/util/git_version.py", line 74, in get_version
    raise ValueError(msg)
ValueError: Git tag '3.5.8' doesn't correspond with version '0.181.0' specified in the source code
```

**Expected behavior**
Should just works

**Screenshots, console outputs**
If applicable, add screenshots or console outputs to help explain your problem.

**Additional context**

relates to https://github.com/Homebrew/homebrew-core/pull/107925

**Comment by dmach** [comment]
I've submitted #1110 that returns version from the source code if there's no matching git tag.
Please note that there is no `osc --version` option in the latest code, you need to run `osc version` instead.
I'd prefer to keep it this way because the `--version` option can be used elsewhere - e.g. setting a package version in a subcommand etc.

Could you check if the patch works for you?
