### ISSUE TITLE
osc rq list --exclude-target-project => results in error

### ISSUE THREAD

**Issue by DimStar77** [openSUSE/osc#112]
I use the command 
osc rq list GNOME:Next simple-scan --exclude-target-project=GNOME:Next
to see if GNOME:Next simple-scan has currently an 'outgoing' SR (to it's parent normally)

Since recently (can't say when exactly) this is no longer working; osc returns:

Server returned an error: HTTP Error 400: Bad Request
illegal token: ':or'

**Comment by lethliel** [comment]
The error is not shown anymore.
