### ISSUE TITLE
Support ssh authentication with ssh-agent forwarding

### ISSUE THREAD

**Issue by Werkov** [openSUSE/osc#1127]
**Is your feature request related to a problem? Please describe.**

Using osc (with ssh authentication) on a remote machine does not work when ssh-agent forwarding is in use (and no (secret/public) keys on the remote machine.

**Describe the solution you'd like**

` ssh-add -L` . It means that osc could store this to an ephemeral file and supply that to `ssh-keygen` , the `.oscrc`  file (on remote machine) could then only contain fingerprint (to pick right key).

**Describe alternatives you've considered**

Manually copying `id_rsa.pub` to the remote machine.

**Additional context**

I checked that the signing is implemented with `ssh-keygen -Y sign -f path ....`

The ssh-agent protocol [needs full](https://datatracker.ietf.org/doc/html/draft-miller-ssh-agent-04#section-4.5) public key in the request, so the path makes sense to be that of the public keys.

It has implication when using OBS ssh authentication on remote hosts with ssh-agent forwarding. The remote host won't have neither `~/.ssh/id_rsa`  nor `~/.ssh/id_rsa.pub`. So ssh authentication on the remote host won't work despite ssh-agent forwarding. The solution is to copy only `id_rsa.pub` to the remote host's `~/.ssh/` so that `ssh-keygen` can read it on the remote host (but signing is forwarded to the local agent).

**Comment by dmach** [comment]
I've submitted a pull request that implements ssh-agent forwarding by storing the first line from `ssh-add -L` output to a temporary file. Could you check if it works for you?
