### ISSUE TITLE
Provide manpage for oscrc

### ISSUE THREAD

**Issue by lrupp** [openSUSE/osc#1132]
**Is your feature request related to a problem? Please describe.**
As an old osc user, it's not easy to see if there are new features or flags in ~/.oscrc  that might be useful meanwhile. If you are even using a configuration were all former comments are removed, It's sometimes hard to guess the meaning of an old setting. ;-)

**Describe the solution you'd like**
While the current [Debian documentation policy](https://www.debian.org/doc/debian-policy/ch-docs.html) only suggest that configuration files also have a manual page, the overall idea behind this is clear: people like me should be able to get some descriptions about the configuration file, to be able to adjust them to their needs - even after years or after some breaking changes.

**Describe alternatives you've considered**
I tried to find some template in https://github.com/openSUSE/osc/blob/master/doc/conf.py or https://github.com/openSUSE/osc/tree/master/doc/api. But the only template I found, seems to be hidden inside the code: https://github.com/openSUSE/osc/blob/master/osc/conf.py 

Luckily `osc config --dump` prints out the current configuration. I hope, it uses the _new_conf_template_ content, if there is no existing oscrc. In that case, the solution might be simple:
* create a basic header/footer man page containing some information about the ini file itself (have a look at `man 5 smb.conf`for example
* use `osc config --dump` during (package) build to generate the "EXPLANATION OF EACH PARAMETER" section in the man page
* concatenate the header, dump-output and footer into a `man 5 oscrc` man page
* maybe enhance `osc config --dump` with a `--template`option, which allows to get the full _new_conf_template_ output even after (mis-)configuring an own .oscrc

**Comment by dmach** [comment]
This has been fixed a while ago already.
oscrc man page is generated from the source in a similar fashion as the online documentation: https://opensuse-commander.readthedocs.io/en/latest/oscrc.html
