### ISSUE TITLE
What is a unique ID for a Package?

### ISSUE THREAD

**Issue by dmach** [openSUSE/osc#1139]
`core.findpacs() ` does the following:
```
    pacs = []
    for f in files:
        p = filedir_to_pac(f, progress_obj)
        known = None
        for i in pacs:
            if i.name == p.name and i.prjname == p.prjname:
                known = i
                break
        if known:
            i.merge(p)
        else:
            pacs.append(p)
    return pacs
```

This means it considers packages with the same `name` and `prjname` identical.
Shouldn't the unique ID be (`apiurl`, `prjname`, `name`) instead?
Edit: in some cases also `revision` and/or `likrev` might be part of the unique key.

**Comment by dmach** [comment]
@adrianschroeter @mlschroe @bugfinder @lethliel @darix Any thoughts?
I'd like to make a clear decision and write tests accordingly (and modify the existing code if needed).

**Comment by darix** [comment]
is that to find packages from the local preferred directory?

**Comment by dmach** [comment]
> is that to find packages from the local preferred directory?

Yes; if I understand it correctly, the agument is a list of directory names that contain packages, but in general it can be list of paths to the directories that contain packages.

**Comment by dmach** [comment]
According to a discussion we had in a meeting, `(apiurl, prjname, name)` is the most reasonable unique identifier for a Package.
