### ISSUE TITLE
Non-root user failed to osc build when specify build root

### ISSUE THREAD

**Issue by system-thoughts** [openSUSE/osc#1147]
**Describe the bug**
Non-root user failed to osc build when specify build root

**Versions**
- Operating system: `Fedora Linux 36 (Workstation Edition)`
- Packages: `osc-0.180.0-332.4.1.fc36.noarch`

**To Reproduce**
1. Run command `mkdir tmp && osc build  -j16 --root=$PWD/tmp standard_x86_64`
2. for example, see error
```
osc build  -j16 --root=$PWD/tmp standard_x86_64
WARNING: SSL certificate checks disabled. Connection is insecure!

Building python3.spec for standard_x86_64/x86_64
Getting buildconfig from server and store to /home/Rui/obs/home:system-thoughts:branches:openEuler:22.03:LTS/python3/.osc/_buildconfig-standard_x86_64-x86_64
Getting buildinfo from server and store to /home/Rui/obs/home:system-thoughts:branches:openEuler:22.03:LTS/python3/.osc/_buildinfo-standard_x86_64-x86_64.xml
Updating cache of required packages
0.0% cache miss. 437/437 dependencies cached.

Skipping verification of package signatures
Writing build configuration
Running build
BUILD_ROOT=/home/Rui/obs/home:system-thoughts:branches:openEuler:22.03:LTS/python3/tmp must be owned by root. Exit...

 failed "build " at Wed Sep 21 13:47:56 UTC 2022.


The buildroot was: /home/Rui/obs/home:system-thoughts:branches:openEuler:22.03:LTS/python3/tmp
```

If we do not specofy build root dir, it can start building: `osc build --clean  -j16  standard_x86_64`
**Expected behavior**
Non-root user can osc build when specify build root:

**Comment by dmach** [comment]
I'm afraid this isn't something we can fix in osc.
The error message comes from the `build` tool that is part of the [openSUSE/obs-build](https://github.com/openSUSE/obs-build) project.
Unfortunately I'm unable to transfer this issue there, hence closing.
