### ISSUE TITLE
<package>/.osc/_files differs from API

### ISSUE THREAD

**Issue by dmach** [openSUSE/osc#1161]
**Describe the bug**
.osc/_files differs from API
This applies to packages with linkinfo.

**Versions**
- Operating system: openSUSE Tumbleweed
- Packages: 1.x from git

**To Reproduce**
1. `osc checkout openSUSE:Tools/osc`
2. `osc api /source/openSUSE:Tools/osc > _files-api`
3. `diff -u _files-api openSUSE:Tools/osc/.osc/_files`

```
-<directory name="osc" rev="373" vrev="339" srcmd5="30ccce6c3a1a4322e79c2935a52af18b">
-  <linkinfo project="openSUSE:Factory" package="osc" srcmd5="1ccbcd1b0b531a37ad75b34b5a1e2e3e" baserev="2c3ae65909d69e0f63113ccfe0e5f3f8" xsrcmd5="6a31b956f9431b0644ad6cf8e845c4e5" lsrcmd5="30ccce6c3a1a4322e79c2935a52af18b"/>
+<directory name="osc" rev="6a31b956f9431b0644ad6cf8e845c4e5" srcmd5="6a31b956f9431b0644ad6cf8e845c4e5">
+  <linkinfo project="openSUSE:Factory" package="osc" srcmd5="1ccbcd1b0b531a37ad75b34b5a1e2e3e" baserev="2c3ae65909d69e0f63113ccfe0e5f3f8" lsrcmd5="30ccce6c3a1a4322e79c2935a52af18b" />
```

**Expected behavior**
Whatever we retrieve from the API should be stored on disk.

**Comment by marcus-h** [comment]
On 2022-10-05 04:29:15 -0700, Daniel Mach wrote:
> **Describe the bug**
> .osc/_files differs from API
> This applies to packages with linkinfo.
>
> **Versions**
> - Operating system: openSUSE Tumbleweed
> - Packages: 1.x from git
>
> **To Reproduce**
> Steps to reproduce the behavior:
> 1. `osc checkout openSUSE:Tools/osc`

osc checks out the expanded sources by default

> 2. `osc api /source/openSUSE:Tools/osc > _files-api`

This corresponds to the unexpanded sources. To get the expanded sources,
you can use "osc api /source/openSUSE:Tools/osc?expand=1 > _files-api",
which should be identical to the .osc/_files file (unless a _service
file is involved).

> 3. `diff -u _files-api openSUSE:Tools/osc/.osc/_files`
>
> ```
> -<directory name="osc" rev="373" vrev="339" srcmd5="30ccce6c3a1a4322e79c2935a52af18b">
> -  <linkinfo project="openSUSE:Factory" package="osc" srcmd5="1ccbcd1b0b531a37ad75b34b5a1e2e3e" baserev="2c3ae65909d69e0f63113ccfe0e5f3f8" xsrcmd5="6a31b956f9431b0644ad6cf8e845c4e5" lsrcmd5="30ccce6c3a1a4322e79c2935a52af18b"/>
> +<directory name="osc" rev="6a31b956f9431b0644ad6cf8e845c4e5" srcmd5="6a31b956f9431b0644ad6cf8e845c4e5">
> +  <linkinfo project="openSUSE:Factory" package="osc" srcmd5="1ccbcd1b0b531a37ad75b34b5a1e2e3e" baserev="2c3ae65909d69e0f63113ccfe0e5f3f8" lsrcmd5="30ccce6c3a1a4322e79c2935a52af18b" />
> ```
>
> **Expected behavior**
> Whatever we retrieve from the API should be stored on disk.
>

**Comment by dmach** [comment]
It turns out that this is more complex than expanded/unexpanded sources.
The revision of packages with linkinfo is obtained via `show_upstream_xsrcmd5()` and the resulting xml is different.
It would require significant effort to change that and the benefit would be negligible. Closing.
