### ISSUE TITLE
Support for PEP 561

### ISSUE THREAD

**Issue by SchoolGuy** [openSUSE/osc#1186]
**Is your feature request related to a problem? Please describe.**

As a consumer of `core.py` (or the new API) it is not possible to execute static type checkers like mypy against your code without getting the following warning:

```
/home/<user>/PycharmProjects/release-management-tools/venv/bin/python -m mypy release_management_tools 
release_management_tools/list_accepted_pkgs.py:8: error: Skipping analyzing "osc": module is installed, but missing library stubs or py.typed marker
release_management_tools/list_accepted_pkgs.py:8: note: See https://mypy.readthedocs.io/en/stable/running_mypy.html#missing-imports
Found 1 error in 1 file (checked 13 source files)
```

**Describe the solution you'd like**

Add a file called `py.typed` to the root folder of the project and execute `mypy on the project to confirm its predictability in regard to types returned.

**Describe alternatives you've considered**

- `pyi` files: Hard to maintain imho since these are separate files.
- Not having support for PEP 561: Well this is the status quo. It makes it hard for consumers of osc to know what to expect of its code.

**Additional context**

- PEP: https://peps.python.org/pep-0561/
- PR that is a first try to implement this: #1179

**Comment by dmach** [comment]
This is nothing we can fix in couple pull requests -> no chance to deliver it in a reasonable time.
It's more an ongoing effort which is already happening; thanks for initiating it, BTW!
I'll close this issue; let me know in case you want it open for any reason.
