### ISSUE TITLE
vc command not found

### ISSUE THREAD

**Issue by saber716rus** [openSUSE/osc#1196]
**Describe the bug**
osc is running in a container (fedora 35) proot-distro. in turn, proot-distro is launched in termux on android

**Versions**
- Operating system: `(source /etc/os-release; echo $PRETTY_NAME)`
- Packages: `rpm -q osc`
root@localhost ~# cat ../etc/os-release                       NAME="Fedora Linux"
VERSION="35 (Container Image)"                                ID=fedora
VERSION_ID=35                                                 VERSION_CODENAME=""
PLATFORM_ID="platform:f35"                                    PRETTY_NAME="Fedora Linux 35 (Container Image)"
ANSI_COLOR="0;38;2;60;110;180"                                LOGO=fedora-logo-icon
CPE_NAME="cpe:/o:fedoraproject:fedora:35"                     HOME_URL="https://fedoraproject.org/"
DOCUMENTATION_URL="https://docs.fedoraproject.org/en-US/fedora/f35/system-administrators-guide/"
SUPPORT_URL="https://ask.fedoraproject.org/"                  BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Fedora"                              REDHAT_BUGZILLA_PRODUCT_VERSION=35
REDHAT_SUPPORT_PRODUCT="Fedora"                               REDHAT_SUPPORT_PRODUCT_VERSION=35
PRIVACY_POLICY_URL="https://fedoraproject.org/wiki/Legal:PrivacyPolicy"
VARIANT="Container Image"                                     VARIANT_ID=container
root@localhost ~# rpm -q osc                                  osc-0.182.0-343.23.noarch
root@localhost ~#

**To Reproduce**
1. Run command `osc vc'
2. See error 'Error: vc ('/usr/lib/build/vc') command not found             Install the build package from http://download.opensuse.org/repositories/openSUSE:/Tools/'

**Expected behavior**
the command is found

**Screenshots, console outputs**

**Additional context**
reinstalling does not help.
the container in proot-distro is started by the command
proot-distro login --termux-home fedora

**Comment by saber716rus** [comment]
in the opesuse container, the same error itself
root@localhost ~/h/serviio# osc vc
Error: vc ('/usr/lib/build/vc') command not found
Install the build package from http://download.opensuse.org/repositories/openSUSE:/Tools/
root@localhost ~/h/serviio [1]#

root@localhost ~# cat ../etc/os-release
NAME="openSUSE Tumbleweed"
# VERSION="20221120"
ID="opensuse-tumbleweed"
ID_LIKE="opensuse suse"
VERSION_ID="20221120"
PRETTY_NAME="openSUSE Tumbleweed"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:opensuse:tumbleweed:20221120"
BUG_REPORT_URL="https://bugs.opensuse.org"
HOME_URL="https://www.opensuse.org/"
DOCUMENTATION_URL="https://en.opensuse.org/Portal:Tumbleweed"
LOGO="distributor-logo-Tumbleweed"
root@localhost ~# rpm -q osc
osc-0.182.0-2.1.noarch
root@localhost ~#

**Comment by saber716rus** [comment]
With the --termux-home function disabled, the vc command is still not found.

**Comment by luc14n0** [comment]
Hi there,

I wouldn't consider this to be a bug, the error message is telling what to do -- to install the `build` package, even though it may sound a bit obscure:

```
'Error: vc ('/usr/lib/build/vc') command not found Install the build package from http://download.opensuse.org/repositories/openSUSE:/Tools/'
```

**OSC** only has a soft requirement (`Recommends`) on `build`, which makes sense, by the way. If we want to build packages locally and use the `vc` `osc`'s sub-command to add entries to the `foo.changes` file, we need to install the `build` package then.

So, somehow you have to install this extra package, I suppose just like the way you installed `osc`, in the first place.

**Comment by saber716rus** [comment]
Yes you are right.  The only question is why this dependency is not pulled by default?

**Comment by lethliel** [comment]
The dependency on `build` is only a recommendation:

`Recommends:     build`

The reason for this is that you can also use osc for just managing your sources in  a build service instance without building locally. Therefore the installation of build is not necessary.

**Comment by saber716rus** [comment]
But without this package, there is no work with the source code. Sending works crookedly. More precisely, the osc reports what it sent, but it did not appear on obs. After installing the build package. Sending worked as it should.Therefore, I would strongly recommend moving from recommends to requires.16:41, 24 ноября 2022 г., Marco Strigl ***@***.***>:
The dependency on build is only a recommendation:
Recommends:     build
The reason for this is that you can also use osc for just managing your sources in  a build service instance without building locally. Therefore the installation of build is not necessary.

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>
С Уважением, Николай.Специалист IT-систем.+79625490833 (whatsapp)telegram: https://t.me/Saber716RUSinstagram: @saber716russkype: nicksab1491

**Comment by luc14n0** [comment]
Can you be more specific on what exactly did you do? On this machine here (Windows/MSYS2) I only have `osc` at the moment and I did this:

``` bash
touch dummy.spec
osc add dummy.spec
osc ci -m 'Add dummyp.spec'
```

It worked for me.

**Comment by saber716rus** [comment]
localhost:~ # zypper in fish osc
Loading repository data...
Reading installed packages...
Resolving package dependencies...

The following 56 NEW packages are going to be installed:
  alts bc dbus-1 dbus-1-common dbus-1-daemon dbus-1-tools diffutils
  file file-magic findutils fish groff kbd kbd-legacy less
  libalternatives1 libapparmor1 libdbus-1-3 libdw1 libelf1 libexpat1
  libgdbm6 libgomp1 libip4tc2 libkmod2 libmagic1 libmpdec3 libnsl3
  libpcre2-32-0 libpipeline1 libpkgconf3 libpython3_10-1_0
  librpmbuild9 libseccomp2 libtirpc-netconfig libtirpc3 libzio1 man
  osc pam-config perl-base pkgconf pkgconf-m4 pkgconf-pkg-config
  python310 python310-M2Crypto python310-base python310-chardet
  python310-rpm system-user-man systemd systemd-default-settings
  systemd-default-settings-branding-SLE
  systemd-presets-branding-MicroOS systemd-presets-common-SUSE which

56 new packages to install.
Overall download size: 28.1 MiB. Already cached: 0 B. After the
operation, additional 109.3 MiB will be used.
Continue? [y/n/v/...? shows all options] (y): y
Retrieving package bc-1.07.1-4.20.aarch64
                                (1/56), 114.2 KiB (281.9 KiB unpacked)
Retrieving: bc-1.07.1-4.20.aarch64.rpm ...........[done (121.8 KiB/s)]
Retrieving package dbus-1-common-1.14.4-1.1.noarch
                                (2/56),  31.6 KiB ( 11.7 KiB unpacked)
Retrieving: dbus-1-common-1.14.4-1.1.noarch.rpm ................[done]
Retrieving package diffutils-3.8-3.1.aarch64
                                (3/56), 188.4 KiB (451.3 KiB unpacked)
Retrieving: diffutils-3.8-3.1.aarch64.rpm ......................[done]
Retrieving package file-magic-5.43-1.1.noarch
                                (4/56), 620.7 KiB (  9.0 MiB unpacked)
Retrieving: file-magic-5.43-1.1.noarch.rpm .....................[done]
Retrieving package findutils-4.9.0-1.9.aarch64
                                (5/56), 282.1 KiB (580.3 KiB unpacked)
Retrieving: findutils-4.9.0-1.9.aarch64.rpm ....................[done]
Retrieving package kbd-legacy-2.4.0-10.2.noarch
                                (6/56), 534.6 KiB (560.2 KiB unpacked)
Retrieving: kbd-legacy-2.4.0-10.2.noarch.rpm .....[done (878.5 KiB/s)]
Retrieving package libalternatives1-1.2+3.b848aad-3.1.aarch64
                                (7/56),  21.0 KiB ( 73.4 KiB unpacked)
Retrieving: libalternatives1-1.2+3.b848aad-3.1.aarch64.rpm .....[done]
Retrieving package libapparmor1-3.0.7-3.1.aarch64
                                (8/56),  58.6 KiB (130.8 KiB unpacked)
Retrieving: libapparmor1-3.0.7-3.1.aarch64.rpm ....[done (24.7 KiB/s)]
Retrieving package libelf1-0.188-2.1.aarch64
                                (9/56),  63.7 KiB (130.1 KiB unpacked)
Retrieving: libelf1-0.188-2.1.aarch64.rpm ......................[done]
Retrieving package libexpat1-2.5.0-1.1.aarch64
                               (10/56),  90.0 KiB (194.0 KiB unpacked)
Retrieving: libexpat1-2.5.0-1.1.aarch64.rpm ......[done (184.9 KiB/s)]
Retrieving package libgdbm6-1.23-1.10.aarch64
                               (11/56),  53.2 KiB (164.4 KiB unpacked)
Retrieving: libgdbm6-1.23-1.10.aarch64.rpm .....................[done]
Retrieving package libgomp1-12.2.1+git537-1.1.aarch64
                               (12/56), 132.0 KiB (322.6 KiB unpacked)
Retrieving: libgomp1-12.2.1+git537-1.1.aarch64.rpm .............[done]
Retrieving package libip4tc2-1.8.8-2.2.aarch64
                               (13/56),  24.2 KiB ( 66.5 KiB unpacked)
Retrieving: libip4tc2-1.8.8-2.2.aarch64.rpm ....................[done]
Retrieving package libkmod2-30-1.5.aarch64
                               (14/56),  56.9 KiB (130.2 KiB unpacked)
Retrieving: libkmod2-30-1.5.aarch64.rpm ........................[done]
Retrieving package libmpdec3-2.5.1-2.11.aarch64
                               (15/56),  84.1 KiB (259.7 KiB unpacked)
Retrieving: libmpdec3-2.5.1-2.11.aarch64.rpm ...................[done]
Retrieving package libpcre2-32-0-10.40-3.6.aarch64
                               (16/56), 222.1 KiB (645.8 KiB unpacked)
Retrieving: libpcre2-32-0-10.40-3.6.aarch64.rpm ..[done (507.3 KiB/s)]
Retrieving package libpipeline1-1.5.7-1.1.aarch64
                               (17/56),  28.4 KiB ( 65.9 KiB unpacked)
Retrieving: libpipeline1-1.5.7-1.1.aarch64.rpm .................[done]
Retrieving package libpkgconf3-1.8.0-1.13.aarch64
                               (18/56),  37.3 KiB (131.6 KiB unpacked)
Retrieving: libpkgconf3-1.8.0-1.13.aarch64.rpm .................[done]
Retrieving package libseccomp2-2.5.4-2.6.aarch64
                               (19/56),  65.4 KiB (153.9 KiB unpacked)
Retrieving: libseccomp2-2.5.4-2.6.aarch64.rpm ..................[done]
Retrieving package libtirpc-netconfig-1.3.3-1.5.aarch64
                               (20/56),  14.4 KiB (  1.9 KiB unpacked)
Retrieving: libtirpc-netconfig-1.3.3-1.5.aarch64.rpm ...........[done]
Retrieving package libzio1-1.08-2.5.aarch64
                               (21/56),  26.9 KiB ( 83.7 KiB unpacked)
Retrieving: libzio1-1.08-2.5.aarch64.rpm ...........[done (3.0 KiB/s)]
Retrieving package pam-config-1.8-1.1.aarch64
                               (22/56), 140.5 KiB (698.0 KiB unpacked)
Retrieving: pam-config-1.8-1.1.aarch64.rpm .....................[done]
Retrieving package perl-base-5.36.0-3.5.aarch64
                               (23/56),   1.5 MiB (  6.1 MiB unpacked)
Retrieving: perl-base-5.36.0-3.5.aarch64.rpm .......[done (3.5 KiB/s)]
Retrieving package pkgconf-m4-1.8.0-1.13.noarch
                               (24/56),  18.0 KiB ( 13.9 KiB unpacked)
Retrieving: pkgconf-m4-1.8.0-1.13.noarch.rpm .......[done (3.0 KiB/s)]
Retrieving package system-user-man-20170617-24.12.noarch
                               (25/56),  10.2 KiB (   83   B unpacked)
Retrieving: system-user-man-20170617-24.12.noarch.rpm ..........[done]
Retrieving package
systemd-default-settings-branding-SLE-0.7-2.5.noarch
                               (26/56),  10.4 KiB (  1.5 KiB unpacked)
Retrieving: systemd-default-settings-branding-SLE-0.[done (3.4 KiB/s)]
Retrieving package systemd-default-settings-0.7-2.5.noarch
                               (27/56),  11.5 KiB (  2.0 KiB unpacked)
Retrieving: systemd-default-settings-0.7-2.5.noarch.rpm ........[done]
Retrieving package systemd-presets-common-SUSE-15-24.2.noarch
                               (28/56),  14.3 KiB (  4.5 KiB unpacked)
Retrieving: systemd-presets-common-SUSE-15-24.2.noarch.rpm .....[done]
Retrieving package which-2.21-5.8.aarch64
                               (29/56),  39.2 KiB (118.6 KiB unpacked)
Retrieving: which-2.21-5.8.aarch64.rpm .........................[done]
Retrieving package libdbus-1-3-1.14.4-1.1.aarch64
                               (30/56), 153.2 KiB (386.2 KiB unpacked)
Retrieving: libdbus-1-3-1.14.4-1.1.aarch64.rpm .....[done (2.9 KiB/s)]
Retrieving package libmagic1-5.43-1.1.aarch64
                               (31/56),  90.4 KiB (194.3 KiB unpacked)
Retrieving: libmagic1-5.43-1.1.aarch64.rpm .....................[done]
Retrieving package kbd-2.4.0-10.2.aarch64
                               (32/56),   1.9 MiB (  5.6 MiB unpacked)
Retrieving: kbd-2.4.0-10.2.aarch64.rpm .........................[done]
Retrieving package alts-1.2+3.b848aad-3.1.aarch64
                               (33/56),  28.1 KiB (104.6 KiB unpacked)
Retrieving: alts-1.2+3.b848aad-3.1.aarch64.rpm .................[done]
Retrieving package libdw1-0.188-2.1.aarch64
                               (34/56), 231.9 KiB (643.1 KiB unpacked)
Retrieving: libdw1-0.188-2.1.aarch64.rpm .........[done (281.7 KiB/s)]
Retrieving package pkgconf-1.8.0-1.13.aarch64
                               (35/56),  42.7 KiB (101.6 KiB unpacked)
Retrieving: pkgconf-1.8.0-1.13.aarch64.rpm .....................[done]
Retrieving package libtirpc3-1.3.3-1.5.aarch64
                               (36/56),  96.7 KiB (229.2 KiB unpacked)
Retrieving: libtirpc3-1.3.3-1.5.aarch64.rpm ......[done (312.0 KiB/s)]
Retrieving package groff-1.22.4-7.5.aarch64
                               (37/56),   1.3 MiB (  5.5 MiB unpacked)
Retrieving: groff-1.22.4-7.5.aarch64.rpm .......................[done]
Retrieving package
systemd-presets-branding-MicroOS-20200323-2.9.noarch
                               (38/56),  10.6 KiB (  706   B unpacked)
Retrieving: systemd-presets-branding-MicroOS-2020032[done (3.4 KiB/s)]
Retrieving package dbus-1-tools-1.14.4-1.1.aarch64
                               (39/56),  54.7 KiB (272.0 KiB unpacked)
Retrieving: dbus-1-tools-1.14.4-1.1.aarch64.rpm ................[done]
Retrieving package dbus-1-daemon-1.14.4-1.1.aarch64
                               (40/56), 144.4 KiB (480.6 KiB unpacked)
Retrieving: dbus-1-daemon-1.14.4-1.1.aarch64.rpm ...............[done]
Retrieving package file-5.43-1.1.aarch64
                               (41/56),  57.9 KiB (136.1 KiB unpacked)
Retrieving: file-5.43-1.1.aarch64.rpm ..........................[done]
Retrieving package librpmbuild9-4.17.1.1-3.1.aarch64
                               (42/56),  99.6 KiB (195.3 KiB unpacked)
Retrieving: librpmbuild9-4.17.1.1-3.1.aarch64.rpm ..............[done]
Retrieving package pkgconf-pkg-config-1.8.0-1.13.aarch64
                               (43/56),  13.2 KiB (  896   B unpacked)
Retrieving: pkgconf-pkg-config-1.8.0-1.13.aarch64.rpm ..........[done]
Retrieving package libnsl3-2.0.0-1.12.aarch64
                               (44/56),  29.5 KiB ( 98.6 KiB unpacked)
Retrieving: libnsl3-2.0.0-1.12.aarch64.rpm .....................[done]
Retrieving package dbus-1-1.14.4-1.1.aarch64
                               (45/56), 109.3 KiB (333.8 KiB unpacked)
Retrieving: dbus-1-1.14.4-1.1.aarch64.rpm ......................[done]
Retrieving package less-608-1.1.aarch64
                               (46/56), 161.3 KiB (452.7 KiB unpacked)
Retrieving: less-608-1.1.aarch64.rpm ...........................[done]
Retrieving package python310-base-3.10.8-3.1.aarch64
                               (47/56),   9.1 MiB ( 35.2 MiB unpacked)
Retrieving: python310-base-3.10.8-3.1.aarch64.rpm ..[done (4.9 MiB/s)]
Retrieving package libpython3_10-1_0-3.10.8-3.1.aarch64
                               (48/56),   1.2 MiB (  3.3 MiB unpacked)
Retrieving: libpython3_10-1_0-3.10.8-3.1.aarch64.rpm ...........[done]
Retrieving package systemd-252.1-2.1.aarch64
                               (49/56),   3.5 MiB ( 13.3 MiB unpacked)
Retrieving: systemd-252.1-2.1.aarch64.rpm ......................[done]
Retrieving package python310-3.10.8-3.1.aarch64
                               (50/56), 161.7 KiB (286.0 KiB unpacked)
Retrieving: python310-3.10.8-3.1.aarch64.rpm ...................[done]
Retrieving package man-2.10.2-1.2.aarch64
                               (51/56),   1.1 MiB (  2.9 MiB unpacked)
Retrieving: man-2.10.2-1.2.aarch64.rpm .........................[done]
Retrieving package python310-rpm-4.17.1.1-3.1.aarch64
                               (52/56),  60.9 KiB (242.5 KiB unpacked)
Retrieving: python310-rpm-4.17.1.1-3.1.aarch64.rpm .[done (3.0 KiB/s)]
Retrieving package python310-chardet-5.0.0-1.2.noarch
                               (53/56), 246.9 KiB (  2.4 MiB unpacked)
Retrieving: python310-chardet-5.0.0-1.2.noarch.rpm .............[done]
Retrieving package python310-M2Crypto-0.38.0-5.1.aarch64
                               (54/56), 292.2 KiB (  1.5 MiB unpacked)
Retrieving: python310-M2Crypto-0.38.0-5.1.aarch64.rpm ..........[done]
Retrieving package fish-3.5.1-1.1.aarch64
                               (55/56),   3.1 MiB ( 13.4 MiB unpacked)
Retrieving: fish-3.5.1-1.1.aarch64.rpm .............[done (1.1 MiB/s)]
Retrieving package osc-0.182.0-2.1.noarch
                               (56/56), 505.7 KiB (  1.9 MiB unpacked)
Retrieving: osc-0.182.0-2.1.noarch.rpm .............[done (2.9 KiB/s)]

Checking for file conflicts: ...................................[done]
( 1/56) Installing: bc-1.07.1-4.20.aarch64 .....................[done]
( 2/56) Installing: dbus-1-common-1.14.4-1.1.noarch ............[done]
( 3/56) Installing: diffutils-3.8-3.1.aarch64 ..................[done]
( 4/56) Installing: file-magic-5.43-1.1.noarch .................[done]
( 5/56) Installing: findutils-4.9.0-1.9.aarch64 ................[done]
( 6/56) Installing: kbd-legacy-2.4.0-10.2.noarch ...............[done]
( 7/56) Installing: libalternatives1-1.2+3.b848aad-3.1.aarch64 .[done]
( 8/56) Installing: libapparmor1-3.0.7-3.1.aarch64 .............[done]
( 9/56) Installing: libelf1-0.188-2.1.aarch64 ..................[done]
(10/56) Installing: libexpat1-2.5.0-1.1.aarch64 ................[done]
(11/56) Installing: libgdbm6-1.23-1.10.aarch64 .................[done]
(12/56) Installing: libgomp1-12.2.1+git537-1.1.aarch64 .........[done]
(13/56) Installing: libip4tc2-1.8.8-2.2.aarch64 ................[done]
(14/56) Installing: libkmod2-30-1.5.aarch64 ....................[done]
(15/56) Installing: libmpdec3-2.5.1-2.11.aarch64 ...............[done]
(16/56) Installing: libpcre2-32-0-10.40-3.6.aarch64 ............[done]
(17/56) Installing: libpipeline1-1.5.7-1.1.aarch64 .............[done]
(18/56) Installing: libpkgconf3-1.8.0-1.13.aarch64 .............[done]
(19/56) Installing: libseccomp2-2.5.4-2.6.aarch64 ..............[done]
(20/56) Installing: libtirpc-netconfig-1.3.3-1.5.aarch64 .......[done]
(21/56) Installing: libzio1-1.08-2.5.aarch64 ...................[done]
ERROR: module /lib64/security/pam_pwquality.so is not installed.
*** write_config (account, /etc/pam.d/common-account-pc, ...)
**** write config for pam_access.so (account, disabled)
**** write config for pam_systemd_home.so (account, disabled)
**** write config for pam_unix2.so (account, disabled)
**** write config for pam_unix.so (account, enabled)
**** write config for pam_krb5.so (account, disabled)
**** write config for pam_localuser.so (account, disabled)
**** write config for pam_sss.so (account, disabled)
**** write config for pam_ldap.so (account, disabled)
**** write config for pam_nam.so (account, disabled)
**** write config for pam_winbind.so (account, disabled)
**** write config for pam_time.so (account, disabled)
*** write_config (auth, /etc/pam.d/common-auth-pc, ...)
**** write config for pam_env.so (auth, enabled)
**** write config for pam_group.so (auth, disabled)
**** write config for pam_pkcs11.so (auth, disabled)
**** write config for pam_fp.so (auth, disabled)
**** write config for pam_fprint.so (auth, disabled)
**** write config for pam_fprintd.so (auth, disabled)
**** write config for pam_thinkfinger.so (auth, disabled)
**** write config for pam_gnome_keyring.so (auth, disabled)
**** write config for pam_kwallet5.so (auth, disabled)
**** write config for pam_systemd_home.so (auth, disabled)
**** write config for pam_ssh.so (auth, disabled)
**** write config for pam_unix2.so (auth, disabled)
**** write config for pam_unix.so (auth, enabled)
**** write config for pam_ecryptfs.so (auth, disabled)
**** write config for pam_krb5.so (auth, disabled)
**** write config for pam_sss.so (auth, disabled)
**** write config for pam_ldap.so (auth, disabled)
**** write config for pam_nam.so (auth, disabled)
**** write config for pam_winbind.so (auth, disabled)
*** write_config (password, /etc/pam.d/common-password-pc, ...)
**** write config for pam_winbind.so (password, disabled)
**** write config for pam_pwcheck.so (password, disabled)
**** write config for pam_passwdqc.so (password, disabled)
**** write config for pam_pwquality.so (password, disabled)
**** write config for pam_cracklib.so (password, disabled)
**** write config for pam_pwhistory.so (password, disabled)
**** write config for pam_gnome_keyring.so (password, disabled)
**** write config for pam_kwallet5.so (password, disabled)
**** write config for pam_ecryptfs.so (password, disabled)
**** write config for pam_systemd_home.so (password, disabled)
**** write config for pam_unix2.so (password, disabled)
**** write config for pam_unix.so (password, enabled)
**** write config for pam_make.so (password, disabled)
**** write config for pam_exec.so (password, disabled)
**** write config for pam_krb5.so (password, disabled)
**** write config for pam_sss.so (password, disabled)
**** write config for pam_ldap.so (password, disabled)
**** write config for pam_nam.so (password, disabled)
*** write_config (session, /etc/pam.d/common-session-pc, ...)
**** write config for pam_selinux.so (session, disabled)
**** write config for pam_mkhomedir.so (session, disabled)
**** write config for pam_systemd_home.so (session, disabled)
**** write config for pam_systemd.so (session, disabled)
**** write config for pam_limits.so (session, enabled)
**** write config for pam_unix2.so (session, disabled)
**** write config for pam_unix.so (session, enabled)
**** write config for pam_apparmor.so (session, disabled)
**** write config for pam_krb5.so (session, disabled)
**** write config for pam_sss.so (session, disabled)
**** write config for pam_ldap.so (session, disabled)
**** write config for pam_winbind.so (session, disabled)
**** write config for pam_nam.so (session, disabled)
**** write config for pam_umask.so (session, enabled)
**** write config for pam_ssh.so (session, disabled)
**** write config for pam_selinux.so (session, disabled)
**** write config for pam_gnome_keyring.so (session, disabled)
**** write config for pam_kwallet5.so (session, disabled)
**** write config for pam_exec.so (session, disabled)
**** write config for pam_ecryptfs.so (session, disabled)
**** write config for pam_env.so (session, enabled)
**** write config for pam_mktemp.so (session, disabled)
(22/56) Installing: pam-config-1.8-1.1.aarch64 .................[done]
(23/56) Installing: perl-base-5.36.0-3.5.aarch64 ...............[done]
(24/56) Installing: pkgconf-m4-1.8.0-1.13.noarch ...............[done]
/usr/sbin/groupadd -r -g 62 man
/usr/sbin/useradd -r -c Manual pages viewer -d /var/lib/empty -g man -u 13 man -s /usr/sbin/nologin
(25/56) Installing: system-user-man-20170617-24.12.noarch ......[done]
(26/56) Installing: systemd-default-settings-branding-SLE-0.7-2.[done]
(27/56) Installing: systemd-default-settings-0.7-2.5.noarch ....[done]
(28/56) Installing: systemd-presets-common-SUSE-15-24.2.noarch .[done]
(29/56) Installing: which-2.21-5.8.aarch64 .....................[done]
(30/56) Installing: libdbus-1-3-1.14.4-1.1.aarch64 .............[done]
(31/56) Installing: libmagic1-5.43-1.1.aarch64 .................[done]
Updating /etc/sysconfig/console ...
Updating /etc/sysconfig/keyboard ...
(32/56) Installing: kbd-2.4.0-10.2.aarch64 .....................[done]
(33/56) Installing: alts-1.2+3.b848aad-3.1.aarch64 .............[done]
(34/56) Installing: libdw1-0.188-2.1.aarch64 ...................[done]
(35/56) Installing: pkgconf-1.8.0-1.13.aarch64 .................[done]
(36/56) Installing: libtirpc3-1.3.3-1.5.aarch64 ................[done]
(37/56) Installing: groff-1.22.4-7.5.aarch64 ...................[done]
(38/56) Installing: systemd-presets-branding-MicroOS-20200323-2.[done]
(39/56) Installing: dbus-1-tools-1.14.4-1.1.aarch64 ............[done]
(40/56) Installing: dbus-1-daemon-1.14.4-1.1.aarch64 ...........[done]
(41/56) Installing: file-5.43-1.1.aarch64 ......................[done]
(42/56) Installing: librpmbuild9-4.17.1.1-3.1.aarch64 ..........[done]
(43/56) Installing: pkgconf-pkg-config-1.8.0-1.13.aarch64 ......[done]
(44/56) Installing: libnsl3-2.0.0-1.12.aarch64 .................[done]
/usr/sbin/useradd -r -c User for D-Bus -d /run/dbus -U messagebus -s /usr/sbin/nologin
Warning: running kernel does not support fscaps
/usr/libexec/dbus-1/dbus-daemon-launch-helper: setting to root:messagebus 4750 (wrong owner/group root:root)
(45/56) Installing: dbus-1-1.14.4-1.1.aarch64 ..................[done]
(46/56) Installing: less-608-1.1.aarch64 .......................[done]
(47/56) Installing: python310-base-3.10.8-3.1.aarch64 ..........[done]
(48/56) Installing: libpython3_10-1_0-3.10.8-3.1.aarch64 .......[done]
warning: group systemd-journal does not exist - using root
Incorrect file mode bits for /etc/machine-id which should be 0444, fixing...
Creating group 'systemd-journal' with GID 485.
Creating group 'systemd-timesync' with GID 484.
Creating user 'systemd-timesync' (systemd Time Synchronization) with UID 484 and GID 484.
System has not been booted with systemd as init system (PID 1). Can't operate.
Failed to connect to bus: Host is down
/usr/lib/tmpfiles.d/journal-nocow.conf:26: Failed to resolve specifier: uninitialized /etc/ detected, skipping.
All rules containing unresolvable specifiers will be skipped.
(49/56) Installing: systemd-252.1-2.1.aarch64 ..................[done]
(50/56) Installing: python310-3.10.8-3.1.aarch64 ...............[done]
Updating /etc/sysconfig/cron ...
Created symlink /etc/systemd/system/multi-user.target.wants/man-db-create.service -> /usr/lib/systemd/system/man-db-create.service.
Created symlink /etc/systemd/system/timers.target.wants/man-db.timer -> /usr/lib/systemd/system/man-db.timer.
(51/56) Installing: man-2.10.2-1.2.aarch64 .....................[done]
(52/56) Installing: python310-rpm-4.17.1.1-3.1.aarch64 .........[done]
(53/56) Installing: python310-chardet-5.0.0-1.2.noarch .........[done]
(54/56) Installing: python310-M2Crypto-0.38.0-5.1.aarch64 ......[done]
(55/56) Installing: fish-3.5.1-1.1.aarch64 .....................[done]
(56/56) Installing: osc-0.182.0-2.1.noarch .....................[done]
Created symlink /etc/systemd/system/multi-user.target.wants/remote-fs.target -> /usr/lib/systemd/system/remote-fs.target.
Created symlink ***@***.*** -> ***@***.***
Created symlink /etc/systemd/system/multi-user.target.wants/kbdsettings.service -> /usr/lib/systemd/system/kbdsettings.service.
Created symlink /etc/systemd/system/default.target.wants/ca-certificates.path -> /usr/lib/systemd/system/ca-certificates.path.
Created symlink /etc/systemd/user/timers.target.wants/systemd-tmpfiles-clean.timer -> /usr/lib/systemd/user/systemd-tmpfiles-clean.timer.
Created symlink /etc/systemd/user/basic.target.wants/systemd-tmpfiles-setup.service -> /usr/lib/systemd/user/systemd-tmpfiles-setup.service.
Executing %posttrans scripts ...................................[done]
localhost:~ #

**Comment by luc14n0** [comment]
That output is of no use. I should've been more explicit, I'm sorry. You said:

> But without this package, there is no work with the source code. Sending works crookedly. More precisely, the osc reports what it sent, but it did not appear on obs. After installing the build package. Sending worked as it should.

That's what I was referring to when I said "Can you be more specific on what exactly did you do?"! What `osc` commands did you use prior to committing your local changes to OBS?

**Comment by saber716rus** [comment]
I didn't do anything like that. Perhaps the problems were with the obs itself. I uploaded the file to obs and it took and deleted all the files that were in the package. But now everything is stable. Without deviations. perhaps it's the Internet itself.

**Comment by luc14n0** [comment]
> I didn't do anything like that. Perhaps the problems were with the obs itself. I uploaded the file to obs and it took and deleted all the files that were in the package. But now everything is stable. Without deviations. perhaps it's the Internet itself.

That's an odd behavior. But, again, I don't know what `osc` commands you used. Next time `osc` does something funny or suspicious, you can add verbosity to the command, like:

``` bash
osc -v subcommand
```

For more detailed output:

``` bash
osc -vv subcommand
```

For even more detailed output:

``` bash
osc -vvv subcommand
```

That help a lot, depending on the nature of the issue.

**Comment by saber716rus** [comment]
> > I didn't do anything like that. Perhaps the problems were with the obs itself. I uploaded the file to obs and it took and deleted all the files that were in the package. But now everything is stable. Without deviations. perhaps it's the Internet itself.
> 
> That's an odd behavior. But, again, I don't know what `osc` commands you used. Next time `osc` does something funny or suspicious, you can add verbosity to the command, like:
> 
> ``` bash
> osc -v subcommand
> ```
> 
> For more detailed output:
> 
> ``` bash
> osc -vv subcommand
> ```
> 
> For even more detailed output:
> 
> ``` bash
> osc -vvv subcommand
> ```
> 
> That helps a lot, depending on the nature of the issue.

I'm saying the same thing, that there was a strange behavior, but now it behaves correctly. I thought maybe the problem was in the container I was collecting in, but no, it's not about him. I think most likely the problem was in openbuildservice. Why am I sinning against her? I sent the file via the website to openbuildservice, then instead of appearing in the package, but for some reason that I don't understand, the rest of the files from the package disappeared.

**Comment by luc14n0** [comment]
OK, I see. I installed Tumbleweed using `proot-distro` on my cellphone to play with `osc` there. And I see a **solver.onlyRequires = true** in `/etc/zypp/zypp.conf` -- which turns off installation of recommended packages --, so that's why when installing `osc`, the `build` package -- the one providing the `vc` command -- is not being installed too.

So the issue is not with `osc`, since it recommends the `build` package by default. Therefore, in my opinion, we shouldn't put a hard requirement on `build`.

**Comment by saber716rus** [comment]
on fedora installed in Proot-distro similar behavior.07:16, 30 ноября 2022 г., Luciano Santos ***@***.***>:
OK, I see. I installed Tumbleweed using proot-distro on my cellphone to play with osc there. And I see a solver.onlyRequires = true in /etc/zypp/zypp.conf -- which turns off installation of recommended packages --, so that's why when installing osc, the build package -- the one providing the vc command -- is not being installed too.
So the issue is not with osc, since it recommends the build package by default. Therefore, in my opinion, we shouldn't put a hard requirement on build.

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>
С Уважением, Николай.Специалист IT-систем.+79625490833 (whatsapp)telegram: https://t.me/Saber716RUSinstagram: @saber716russkype: nicksab1491
