### ISSUE TITLE
osc ls appends a `deleted=0` query to the API call resulting in a 404 for some projects

### ISSUE THREAD

**Issue by dcermak** [openSUSE/osc#1197]
**Describe the bug**

osc 1.0.0b2 appends `?deleted=0` to the API call to list the packages in a project, which leads to failures in remote projects.

**Versions**
- Operating system: `Fedora Linux 36 (Thirty Six)`
- Packages: `osc-1.0.0~b2-1.fc36.noarch` (manual build, equivalent to the version in F37 & Rawhide)

**To Reproduce**
1. Run command `osc -A https://api.suse.de ls openSUSE.org:devel:BCI:SLE-15-SP5`
2. See error:
```
Server returned an error: HTTP Error 404: Not Found
Project not found: openSUSE.org:devel:BCI:SLE-15-SP5
```

**Expected behavior**

The project exists and its contents should be printed

**Additional context**

using `-H` reveals that osc appends the query `deleted=0`:
```ShellSession
❯ isc -H ls openSUSE.org:devel:BCI:SLE-15-SP5
DEBUG: ----------------------------------------
DEBUG: GET https://api.suse.de/source/openSUSE.org:devel:BCI:SLE-15-SP5?deleted=0
DEBUG: send: b'GET /source/openSUSE.org:devel:BCI:SLE-15-SP5?deleted=0 HTTP/1.1\r\nHost: api.suse.de\r\nAccept-Encoding: identity\r\nuser-agent: osc/1.0.0b2\r\nAccept: application/xml\r\n\r\n'
DEBUG: reply: 'HTTP/1.1 404 Not Found\r\n'
DEBUG: header: Date: Thu, 24 Nov 2022 13:31:23 GMT
DEBUG: header: Server: Apache/2.4.51 (Linux/SUSE)
DEBUG: header: Strict-Transport-Security: max-age=31536000
DEBUG: header: cache-control: no-cache
DEBUG: header: vary: Accept,Accept-Encoding
DEBUG: header: referrer-policy: strict-origin-when-cross-origin
DEBUG: header: x-permitted-cross-domain-policies: none
DEBUG: header: x-xss-protection: 1; mode=block
DEBUG: header: x-opensuse-runtimes: {"view":0.9145450312644243,"db":5.285897254943848,"backend":10.802048}
DEBUG: header: x-request-id: 3cb6967c-b789-4871-bcf1-bd0ca67942e5
DEBUG: header: x-opensuse-apiversion: 2.11~alpha.20221107T170556.fa77bc968
DEBUG: header: x-download-options: noopen
DEBUG: header: x-runtime: 0.038029
DEBUG: header: x-frame-options: SAMEORIGIN
DEBUG: header: x-content-type-options: nosniff
DEBUG: header: x-opensuse-errorcode: unknown_project
DEBUG: header: x-powered-by: Phusion Passenger(R) 6.0.14
DEBUG: header: status: 404 Not Found
DEBUG: header: content-type: application/xml; charset=utf-8
DEBUG: header: Transfer-Encoding: chunked
Server returned an error: HTTP Error 404: Not Found
Project not found: openSUSE.org:devel:BCI:SLE-15-SP5
```

The project itself can be accessed via `isc api /source/openSUSE.org:devel:BCI:SLE-15-SP5`:
```ShellSession
❯ isc api /source/openSUSE.org:devel:BCI:SLE-15-SP5
<directory>
  <entry name="389-ds-container"/>
  <entry name="alertmanager-image"/>
  <entry name="blackbox_exporter-image"/>
  <entry name="busybox-image"/>
  <entry name="distribution-image"/>
  <entry name="golang-1.18-image"/>
  <entry name="golang-1.19-image"/>
  <entry name="grafana-image"/>
  <entry name="init-image"/>
  <entry name="micro-image"/>
  <entry name="minimal-image"/>
  <entry name="nodejs-14-image"/>
  <entry name="nodejs-16-image"/>
  <entry name="openjdk-11-devel-image"/>
  <entry name="openjdk-11-image"/>
  <entry name="openjdk-17-devel-image"/>
  <entry name="openjdk-17-image"/>
  <entry name="pcp-image"/>
  <entry name="postgres-10-image"/>
  <entry name="postgres-12-image"/>
  <entry name="postgres-13-image"/>
  <entry name="postgres-14-image"/>
  <entry name="prometheus-image"/>
  <entry name="python-3.6-image"/>
  <entry name="rmt-mariadb-client-image"/>
  <entry name="rmt-mariadb-image"/>
  <entry name="rmt-nginx-image"/>
  <entry name="rmt-server-image"/>
  <entry name="ruby-2.5-image"/>
  <entry name="rust-1.64-image"/>
  <entry name="rust-1.65-image"/>
</directory>

```

**Comment by Thaodan** [comment]
Did you try to revert this? I've noticed a similar issue.

The commit causing issues for me was be8a5268a8dfa8613443a8c08c4e79be30d2dd5c.

**Comment by dmach** [comment]
`isc api /source/openSUSE.org:devel:BCI:SLE-15-SP5` works
while `isc api /source/openSUSE.org:devel:BCI:SLE-15-SP5?deleted=0` doesn't (returns 404 as reported)

So the root cause seems to be really in `&deleted=0`.
The related change is d222a38d0353d98c78eb8b10363b27f7a64a3644.
The `deleted=0` was added to fix listing of multibuild packages.
See more details in related OBS issue: https://github.com/openSUSE/open-build-service/issues/9715

**Comment by adrianschroeter** [comment]
what deleted=0 is to workaround an issue by handing over the request to the backend (avoiding processing it to the api).
But it should have actually no effect, since listing the non-deleted ones is default.

Usually this parameter should be used without any = argument. If the deleted exists (eg. ?deleted&something=..) it should list the deleted ones, and if it is not there it should list the not deleted ones.

When you set deleted=0 you just workaround a misbehaviour by an inconsistency of api and backend.

**Comment by dcermak** [comment]
This appears to be fixed now.
