### ISSUE TITLE
Add --keep option to osc build

### ISSUE THREAD

**Issue by frispete** [openSUSE/osc#1209]
I find myself way too often adding some kind of error to the spec in order to keep the build files for further investigation.

Therefore, I kindly ask for a `osc build` option to keep the build structure intact, even if build succeeds. 

This comes handy for a `osc chroot` operation thereafter.

**Comment by dmach** [comment]
@frispete I just realized that this doesn't need a new option.
`osc` calls underlying `(obs-)build` and that calls `rpmbuild`.
It is possible to pass options to `rpmbuild` such as:
```
osc build --buildtool-opt=--noclean
```

Would that work for you?

**Comment by frispete** [comment]
Hi @dmach, thanks for taking care on this.

> Would that work for you?

In general yes, but I'm pretty sure, I will forget about this again, especially in that special moment, when things go south and I'm in a hurry... Hence, for documentation’s sake, it would still be nice to have a --keep option, that uses this mechanism internally.

**Comment by jubalh** [comment]
Or have it added to the man page in some way or another?

**Comment by frispete** [comment]
> Or have it added to the man page in some way or another?

Usually, people might look into --help info at that point, but if it takes longer to find the correct information, and man pages tend to take longer to read, it's cheaper to add `exit 1` at the end of the `%build` section.

**Comment by dmach** [comment]
There's nearly 60 options for `osc build` already, that's why I decided not to add a new one and documented this use case instead.
