### ISSUE TITLE
osc bugowner errors out for packages without a bugowner with HTTP Error 404: Not Found

### ISSUE THREAD

**Issue by dcermak** [openSUSE/osc#1215]
**Describe the bug**

For packages that have no bugowner, osc tries first to search for the bugowner via package name, then via binaries and it looks for a project with that package name, which often results in a 404.

E.g.:
```ShellSession
❯ osc bugowner zellij
Server returned an error: HTTP Error 404: Not Found
Project not found: zellij
```

This error looks odd and occurs via the last API call:
```ShellSession
❯ osc --debug bugowner zellij
makeurl: https://api.opensuse.org ['search', 'owner'] {'package': 'zellij', 'filter': 'bugowner'}
makeurl: https://api.opensuse.org ['search', 'owner'] {'binary': 'zellij', 'filter': 'bugowner'}
makeurl: https://api.opensuse.org ['source', 'zellij', '_meta'] []
Server returned an error: HTTP Error 404: Not Found
HTTPHeaderDict({'Date': 'Wed, 18 Jan 2023 16:52:47 GMT', 'Server': 'Apache/2.4.51 (Linux/SUSE)', 'Strict-Transport-Security': 'max-age=31536000', 'cache-control': 'no-cache', 'vary': 'Accept,Accept-Encoding', 'referrer-policy': 'strict-origin-when-cross-origin', 'x-permitted-cross-domain-policies': 'none', 'x-xss-protection': '1; mode=block', 'x-opensuse-runtimes': '{"view":1.605343073606491,"db":5.064180612564087,"backend":0}', 'x-request-id': '5baf2254-8a74-419a-9c6e-7c57979cd8bd', 'x-opensuse-apiversion': '2.11~alpha.20230118T110247.0860c9af0', 'x-download-options': 'noopen', 'x-runtime': '0.016876', 'x-frame-options': 'SAMEORIGIN', 'x-content-type-options': 'nosniff', 'x-opensuse-errorcode': 'unknown_project', 'x-powered-by': 'Phusion Passenger(R) 6.0.14', 'status': '404 Not Found', 'content-type': 'application/xml; charset=utf-8', 'Transfer-Encoding': 'chunked'})
b'<status code="unknown_project">\n  <summary>Project not found: zellij</summary>\n</status>\n'
Project not found: zellij
```

**Versions**
- Operating system: `(source /etc/os-release; echo $PRETTY_NAME)` Fedora Linux 37 (Thirty Seven)
- Packages: `rpm -q osc` osc-1.0.0~b3-1.fc37.noarch

**To Reproduce**
1. Run command `osc bugowner zellij`
2. See error

**Expected behavior**

Something along the lines of "no bugowner set/found for package zellij"

**Comment by dmach** [comment]
> ❯ osc bugowner zellij
> Server returned an error: HTTP Error 404: Not Found
> Project not found: zellij

Isn't this the correct behavior?
You've specified a **project** that doesn't exist.

I need to double-check what the underlying calls do ...

**Comment by dmach** [comment]
It seems it's a magical command that tries to resolve the input string to something meaningful.
When you provide a `string`,  it seems to be trying project and package.
If you provide `string/string`, it tries only package.

Would you mind closing this issue?
I'd like to improve the behavior, but I don't think it's something on my priority list in the nearby future.
