### ISSUE TITLE
Broken link on "osc mr -h"

### ISSUE THREAD

**Issue by tomschr** [openSUSE/osc#1218]
**Describe the bug**
Run `osc mr -h` and you get this output:

```
$ osc mr -h
maintenancerequest (mr): Create a request for starting a maintenance incident.

[See http://openbuildservice.org/help/manuals/obs-reference-guide/cha.obs.maintenance_setup.html
for information on this topic.]

[... other output pruned ...]
```

The link that is shown in the output doesn't exist anymore.

**Versions**
- Operating system: `(source /etc/os-release; echo $PRETTY_NAME)`: openSUSE Leap 15.4
- Packages: `rpm -q osc`: osc-0.182.0-150100.3.32.1.noarch

**To Reproduce**
1. Run command `osc mr -h`
2. See output and the given link.

**Expected behavior**
The link works and point to https://openbuildservice.org/help/manuals/obs-user-guide/cha.obs.maintenance_setup.html

**Screenshots, console outputs**
n/a

**Additional context**
n/a

**Comment by dmach** [comment]
This was fixed in 2bbb098a8bc249c7858397df682e27365d712c7c already.
The commit is part of the 1.0.0b3 release.
The release has couple issues I'm currently fixing, expect a new one coming soon.
