### ISSUE TITLE
Regression: Multiple removals of tracked files results to Duplicate package error.

### ISSUE THREAD

**Issue by uncomfyhalomacro** [openSUSE/osc#1225]
**Describe the bug**
Removing multiple tracked files can cause a `Duplicate package` error. This does not happen on previous versions of `osc`.

**Versions**
- Operating system: `openSUSE Tumbleweed`
- Packages: `osc-1.0.0~b3-1.1.noarch`

**To Reproduce**
1. Run command `osc rm *.tar.xz`
2. See error `Duplicate package`

**Expected behavior**
Remove multiple tracked files containing the glob/pattern `*.tar.xz`

**Screenshots, console outputs**

![image](https://user-images.githubusercontent.com/66054069/214069022-962d60da-856d-4c0f-9641-6cd5379ae90c.png)

![image](https://user-images.githubusercontent.com/66054069/214069607-314b30ea-8109-463e-8201-b7323095681c.png)

![image](https://user-images.githubusercontent.com/66054069/214070566-fd8aad4e-20ee-43c8-8ce2-6a2454004672.png)

**Comment by dmach** [comment]
This has been fixed in #1220.
I'll make a new release later this week.
In the meantime a build with this change is available in https://build.opensuse.org/project/show/OBS:Server:Unstable.

**Comment by dmach** [comment]
I've added a test for this: #1233
