### ISSUE TITLE
regression: osc build -x -vim no longer valid command

### ISSUE THREAD

**Issue by DimStar77** [openSUSE/osc#1227]
**Describe the bug**

It was not uncommon for me to further debug changes between local and remote builds by excluding the 'extra debug packages' osc adds on local build compared to server builds.

OBS uses this to inject a few packages: `Substitute: obs:cli_debug_packages gdb vim strace less rzsz`

In order to debug locally and be sure I get the same results (gdb and vim both pull in some stuff that sometimes changes the build outcome) I often used:

`osc build -x -vim -x -strace -x -gdb -x -rzsz` To 'remove those packages from the build dep tree'

Since osc 1.0, this no longer works and fails with:

`osc [global opts] build: error: argument -x/--extra-pkgs: expected one argument`

**Versions**
- Operating system: PRETTY_NAME="openSUSE Tumbleweed"
- Packages: osc-1.0.0~b3-1.1.noarch

**To Reproduce**
1. Run command as describe above
2. See error

**Expected behavior**
Build should start, with the negative-list of packages taken into account

**Comment by dmach** [comment]
This is a behavior of python's argparse:
```
import argparse
parser = argparse.ArgumentParser()
parser.add_argument("-x", action="append")
args = parser.parse_args()
print(args.x)
```

This doesn't work: `-x foo -x -bar -x -baz`
This works: `-x foo -x-bar -x=-baz`

I'm afraid we can't fix it easily.
