### ISSUE TITLE
Persistent hdrmd5 mismatches between builds

### ISSUE THREAD

**Issue by bnavigator** [openSUSE/osc#1230]
**Describe the bug**

I am seeing this a lot lately, causing the re-download of some packages on every local `osc build`:

```
28.1% cache miss. 394/548 dependencies cached.

[1/154] (devel:languages:python) python38-pip-22.3.1-1.11.noarch.rpm: 100%|##########################################################################################################| Time: 0:00:00
devel:languages:python/python38-pip: allowing invalid file, probably an OBS bug - hdrmd5 did not match - 0d675712efdf39f805f5df5883704313 != 5e6287d2f64d397a9ef27a682a2aad16
[2/154] (devel:languages:python) python39-pip-22.3.1-1.11.noarch.rpm: 100%|##########################################################################################################| Time: 0:00:00
devel:languages:python/python39-pip: allowing invalid file, probably an OBS bug - hdrmd5 did not match - 03b5b08bd88c633316b80ce712e05ae3 != 6e969fc0b97d29284c429eb3a63d7bd4
...
Verifying integrity of cached packages
using keys from openSUSE:Tumbleweed, devel:languages:python, openSUSE:Tumbleweed:OldKey
WARNING: OBS BUG hdrmd5 mismatch for /var/tmp/osbuild-packagecache/devel:languages:python/openSUSE_Tumbleweed/x86_64/python38-pip-22.3.1-1.11.noarch.rpm: 0d675712efdf39f805f5df5883704313 != 5e6287d2f64d397a9ef27a682a2aad16
WARNING: OBS BUG hdrmd5 mismatch for /var/tmp/osbuild-packagecache/devel:languages:python/openSUSE_Tumbleweed/x86_64/python39-pip-22.3.1-1.11.noarch.rpm: 03b5b08bd88c633316b80ce712e05ae3 != 6e969fc0b97d29284c429eb3a63d7bd4
```

On the next build only a few seconds later:
```
23.5% cache miss. 419/548 dependencies cached.

[1/129] (devel:languages:python) python38-pip-22.3.1-1.11.noarch.rpm: 100%|##########################################################################################################| Time: 0:00:00
devel:languages:python/python38-pip: allowing invalid file, probably an OBS bug - hdrmd5 did not match - 0d675712efdf39f805f5df5883704313 != 5e6287d2f64d397a9ef27a682a2aad16
[2/129] (devel:languages:python) python39-pip-22.3.1-1.11.noarch.rpm: 100%|##########################################################################################################| Time: 0:00:00
devel:languages:python/python39-pip: allowing invalid file, probably an OBS bug - hdrmd5 did not match - 03b5b08bd88c633316b80ce712e05ae3 != 6e969fc0b97d29284c429eb3a63d7bd4
...
```

**Versions**
- Operating system: openSUSE Tumbleweed
- Packages: `osc-1.0.0~b3-1.1.noarch`

**To Reproduce**
1. Run command `osc build`
2. See error

**Expected behavior**
Use the cached packages, they are valid

**Comment by dmach** [comment]
@Firstyear this is related to your #1072. We probably need to improve the behavior:
* these error messages should not show up to most of the osc users
* people who experience frequent hdrmd5 mismatches should have an option to disable checksum checking

**Comment by bnavigator** [comment]
> * people who experience frequent hdrmd5 mismatches should have an option to disable checksum checking

I strongly disagree. It should not be the default to re-download any files just because OBS thinks files are different when they are not and let the user decide to override it. This needs to be fixed.

Might the new occurrence be related to the recent reconfiguration how i586 is/will be handled?

**Comment by Firstyear** [comment]
My warning message is correct 🙃 the issue (from what I have been told) is that when a noarch package is built by different arch workers you can have differences. I think it's something like:

```
i686 -> noarch checksum A
x86_64 -> noarch checksum B
```

The problem being that OBS only publishes one checksum, when the output artefacts have divergent checksums.

As previously mentioned md5's are *not* secure as a cryptographic verification alg, so these checksums are clearly not for security. And they obviously aren't working as a proper check of "did we get the right package".

So what are these hdrmd5s doing anyway? Are they even used? Since they can be ignored, does it even matter?

**Comment by bnavigator** [comment]
> The problem being that OBS only publishes one checksum, when the output artefacts have divergent checksums.

Specifically it keeps the file with a different checksum than the checksum it provides to osc with "here download this and you will get the right package".

**Comment by Firstyear** [comment]
@dmach Any update on this? I think you made some changes recently here didn't you?

**Comment by dmach** [comment]
@Firstyear I have a reproducer and I opened https://github.com/openSUSE/open-build-service/issues/13821.
I don't have any definite fix yet.

**Comment by Firstyear** [comment]
Thanks mate, appreciate it :)

**Comment by bnavigator** [comment]
Gentle ping.

It's really no fun to have to wait for a re-download of 100+ packages on every iteration of `osc build`.

**Comment by dmach** [comment]
Okay, I've submitted a patch that doesn't contain a proper fix (OBS change is needed for that), but fixes a regression from #1072 that caused re-downloading files to cache. When ignoring hdrmd5 on download, it's also a good idea to do the same on cache load.

Also, I've updated the patch with accurate description of what's going on with the hdrmd5 mismatches.

@bnavigator Could you test the patch, please?

**Comment by adrianschroeter** [comment]
..
> The problem being that OBS only publishes one checksum, when the output artefacts have divergent checksums.

yes, and that is wanted that we only publish one noarch.rpm to the mirrors.

> As previously mentioned md5's are _not_ secure as a cryptographic verification alg, so these checksums are clearly not for security. And they obviously aren't working as a proper check of "did we get the right package".

They are not used as security mechanism (we also verify gpg signatures to achieve this), but they are used as identifiers. rpms are defined that way that they provide these md5sum as identifiers in their headers.

> So what are these hdrmd5s doing anyway? Are they even used? Since they can be ignored, does it even matter?

They can not be ignored, we often enough debug issues when noarch rpms were actually not noarch, but differ due to codeing/packaging bugs.

And that is impossible when one can not reproduce the error from the server also on the local machine.

**Comment by bnavigator** [comment]
> They can not be ignored, we often enough debug issues when noarch rpms were actually not noarch, but differ due to codeing/packaging bugs.

When you only publish one, you should only build from that one. And not force osc to download another, over and over again.

**Comment by Firstyear** [comment]
@dmach Do you know when the fix will be released in a new version of osc?

**Comment by adrianschroeter** [comment]
> > They can not be ignored, we often enough debug issues when noarch rpms were actually not noarch, but differ due to codeing/packaging bugs.
> 
> When you only publish one, you should only build from that one. And not force osc to download another, over and over again.

Publishing happens way later in time. Also there might be multiple publish channels (repos, products, image builds, channels,...) and all of them might pick a different package. Also, this is not limited to noarch packages, the same can happen also with rebuild architecture rpms without increased build counter.

**Comment by bnavigator** [comment]
> Publishing happens way later in time.

Doesn't matter. What matters is what is the correct state at the time of building. The served buildinfo must be able to determine the correct pointers for the builder to get the right packages. Serving a different buildinfo than than what the builder can verify is a bug.

**Comment by adrianschroeter** [comment]
???? Yes ... and that is exactly the purpose of the check. We verify that it is the used binary same with the server side build. A published repo can therefore never ever used for verification as it is never used for building (it might not even existyet or never in future).

You may prefer the rpm for third places like any published repo optionally for bandwidth reasons and you may not want to wait for publishing these for building, but that is therefore entirely your decision.

**Comment by bnavigator** [comment]
>  We verify that it is the used binary same with the server side build.

Then make sure to serve the same binary as the server side build uses. That's the whole point of this bug report.

**Comment by Firstyear** [comment]
@bnavigator Is completely correct here.

**Comment by adrianschroeter** [comment]
As written before, the serving of the binary is complete independent, may not happen at all and usually not in the time you want to do the build or even be in contradication to multiple builds. We won't block use local builds until then and won't delay publishing repositories until really all images in entire build service have been finished. We may never reach this state.

You are not fighting against me here, you are fighting reality.

**Comment by bnavigator** [comment]
No, I am not fighting a fundamental law of physics here. I am fighting you to accept that it is a bug in the obs workflow.

If the server-side build can have the correct package, the you MUST be able to serve the local builder with the same information AND package at the same time. Nobody has to predict the future. At time of execution, `osc build` asks the obs API which packages to get for a correct build, and said API answers with a different set of hash values than the same server already uses for server-side builds. Don't tell me that this is a reality I have to accept.

**Comment by bnavigator** [comment]
Btw, you talk about "publishing", when this is actually an issue with "use-for-build".

**Comment by bnavigator** [comment]
@dmach, still an issue BTW. #1267 does not change the default behavior and this comment line is the essence of the argument here:

https://github.com/openSUSE/osc/blob/3828cec5c274fe2230d61e1de2e8cbb14e3afc5f/osc/conf.py#L144-L145

Why must osc download the same wrong package over and over again over the OBS API? Note, not from published reposories, but over the API.

**Comment by adrianschroeter** [comment]
> osc build asks the obs API which packages to get for a correct build, and said API answers with a different set of hash 
> values than the same backend has already used for server-side builds.

No, the api answer for local builds and for server side builds is consistent. This is our highest goal her.

Yes, there was buggy code in osc (which got introduced together with the misleading error message that there is an OBS bug). But Daniel is cleaning this up atm.

Yes, I acknowledge that you have an issue regarding download bandwidth and there should be ways to optimize this. But still, the highest prio is to have consistent builds server and client side. And it is fine if a user want's to opt-out from that to save bandwidth.

But none of use has control over the publishing process as it depends on many implementations and timings which are not under control of anyone. And we definitive can not slow down build processes by days or month, we would just get killed for such a proposal.

**Comment by Firstyear** [comment]
What's the point of the "consistent builds client and server" if the packages the client will eventually get are the ones published and don't match?

Seems a lot like these reproducible builds don't mean much since we just yolo to our clients what they actually end up with.

**Comment by adrianschroeter** [comment]
This is exactly what we rule out, we only use them from the published repos when they are the same. 

Using the published repositories is only done for bandwidth/geo location reasons, otherwise  we would not do it at all.

Therefore, the packages have to match when osc is calling the build script.

**Comment by Firstyear** [comment]
That's not my point.

If I build package A with dependency B that can change between mirror and OBS API, then when I ship package A to users, we don't know which variant of B they will get since there isn't a consistent package that's published.

So the real issue is "what's published can vary" not "lets try to just make obs reproducible".

Reproducible builds should at the least mean "what you build" is "what you get" and currently that's not occuring.

And how this manifests is now, where the "build process" is now getting the "consumer view" and we get bugs like this. 

So either reproducible builds matter, so publishing needs to be fixed to ensure that these noarch published packages are consistent.

Or reproducible builds don't matter (hint, they dont), and so we can ditch this pointless check.

**Comment by adrianschroeter** [comment]
nearly every sentence of this is wrong as I tried to explain before, but I am clearly too stupid to explain this ....

**Comment by Firstyear** [comment]
The point that @bnavigator and I are trying to make is that we want the hdrmd5 check disabled by default because this affects the experience of many people around the world.

So either the hdrmd5 check is "so important" that we can't skip it by default (thus raising why this boolean exists at all).

Or the hdrmd5 check is not important outside extremely niche and hyper specific scenarioes, and to improve the experience of many people around the world *and* reduce load and bandwidth demands on OBS, then we disable this check by default.

**Comment by bnavigator** [comment]
> The point that @bnavigator and I are trying to make is that we want the hdrmd5 check disabled by default

That's not my point. I want the check to succeed. Instead the server tells me to download the wrong file over and over again.

> No, the api answer for local builds and for server side builds is consistent

So why is it not used then? This is not hidden information. The server should be able to tell osc which file it must download. Instead osc pulls the wrong file over and over again.

> The packages get downloaded from mirrors and if their checksum doesn't match from the API.

Obviously wrong here. Look at the posted outputs.


> Yes, I acknowledge that you have an issue regarding download bandwidth

It's not so much my bandwith, it's the bandwith of your servers!

**Comment by bnavigator** [comment]
> Could you give me a reproducer?
> If it downloads wrong packages from the API, then we must fix it.

```shell
osc co devel:languages:python:numeric/python-dask
cd $_
# build1: get all packages and cache them; abort after download is complete and build has started
osc build i586 -M test-py310 --clean >build1.log
# build2: rerun, the packages should all be cached, but there are mismatches
osc build i586 -M test-py310 --clean >build2.log
# build3: rerun, the packages should all be cached, but there are mismatches
osc build i586 -M test-py310 >build3.log
```


[build1.log](https://github.com/openSUSE/osc/files/10938384/build1.log)
[build2.log](https://github.com/openSUSE/osc/files/10938425/build2.log)
[build3.log](https://github.com/openSUSE/osc/files/10938430/build3.log)

**Comment by adrianschroeter** [comment]
> > The point that @bnavigator and I are trying to make is that we want the hdrmd5 check disabled by default
>
> That's not my point. I want the check to succeed. Instead the server tells me to download the wrong file over and over again.

That is a regression in cache handling of osc introduced together with the "OBS BUG" message handling. AFAIK this got fixed by Daniel already in latest git master. Is it still reproducible for you with current git master for you? Or asked the opposite way, which exact osc version do you use atm?

**Comment by bnavigator** [comment]
The above logs were with `osc-1.0.0~b5-1.1` from Tumbleweed.

With ` osc-1.0.0b5+25.git.b0cf1b4` from ` pip install git+http://github.com/openSUSE/osc.git` in a venv, I get a new class of messages on the first try and 0.0% cache miss on the second try. :tada: 

```
Building python-dask.spec for openSUSE_Tumbleweed/i586
Run source service: /usr/lib/obs/service/format_spec_file --outdir /home/ben/src/osc/home:bnavigator:branches:devel:languages:python:numeric/python-dask/tmpsipbdp6l.format_spec_file.service
Run source service: /usr/lib/obs/service/source_validator --outdir /home/ben/src/osc/home:bnavigator:branches:devel:languages:python:numeric/python-dask/tmpg8kmsh7q.source_validator.service
(W) Attention, "osc-git-build1.log" is not mentioned in spec files as source or patch.
###ASK /home/ben/src/osc/home:bnavigator:branches:devel:languages:python:numeric/python-dask/osc-git-build1.log
Getting buildconfig from server and store to /home/ben/src/osc/home:bnavigator:branches:devel:languages:python:numeric/python-dask/.osc/_buildconfig-openSUSE_Tumbleweed-i586
Getting buildinfo from server and store to /home/ben/src/osc/home:bnavigator:branches:devel:languages:python:numeric/python-dask/.osc/_buildinfo-openSUSE_Tumbleweed-i586.xml
Updating cache of required packages
28.3% cache miss. 129/180 dependencies cached.

1/51 (openSUSE:Tumbleweed) filesystem-84.87-12.1.i586.rpm
The file will be redownloaded from the API due to a hdrmd5 mismatch for /var/tmp/osbuild-packagecache/openSUSE:Tumbleweed/dod/i586/filesystem-84.87-12.1.i586.rpm: 1543853e0b01ef943f624c41b8ca474a (actual) != d763670051cff06ae92c48c128c1e0e3 (expected)
2/51 (openSUSE:Tumbleweed) grep-3.9-1.1.i586.rpm
The file will be redownloaded from the API due to a hdrmd5 mismatch for /var/tmp/osbuild-packagecache/openSUSE:Tumbleweed/dod/i586/grep-3.9-1.1.i586.rpm: 837155463325b77347cd0f7783af33fd (actual) != 19b59b41934865885f183ba420602e71 (expected)
3/51 (openSUSE:Tumbleweed) tar-1.34-10.1.i586.rpm
The file will be redownloaded from the API due to a hdrmd5 mismatch for /var/tmp/osbuild-packagecache/openSUSE:Tumbleweed/dod/i586/tar-1.34-10.1.i586.rpm: f063b112cf5c180d95623b8b2d77ff94 (actual) != 90f5cb73ebefbe151aa8b09c670ba5e3 (expected)
4/51 (openSUSE:Tumbleweed) libbz2-1-1.0.8-5.1.i586.rpm
...
```

Instead of telling me that I am delusional of reality, you could have pointed to the existing fix. And you could make a new release.
