### ISSUE TITLE
spammy pkglistgen due to a deprecation warning in osc/connecton.py

### ISSUE THREAD

**Issue by lkocman** [openSUSE/osc#1239]
**Describe the bug**
We seem to be using deprecated call in osc/connection.py API which results into thousands of lines of "converted retries value"
Converted retries value: 3 -> Retry(total=3, connect=None, read=None, redirect=None, status=None)

@DimStar77 mentioned that this only happens with --debug which seems to be the case on botmaster.

He uses following as a local workaround
`pool_kwargs["retries"] = urllib3.Retry(total=int(conf.config["http_retries"])) in osc/connection.py, line 220`
He's worried that it might not work on older versions of urlllib3

**Versions**
latest version of osc

**To Reproduce**
Trigger e.g. 15.5 pkglistgen with --debug (which is default on botmaster) which then uses osc.connecction
https://botmaster.suse.de/go/tab/build/detail/Pkglistgen.openSUSE_Leap_15.5/2417/pkglistgen/1/openSUSE_Leap_15.5_target

**Expected behavior**
not thousands of "converted retries value 3 -> into" notifications in the log

`DEBUG:urllib3.util.retry:Converted retries value: 3 -> Retry(total=3, connect=None, read=None, redirect=None, status=None)
DEBUG:urllib3.connectionpool:https://api.opensuse.org:None "GET /source/openSUSE:Leap:15.5/000update-repos/config.yml?rev=199 HTTP/1.1" 200 4197
DEBUG:urllib3.util.retry:Converted retries value: 3 -> Retry(total=3, connect=None, read=None, redirect=None, status=None)
DEBUG:urllib3.connectionpool:https://api.opensuse.org:None "GET /source/openSUSE:Leap:15.5/000update-repos/_meta HTTP/1.1" 200 None
DEBUG:root:-> do_update
DEBUG:urllib3.util.retry:Converted retries value: 3 -> Retry(total=3, connect=None, read=None, redirect=None, status=None)
DEBUG:urllib3.connectionpool:https://api.opensuse.org:None "GET /source/openSUSE:Leap:15.5/_meta HTTP/1.1" 200 None`

**Screenshots, console outputs**
![spammy_pkglistgen](https://user-images.githubusercontent.com/510119/214874663-591500ba-7caa-4dc1-9ef8-581d20530b51.png)

**Additional context**

**Comment by dmach** [comment]
> He uses following as a local workaround
> `pool_kwargs["retries"] = urllib3.Retry(total=int(conf.config["http_retries"])) in osc/connection.py, line 220`
> He's worried that it might not work on older versions of urlllib3

None if the tests failed, let's give it a try.
If there's an unexpected compatibility issue, we'll fix it later.
