### ISSUE TITLE
sshkey= and agent-forwarding supports only a single key

### ISSUE THREAD

**Issue by olafhering** [openSUSE/osc#1245]
While PR #1135 attempted to support ssh-agent forwarding, the support for agent-forwarding is incomplete. This PR picks the first key in the list, which breaks if `ssh-add -L` lists more than a single key.

I think it is wrong that `sshkey=` in oscrc refers to a file. Instead it should specify the key which was posted on the idp-mfa website. In this case osc should be able to query to local or remote ssh agents to retrieve the key from the list of available keys as needed.

**Comment by dmach** [comment]
@mlschroe IIRC the ssh key auth supports specifying only one key, correct?
The only way to make it work now is that the client would have to try all available keys in subsequent requests.

**Comment by olafhering** [comment]
Just paste the second entry of the `*.pub` file into `sshkey=`. I almost sure, whatever code is processing the `*.pub` files, it will get the exact same information.

That way it is obvious for the user what key is supposed to be used for a given API host.

**Comment by dmach** [comment]
> Would this work for SSH keys that are stored in HW tokens like Yubikey or gpg-agent?

I managed to get the comment exposed in gpg-agent by manually editing `~/.gnupg/private-keys-v1.d/<id>.key`:
change trailing `)))`  to something like this: `))(comment "dmach obs=api.suse.de"))`
Not sure if this can be achieved with a command or if it could work with yubikey.

Possibly related links:

- https://lists.gnupg.org/pipermail/gnupg-users/2016-October/056911.html
- https://dev.gnupg.org/T2760

**Comment by dmach** [comment]
> Just paste the second entry of the `*.pub` file into `sshkey=`. I almost sure, whatever code is processing the `*.pub` files, it will get the exact same information.
> 
> That way it is obvious for the user what key is supposed to be used for a given API host.

Editing pub keys doesn't seem to be a good idea.
ssh-agent reads the comments from the private keys.

What I'm trying to do is to achieve seamless credentials forwarding through ssh-agent - so you can ssh to another host and use osc without configuring the ssh key at all.
