### ISSUE TITLE
osc rdiff traceback and missing expected results

### ISSUE THREAD

**Issue by frispete** [openSUSE/osc#1253]
I would expect to get an output similar to https://build.opensuse.org/package/rdiff/graphics/blender?linkrev=base&rev=453
when executing `osc rdiff -c 453 graphics/blender`, but the result is a traceback with `osc-1.0.0~b3-2.1.noarch` on a fairly recent TW here:

```
Traceback (most recent call last):
  File "/usr/bin/osc", line 33, in <module>
    sys.exit(load_entry_point('osc==1.0.0b3', 'console_scripts', 'osc')())
  File "/usr/lib/python3.10/site-packages/osc/babysitter.py", line 208, in main
    sys.exit(run(commandline.Osc()))
  File "/usr/lib/python3.10/site-packages/osc/babysitter.py", line 56, in run
    return prg.main(argv)
  File "/usr/lib/python3.10/site-packages/osc/cmdln.py", line 262, in main
    cmd(self.options.command, self.options, *self.args)
  File "/usr/lib/python3.10/site-packages/osc/commandline.py", line 4240, in do_rdiff
    rdiff = server_diff_noex(apiurl,
  File "/usr/lib/python3.10/site-packages/osc/core.py", line 5200, in server_diff_noex
    return server_diff(apiurl,
  File "/usr/lib/python3.10/site-packages/osc/core.py", line 5162, in server_diff
    u = makeurl(apiurl, ['source', new_project, new_package], query=query)
  File "/usr/lib/python3.10/site-packages/osc/core.py", line 3472, in makeurl
    return urlunsplit((scheme, netloc, '/'.join([path] + list(l)), query, ''))
TypeError: sequence item 2: expected str instance, NoneType found
```

Next. I tried to address this issue with
```
--- /usr/lib/python3.10/site-packages/osc/commandline.py~       2023-01-17 09:35:55.000000000 +0100
+++ /usr/lib/python3.10/site-packages/osc/commandline.py        2023-02-04 11:26:38.760421515 +0100
@@ -4201,6 +4201,9 @@ Please submit there instead, or use --no
         )
         ensure_no_remaining_args(args)
 
+        if not new_project:
+            new_project = old_project
+
         if not new_package:
             new_package = old_package
 
```

which eliminates the TB, but still does not return the expected diff, but an empty return, aka. `No source changes.`.

Hah, fun, looking into the `osc` commit history, I found 286db02a40, that is looking exactly like my diff from above. Great.

@dmach The new TW release of `osc` is still ongoing. I believe, the result is still wrong, but will check again, when published!

**Comment by dmach** [comment]
@frispete The new osc has landed in TW. Could you try again?

I tried:
```
osc rdiff -c 453 graphics/blender
```

Which translates to:
```
osc api -X POST 'https://api.opensuse.org/source/graphics/blender?cmd=diff&expand=1&oproject=graphics&opackage=blender&orev=452&rev=453&unified=1&filelimit=0&tarlimit=0'
```

And I'm getting an empty result.
Osc from the 0.x-maint branch behaves the same.
If you expect a result here, I suspect a bug in the OBS API.

**Comment by frispete** [comment]
If you click on this [link](https://build.opensuse.org/package/rdiff/graphics/blender?linkrev=base&rev=453), you see the expected result (in pure diff format, not a web render of course), hence I agree, this is an OBS API issue. Will take it there!

**Comment by frispete** [comment]
Done: https://github.com/openSUSE/open-build-service/issues/13805
