### ISSUE TITLE
Checkout of project fails with subdproject checkout with checkout_no_colon

### ISSUE THREAD

**Issue by Thaodan** [openSUSE/osc#1255]
**Describe the bug**

Osc fails to checkout a subproject of a project  ,when checkout_no_colon is true.

**Versions**
- Operating system:  Arch Linux
- Packages:  osc 1.0.0b4

**To Reproduce**
0. checkout_no_colon = True
1. Run command `osc -A <apiurl>  co foobar/bar`
2.  Run command `osc -A <apiurl>  co foobar`
3. See error

**Expected behavior**
No error, checkout works

**Screenshots, console outputs**
osc: project directory 'foo` already exists.

**Additional context**

**Comment by dmach** [comment]
Could you give me an example from build.opensuse.org I could use as a reproducer?
Does osc from the 0.x-maint branch behave the same?

**Comment by Thaodan** [comment]
> Could you give me an example from build.opensuse.org I could use as a reproducer?
Yes I can:
osc -A https://build.opensuse.org  co home:Thaodan:emacs:unstable
osc -A https://build.opensuse.org  co home:Thaodan:emacs

**Comment by Thaodan** [comment]
> Does osc from the 0.x-maint branch behave the same?

Yes same result.

**Comment by dmach** [comment]
@Thaodan could you test the linked pull request?
Please note that using `/` as the separator can cause conflicts:

`home:Thaodan:emacs` project with `unstable` package
would conflict with
`home:Thaodan:emacs:unstable` project
on disk

**Comment by dmach** [comment]
https://github.com/openSUSE/osc/pull/1264 has been merged, closing
