### ISSUE TITLE
osc does not flush stdout before asking questions

### ISSUE THREAD

**Issue by olafhering** [openSUSE/osc#126]
osc build $REPO $ARCH &> log.$REPO.$ARCH.txt

This hangs and nothing in log.$REPO.$ARCH.txt indicates why. I guess its sitting there and asking if its ok to use packages from some  other repo referenced by $REPO. 

It would be nice of whatever is asking for user input does flush stdout before reading from stdin.

**Comment by kiwidude** [comment]
Totally agree! There are more manifestations of the same problem, see
http://lists.opensuse.org/opensuse-buildservice/2015-05/msg00026.html

**Comment by marcus-h** [comment]
This was fixed in the meantime (see commits 22b272f3afc1a3f3b83b764b7745a662bc0aa234
and 56a9ab60dc77f5dcbf1b29b7846c09f8d80c138c).
