### ISSUE TITLE
Avoid the need to cascade over --build-opt to pass build tool options

### ISSUE THREAD

**Issue by rhabacker** [openSUSE/osc#1280]
**Does your feature request relate to a problem? Please describe it.**
With https://github.com/openSUSE/obs-build/pull/923, the obs build tool `build` has been given a new command line option `--buildtool-opt=OPTIONS` to pass generator options (for example, `--rpmfcdebug` to track the rpmbuild dependency generator), which can be used by osc as follows
```sh
osc build --build-opt="--buildtool-opt=OPTIONS" ...
```

**Describe the solution you want**.
To avoid the need to cascade over `--build-opt`, it would be nice if osc had a similar `--buildtool-opt` as mentioned at https://github.com/openSUSE/obs-build/pull/923#issuecomment-1468089075.

**Describe the alternatives you considered**.
No alternative available

**Comment by dmach** [comment]
@rhabacker How can I pass multiple options to rpmbuild this way?
I've implemented `--buildtool-opt` as an append option in osc so you can specify it multiple times.

When I concatenate them and use build's `--buildtool-opt` option only once, I get an error:
```
    if opts.buildtool_opt:
        buildtool_opt_str = " ".join(opts.buildtool_opt)
        buildargs += [f"--buildtool-opt={buildtool_opt_str}"]

$ osc-wrapper.py build --buildtool-opt='--foo' --buildtool-opt='--bar'
exec rpmbuild -ba --define '_srcdefattr (-,root,root)' '--foo --bar' ...
rpmbuild: --foo --bar: unknown option
```

Passing the options individually leads to ignoring all but the last option:
```
    if opts.buildtool_opt:
        buildargs += [f"--buildtool-opt={opt}" for opt in opts.buildtool_opt]

$ osc-wrapper.py build --buildtool-opt='--foo' --buildtool-opt='--bar'
exec rpmbuild -ba --define '_srcdefattr (-,root,root)' --bar
rpmbuild: --bar: unknown option
^^^ no --foo option
```

Doesn't obs-build require an additional fix?

**Comment by rhabacker** [comment]
> osc-wrapper.py build --buildtool-opt='--foo' --buildtool-opt='--bar'

`--foo` and `--bar` is not supported,  you need to add a supported option, try the `--rpmfcdebug` option, mentioned above or

```
   osc build --buildtool-opt="--define '_myvar xyz' "
```

> Doesn't obs-build require an additional fix?

yes, you need to use at least a build tool with https://github.com/openSUSE/obs-build/commit/641a8737585a50dfa96a49f188775342b86aeddc applied.

**Comment by dmach** [comment]
Yes, the `--foo` and `--bar` options do not exist in rpmbuild, I used them to illustrate that one of those get lost along the way. I submitted https://github.com/openSUSE/obs-build/pull/930 that allows specifying multiple options such as:
```
   osc build --buildtool-opt="--define '_myvar xyz' " --buildtool-opt="--define '_another_var QWERTY' "
```

**Comment by rhabacker** [comment]
>  I used them to illustrate that one of those get lost along the way

I see

> I submitted https://github.com/openSUSE/obs-build/pull/930 that allows specifying multiple options such

Thank you for making it available - I will test it on my computer.

**Comment by rhabacker** [comment]
> Thank you for making it available - I will test it on my computer.

Works as expected.
