### ISSUE TITLE
Make it easier to migrate to a new project signing key

### ISSUE THREAD

**Issue by mlschroe** [openSUSE/osc#1283]
Migrating to a new key is currently very unpleasant. The problem is that after creating a new key we have rpms both signed with the old and the new key until a complete rebuild is done (and there were no build failures).

It would be nicer if we are able to offer multiple public keys for a time. We could extend the keyinfo xml so that there can be multiple `<pubkey>` elements.

**Comment by dmach** [comment]
Related to #781
