### ISSUE TITLE
[osc 1.1] each 'osc staging' call triggers a warning

### ISSUE THREAD

**Issue by DimStar77** [openSUSE/osc#1295]
**Describe the bug**
Since the update to osc 1.1.0, every single osc call I execute triggers a warning when the openSUSE-release-tools are configured as plugins

the osr-tools is a 'main' osc plugin (osc-staging.py) plus a library directory, which are both  present in the .osc-plugins directory:

```
> ls -l ~/.osc-plugins 
lrwxrwxrwx 1 dimstar dimstar  61 Jan 16 12:39 osclib -> /home/dimstar/Documents/git-rw/openSUSE-release-tools/osclib//
lrwxrwxrwx 1 dimstar dimstar  68 Jan 16 12:39 osc-staging.py -> /home/dimstar/Documents/git-rw/openSUSE-release-tools/osc-staging.py

```

The warning spit out is:

> Failed to load commands from module 'osc.commands.home.osc-staging': No module named 'osclib'

**Versions**
- Operating system: Tumbleweed
- Packages: osc-1.1.0-1.1.noarch

**Comment by dmach** [comment]
I believe #1293 fixes this.
