### ISSUE TITLE
# diff failed: <status code="400" origin="backend"> <summary>filename '.' is illegal</summary>

### ISSUE THREAD

**Issue by andreas-schwab** [openSUSE/osc#1316]
$ osc diff -c1
# diff failed: <status code="400" origin="backend">
  <summary>filename '.' is illegal</summary>

**Comment by dmach** [comment]
@andreas-schwab I can't reproduce it. Could you be more specific about when exactly the command fails?

**Comment by andreas-schwab** [comment]
Any package working copy.

**Comment by dmach** [comment]
A regression in 1.1.2, I see...
I was trying to reproduce it with the previous version from Factory...
