### ISSUE TITLE
feature: osc maintained <package> -V return the version of the maintained package

### ISSUE THREAD

**Issue by vpereira** [openSUSE/osc#132]
if i want to get all maintained codestreams for a package i do:

`osc maintained <package>`

but then if i want to check the versions, I have to fire a `osc search <package> -V`

would be great to have a `osc maintained <package> -V`
that could answer with something similar:

```
openSUSE:12.3:Update/package (1.2.3)
openSUSE:13.1:Update/package (1.5.6)
openSUSE:13.2:Update/ppackage (x.y.z)
```

or at least a way to reduce the "search" scope just for maintained codestreams (however we would have to bring back the --maintained option). It could be called like:

```
osc search --maintained <package> -V 
```

is that possible or do we have already a way to achieve it?

**Comment by adrianschroeter** [comment]
it is possible to implement that, but it is more then a one liner. Since we need to follow links and ask the backend. Or we start with tracking versions in the DB

**Comment by ketheriel** [comment]
I can implement this next week and use some time in the weekend to check the current API. Is this to implement using the suggested syntax or is there any other way that is prefered?

**Comment by vpereira** [comment]
I still think that its a good syntax

**Comment by ketheriel** [comment]
I am going to take a closer look to the current API and check if we can retrieve package version without having to mess on the obs backend side. 
I don't see issues with implementing 'osc maintained -V <package>'.
