### ISSUE TITLE
osc ci errors out with error 400

### ISSUE THREAD

**Issue by rrahl0** [openSUSE/osc#1333]
When I try to commit anything through osc I get this error 

```
user@localhost:~/osc/home:rrahl0/turtlegit> osc ci
Sending meta data...
Done.
Sending    turtlegit
Sending    turtlegit/_service
Sending    turtlegit/turtlegit.spec
Sending    turtlegit/turtlegit.changes
Sending    turtlegit/env.patch
Transmitting file data .Server returned an error: HTTP Error 400: Bad Request
service validation error: 3:0: ERROR: Invalid attribute mode for element service
10:0: ERROR: Invalid attribute mode for element service

If you lost any edited commit messages due to an error, you may find them here:
  - /home/user/.cache/osc/edited-messages/2023-05-30_10:44:14.961437
```

  Even trying to upload the edited files through the webgui errors out with the same error. If wanted, I can post a screen or log from the gui part.

**Comment by dmach** [comment]
You seem to have an invalid content of the `_service` file.
Could you paste the contents of the file here?

**Comment by rrahl0** [comment]
```
<?xml version="1.0"?>
<services>
  <service name="obs_scm" mode="default">
    <param name="scm">git</param>
    <param name="url">https://gitlab.gnome.org/philippun1/turtlegit.git</param>
    <param name="revision">refs/tags/0.2</param>
    <param name="versionformat">@PARENT_TAG@</param>
    <param name="changesgenerate">enable</param>
  </service>
  <service name="tar" mode="default" />
  <service name="set_version" mode="manual" />
</services>
```
I wonder if this is really the _service file, as this happens with all the packages I want to upload. (tbf, I do have a "template" for the _service file

**Comment by hennevogel** [comment]
@rrahl0 is this with your own OBS installation? 2.10 has a different set of modes.

**Comment by rrahl0** [comment]
@hennevogel no, official build.opensuse.org

**Comment by adrianschroeter** [comment]
just remove the  

  mode="default" 

part. This mode does not exist, but I suppose you want to have the standard behaviour.

**Comment by adrianschroeter** [comment]
but please do not use the standard mode for "tar" service. Esp. without compression.

you may want to use

 mode="buildtime"

for that one.

**Comment by adrianschroeter** [comment]
closing as this is not an osc bug.
