### ISSUE TITLE
user not found

### ISSUE THREAD

**Issue by rrahl0** [openSUSE/osc#1334]
It would be nice to add ASCII chars (all) to passwords, as the webgui already allows this and you are able to login, osc on the other hand just throws an error of user not found. Took me some time to figure out that it is actually the password which gets me to this error.

**Comment by dmach** [comment]
Do you know which characters in your password caused the problem?

**Comment by rrahl0** [comment]
sadly, no. but I created the password with keepassxc advanced and all chars enabled. I created a new account and created a password with 
```
¯?]÷çöÚ×Â&yvä"¸äÝhÁÈöÖ¬Â&ê¾s+×7ék9YÞÈXúÛ¹Q¢°®ÄðfÐñËoJ5~[Ãß7Ã-þi³=®ñÏøñZ_.ð@.C¦vÁÅËøXå¡Ãx)¸fWÀãç~nÓ!ë5´QbC7dÖ"xÐyÕèª.QaÃ»éSÒ\Í5ÍÖ
```

and the same error comes up

**Comment by dmach** [comment]
> ```
> user '<user>' not found
> ```
This probably means that the user doesn't exist on server.

Could you try a standard password that contains only basic ASCII characters and switch to unicode password once everything works?
