### ISSUE TITLE
osc rbl only prints partial log

### ISSUE THREAD

**Issue by Vogtinator** [openSUSE/osc#1346]
I wanted to read the full log of the last FF build, so I ran

```
osc rbl --last openSUSE:Factory MozillaFirefox standard x86_64
```

The output stopped way too early, then there was a delay and I got the prompt back:

```
[  899s] 12:31.64 /home/abuild/rpmbuild/BUILD/obj/dist/include/nsTArray.h:2951:19:   required from ‘CopyableTArray<E>& CopyableTArray<E>::operator=(const CopyableTArray<E>&) [with E = mozilla::dom::workerinternals::JSSettings::JSGCSetting]â
[  899s] 12:31.64 /home/abuild/rpmbuild/BUILD/obj/dist/include/mozilla/dom/workerinternals/JSSettings.h:24:8:   required from here
[  899s] 12:31.64 /home/abuild/rpmbuild/BUILD/obj/dist/include/nsTArray.h:672:13: warning: â
fabian@fabians-envy:~> 
```

I suspected network issues, but curl behaves properly. What actually happened is that the received data was wrongly "decoded" from UTF-8 into UTF-8. curl printed `5D E2 80 99 0A`, but osc wrote `5D C3 A2 C2 80 C2 99 0A`, which is UTF-8 interpreted as Latin-1 reencoded as UTF-8.

The reason for this is actually already explained in a code comment:

https://github.com/openSUSE/osc/blob/03016a6f7b8182e3fe1eaa3dbbd26f8153c3d905/osc/core.py#L6928-L6930

I could confirm this by making the decoding strict instead with `sys.stdout.write(data.decode(encoding="utf-8", errors="strict"))`:

```
[  899s] 12:31.64 /home/abuild/rpmbuild/BUILD/obj/dist/include/nsTArray.h:2951:19:   required from ‘CopyableTATraceback (most recent call last):
  File "/usr/bin/osc", line 33, in <module>
    sys.exit(load_entry_point('osc==1.1.4', 'console_scripts', 'osc')())
  File "/usr/lib/python3.10/site-packages/osc/babysitter.py", line 236, in main
    sys.exit(run(commandline.OscMainCommand()))
  File "/usr/lib/python3.10/site-packages/osc/babysitter.py", line 69, in run
    prg.main(argv)
  File "/usr/lib/python3.10/site-packages/osc/commandline.py", line 531, in main
    cmd.run(args)
  File "/usr/lib/python3.10/site-packages/osc/commandline.py", line 240, in run
    cmd.run(args)
  File "/usr/lib/python3.10/site-packages/osc/commandline.py", line 475, in run
    self.func(args.command, args, *args.positional_args)
  File "/usr/lib/python3.10/site-packages/osc/commandline.py", line 6307, in do_remotebuildlog
    print_buildlog(apiurl, quote_plus(project), quote_plus(package), quote_plus(repository), quote_plus(arch), offset, strip_time, opts.last, opts.lastsucceeded)
  File "/usr/lib/python3.10/site-packages/osc/core.py", line 6951, in print_buildlog
    print_data(data, strip_time)
  File "/usr/lib/python3.10/site-packages/osc/core.py", line 6926, in print_data
    sys.stdout.write(data.decode(encoding="utf-8", errors="strict"))
UnicodeDecodeError: 'utf-8' codec can't decode bytes in position 8190-8191: unexpected end of data
```

Something needs to be done to distinguish partial UTF-8 sequences from invalid ones.

**Comment by dmach** [comment]
> Something needs to be done to distinguish partial UTF-8 sequences from invalid ones.

The solution is actually much more simple.
Decoding data chunks is definitely a bad idea.
What we can do instead is forward the bytes to stdout by  calling `sys.stdout.buffer.write(data)`.

This is broken in several places in osc code, let me fix it everywhere...

**Comment by Vogtinator** [comment]
> What we can do instead is forward the bytes to stdout by calling sys.stdout.buffer.write(data).

I assumed there was some specific reason why decoding is done manually, like some distro using Latin-1 as codec in logfiles... 

For the case of `sys.stdout.encoding != "utf-8"` the decoding would be necessary still but is that even supported?

**Comment by dmach** [comment]
> > What we can do instead is forward the bytes to stdout by calling sys.stdout.buffer.write(data).
> 
> I assumed there was some specific reason why decoding is done manually, like some distro using Latin-1 as codec in logfiles...

I believe it is a result of supporting the code on Python 2 and Python 3 at the same time.
And this is where it went wrong.

> For the case of `sys.stdout.encoding != "utf-8"` the decoding would be necessary still but is that even supported?

We support only utf-8 in osc.
Writing to buffer is the right thing to do now.
If someone comes with a strong reason to support encodings other than utf-8, we'll have to redo a lot of code anyway.
