### ISSUE TITLE
oscrc file cannot handle multiple user accounts for the same server

### ISSUE THREAD

**Issue by pallaswept** [openSUSE/osc#1348]
**Describe the bug**
I wanted to have two different accounts in my oscrc file, so I create separate entries with different username and aliases, for the same URL. When running OSC, I receive a message that there is no username for that URL (it fails to recognise _either_ entry apparently?)

**Versions**
- Operating system: openSUSE Tumbleweed
- Packages: osc-1.1.4-1.2.noarch

**To Reproduce**
1. Make an oscrc something like 

[general]
apiurl = https://my.server

[https://my.server]
aliases = mine, awesome
user=normaluser
credentials_mgr_class=osc.credentials.KeyringCredentialsManager:keyring.backends.SecretService.Keyring

[https://my.server]
aliases = mine_admin, awesome_admin
user=admin
credentials_mgr_class=osc.credentials.KeyringCredentialsManager:keyring.backends.SecretService.Keyring

2) Try to use it like
osc -A mine_admin somecommand
osc -A mine othercommand

3) Note the error that no credentials are present for the alias you provide, and the request for new credentials.

**Expected behavior**
Be able to log in as multiple users without having to edit oscrc every time I switch user

Perhaps there is some error in my syntax but I could not find any documentation to confirm or deny this. Thanks for any help.

**Additional context**
I went looking for documentation but https://github.com/openSUSE/osc/issues/1132

**Comment by dmach** [comment]
This is quite difficult with the current oscrc design.
The `[https://my.server]`  section is unique and must exist only once.

There's something you can use even without changing the code:
* create multiple oscrc files
* create an alias for each, e.g. `alias osc-admin="osc --config=~/.config/osc/oscrc-admin"`

**Comment by pallaswept** [comment]
>     * create multiple oscrc files
> 
>     * create an alias for each, e.g. `alias osc-admin="osc --config=~/.config/osc/oscrc-admin"`

This seems to be a very straightforward workaround and given the difficulty in implementing a true solution, I feel like this can be resolved. Thanks very much for your advice!
