### ISSUE TITLE
TypeError in the error report of run_source_services

### ISSUE THREAD

**Issue by HouzuoGuo** [openSUSE/osc#139]
When executing osc commit on an OpenSUSE 13.2 (version 0.151), a failure of run_source_services raises TypeError with the following stack trace:

<pre>
Traceback (most recent call last):
  File "/usr/bin/osc", line 26, in <module>
    r = babysitter.run(osccli)
  File "/usr/lib/python2.7/site-packages/osc/babysitter.py", line 61, in run
    return prg.main(argv)
  File "/usr/lib/python2.7/site-packages/osc/cmdln.py", line 343, in main
    return self.cmd(args)
  File "/usr/lib/python2.7/site-packages/osc/cmdln.py", line 366, in cmd
    retval = self.onecmd(argv)
  File "/usr/lib/python2.7/site-packages/osc/cmdln.py", line 500, in onecmd
    return self._dispatch_cmd(handler, argv)
  File "/usr/lib/python2.7/site-packages/osc/cmdln.py", line 1230, in _dispatch_cmd
    return handler(argv[0], opts, *args)
  File "/usr/lib/python2.7/site-packages/osc/commandline.py", line 4417, in do_commit
    prj.commit(packages, msg=msg, files=files, skip_local_service_run=skip_local_service_run, verbose=opts.verbose, can_branch=can_branch)
  File "/usr/lib/python2.7/site-packages/osc/core.py", line 931, in commit
    p.commit(msg, verbose=verbose, skip_local_service_run=skip_local_service_run, can_branch=can_branch)
  File "/usr/lib/python2.7/site-packages/osc/core.py", line 1356, in commit
    r = self.run_source_services(mode="trylocal", verbose=verbose)
  File "/usr/lib/python2.7/site-packages/osc/core.py", line 2299, in run_source_services
    r = si.execute(self.absdir, mode, singleservice, verbose)
  File "/usr/lib/python2.7/site-packages/osc/core.py", line 413, in execute
    print("Aborting: service call failed: " + cmd)
TypeError: cannot concatenate 'str' and 'list' objects
</pre>

By putting cmd inside str(), the error message returns normally and says:

<pre>
Aborting: service call failed: ['/usr/lib/obs/service/source_validator', '--outdir', '/tmp/tmp7KPPcL']
A service failed with error: 1
</pre>

**Comment by adrianschroeter** [comment]
On Dienstag, 24. M�rz 2015, 05:26:52 wrote Howard:
> When executing osc commit on an OpenSUSE 13.2 (version 0.151), a failure of run_source_services raises TypeError with the following stack trace:

fixed in 0.151.1 ...
please note that this is just an error in printing an error of your real problem

> <code>
> Traceback (most recent call last):
>   File "/usr/bin/osc", line 26, in <module>
>     r = babysitter.run(osccli)
>   File "/usr/lib/python2.7/site-packages/osc/babysitter.py", line 61, in run
>     return prg.main(argv)
>   File "/usr/lib/python2.7/site-packages/osc/cmdln.py", line 343, in main
>     return self.cmd(args)
>   File "/usr/lib/python2.7/site-packages/osc/cmdln.py", line 366, in cmd
>     retval = self.onecmd(argv)
>   File "/usr/lib/python2.7/site-packages/osc/cmdln.py", line 500, in onecmd
>     return self._dispatch_cmd(handler, argv)
>   File "/usr/lib/python2.7/site-packages/osc/cmdln.py", line 1230, in _dispatch_cmd
>     return handler(argv[0], opts, *args)
>   File "/usr/lib/python2.7/site-packages/osc/commandline.py", line 4417, in do_commit
>     prj.commit(packages, msg=msg, files=files, skip_local_service_run=skip_local_service_run, verbose=opts.verbose, can_branch=can_branch)
>   File "/usr/lib/python2.7/site-packages/osc/core.py", line 931, in commit
>     p.commit(msg, verbose=verbose, skip_local_service_run=skip_local_service_run, can_branch=can_branch)
>   File "/usr/lib/python2.7/site-packages/osc/core.py", line 1356, in commit
>     r = self.run_source_services(mode="trylocal", verbose=verbose)
>   File "/usr/lib/python2.7/site-packages/osc/core.py", line 2299, in run_source_services
>     r = si.execute(self.absdir, mode, singleservice, verbose)
>   File "/usr/lib/python2.7/site-packages/osc/core.py", line 413, in execute
>     print("Aborting: service call failed: " + cmd)
> TypeError: cannot concatenate 'str' and 'list' objects
> </code>
> 
> By putting cmd inside str(), the error message returns normally and says:
> 
> Aborting: service call failed: ['/usr/lib/obs/service/source_validator', '--outdir', '/tmp/tmp7KPPcL']
> A service failed with error: 1
> 
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/openSUSE/osc/issues/139

-- 

Adrian Schroeter
email: adrian@suse.de

SUSE Linux GmbH, GF: Felix Imend�rffer, Jane Smithard, Jennifer Guild, Dilip Upmanyu, Graham Norton, HRB 21284 (AG N�rnberg) 
Maxfeldstra�e 5                         
90409 N�rnberg 
Germany

**Comment by HouzuoGuo** [comment]
thanks Andrian!
