### ISSUE TITLE
Support sparse commits

### ISSUE THREAD

**Issue by dcermak** [openSUSE/osc#1398]
**Is your feature request related to a problem? Please describe.**

This is an enhancement to https://github.com/openSUSE/osc/issues/1397. Assuming that osc could perform a sparse checkout, it would be great if it could also create a commit from a sparse checkout.

**Describe the solution you'd like**

`osc co` should just send the modified files, but not delete the missing (omitted) files.

I guess that osc could maybe reuse `.osc/_files` and mark a certain file as `checked_out="false"`?

**Additional context**

**Comment by dmach** [comment]
Sparse commits are supported already - if a package is marked as `skipped` during checkout, it is not considered during commit.
