### ISSUE TITLE
osc 1.4.1: No option "pass" in oscrc

### ISSUE THREAD

**Issue by jengelh** [openSUSE/osc#1427]
**Describe the bug**

Regression after Tumbleweed upgraded from osc-1.3.1 to 1.4.1:

```
$ osc up
No option 'pass' in section: 'https://api.opensuse.org'
```

**Versions**
- Operating system: openSUSE TW 2023-10-10
- Packages: osc 1.4.1

**To Reproduce**

Let `~/.config/osc/oscrc` contain a section for an arbitrary target (can be api.opensuse.org, but can be any other host).

```
[https://api.opensuse.org]
user=jengelh
trusted_prj=openSUSE:Factory network KDE:Extra
passx=somebase64thing
```

2. run any osc command that involves network.

**Expected behavior**

Don't exit with status $?=1.
Go back to accepting 'passx' or show a re-login prompt.

**Comment by dmach** [comment]
This is clearly a regression - I removed `passx` thinking that it is not used anymore.
Let me revert the change and make a new osc release shortly.

To make it work again immediately, you can do the following:
```
pass=somebase64thing
credentials_mgr_class=osc.credentials.ObfuscatedConfigFileCredentialsManager
```
