### ISSUE TITLE
osc 1.4.1: excess verbosity during `osc up`

### ISSUE THREAD

**Issue by jengelh** [openSUSE/osc#1428]
**Observed behavior**

osc is now doubly verbose (and kinda redundant at that) than it used to be:

```
$ osc co home:jengelh:man/openssl-3
A    home/jengelh/man
A    home/jengelh/man/openssl-3
Please install the progressbar module
Processing: baselibs.conf
A    home/jengelh/man/openssl-3/baselibs.conf
Processing: openssl-3.1.3.tar.gz
A    home/jengelh/man/openssl-3/openssl-3.1.3.tar.gz
Processing: openssl-3.1.3.tar.gz.asc
...
```

**Expected behavior**

More like osc 1.3.1:

```
$ osc co home:jengelh:man/openssl-3
A    home/jengelh/man
A    home/jengelh/man/openssl-3
A    home/jengelh/man/openssl-3/baselibs.conf
A    home/jengelh/man/openssl-3/openssl-3.1.3.tar.gz
...
```

**Versions**
- Operating system: TW 2023-10-10 amd64
- Packages:  osc-1.4.1

**Comment by dmach** [comment]
I've made working with `osc.conf.config` more consistent by enforcing types of the fields.
It fixed progressbars (they're finally showing up now), but as a side effect, it triggered this issue in `osc.meter.NoPBTextMeter` class that is used when the python3-progressbar package is not installed.
