### ISSUE TITLE
osc maintainer could also provide email of bugowner

### ISSUE THREAD

**Issue by mmaslano** [openSUSE/osc#1445]
**Is your feature request related to a problem? Please describe.**
As a TPM I' always looking for bug owners or maintainers, so I can create a bug report with the correct assignee and bugs might be fixed faster.
If I try "osc -A https://api.suse.de maintainer perl", it will provide me with a username, which might be completely different than the BZ email.

**Describe the solution you'd like**
osc maintainer command could look up for email from OSB database based on a new option parameter. Let's say "osc maintainer perl --mail" will give me a mail of the bug owner.

**Describe alternatives you've considered**
I usually go to workday and try to guess from username the real name and then got some email.

**Comment by hennevogel** [comment]
It's already there...

```shell
$ osc maintainer --help |grep email
  -e, --email           show email addresses instead of user names
```

**Comment by dmach** [comment]
Actually, I could make an improvement to the command.
It seems that `osc maintainer -U <user>` takes only login.
We could either re-use `--email` to use an email instead or auto-detect emails and resolve them to logins when there's `@` specified.
