### ISSUE TITLE
Take environment variable for username and password for the initial run

### ISSUE THREAD

**Issue by AvengerMoJo** [openSUSE/osc#1453]
When using osc in a new container e.g. CI in gitea action runner. 
It doesn't provide an interactive way to provide a username and password. Instead, it allows a secret to be created in the environment variable. Since it doesn't make sense to prepopulate the user credentials in the container or a public repo either. 
The possible solution is to either create an interaction script like expect to grab the secret environment variable to use osc, or better the osc cli can take a default username password environment variable before generating the oscrc configuration. 

[The example script of the workaround](https://src.opensuse.org/alexlau/bc-docker-action/src/branch/factory/osc_checkout)

**Comment by dmach** [comment]
Fixed in #1463
