### ISSUE TITLE
Cannot obtain linkdiff

### ISSUE THREAD

**Issue by hramrach** [openSUSE/osc#1468]
**Describe the bug**
Cannot obtain linkdiff

**Versions**
- Operating system: openSUSE Leap 15.5
- Packages: osc-0.182.1-150100.3.35.1.noarch

**To Reproduce**
```
osc co home:michals/sensors.5
cd home:michals/sensors.5
osc linkdiff
```
```
diff working copy against last committed version

Server returned an error: HTTP Error 400: home michals/sensors.5/f9e18b2d22124e93b78e0ad62c16a51c  not in repository. Either not existing or misconfigured server setting for '$nosharedtrees' setting in BSConfig.pm
home:michals/sensors.5/f9e18b2d22124e93b78e0ad62c16a51c: not in repository. Either not existing or misconfigured server setting for '$nosharedtrees' setting in BSConfig.pm
```

**Expected behavior**
There is always a diff, at least when OBS itself can expand the packages.

**Comment by dmach** [comment]
@hramrach could you check if the patch in the pull request fixes your problem and displays what you expect?

**Comment by hramrach** [comment]
Seems to work, thanks
