### ISSUE TITLE
broken build with kvm

### ISSUE THREAD

**Issue by bmwiedemann** [openSUSE/osc#1475]
**Describe the bug**
builds with `OSC_BUILD_ROOT` fail because it uses wrong kernel+initrd.

**Versions**
- Operating system: openSUSE Leap 15.5
- Packages: `osc-1.5.1-150500.399.1.noarch build-20231027-150500.430.1.noarch`

**To Reproduce**
1. as non-root user
2. osc co openSUSE:Factory/libcontainers-common && cd $_
3. OSC_BUILD_ROOT=/var/tmp/build-root.11 osc build --noservice --vm-type=kvm standard

**Expected behavior**
It should allow to build the package in a custom location - and use kernel-obs-build from the build target.

**Screenshots, console outputs**
```
[...]
[    2s] booting kvm...
[    2s] Using UART console
[    2s] /usr/bin/qemu-kvm -nodefaults -no-reboot -nographic -vga none -cpu host -M pc,accel=kvm,usb=off,dump-guest-core=off,vmport=off -sandbox on -object rng-random,filename=/dev/random,id=rng0 -device virtio-rng-pci,rng=rng0 -net none -kernel /boot/vmlinuz -initrd /boot/initrd -append root=/dev/sda rootfstype=ext4 rootflags=noatime no-kvmclock mitigations=off elevator=noop nmi_watchdog=0 rw rd.driver.pre=binfmt_misc oops=panic panic=1 quiet console=ttyS0 init=/.build/build -m 7600 -drive file=/var/tmp/build-root.11/img,format=raw,if=none,id=disk,cache=unsafe -device ide-hd,drive=disk,serial=0 -drive file=/var/tmp/build-root.11/swap,format=raw,if=none,id=swap,cache=unsafe -device ide-hd,drive=swap,serial=1 -serial stdio -chardev socket,id=monitor,server=on,wait=off,path=/var/tmp/build-root.11/img.qemu/monitor -mon chardev=monitor,mode=readline -smp 8
[    2s] qemu: error reading initrd /boot/initrd: Failed to open file “/boot/initrd”: open() failed: Permission denied
[    2s] No buildstatus set, either the base system is broken (kernel/initrd/udev/glibc/bash/perl)
[    2s] or the build host has a kernel or hardware problem...
```

**Additional context**
This bug was found while working on reproducible builds for openSUSE.

**Comment by bmwiedemann** [comment]
Now I could also trigger it with a simple `osc build --clean --noservice --vm-type=kvm standard`

**Comment by bmwiedemann** [comment]
I think, the problem comes from prjconf, that now has `VMinstall: kernel-obs-build` commented out.

**Comment by Vogtinator** [comment]
It's also kind of a bug in osc. It falls back to using the local kernel+initrd, but runs the VM without root privs which means that qemu doesn't have access to the initrd

**Comment by adrianschroeter** [comment]
checked with factory people, it is temporary and should come back.

You might want to check why your fallback kernel and initrd is not working, usually it should. Maybe we can improve the handling in the build script.

However, this is in first place a factory config and build script topic, so closing it here for osc.

**Comment by Vogtinator** [comment]
> You might want to check why your fallback kernel and initrd is not working, usually it should.

See my previous comment.

**Comment by adrianschroeter** [comment]
hm, since when we did not have readable initrd`s anymore? We should maybe created one on the fly then... but that is still a build script topic

**Comment by Vogtinator** [comment]
> hm, since when we did not have readable initrd`s anymore?

Ages.

> We should maybe created one on the fly then... but that is still a build script topic

Possible. Should be as simple as `dracut some/where/initrd`
