### ISSUE TITLE
osc branch on SCM-driven packages does NOT fail and creates empty package

### ISSUE THREAD

**Issue by mcepl** [openSUSE/osc#1478]
**Describe the bug**
`osc branch openSUSE:Factory git-bug home:mcepl` creates https://build.opensuse.org/package/show/home:mcepl/git-bug with no content. There are no error messages displayed anywhere.

**Versions**
- Operating system: `openSUSE Tumbleweed`
- Packages: out of git, commit 9070d03c

**To Reproduce**
1. Run command `osc branch openSUSE:Factory git-bug home:mcepl`
2. Visit the package on the web UI

**Expected behavior**
New SCM-driven package in the right project
OR
Error message

**Screenshots, console outputs**
https://build.opensuse.org/package/show/home:mcepl/git-bug

**Comment by dmach** [comment]
I submitted a pull-request that errors out when branching a scmsync package.
That's something we can do immediately, but in my opinion a proper fix should be made in OBS API.
