### ISSUE TITLE
osc diff outputs zilch for a change that was actually done

### ISSUE THREAD

**Issue by jengelh** [openSUSE/osc#149]
build.opensuse.org network:chromium/chromium changed between rev 734 and 735, chaing %patch102 to #patch102, but osc is broken and shows nothing when calling diff.
```
14:37 ares40:../chromium/chromium > osc up -r734
U    adjust-ldflags-no-keep-memory.patch
At revision 734.
14:37 ares40:../chromium/chromium > grep 102 *spec
Source102:      chromium-browser.xml
Patch102:       skia.patch
%patch102 -p0
        cp -a %{SOURCE102} %{buildroot}%{_datadir}/gnome-control-center/default-apps/

14:37 ares40:../chromium/chromium > osc up -r735
U    chromium.spec
At revision 735.

14:37 ares40:../chromium/chromium > grep 102 *spec
Source102:      chromium-browser.xml
Patch102:       skia.patch
#patch102 -p0
        cp -a %{SOURCE102} %{buildroot}%{_datadir}/gnome-control-center/default-apps/

14:37 ares40:../chromium/chromium > osc diff -r734:735
14:37 ares40:../chromium/chromium > 
```
Package used is osc-0.151.2-11.1.noarch

**Comment by bitstreamout** [comment]
On Tue, May 05, 2015 at 05:39:32AM -0700, jengelh wrote:
> build.opensuse.org network:chromium/chromium changed between rev 734 and 735, chaing %patch102 to #patch102, but osc is broken and shows nothing when calling diff.
> ```
> 14:37 ares40:../chromium/chromium > osc up -r734
> U    adjust-ldflags-no-keep-memory.patch
> At revision 734.
> 14:37 ares40:../chromium/chromium > grep 102 *spec
> Source102:      chromium-browser.xml
> Patch102:       skia.patch
> %patch102 -p0
>         cp -a %{SOURCE102} %{buildroot}%{_datadir}/gnome-control-center/default-apps/
> 
> 14:37 ares40:../chromium/chromium > osc up -r735
> U    chromium.spec
> At revision 735.
> 
> 14:37 ares40:../chromium/chromium > grep 102 *spec
> Source102:      chromium-browser.xml
> Patch102:       skia.patch
> #patch102 -p0
>         cp -a %{SOURCE102} %{buildroot}%{_datadir}/gnome-control-center/default-apps/
> 
> 14:37 ares40:../chromium/chromium > osc diff -r734:735
> 14:37 ares40:../chromium/chromium > 
> ```
> Package used is osc-0.151.2-11.1.noarch

I guess that this was a failure of mine as I've pressed unintentional return without the
end commit for the pull request for the local commit 70a3272915122256ed3c02c7b9ebef7c7312f28e

There is a second pull request which should show 70a3272915122256ed3c02c7b9ebef7c7312f28e
and a third with 13dec0bff3bc06adb6e80b94a883ad6c05e00a90

Sorry

-- 
  "Having a smoking section in a restaurant is like having
          a peeing section in a swimming pool." -- Edward Burr

**Comment by marcus-h** [comment]
On 2015-05-05 05:39:31 -0700, jengelh wrote:

<SNIP>

> 14:37 ares40:../chromium/chromium > osc diff -r734:735
> 14:37 ares40:../chromium/chromium > 
> ```
This is expected, because "osc diff -r734:735" expands both
revisions and there is no change. You could use
"osc rdiff network:chromium chromium -r734:735 -u".
