### ISSUE TITLE
Getting project maintainers broken

### ISSUE THREAD

**Issue by kiwidude** [openSUSE/osc#150]
I want to see who the maintainers are for a project:

`osc maintainer editors`
Empty search result, you may want to search with other or all roles via -r ''

Somewhere between versions 0.145 and 0.151 someone added BINARY to PRJ:
`osc maintainer -h`

>    osc maintainer BINARY <options>
>    osc maintainer PRJ <options>

It used to work in 0.145. The help output tells me it still ought to work.

To me it looks like someone overlayed BINARY, extending functionailty in a hurry, without checking too much whether it breaks existing functionality. And WTF is BINARY anyway? No mention of it. Not a user-friendly implementation of a new feature.

**Comment by AdamMajer** [comment]
Any update on this?

**Comment by lethliel** [comment]
I will look at it...
