### ISSUE TITLE
mod_wsgi application breaks after updating to the latest osc

### ISSUE THREAD

**Issue by s-leon** [openSUSE/osc#1503]
**Describe the bug**
Using the python binding breaks while using `mod_wsgi` for our webapp

**Versions**
- Operating system: SUSE Linux Enterprise Server 15 SP5
- Packages: osc-1.6.1-150500.403.1.noarch, apache2-mod_wsgi-4.7.1-150400.3.9.4.x86_64

**To Reproduce**
Import osc in the wsgi django app to load the config

**Expected behavior**
No crash. Our second app with a similar tech stack but the previous osc version doesn't have the problem.

**Screenshots, console outputs**
```
mod_wsgi (pid=5879): Exception occurred processing WSGI script
Traceback (most recent call last):
File "/usr/lib/python3.6/site-packages/app/wsgi.py", line 22, in <module>
  application = get_wsgi_application()
File "/usr/lib/python3.6/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
  django.setup(set_prefix=False)
[...]
  File "/usr/lib/python3.6/site-packages/osctiny/utils/conf.py", line 20, in <module>
    from osc import conf as _conf
  File "/usr/lib/python3.6/site-packages/osc/conf.py", line 68, in <module>
   from .output import tty
  File "/usr/lib/python3.6/site-packages/osc/output/__init__.py", line 1, in <module>
    from .key_value_table import KeyValueTable
  File "/usr/lib/python3.6/site-packages/osc/output/key_value_table.py", line 1, in <module>
    from . import tty
  File "/usr/lib/python3.6/site-packages/osc/output/tty.py", line 6, in <module>
    IS_INTERACTIVE = os.isatty(sys.stdout.fileno())
OSError: Apache/mod_wsgi log object is not associated with a file descriptor.
```

**Additional context**
We implemented the following hotfix to get the application running again:
`/usr/lib/python3.6/site-packages/osc/output/tty.py`
```
try:
    IS_INTERACTIVE = os.isatty(sys.stdout.fileno())
except OSError:
    IS_INTERACTIVE = False
```

**Comment by dmach** [comment]
Yup, osc expects `sys.stdout` to have a file descriptor,
I'll probably fix it according to your workaround.

@s-leon what's the project you're working on?
Could you point me to the git repo?
I can add it to an osc test that runs pylint checking errors introduced by osc.
Also, if you have any requirements on the osc API, could you open issue(s)? The current API is not perfect and I'm doing my best to refactor it and having requirements/feedback woud be helpful.

**Comment by der-gabe** [comment]
> what's the project you're working on? Could you point me to the git repo?

The project is internal to SUSE. I will provide you the link off-band.

**Comment by crazyscientist** [comment]
I quickly scanned through the `osc` code-base and noticed that the global variable `IS_INTERACTIVE` only gets used once inside the `colorize` function.

Maybe you would like to consider some lazy evaluation instead?

**Comment by dmach** [comment]
> I quickly scanned through the `osc` code-base and noticed that the global variable `IS_INTERACTIVE` only gets used once inside the `colorize` function.
> 
> Maybe you would like to consider some lazy evaluation instead?

I'm planning to use it in more places. I'll use `try...except` for now.
