### ISSUE TITLE
`osc ci` requests 15 times the password from the password store

### ISSUE THREAD

**Issue by cryptomilk** [openSUSE/osc#1507]
**Describe the bug**
I've stored the osc username/password in keepassxc. As it provides a Secret Service. After doing an `osc ci` the dialog from keepassxc that something wants access to the password popped up 15 times for an `osc ci`.

**Versions**
- Operating system: openSUSE Tumbleweed
- Packages: osc-1.6.1-1.1.noarch

**To Reproduce**
1. Setup keepassxc with secret service
2. Store osc password in keepassxc
3. Run command `osc ci`
4. Click 15 times on Accept ;-)

**Expected behavior**
Request the password just once.

**Comment by cyphar** [comment]
(It should be noted that this happens for basically every `osc` operation for me.)

The patch works for me too. I'm also on Tumbleweed (snapshot 2024-03-06), using KeePassXC. I also don't get a traceback.

**Comment by cyphar** [comment]
@dmach Is there any chance we can get that patch merged as a hotfix? Every osc package update overrides the patch and I have to manually fix it each time.

**Comment by dmach** [comment]
> @dmach Is there any chance we can get that patch merged as a hotfix? Every osc package update overrides the patch and I have to manually fix it each time.

Hi, yes, I'll merge this and probably create a maintenance branch for `1.6.x` because `master` contains changes that still require a lot of testing in the staging repo.

**Comment by cyphar** [comment]
Thanks!
