### ISSUE TITLE
Failed run of "osc service manualrun" does not throw non-zero exit code

### ISSUE THREAD

**Issue by marcosbc** [openSUSE/osc#1532]
**Describe the bug**

We are seeing a behavior where a failed execution of `osc service manualrun` does not throw a non-zero exit code. We know that it failed because the output of the command execution contains the following string: `Aborting: service call failed:`.

This makes it hard to determine if the service run succeeded or not, without having to parse the actual output contents. 

**Versions**
- Operating system: openSUSE Tumbleweed
- Packages: osc-1.6.1-2.1.noarch

**To Reproduce**
1. Create a package in an OBS project where you can execute the `osc` command line (e.g. `osc mkpac mypackage`).
2. Create the following `_service` file:

    ```
    <services>
      <service name="replace_using_env" mode="manual">
        <param name="eval">
    echo Forcing error
    exit 1
    </param>
        <param name="file">filename</param>
      </service>
    </services>
    ```

3. See error:

    ```
    $ osc service manualrun
    Forcing error
    Aborting: service call failed:  /usr/lib/obs/service/replace_using_env --eval
    echo Forcing error
    exit 1
     --file filename --outdir /Users/mbjoerkelund/Dev/projects/ibs/home:mbjoerkelund:buildhooks/failed-osc/tmp0gpoy46t.replace_using_env.service
    $ echo $?
    0
    ```

**Expected behavior**

It would be expected for the above execution to have thrown a non-zero exit code, which would have indicated to the shell that the command failed to be executed.

**Screenshots, console outputs**
```
$ osc service manualrun
...
ERROR:obs-service-go_modules:go mod vendor failed
Aborting: service call failed:  /usr/lib/obs/service/go_modules --archive kustomize-kustomize-v*.tar.gz --compression zst --subdir kustomize --vendorname go-vendor --outdir /path/to/project/tmpim1x0sdd.go_modules.service
$ echo $?
0
```

**Additional context**
N/A

**Comment by dmach** [comment]
Thanks for the report and especially for the reproducer, it's awesome!
I only slightly modified it to return `2` because `1` is a common exit code that appears when `obs-service-replace_using_env` is not installed.
