### ISSUE TITLE
osc list -b --verbose does not return MD5 as documented

### ISSUE THREAD

**Issue by rexx-org** [openSUSE/osc#1554]
**Describe the bug**
When issuing "osc list --verbose -b <project> <package> <dist> <arch>" the list of files returned does not include MD5 as is documented in "osc list --help". The output is the same as using "--long" switch in place of "--verbose"

**Versions**
- Operating system: Debian GNU/Linux 11 (bullseye)
- Version: "osc --version" is 0.169.1

**To Reproduce**
1. Run command "osc list --verbose -b home:rexxman Regina-REXX xUbuntu_24.04 x86_64"
2. Look at list; no MD5

**Expected behavior**
The list of files returned from "osc list -b --verbose" should include the MD5 for each file as documented.

**Screenshots, console outputs**
osc list --verbose -b home:rexxman Regina-REXX xUbuntu_24.04 x86_64                                                                                               
```
    63434 May 03 21:14 _buildenv                               
     1015 May 03 21:14 _statistics                             
   279478 May 03 21:14 libregina3-dev_3.9.6-1_amd64.deb        
   287158 May 03 21:14 libregina3_3.9.6-1_amd64.deb            
     1758 May 03 21:14 regina-rexx_3.9.6-1.diff.gz             
      946 May 03 21:14 regina-rexx_3.9.6-1.dsc                 
     5585 May 03 21:14 regina-rexx_3.9.6-1_amd64.buildinfo     
     3998 May 03 21:14 regina-rexx_3.9.6-1_amd64.changes       
   327262 May 03 21:14 regina-rexx_3.9.6-1_amd64.deb           
  2718613 May 03 21:14 regina-rexx_3.9.6.orig.tar.gz
```

osc list --long -b home:rexxman Regina-REXX xUbuntu_24.04 x86_64                                                                                                  
```
    63434 May 03 21:14 _buildenv                               
     1015 May 03 21:14 _statistics                             
   279478 May 03 21:14 libregina3-dev_3.9.6-1_amd64.deb        
   287158 May 03 21:14 libregina3_3.9.6-1_amd64.deb            
     1758 May 03 21:14 regina-rexx_3.9.6-1.diff.gz             
      946 May 03 21:14 regina-rexx_3.9.6-1.dsc                 
     5585 May 03 21:14 regina-rexx_3.9.6-1_amd64.buildinfo     
     3998 May 03 21:14 regina-rexx_3.9.6-1_amd64.changes       
   327262 May 03 21:14 regina-rexx_3.9.6-1_amd64.deb           
  2718613 May 03 21:14 regina-rexx_3.9.6.orig.tar.gz
```

**Comment by dmach** [comment]
It turns out the help text was misleading (OBS API doesn't return md5 for binaries), that's why I clarified the help text.

**Comment by rexx-org** [comment]
That is a shame. An MD5 would be a definitive means of determining if you have already downloaded the package file. Using the size and/or date/time is crude which leads me to download all built files whether I have already downloaded them or not to be sure I am getting the latest built file.
