### ISSUE TITLE
osc getbinaries specifying an individual binary file does not download

### ISSUE THREAD

**Issue by rexx-org** [openSUSE/osc#1555]
**Describe the bug**
When issuing "osc getbinaries <project> <package> <dist> <arch> <file>" and <file> is a .src.rpm the file is not downloaded.

**Versions**
- Operating system: Debian GNU/Linux 11 (bullseye)
- Version: "osc --version" is 0.169.1

**To Reproduce**
1. Run command "osc getbinaries home:rexxman Regina-REXX Fedora_40 x86_64 regina-rexx-3.9.6-240340.1.src.rpm"
2. Do not see "Processing:' prompt and file is not downloaded.

**Expected behavior**
"osc getbinaries" for a specific source RPM should download like any other binary file

**Screenshots, console outputs**
**osc list -b --verbose home:rexxman Regina-REXX Fedora_40 x86_64**                                                                                                   
```
    84230 May 03 21:15 _buildenv                               
     1014 May 03 21:15 _statistics                             
   273302 May 03 21:15 libregina3-3.9.6-240340.1.x86_64.rpm    
   261029 May 03 21:15 libregina3-devel-3.9.6-240340.1.x86_64.rpm
  2511227 May 03 21:15 regina-rexx-3.9.6-240340.1.src.rpm      
   287428 May 03 21:15 regina-rexx-3.9.6-240340.1.x86_64.rpm   
  1310700 May 03 21:15 regina-rexx-doc-3.9.6-240340.1.x86_64.rpm
```
show binary files available.

**osc getbinaries home:rexxman Regina-REXX Fedora_40 x86_64 regina-rexx-3.9.6-240340.1.src.rpm**
returns with no output and no file downloaded.

**osc getbinaries home:rexxman Regina-REXX Fedora_40 x86_64 regina-rexx-3.9.6-240340.1.x86_64.rpm**                                                                   
produces the following output and the file id downloaded into "binaries" directory
```
Please install the progressbar module
Processing: regina-rexx-3.9.6-240340.1.x86_64.rpm
```

**Comment by dmach** [comment]
There are `--sources` and `--debuginfo` options you should use to enable fetching additional files.
Do you think it's fine or would you want me to change behavior of osc to always download the requested file regardless its type?

**Comment by rexx-org** [comment]
If a file is listed in "osc list -b" (list binaries) I should be able to use "osc getbinaries" to download it.  There is an inconsistency in functionality. One command indicates that a src.rpm is a binary file and another command indicates its not a binary.
I would expect that any file generated by OBS that can be installed is a "binary" file and should be included in a list of binaries and be able to be downloaded as a binary file.
Either "osc list -b" is wrong (which I personally disagree with) or "osc getbinaries" is wrong.

**Comment by dmach** [comment]
Hmm, this requires some clarification in the `ls` command's help and possibly other places.
`sources` refer to source control management
`binaries` refer to built packages which include both binary and source RPMs
