### ISSUE TITLE
osc rebuild --all $prj $pkg misbehaviour

### ISSUE THREAD

**Issue by bmwiedemann** [openSUSE/osc#1560]
**Describe the bug**
I often use `osc wipebinaries --all $prj $pkg` and when I (more than once) did `osc rebuild --all $prj $pkg` I found out that it started to rebuild the whole project instead of just the one package as intended.

**Versions**
- Operating system: `(source /etc/os-release; echo $PRETTY_NAME)` openSUSE Tumbleweed-Slowroll
- Packages: `rpm -q osc` osc-1.6.2-1.1.noarch

**To Reproduce**
1. Run command `osc rebuild --all $prj $pkg`
2. See error

**Expected behavior**
When a package name is given, it should not rebuild the whole project, even with `--all`, to be consistent with the behaviour of `wipebinaries` .  A helpful warning or error message would also work.

**Comment by dmach** [comment]
The `--all` option is a safeguard - if you run `osc rebuild` in a project dir, it wants you to specify `--all` to confirm that you really want to rebuild all packages.

Ignoring the package when `--all` is specified is a bug. Let me add a conflict error there.

**Comment by dmach** [comment]
@bmwiedemann does the linked patch look good to you?
