### ISSUE TITLE
How to disable the "running in virtual environment" warning?

### ISSUE THREAD

**Issue by peti** [openSUSE/osc#1584]
Every since updating to osc version 1.7.0 I get the following warning for every command I run:

~~~
$ osc status
Running in virtual environment, skipping loading plugins installed outside the virtual environment.
Running in virtual environment, skipping loading legacy plugins.
~~~

I don't have any extra plugins installed in my `$HOME`,  so I'm not sure what to do about this warning. The extra text screws up all kinds of scripts that I try to run and I'd really like to disable this output. Is there a way to do that other than patching the source code?

**Comment by dmach** [comment]
The text goes to stderr, so it shouldn't cause any problem with captured stdout.
I'll probably turn these into debug messages that wouldn't show up without specifying `--debug`.

What's more important - are you running osc from a virtualenv or is it a bug?
What is the output of the following commands?
```
which osc
python3 -c "import sys; print(sys.real_prefix)"
python3 -c "import sys; print(sys.base_prefix)"
python3 -c "import sys; print(sys.prefix)"
```

**Comment by peti** [comment]
Hi Daniel,

 > The text goes to stderr, so it shouldn't cause any problem with captured stdout.

yeah, that would be great, but it's not my experience I'm afraid.


 > I'll probably turn these into debug messages that wouldn't show up without specifying --debug.

Yes, please! That would be nice.


 > Are you running osc from a virtualenv or is it a bug?

No, I'm not running osc from a virtualenv. It's installed via Nix using setuptools.


 > What is the output of the following commands?

 | $ which osc
 | /nix/var/nix/profiles/default/bin/osc
 |
 | $ python3 -c "import sys; print(sys.real_prefix)"
 | Traceback (most recent call last):
 |   File "<string>", line 1, in <module>
 | AttributeError: module 'sys' has no attribute 'real_prefix'. Did you mean: 'base_prefix'?
 |
 | $ python3 -c "import sys; print(sys.base_prefix)"
 | /nix/store/6b1fqdwb3g56j5pazv8zkx9qd0mv3wiz-python3-3.11.9
 |
 | $ python3 -c "import sys; print(sys.prefix)"
 | /nix/store/cz0bsi2p3rsjkksf1m5bvgp055x8gpyx-python3-3.11.9-env

Cheers, Peter
