### ISSUE TITLE
Wrong error message from osc "'can't open control.tar.zst without python-zstandard"

### ISSUE THREAD

**Issue by Bischoff** [openSUSE/osc#1607]
# Issue Description

When compiling Debian packages without `python3-zstandard` package installed, one gets the error message
```
can't open control.tar.zst without python-zstandard
```
Same problem for LZMA:
```
can't open control.tar.xz without python-lzma
```

Expected Result
============
```
can't open control.tar.zst without python3-zstandard
```

and same for ZLMA.

How to Reproduce
===============

With a Debian package, use e.g. this command
```
osc build xUbuntu_24.04
```

Further Information
===============

source code:

https://github.com/openSUSE/osc/blob/d8bfd4521e724983e6b9acf49f85c2891a756bfd/osc/util/debquery.py#L100

**Comment by dmach** [comment]
I'm going to add weak dependencies on the packages to the spec file, so they get installed by default.
Would that work for you?

**Comment by Bischoff** [comment]
Of course, it would, thank you Daniel.

**Comment by dmach** [comment]
lzma seems to be part of the standard python library
that's why I only added `Recommends:     %{use_python_pkg}-zstandard`
