### ISSUE TITLE
Where is version 1.9.0?

### ISSUE THREAD

**Issue by peti** [openSUSE/osc#1614]
openSUSE Tumbleweed comes with osc version 1.9.0. Citing from https://build.opensuse.org/projects/openSUSE:Factory/packages/osc/files/osc.spec?expand=1:

~~~
Name:           osc
Version:        1.9.0
Release:        0
Summary:        Command-line client for the Open Build Service
License:        GPL-2.0-or-later
Group:          Development/Tools/Other
URL:            https://github.com/openSUSE/osc

Source:         https://github.com/openSUSE/osc/archive/refs/tags/%{version}.tar.gz#/%{name}-%{version}.tar.gz
~~~

Now, unless I read this wrong somehow, this code suggests that there'd be a 1.9.0 version tag in this repository, but I cannot find any. Am I missing something?

**Comment by dmach** [comment]
Thanks for heads-up.
It was a security release that didn't follow the usual release workflow and I forgot to push the tag.
It's fixed now.
