### ISSUE TITLE
"osc vc" not working on OSX

### ISSUE THREAD

**Issue by ojkastl** [openSUSE/osc#177]
Hi everyone,

I can't get 'osc vc' to work on OSX:

$ osc vc
Error: vc ('/usr/lib/build/vc') command not found
Install the build package from http://download.opensuse.org/repositories/openSUSE:/Tools/

I installed osc via Macports, and I can also install a 'build' package, but that does not help.

Any hints? Any steps that I might have missed? Config option somewhere in .oscrc?

Johannes

**Comment by adrianschroeter** [comment]
On Mittwoch, 11. November 2015, 12:19:19 CET wrote ojkastl:
> Hi everyone,
> 
> I can't get 'osc vc' to work on OSX:
> 
> $ osc vc
> Error: vc ('/usr/lib/build/vc') command not found
> Install the build package from http://download.opensuse.org/repositories/openSUSE:/Tools/
> 
> I installed osc via Macports, and I can also install a 'build' package, but that does not help.
> 
> Any hints? Any steps that I might have missed? Config option somewhere in .oscrc?

The "vc" tool should be at that place, if the build package is installed.

If this is not the case the build package is broken. No need to configure something.

Where get you osc and vc packages from exactly?

-- 

Adrian Schroeter
email: adrian@suse.de

SUSE Linux GmbH, GF: Felix Imend�rffer, Jane Smithard, Graham Norton, HRB 21284 (AG N�rnberg) 
 
Maxfeldstra�e 5                         
90409 N�rnberg 
Germany

**Comment by ojkastl** [comment]
Both the osc and the build package are installed via Macports:
https://trac.macports.org/browser/trunk/dports/devel/osc/Portfile, version 0.152.0
https://trac.macports.org/browser/trunk/dports/devel/build/Portfile, version 0.3.10
(The Macports TRAC seems to be down right now)
Macports installs the packages under /opt/local/..., but I do not find any vc in there.

Johannes

**Comment by adrianschroeter** [comment]
k, but we are not the packagers of these packages. Please report it there.

But it is interessting to know that they exist there, thanks :)

**Comment by ojkastl** [comment]
Adrian, 

not very helpful, no offence meant.

I can also clone both osc and obs-build github repos and use them, but then I also have to tell osc where the vc script is. Because I do not want to install stuff into /usr/lib on my mac just to make osc happy, I would prefer to put it somewhere else. And as it seems to be 'just a shell script' that does not need to be installed just leaving it in the git checkout would be enough, *if* I can tell osc were to find it...

Also, it would be very nice if I could give the macport packages some kind of advice on how to change osc's default setting 'vc is in /usr/lib/build/vc'. 

So, how to tell osc where to look for vc?

Johannes

**Comment by adrianschroeter** [comment]
we can have it on MacOS at a different place and hardcode that in osc to use that place on MacOS only.

But that needs interaction with the macport packager and I do not have any clue atm how to reach him.

**Comment by ojkastl** [comment]
It should be raimue@macports.org, according to the output of 'port info osc' on OSX. I'll drop him a line and ask him to join us...

Hardcoding could be a solution, but why not make it configurable? capath and cafile are configurable, too, and I had to set them in .oscrc to get osc to work (at least osc up etc. work).

Johannes

BTW, what would be the preferred way to

**Comment by marcus-h** [comment]
On 2015-11-13 03:29:54 -0800, ojkastl wrote:
> So, how to tell osc where to look for vc?
> 
osc config general vc-cmd /path/to/vc
(or you can also set this manually in your ~/.oscrc).

**Comment by ojkastl** [comment]
sorry, hit the button to soon:

What would be the preferred way to install both osc and build on OSX?

**Comment by adrianschroeter** [comment]
I like to keep config options reduced if not really needed. They create update problems and every other tool using osc would need to be configured as well.

So, let's try to avoid it if possible.

**Comment by ojkastl** [comment]
Hi Marcus,

thanks, I'll have a try. I already wrote to rainer, maybe this can be included in the macports package.

Johannes

**Comment by raimue** [comment]
This issue is now tracked for MacPorts at https://trac.macports.org/ticket/49694.

**Comment by raimue** [comment]
I fixed the 'osc vc' in MacPorts now by providing vc with a separate port called obs-build-helpers.

Additionally I opened #186 to disable the build-cmd completely with build-type='none' for platforms like OS X that do not support running local builds.

```
$ osc build
Error: build command has been disabled for this platform, cannot run local builds
```
