### ISSUE TITLE
Setting SSL cert check off in .oscrc doesn't allow ignoring self-signed certificates

### ISSUE THREAD

**Issue by Conan-Kudo** [openSUSE/osc#179]
When adding `sslcertck = 0` to the `[<apiurl>]` section of `~/.oscrc`, running actions like `osc co` fails with the following output:

```
WARNING: SSL certificate checks disabled. Connection is insecure!

Failed to reach a server:
 [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)
```

It should not fail this way, and instead it should ignore the verification failure, like it does when the option isn't set and I manually tell it to "continue anyways".

**Comment by marcus-h** [comment]
On 2015-11-20 15:05:20 -0800, Neal Gompa (ニール・ゴンパ) wrote:
> When adding `sslcertck = 0` to the `[<apiurl>]` section of `~/.oscrc`, running actions like `osc co` fails with the following output:
> 
> ```
> WARNING: SSL certificate checks disabled. Connection is insecure!
> 
> Failed to reach a server:
>  [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)
> ```
> 
Which python version are you using? This looks like httplib's ssl codepath.

**Comment by Conan-Kudo** [comment]
Python 2.7 on Fedora 22. `osc` is not available as a Python 3 module on Fedora, AFAICT.

**Comment by Conan-Kudo** [comment]
@marcus-h This issue shows up on Fedora 23 and Ubuntu 15.10, too.

**Comment by jberry-suse** [comment]
This seems to still happen, something that needs to be done post the commit?

**Comment by marcus-h** [comment]
On 2017-10-19 04:17:21 +0000, Jimmy Berry wrote:
> This seems to still happen, something that needs to be done post the commit?
> 
Which python version are you using?

**Comment by jberry-suse** [comment]
`2.7.13` while the commit referenced `python >= 2.7.9` so I would think that would apply.

**Comment by jberry-suse** [comment]
I can reproduce in fresh environment:

```
$ docker run --rm -it opensuse:tumbleweed /bin/bash
$ zypper in osc vim
$ osc # enter Admin and opensuse
$ vim ~/.oscrc # change URLS to be non-https local OBS instance
$ osc api /about
WARNING: SSL certificate checks disabled. Connection is insecure!

<about>
  <title>Open Build Service API</title>
  <description>API to the Open Build Service</description>
  <revision>2.8.50</revision>
</about>
```

**Comment by marcus-h** [comment]
On 2017-10-23 21:29:02 +0000, Jimmy Berry wrote:
> I can reproduce in fresh environment:
> 
> ```
> $ docker run --rm -it opensuse:tumbleweed /bin/bash
> $ zypper in osc vim
> $ osc # enter Admin and opensuse
> $ vim ~/.oscrc # change URLS to be non-https local OBS instance
> $ osc api /about
> WARNING: SSL certificate checks disabled. Connection is insecure!
> 
> <about>
>   <title>Open Build Service API</title>
>   <description>API to the Open Build Service</description>
>   <revision>2.8.50</revision>
> </about>
> ```
I'm a bit confused now. The output from above looks ok to me.
Also, the warning is ok, because ssl is disabled (since you
configured a http:// apiurl).

**Comment by jberry-suse** [comment]
My understanding was the whole point was to be able to disable the check using `sslcertck = 0` which does not seem to work.

**Comment by jberry-suse** [comment]
I suppose that is for actually self signed https connections. Rather obtuse that the default local development setup recommended by OBS produces loads of these warnings. Interspersed with log output makes it hard to read.

**Comment by marcus-h** [comment]
On 2017-10-23 22:10:10 +0000, Jimmy Berry wrote:
> My understanding was the whole point was to be able to disable the check using `sslcertck = 0` which does not seem to work.
> 
No, this was about disabling ssl cert validation. Without the
mentioned fix, it is not possible to talk to an api that provides,
for instance, a self-signed certificate (it resulted in an exception
(see also the first message in this thread)).

**Comment by laf0rge** [comment]
could somebody (@marchs-h) please re-open this bug? It happens still (or again?) in 2021.

**Comment by marcus-h** [comment]
On 2022-02-24 13:52:19 -0800, Harald Welte wrote:
> could somebody ***@***.***) please re-open this bug? It happens still (or again?) in 2021.
>
I just re-opened it. "sslcertck = 0" just disables osc's python-M2Crypto
codepath and falls back to python's default ssl implementation. In former
python releases, the defaults were probably a bit more lenient and allowed
self-signed certificates. It seems that this is not the case anymore (which
is good from a security POV).

As a workaround: can't you just enable the sslcertck again? Then, osc
should ask if you want to accept the self-signed certificate. If you do so,
everything should be fine.

**Comment by dmach** [comment]
What behavior are we trying to achieve?

I have a testing OBS instance running in a VM on address obs-server.kanku.site (192.168.36.38)
It has a self-signed certificate.

```
$ rm ~/.config/osc/trusted-certs/obs-server.kanku.site_443.pem
$ osc -A https://obs-server.kanku.site ls
*** certificate verify failed at depth 0
Subject:  /C=CC/ST=OBS Autogen State or Province/L=OBS Autogen Locality/O=OBS Autogen Organisation/OU=OBS Autogen Organizational Unit/CN=obs-server.kanku.site/emailAddress=test@email.address
Issuer:   /C=CC/ST=OBS Autogen State or Province/L=OBS Autogen Locality/O=OBS Autogen Organisation/OU=OBS Autogen Organizational Unit/CN=obs-server.kanku.site/emailAddress=test@email.address
Valid:  Feb 28 11:35:00 2022 GMT - Feb 28 11:35:00 2023 GMT
Fingerprint(MD5):   9D4D5C962DD468E6AA443276AB9B659A
Fingerprint(SHA1):  D8C4A60D1D523E928ADB8197E2D139F1E90C7C6D
Reason: self signed certificate

The server certificate failed verification

Would you like to
0 - quit (default)
1 - continue anyways
2 - trust the server certificate permanently
9 - review the server certificate

Enter choice [0129]: 2
```
-> trust always
no message about self-signed cert is printed
```

$ osc -A https://obs-server.kanku.site ls
```
cert is trusted already
no message about self-signed cert is printed

This is expected: I trust the certificate, I get no warnings.

When I replace the hostname with ip, I get cert validation error, which is expected (ip is not part of the cert)
```
$ osc -A https://192.168.36.38 ls
Certificate Verification Error: Peer certificate subjectAltName does not match host, expected 192.168.36.38, got DNS:obs-server, DNS:obs-server.kanku.site, DNS:localhost
```

After adding `sslcertck = 0` to oscrc, I get:
```
$ osc -A https://192.168.36.38 ls
WARNING: SSL certificate checks disabled. Connection is insecure!
```
And that is also expected.

I've tested similar actions with curl and it behaves the same (at least from my perspective).

I'm still not getting what's wrong with the current behavior.
Could someone provide exact steps that would reproduce the issue?
Or was the problem with older versions of osc?
I'm using osc-0.176.0-1.1.noarch

**Comment by dmach** [comment]
Since there was no response for over 3 weeks, also we're working on a new codebase in #1000 -> closing.
If there's any problem with the new codebase, please open a new issue.
