### ISSUE TITLE
"osc results -w" doesn't wait for finished builds

### ISSUE THREAD

**Issue by toabctl** [openSUSE/osc#180]
According to "man osc", the "-w, --watch" parameter for "osc results" says "watch the results until all finished building". But the command doesn't wait unti all builds are finished.
```
$ osc results --csv -w home:suse-cloud-ci:rpm-packaging-openstack-ef513e8a985aa5929efa96e7c761c70ec7b76684
_;SLE_12/x86_64/unpublished;openSUSE_Tumbleweed/x86_64/building
python-oslo.i18n;unresolvable;building
```

This happens with osc from openSUSE:Tools (version 0.152.0-173.2)

**Comment by marcus-h** [comment]
Fixed in commit f3a1d12a9641acb593e3c751deddde48a8dcbc15.
Thanks for the report!
