### ISSUE TITLE
Upload to PyPI

### ISSUE THREAD

**Issue by techtonik** [openSUSE/osc#183]
Is it possible to upload this to PyPI - https://pypi.python.org/pypi/osc ?

ping @toabctl

**Comment by marcus-h** [comment]
Hmm there is not much we can do here - maybe the best is to contact
the pypi maintainer directly. I'm closing this for now (if you don't
agree, feel free to reopen it).

**Comment by techtonik** [comment]
@marcus-h, the maintainer is @toabctl from your openSUSE organization. Can you contact him?

**Comment by toabctl** [comment]
hey. I'm happy to upload osc to pypi. Btw. this was the reason why I registered ```osc```. To upload the tool from openSUSE. Just forgot about it.

**Comment by techtonik** [comment]
I'd say that the first step is to upload to PyPI then automate it somehow later. =)
