### ISSUE TITLE
"osc in <package>" fails with confusing error message

### ISSUE THREAD

**Issue by okurz** [openSUSE/osc#185]
## observation
```
osc in <package>
```
fails with
```
osc in <package>
Traceback (most recent call last):
  File "/usr/bin/osc", line 41, in <module>
    r = babysitter.run(osccli)
  File "/usr/lib/python2.7/site-packages/osc/babysitter.py", line 61, in run
    return prg.main(argv)
  File "/usr/lib/python2.7/site-packages/osc/cmdln.py", line 343, in main
    return self.cmd(args)
  File "/usr/lib/python2.7/site-packages/osc/cmdln.py", line 366, in cmd
    retval = self.onecmd(argv)
  File "/usr/lib/python2.7/site-packages/osc/cmdln.py", line 500, in onecmd
    return self._dispatch_cmd(handler, argv)
  File "/usr/lib/python2.7/site-packages/osc/cmdln.py", line 1230, in _dispatch_cmd
    return handler(argv[0], opts, *args)
  File "/usr/lib/python2.7/site-packages/osc/commandline.py", line 3958, in do_install
    (re.sub(':', ':/', args[0]), 'openSUSE_11.4', args[1])
IndexError: list index out of range
```

## expected result
one ore more of
* completely remove "install" if broken
* yield error message that install is not supported
* provide hint to https://github.com/jnweiger/osc-plugin-install
* include https://github.com/jnweiger/osc-plugin-install into OSC

**Comment by marcus-h** [comment]
I removed the command in commit 8a78be684ea73ddb34e5f97827898ae534f740a1.
Thanks for the report!

**Comment by okurz** [comment]
nice, thank you. What about following on "option 3" or "option 4", including https://github.com/jnweiger/osc-plugin-install into OSC?

**Comment by marcus-h** [comment]
On 2016-02-05 05:44:05 -0800, Oliver Kurz wrote:
> nice, thank you. What about following on "option 3" or "option 4", including https://github.com/jnweiger/osc-plugin-install into OSC?
> 
To be honest, I don't know the current state of this plugin (just from
looking at the source, I would say it is a bit out of date (e.g. it
refers to openSUSE 11.X and 12.Y etc.)). Also, I think Juergen explicitly
moved it into a separate plugin.

**Comment by okurz** [comment]
Yes, I can just say it works quite nicely for me. The references to old versions are for an old lookup approach which is not relevant for compatibility with recent versions, it works anyway.
