### ISSUE TITLE
urlgrabber not recognized on OS X 

### ISSUE THREAD

**Issue by m0yellow** [openSUSE/osc#192]
I'm trying to use osc on Mac OS X (10.11.4 / 15E65), with current macports (2.3.4),
and I just installed (after error message) py-celementtree and py-urlgrabber.

the error of py-celementtree goes away, the one about py-urlgrabber stays.

```
Traceback (most recent call last):
  File "setup.py", line 10, in <module>
    from osc import babysitter
  File "/Users/<redacted>/osc/osc/babysitter.py", line 14, in <module>
    from urlgrabber.grabber import URLGrabError
ImportError: No module named urlgrabber.grabber
```
Any hint what is missing in the setup?

**Comment by marcus-h** [comment]
On 2016-03-22 13:41:57 -0700, Matthias Šubik wrote:
> 
> ```
> Traceback (most recent call last):
>   File "setup.py", line 10, in <module>
>     from osc import babysitter
>   File "/Users/<redacted>/osc/osc/babysitter.py", line 14, in <module>
>     from urlgrabber.grabber import URLGrabError
> ImportError: No module named urlgrabber.grabber
> ```
> Any hint what is missing in the setup?
> 
This indicates that the urlgrabber module is still missing. Did you install
the "python 2.7 version" of the urlgrabber module?

**Comment by m0yellow** [comment]
This is what I have in my system, and yes, there is more than one python (see below) as both are installed as dependencies on other ports.

```
port installed | grep urlgrabber
  py-urlgrabber @3.10.1_0 (active)
  py27-urlgrabber @3.10.1_0 (active)
```

```
  python27 @2.7.11_2+universal (active)
  python34 @3.4.4_0+universal (active)
```

**Comment by marcus-h** [comment]
Does the following command also fail?

python2.7 -c "from urlgrabber.grabber import URLGrabError"

(explicitly execute it with the 2.7 interpreter)

**Comment by m0yellow** [comment]
I guess it works.

```
python2.7 -c "from urlgrabber.grabber import URLGrabError" && echo "ok"
ok
```

**Comment by marcus-h** [comment]
On 2016-03-22 14:09:26 -0700, Matthias Šubik wrote:
> I guess it works.
> 
> ```
> python2.7 -c "from urlgrabber.grabber import URLGrabError" && echo "ok"
> ok
> ```

Looks good. Can you try to execute the osc script with the python2.7 binary
as well? Something like: python2.7 /usr/bin/osc (or wherever it is installed)

**Comment by m0yellow** [comment]
thx! 
that works. It seems to be a conflict between the apple delivered python, and the macport delivered python. 2.7.10 vs. 2.7.11.
