### ISSUE TITLE
FR: osc sr should output URL to created request

### ISSUE THREAD

**Issue by aspiers** [openSUSE/osc#194]
Currently it just outputs something like

```
created request id 386220
```

but it would be much more user-friendly if it also outputted the URL:

```
https://build.opensuse.org/request/show/386220
```

so that the submitter can immediately visit it in the browser.

**Comment by marcus-h** [comment]
On 2016-04-08 03:04:13 -0700, Adam Spiers wrote:
> Currently it just outputs something like
> 
>     created request id 386220
> 
> but it would be much more user-friendly if it also outputted the URL:
> 
>     https://build.opensuse.org/request/show/386220
> 
Depends on the user;) it wouldn't really fit to my workflow, because
I usually continue with processing the reqid on the cmdline (so I could
easily "copy" by just double clicking on it - with your proposed change
I would need to "carefully" select reqid;) ) (but that's a lame excuse
for rejecting this...).
From a technical POV, it should be doable (we can get the url via the
/configuration route).

> so that the submitter can immediately visit it in the browser.
> 
Out of curiosity: why do you want to do this?:)

**Comment by adrianschroeter** [comment]
Just want to support Marcus and say that I use also the double click to get the number. We could make this an optional feature of course ....

**Comment by aspiers** [comment]
Marcus Hüwe wrote:
> Depends on the user;)

True :-)

> it wouldn't really fit to my workflow, because
> I usually continue with processing the reqid on the cmdline (so I could
> easily "copy" by just double clicking on it - with your proposed change
> I would need to "carefully" select reqid;) )

Not really, because I'm not proposing to remove the existing line of
output, merely to add a new one.

> From a technical POV, it should be doable (we can get the url via the
> /configuration route).
> 
> > so that the submitter can immediately visit it in the browser.
> > 
> Out of curiosity: why do you want to do this?:)

One or more of the following:

-   To keep an eye on the builds if for some reason I prefer to do that
    in the browser than via "osc r -vw".
-   To double-check I got everything right (it's easier to visually
    review in the web-rendered UI than "osc linkdiff" or similar)
-   To browse around the source or destination package/project
-   To share the URL with someone else
-   To cross-reference the request from another system, e.g. via
    https://github.com/aspiers/desktop-config/blob/master/lib/browser/userscripts/page-id-helpers/README.md

I'm sure there are other use cases.

**Comment by aspiers** [comment]
@adrianschroeter As per my previous comment, I am not proposing to remove the number from the output which you currently double-click on.  That's why I used the word "**also**" in my original description :-)
