### ISSUE TITLE
osc sr submits request even if superseding is impossible

### ISSUE THREAD

**Issue by aspiers** [openSUSE/osc#195]
```
$ osc sr -s 386220 
Waiting for Emacs...
Server returned an error: HTTP Error 403: Forbidden
set state to superseded from a final state is not allowed.
```

but then https://build.opensuse.org/request/show/386223 got created anyway.  It should check for a final state before submitting, not after.  (Even if you disagree with this, there's still the bug that it failed to output the number of the newly created request.)

**Comment by lethliel** [comment]
I don't think that it should abort. 

The newly created request ID is printed: 

```
osc sr -s 766585 home:mstrigl test-osc
created request id 766587
Server returned an error: HTTP Error 403: Forbidden
change state from an accepted state is not allowed.
```
