### ISSUE TITLE
osc.core.get_request_list: illegal token when using exclude_target_projects parameter

### ISSUE THREAD

**Issue by andreasstieger** [openSUSE/osc#205]
osc.core.get_request_list throws an illegal token api error when using exclude_target_projects parameter.

My code:

    reqs = get_request_list(apiurl, dprj, dpkg, req_state=('new', 'review'), exclude_target_projects=['openSUSE:Leap:42.2'] )

Generates the following debug:

    GET https://api.opensuse.org/search/request?match=%28state%2F%40name%3D%27new%27+or+state%2F%40name%3D%27review%27%29+and+%28action%2Ftarget%2F%40project%3D%27openSUSE%3ALeap%3A42.1%3AUpdate%27+or+submit%2Ftarget%2F%40project%3D%27openSUSE%3ALeap%3A42.1%3AUpdate%27+or+action%2Fsource%2F%40project%3D%27openSUSE%3ALeap%3A42.1%3AUpdate%27+or+submit%2Fsource%2F%40project%3D%27openSUSE%3ALeap%3A42.1%3AUpdate%27%29+and+%28action%2Ftarget%2F%40package%3D%27squid%27+or+submit%2Ftarget%2F%40package%3D%27squid%27+or+action%2Fsource%2F%40package%3D%27squid%27+or+submit%2Fsource%2F%40package%3D%27squid%27%29+and+%28not%28action%2Ftarget%2F%40project%3D%27openSUSE%3ALeap%3A42.2%27+or+submit%2Ftarget%2F%40project%3D%27openSUSE%3ALeap%3A42.2%27%29%29
    Server returned an error: HTTP Error 400: Bad Request
    Date: Wed, 01 Jun 2016 12:07:46 GMT
    Server: Apache/2.4.16 (Linux/SUSE)
    Strict-Transport-Security: max-age=31536000
    Cache-Control: no-cache
    Vary: Accept-Encoding
    X-XSS-Protection: 1; mode=block
    X-Opensuse-Runtimes: {"view":1.4730661641806364,"db":2.699614,"backend":0,"xml":0}
    X-Request-Id: 530a849b-88cb-4168-a986-51be8b318feb
    X-Opensuse-APIVersion: 2.7.51.git20160518.b696773
    X-Runtime: 0.014364
    X-Frame-Options: SAMEORIGIN
    X-Content-Type-Options: nosniff
    X-Opensuse-Errorcode: illegal_xpath_error
    X-Powered-By: Phusion Passenger 5.0.22
    Status: 400 Bad Request
    Content-Type: application/xml; charset=utf-8
    Connection: close
    Transfer-Encoding: chunked
    
    <status code="illegal_xpath_error">
      <summary>illegal token: ':or'</summary>
    </status>
        
    illegal token: ':or'

**Comment by andreasstieger** [comment]
Code was added in c6b74d6425529b47c18cc14786ad1e26d6e59e16

**Comment by adrianschroeter** [comment]
This is in first place an api bug. api search implementation of "not()" is currently not supporting any expressions inside, just pure existens checks.

**Comment by adrianschroeter** [comment]
This should fix it:  https://github.com/openSUSE/open-build-service/pull/1864
