### ISSUE TITLE
osc review operates on all review types

### ISSUE THREAD

**Issue by jengelh** [openSUSE/osc#215]
Suppose request 123456 has review open for multiple users/groups. When you do `osc review show -i 123456` and accept/decline it, osc will ask for which actor the review shall be made.

```
Please chose one of the following reviews:
(0) by Group      legal-team
(1) by Group      opensuse-review-team
(2) by User       factory-repo-checker(factory-repo-checker)
(3) by Project    openSUSE:Factory:Staging:adi:15
> 
```

So far so good, but it does not do this when using the non-interactive mode, in which case it attempts to set the accept/decline flag for _more than one_ review, like

```
$ sosc review decline 414374 -m "License: GPL-3.0"
No permission on review by group legal-auto
No permission on review by group factory-auto
No permission on review by group factory-staging
No permission on review by group legal-team
ok
No permission on review by user factory-repo-checker
```

**Comment by marcus-h** [comment]
On 2016-07-23 05:31:38 -0700, jengelh wrote:
> Suppose request 123456 has review open for multiple users/groups. When you do `osc review show -i 123456` and accept/decline it, osc will ask for which actor the review shall be made.
> ```
> Please chose one of the following reviews:
> (0) by Group      legal-team
> (1) by Group      opensuse-review-team
> (2) by User       factory-repo-checker(factory-repo-checker)
> (3) by Project    openSUSE:Factory:Staging:adi:15
> > 
> ```
> So far so good, but it does not do this when using the non-interactive mode, in which case it attempts to set the accept/decline flag for *more than one* review, like
> ```
> $ sosc review decline 414374 -m "License: GPL-3.0"
> No permission on review by group legal-auto
> No permission on review by group factory-auto
> No permission on review by group factory-staging
> No permission on review by group legal-team
> ok
> No permission on review by user factory-repo-checker
> ```
If you want to accept/decline a specific review, you can specify it via
a cmdline option. For instance, "osc review accept 1234 -G legal-team".
We could add a config option such that it asks in the non-interactive
review case as well (if no cmdline option was specified).

What do you think?

**Comment by dmach** [comment]
@jengelh is the `-G` option sufficient for you or were you looking for something else?

**Comment by jengelh** [comment]
I guess it will do for now.
