### ISSUE TITLE
How do I use osc as a python3 package ?

### ISSUE THREAD

**Issue by black-perl** [openSUSE/osc#222]
`osc` seems to work fine with **python 2.7** and I can use it as a module. But for **python 3.3** I am unable to build it locally and use it as a module. I guess the issue is with the dependency urlgrabber. It would be great if you can help me making it work ?

**Comment by marcus-h** [comment]
On 2016-08-16 10:45:03 -0700, Ankush Sharma wrote:
> `osc` seems to work fine with python 2.7 and I can use it as a module. But for python3 I am unable to build it locally and use it as a module. I guess the issue is with the dependency urlgrabber. Can anybody help me making it work ?
> 
I never tried to use it as a python3 module, but in the past some
code was ported so that it works with python3 as well. Can you post
the concrete error message and/or a concrete example?

**Comment by black-perl** [comment]
Hi, thanks for replying. I mean I can use osc as python3 by pulling out the osc module but cannot install it on the system by building it. 
Also, I faced an issue after installing one of the deps `M2Crypto`:

```Python
ImportError: /usr/local/lib/python3.4/dist-packages/M2Crypto-0.25.1-py3.4-linux-x86_64.egg/M2Crypto/__m2crypto.cpython-34m.so: undefined symbol: SSLv2_method
```
Can you help in this regard ?

**Comment by marcus-h** [comment]
On 2016-08-17 09:34:56 -0700, Ankush Sharma wrote:
> Hi, thanks for replying. I mean I can use osc as python3 by pulling out the osc module but cannot install it on the system by building it. 

Hmm what do you exactly mean? Do you have a concrete error
message?

> Also, I faced an issue after installing one of the deps `M2Crypto`:
> 
> ```Python
> ImportError: /usr/local/lib/python3.4/dist-packages/M2Crypto-0.25.1-py3.4-linux-x86_64.egg/M2Crypto/__m2crypto.cpython-34m.so: undefined symbol: SSLv2_method
> ```
> Can you help in this regard ?
> 
This looks like your installed m2crypto version doesn't fit to your
installed libopenssl lib (or the other way around).

**Comment by black-perl** [comment]
Okay, I got a work around.

**Comment by marcus-h** [comment]
Ok. Closing.
