### ISSUE TITLE
osc.core.get_package_results wrong xml parsing

### ISSUE THREAD

**Issue by ssedlmaier** [openSUSE/osc#224]
In get_package_results the current state of a package is requested from the backend. Such a result looks like this:
```xml
<resultlist state="bd471b0415abaae7a369c8f21139589a">
    <result project="<projectname>" repository="<reponame>" arch="<arch>" code="published" state="published">
        <status package="<packagename>" code="succeeded"/>
    </result>
</resultlist>
```
Now the attribute ' repostate' of the element 'result' is tested for equality to 'published'. Because the attribute isn't defined this test will always be false.
I would like to know how this function is intended to work, because aside this mistake I assume that the 'code' attribute of the 'result' element and the 'status' element are mixed up.
If I get a clear impression how this function should work I would be able to make the changes by myself.

**Comment by marcus-h** [comment]
On 2016-08-17 08:19:54 -0700, ssedlmaier wrote:
> Now the attribute ' repostate' of the element 'result' is tested for equality to 'published'. Because the attribute isn't defined this test will always be false.
> I would like to know how this function is intended to work, because aside this mistake I assume that the 'code' attribute of the 'result' element and the status 'element' are mixed up.

Yes and repostate was supposed to be the "code" attribute of the result
node.

> If I get a clear impression how this function should work I would be able to make the changes by myself.
> 
Apart from the above error, the whole check was nonsense. For the
whole story, please have a look at the message of commit
e7dc0c740a60bb7f0e4ae2a77754af92f2367ea7 (which fixes this issue).
Thanks for the detailed report!

**Comment by ssedlmaier** [comment]
Perfect!
Thank you!
