### ISSUE TITLE
While OSC is python 3 friendly URLGrabbber is not therefore osc can't be used with Python 3

### ISSUE THREAD

**Issue by AJDempsey** [openSUSE/osc#226]
Looking through the code there's a lot of code based around URLGrabber has there been any thought put into moving away from URLGrabber to something like requests?

I've been messing around with the meter.py file to try and replace the progress bar with something which should be friendlier to python 3 using https://github.com/niltonvolpato/python-progressbar (https://pypi.python.org/pypi/progressbar) and it works about the same as the URLGrabber code except: 
1) it fills the whole of my terminal where as the URLGrabber takes up a bit less space; 2) The download eta has Time: HH:MM:SS instead of just HH:MM:SS once the file has downloaded.

I've attached the quick hack I've done to meter.py to remove URLGrabber.

[progressbar_meter.txt](https://github.com/openSUSE/osc/files/435395/progressbar_meter.txt)

**Comment by marcus-h** [comment]
On 2016-08-24 11:16:20 -0700, Anthony Dempsey wrote:
> Looking through the code there's a lot of code based around URLGrabber has there been any thought put into moving away from URLGrabber to something like requests?
> 
Hmm I haven't thought about switching so far... what's wrong with
fixing/adding python3 support to urlgrabber instead?:)

> I've attached the quick hack I've done to meter.py to remove URLGrabber.
> 
Well it only removes the dependency from the meter module. A
class in the fetch.py also relies on urlgrabber.

**Comment by AJDempsey** [comment]
It looks like there's been a few attempts to add support for python 3 to urlgrabber but the project seems to have been dropped. (https://bugzilla.redhat.com/show_bug.cgi?id=985288 http://lists.baseurl.org/pipermail/yum-devel/2014-June/010653.html http://lists.baseurl.org/pipermail/yum-devel/2014-June/010638.html 
http://lists.baseurl.org/pipermail/yum-devel/2014-August/010675.html )

I'll look at how easy it'll be to remove urlgrabber from the fetch.py as well. (It might take me a while to understand everything the code is doing)

**Comment by Conan-Kudo** [comment]
@AJDempsey [urlgrabber moved to GitHub](https://github.com/rpm-software-management/urlgrabber) a few months ago, so you may want to give a go at making a pull request to fix it up.

**Comment by rustydb** [comment]
@AJDempsey I'm using Py3 and OSC and have hit this problem. Did you happen to make any progress with removing urlgrabber? :)

**Comment by Conan-Kudo** [comment]
Well, we also need M2Crypto to finish porting to Python 3 as well... https://gitlab.com/m2crypto/m2crypto/merge_requests/65

**Comment by mcepl** [comment]
> Well, we also need M2Crypto to finish porting to Python 3 as well... https://gitlab.com/m2crypto/m2crypto/merge_requests/65

It happened, M2Crypto 0.28.2 supports Python 3.3 and above.

**Comment by nickbroon** [comment]
Fixed by #387 ?

**Comment by AJDempsey** [comment]
As there's on going work on this https://github.com/openSUSE/osc/commits/python3 I think this issue can be closed. I'll keep an eye on the development branch
