### ISSUE TITLE
openSUSE build system can't display all request,

### ISSUE THREAD

**Issue by qiangzhao** [openSUSE/osc#231]
Recent days, 
openSUSE build system can't display all request in a person's home page.
Could you help to solve this ?
Thanks !

**Comment by marcus-h** [comment]
On 2016-09-22 20:35:23 -0700, qzhao wrote:
> Recent days, 
> openSUSE build system can't display all request in a person's home page.

Hmm about which "osc" command are you talking (or are you talking about
the webui)?

**Comment by qiangzhao** [comment]
I mean on the website, my home page.
But it's already worked for these days.
