### ISSUE TITLE
osc build foo creates "unneeded" directory in ~/

### ISSUE THREAD

**Issue by zaitor** [openSUSE/osc#232]
Whenever I do osc build foo, I get a new directory in my homefolder called 
rpmbuild.

From what I can tell, there is no reason for this to be created since the build takes place in 
/var/tmp/build-root/.

The culprit seems to be services, since doing 
osc build foo --no-service 
does not created the "offending" dir.

**Comment by marcus-h** [comment]
On 2016-09-27 08:57:52 -0700, Bjørn Lie wrote:
> Whenever I do osc build foo, I get a new directory in my homefolder called 
> rpmbuild.
> 
> From what I can tell, there is no reason for this to be created since the build takes place in 
> /var/tmp/build-root/.
> 
Well the services are executed on your machine - not in the chroot/vm...

> The culprit seems to be services, since doing 
> osc build foo --no-service 
> does not created the "offending" dir.
> 
Hmm the best is probably to file a bug against the particular service.
About which project/package are you talking?

**Comment by zaitor** [comment]
Any random package, but as an example I just branched fping.
https://build.opensuse.org/package/show/home:Zaitor:branches:network:utilities/fping

This is a bog standard package, with no fancy _service.

I currently have these services (all recommended, and autopulled when doing zypper in osc)

i | obs-service-download_files   | pakke | 0.5.1.git.1455712026.9c0a4a0-2.2 | noarch | oss       
i | obs-service-format_spec_file | pakke | 20160406-1.1                     | noarch | oss       
i | obs-service-recompress       | pakke | 0.3.1+git20160217.7897d3f-2.2    | noarch | oss       
i | obs-service-set_version      | pakke | 0.5.3-4.2                        | noarch | oss       
i | obs-service-source_validator | pakke | 0.6+git20160707.a6ff89d-1.1      | noarch | oss       
i | obs-service-tar_scm          | pakke | 0.6.1.1473925745.c5264bb-1.1     | noarch | oss       
i | obs-service-verify_file      | pakke | 0.1.1-2.2                        | noarch | oss       

------
bjolie@drude:~/test/fping> osc --verbose build --clean
makeurl: https://api.opensuse.org ['source', 'home:Zaitor:branches:network:utilities', '_meta'] []
makeurl: https://api.opensuse.org ['source', 'home:Zaitor:branches:network:utilities', 'fping'] cmd=getprojectservices
Run source service: /usr/lib/obs/service/format_spec_file --outdir /home/bjolie/test/fping/tmpatkPHb.format_spec_file.service
Run source service: /usr/lib/obs/service/source_validator --outdir /home/bjolie/test/fping/tmpHQTdVl.source_validator.service
Building fping.spec for openSUSE_Factory/x86_64
Getting buildinfo from server and store to /home/bjolie/test/fping/.osc/_buildinfo-openSUSE_Factory-x86_64.xml
makeurl: https://api.opensuse.org ['build', 'home:Zaitor:branches:network:utilities', 'openSUSE_Factory', 'x86_64', 'fping', '_buildinfo'] []
Getting buildconfig from server and store to /home/bjolie/test/fping/.osc/_buildconfig-openSUSE_Factory-x86_64
makeurl: https://api.opensuse.org ['build', 'home:Zaitor:branches:network:utilities', 'openSUSE_Factory', '_buildconfig'] []
Updating cache of required packages
65.8% cache miss. 38/111 dependencies cached.

(openSUSE:Factory) kernel-obs-buil  56% |=========        | 7.5 MB    00:04 ETA ^CCancelled by user (ctrl-c)
Exiting.
bjolie@drude:~/test/fping>   ls ~/rpmbuild/
BUILD  BUILDROOT  RPMS  SOURCES  SPECS  SRPMS
bjolie@drude:~/test/fping> 

After looking at the above verbose log, I nuked away obs-service-format_spec_file

And now the folder did not created.

**Comment by marcus-h** [comment]
On 2016-09-27 13:50:44 -0700, Bjørn Lie wrote:
> Any random package, but as an example I just branched fping.
> https://build.opensuse.org/package/show/home:Zaitor:branches:network:utilities/fping
> 
> This is a bog standard package, with no fancy _service.
> 
The executed services are inherited from the openSUSE:Factory project.

<SNIP>

> bjolie@drude:~/test/fping>   ls ~/rpmbuild/
> BUILD  BUILDROOT  RPMS  SOURCES  SPECS  SRPMS
> bjolie@drude:~/test/fping> 
> 
> After looking at the above verbose log, I nuked away obs-service-format_spec_file
> 
Hmm in this case "osc build" should complain about a missing service (except you
used the --no-service" option).

> And now the folder did not created.
> 
Are you sure that the obs-service-format_spec_file created the ~/rpmbuild
directory? From what I see it is created by the obs-service-source_validator,
when running the 20-files-present-and-referenced script (which calls
"rpmbuild"). There is a PR for the obs-service-source_validator that fixes
this issue as a side effect (see
https://github.com/openSUSE/obs-service-source_validator/pull/39).

**Comment by zaitor** [comment]
Aha you might be right that osb-service-format-spec is a red herring, as removing it (while keeping all the others) leads to this warning

bjolie@haldis:~/testing/home:Zaitor:branches:network:utilities/fping> rm -rf ~/rpmbuild/
bjolie@haldis:~/testing/home:Zaitor:branches:network:utilities/fping> osc --verbose build --cleanmakeurl: https://api.opensuse.org ['source', 'home:Zaitor:branches:network:utilities', '_meta'] []
makeurl: https://api.opensuse.org ['source', 'home:Zaitor:branches:network:utilities', 'fping'] cmd=getprojectservices
WARNING: package is not existing on server yet
WARNING: source service from package or project will not be executed. This may not be the same build as on server!
Building fping.spec for openSUSE_Factory/x86_64
Getting buildinfo from server and store to /home/bjolie

So I guess the "effect" is the same as passing --no-service in this case.

**Comment by marcus-h** [comment]
Should be fixed with a new version of the obs-service-source_validator
(see https://github.com/openSUSE/obs-service-source_validator/commit/0cb832185b71e869bb84fc995f483275c5c4158d)
Closing for now.
