### ISSUE TITLE
Make plain_passwd = 0 default in new .oscrc

### ISSUE THREAD

**Issue by kdave** [openSUSE/osc#233]
Fresh osc setup, where no .oscrc exists, asks for username and password when it's first needed. The username and password are stored to .oscrc, but the password is plaintext. Tested with version 0.155.0 and I recall this happens like forever.

The workaround is to login once to create .oscrc, edit and set plain_passwd=0, delete the whole [https://api.opensuse.org] section, login again.

Suggested fix: make plain_passwd = 0 default

**Comment by marcus-h** [comment]
On 2016-09-29 14:04:31 -0700, kdave wrote:
> The workaround is to login once to create .oscrc, edit and set plain_passwd=0, delete the whole [https://api.opensuse.org] section, login again.
> 
You can simply do:
osc config general plaintext_passwd 0
which automatically rewrites the config file.

> Suggested fix: make plain_passwd = 0 default
> 
Hmm storing the obfuscated password might give a false impression
of "security" to some users...

**Comment by kdave** [comment]
> osc config general plaintext_passwd 0

Well, thanks, I din't know about that.

> Hmm storing the obfuscated password might give a false impression of "security" to some users...

Still better than storing the plain text, to prevent accidentaly exposing  the password to people around.

**Comment by marcus-h** [comment]
On 2016-09-30 02:51:48 -0700, kdave wrote:
> > Hmm storing the obfuscated password might give a false impression of "security" to some users...
> 
> Still better than storing the plain text, to prevent accidentaly exposing  the password to people around.
> 
Yes that's true, but I'm still in favor of keeping the current default...
However, if there are more people that want to have a new default, I'll
reconsider it:)

Btw., you could also use keyring or gnome-keyring to store your passwords
(if you want to use more "advanced" storing mechanisms).
Btw. 2, I just checked the "svn" tool and it also stores the plaintext
password.

**Comment by kdave** [comment]
> Yes that's true, but I'm still in favor of keeping the current default... However, if there are more people that want to have a new default, I'll reconsider it:)

How many more do you need? IOW you're saying this will never happen. I know about one, a new colleague who was surprised to see the plain text password. You don't need to support your argument by pointing to other bad examples (svn).

Would it be feasible to implement token-based auth? Server asks for password, generates token and client stores it to the config.

**Comment by marcus-h** [comment]
On 2016-09-30 04:36:20 -0700, kdave wrote:
> > Yes that's true, but I'm still in favor of keeping the current default... However, if there are more people that want to have a new default, I'll reconsider it:)
> 
> How many more do you need? IOW you're saying this will never happen. I know about one, a new colleague who was surprised to see the plain text password. You don't need to support your argument by pointing to other bad examples (svn).
> 
I'm pretty sure that once we changed the default, other people will
eventually show up and complain as well...
Maybe bring up this topic on the buildservice mailinglist? Then, we
will (hopefully) see what the others think about it...

> Would it be feasible to implement token-based auth? Server asks for password, generates token and client stores it to the config.
> 
So far, tokens are only used to run source services (see [1]).

[1] http://openbuildservice.org/help/manuals/obs-reference-guide/cha.obs.authorization.token.html#idm140508499042912

**Comment by Conan-Kudo** [comment]
@marcus-h I was pretty surprised to find out that token based auth didn't exist for general actions. Hopefully that could be something for OBS 2.8?

**Comment by marcus-h** [comment]
On 2016-10-04 08:19:07 -0700, Neal Gompa (ニール・ゴンパ) wrote:
> @marcus-h I was pretty surprised to find out that token based auth didn't exist for general actions. Hopefully that could be something for OBS 2.8?
> 
I don't know the roadmap for 2.8 - the best is if you file a
feature request (open-build-service repo).

**Comment by mschnitzer** [comment]
@Conan-Kudo please create a request here: https://github.com/openSUSE/open-build-service/issues/new

**Comment by lethliel** [comment]
This is outdated, since we have a new password handling backend anyway.
