### ISSUE TITLE
FR: osc should pass apiurl to source services

### ISSUE THREAD

**Issue by aspiers** [openSUSE/osc#234]
Some source services need to retrieve values from `~/.oscrc`; for example `tar_scm` needs to know the user's email so it can include it in the generated changes which are automatically prepended to the changelog.  In order to do this lookup correctly, it needs to know the apiurl of the BS instance currently in use, in order to use the right section of `~/.oscrc`.

A real world example demonstrating the need for this feature request is described in https://github.com/openSUSE/obs-service-tar_scm/pull/119.

**Comment by aspiers** [comment]
I just experienced the oddest thing - I started to look in my own working tree checkout of this repo to see how easy this would be to implement, and found the implementation already in the repo, uncommitted and unstaged!  Noone else could have put it there, but I have no recollection of coding it, and can't even remember why I would have done it!  There must have been some other use case I was doing it for, which hopefully I'll remember at some point :-)

**Comment by marcus-h** [comment]
On 2016-10-01 14:51:41 -0700, Adam Spiers wrote:
> Some source services need to retrieve values from `~/.oscrc`; for example `tar_scm` needs to know the user's email so it can include it in the generated changes which are automatically prepended to the changelog.  In order to do this lookup correctly, it needs to know the apiurl of the BS instance currently in use, in order to use the right section of `~/.oscrc`.
> 
Note that not every section has the email option set. If you have
to cope with such situations as well, you might want to have a look
at osc's "vc" command (do_vc in commandline.py) (it just demonstrates
how to retrieve the "email" from api itself).

**Comment by aspiers** [comment]
@marcus-h Thanks, that's super helpful!!

**Comment by adrianschroeter** [comment]
JFYI, such an extension needs to be kept in sync with bs_service or it won't work on server side (even though might not want to use it in your source service atm)

**Comment by adrianschroeter** [comment]
IMHO it would be also better to provide user and email directly here via the environment.

**Comment by marcus-h** [comment]
On 2016-10-20 04:40:51 -0700, Adrian Schröter wrote:
> JFYI, such an extension needs to be kept in sync with bs_service or it won't work on server side (even though might not want to use it in your source service atm)
> 
Hmm from what I understand this is a "localrun" only feature.
