### ISSUE TITLE
checkout silently accepts '#' in names

### ISSUE THREAD

**Issue by Vogtinator** [openSUSE/osc#240]
> osc co home:favogt:branches:devel:ARM:Factory:Contrib:Pine64/firmware-pine64#asdf

A    home:favogt:branches:devel:ARM:Factory:Contrib:Pine64/firmware-pine64#asdf[...
[...]

> cd home:favogt:branches:devel:ARM:Factory:Contrib:Pine64/firmware-pine64#asdf
> osc build

Server returned an error: HTTP Error 403: Forbidden
Upload of binaries is only permitted for administrators

**Comment by marcus-h** [comment]
Hmm yes. It seems we don't quote the "#" when constructing the urls. I'll
have a look at it.
