### ISSUE TITLE
local builds: Set build dir as environment

### ISSUE THREAD

**Issue by bgeuken** [openSUSE/osc#248]
I often find myself searching for the build directory of my local package build. I know it's static and should be easy to remember, but I keep forgetting it.

It would come handy to have this information set as environment variable. This could even be re-used by osc, eg. osc --build-dir or --build-root

**Comment by marcus-h** [comment]
On 2016-11-22 02:54:13 -0800, Björn Geuken wrote:
> It would come handy to have this information set as environment variable.

You can override the default config value by setting the
OSC_BUILD_ROOT env variable.

> This could even be re-used by osc, eg. osc --build-dir or --build-root
> 
Hmm what do exactly mean?

**Comment by dmach** [comment]
There's no sufficient information in the report and there's no answer for ~8 years. Closing.

If it helps, there's the `osc build --just-print-buildroot` command now.
