### ISSUE TITLE
Enhancement: osc command to only add a comment to a request

### ISSUE THREAD

**Issue by jsmeix** [openSUSE/osc#250]
See
https://github.com/openSUSE/open-build-service/issues/2408

I would like that I can only add a comment to a request
(without accepting or declining the request)
using plain 'osc' command line tool.

For example when I have noticed a submitrequest
but I need some longer time to check it, I would like
to inform the submitter that I noticed it but that he
needs to be patient e.g. using something like
a sub-command to the 'request' command
<pre>
osc request comment -m 'Please be patient' ID
</pre>
or more generally a separated 'comment' command like
<pre>
osc comment -m 'Please be patient' ID
</pre>
that works for any "commentable" elements
(for instance, projects and packages).

With such a comment other people who are looking e.g.
for pending requests would get the info what is going on
which avoids that they also start to work on it
or have to ask around why things are not moving.

**Comment by lethliel** [comment]
implemented with #272
