### ISSUE TITLE
IPv6 not working

### ISSUE THREAD

**Issue by susnux** [openSUSE/osc#261]
One of the networks I am using is IPv6 only, this leads to unresolvable address using osc:

> Failed to reach a server:
>  [Errno 101] Network is unreachable: 'https://api.opensuse.org/source/home:susnux:branches:openSUSE:Leap:42.2:NonFree:Update/_meta'

But the host name is resolvable, and I can connect to api.opensuse.org (e.g. with firefox).
> % dig api.opensuse.org AAAA
> 
> ; <<>> DiG 9.9.9-P1 <<>> api.opensuse.org AAAA
> ;; global options: +cmd
> ;; Got answer:
> ;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 19947
> ;; flags: qr rd ra ad; QUERY: 1, ANSWER: 2, AUTHORITY: 0, ADDITIONAL: 0
> 
> ;; QUESTION SECTION:
> ;api.opensuse.org.              IN      AAAA
> 
> ;; ANSWER SECTION:
> api.opensuse.org.       560     IN      CNAME   login.opensuse.org.
> login.opensuse.org.     180     IN      AAAA    2001:67c:2178:8::12
> 
> ;; Query time: 11 msec
> ;; SERVER: 2a02:810a:8380:8bf4::1#53(2a02:810a:8380:8bf4::1)
> ;; WHEN: Thu Jan 26 13:53:35 CET 2017
> ;; MSG SIZE  rcvd: 94

**Comment by marcus-h** [comment]
Fixed in commit 3b3bb21645baa0d48e006ecbb6374dc040c01688. If you
want to give it a try, you can have a look at the devel:tools:scm/osc
package (which is based on osc's master branch and has the fix - note:
this is no "official" osc release).

**Comment by susnux** [comment]
Thank you! Tested it and it works 👍

**Comment by susnux** [comment]
One question: Will this get published as an update of OSC for openSUSE Leap?

**Comment by marcus-h** [comment]
On 2017-01-31 02:27:41 -0800, Ferdinand Thiessen wrote:
> One question: Will this get published as an update of OSC for openSUSE Leap?
> 
Hmm I think we could do that. @adrianschroeter any objection?
But let's see if this also fixes #246 (though, I'm pretty sure it
does;) ).
