### ISSUE TITLE
excess .lock files

### ISSUE THREAD

**Issue by jengelh** [openSUSE/osc#262]
On Tumbleweed

> rpm -qa --last | grep -P "osc|service"
obs-service-source_validator-0.6+git20170111.82ea590-1.1.noarch 2017-01-27T09:48:45 CET
obs-service-tar_scm-0.7.0.1484082405.7671be8-1.1.noarch 2017-01-24T15:13:32 CET
obs-service-set_version-0.5.4-1.1.noarch      2017-01-24T15:13:18 CET
obs-service-verify_file-0.1.1-2.2.noarch      2017-01-15T13:50:57 CET
obs-service-refresh_patches-0.3.9+git.1394121974.21d4106-3.2.noarch 2017-01-15T13:50:57 CET
obs-service-recompress-0.3.1+git20160217.7897d3f-2.2.noarch 2017-01-15T13:50:57 CET
obs-service-extract_file-0.3-3.1.noarch       2017-01-15T13:50:57 CET
obs-service-download_url-0.1-3.2.noarch       2017-01-15T13:50:57 CET
obs-service-download_files-0.5.1.git.1455712026.9c0a4a0-2.2.noarch 2017-01-15T13:50:57 CET
obs-service-format_spec_file-20160929-1.1.noarch 2017-01-15T13:50:21 CET
osc-0.156.0-1.1.noarch                        2017-01-11T13:40:59 CET

`.lock` files are created by `osc service lr`, and they stick around after it exits, which is really annoying when doing `osc ar` later on.
(This happens in server:database/libdbi-drivers and with the git download.)

**Comment by marcus-h** [comment]
On 2017-01-27 06:36:19 -0800, jengelh wrote:
> `.lock` files are created by `osc service lr`, and they stick around after it exits, which is really annoying when doing `osc ar` later on.
> 
This is probably caused by some service (osc doesn't do any locking).
About which project/package are you talking? If it is on private
obs, please post the _service file and all project services
(see
curl -X POST -d '' https://<api>/source/<prj>/<pkg>?cmd=getprojectservices)

**Comment by dmach** [comment]
This issue has been inactive for a long time.
We have insufficient information to reproduce and fix it.
Closing, but if the problem persists, please create a new issue with a recent reproducer.

**Comment by jengelh** [comment]
```
09:25 a4:~/obs/zu $ cd filesystems/f2fs-tools/
09:25 a4:../filesystems/f2fs-tools $ l
total 400
drwxr-xr-x  5 jengelh users    203 Dec 27 08:01 .
drwx--x--x 17 jengelh users    235 Dec 19 11:15 ..
drwxr-xr-x  2 jengelh users   4096 Dec 27 08:01 .osc
drwxr-xr-x  2 jengelh users    287 May  3  2021 binaries
drwxr-xr-x 11 jengelh users    286 Oct  1 20:41 f2fs-tools
-rw-r--r--  1 jengelh users    666 Dec 27 07:54 _service
-rw-r--r--  1 jengelh users  91718 Dec 27 08:00 bl
-rw-r--r--  1 jengelh users 289056 Dec 27 07:55 f2fs-tools-1.14.0.g67.tar.xz
-rw-r--r--  1 jengelh users    558 Aug 28  2016 f2fs-tools-1.4.0-bigendian.patch
-rw-r--r--  1 jengelh users   6511 Dec 27 07:55 f2fs-tools.changes
-rw-r--r--  1 jengelh users   3510 Dec 27 07:58 f2fs-tools.spec
09:25 a4:../filesystems/f2fs-tools $ osc service dr
merge: origin/972d71073af32a1854aeece018746a9f8021dd14 - not something we can merge
Already up to date.
972d71073af32a1854aeece018746a9f8021dd14
Identical target file f2fs-tools-1.14.0.g67.tar.xz already exists, skipping..
09:26 a4:../filesystems/f2fs-tools $ l
total 400
drwxr-xr-x  5 jengelh users    216 Dec 28 09:26 .
drwx--x--x 17 jengelh users    235 Dec 19 11:15 ..
drwxr-xr-x  2 jengelh users   4096 Dec 27 08:01 .osc
drwxr-xr-x  2 jengelh users    287 May  3  2021 binaries
drwxr-xr-x 11 jengelh users    286 Oct  1 20:41 f2fs-tools
-rw-r--r--  1 jengelh users      0 Dec 28 09:26 .lock
-rw-r--r--  1 jengelh users    666 Dec 27 07:54 _service
-rw-r--r--  1 jengelh users  91718 Dec 27 08:00 bl
-rw-r--r--  1 jengelh users 289056 Dec 27 07:55 f2fs-tools-1.14.0.g67.tar.xz
-rw-r--r--  1 jengelh users    558 Aug 28  2016 f2fs-tools-1.4.0-bigendian.patch
-rw-r--r--  1 jengelh users   6511 Dec 27 07:55 f2fs-tools.changes
-rw-r--r--  1 jengelh users   3510 Dec 28 09:26 f2fs-tools.spec
```

```
$ rpm -qa "obs*"
obs-service-format_spec_file-20211115-2.1.noarch
obs-service-extract_file-0.4-1.6.noarch
obs-service-refresh_patches-0.3.9+git.1625238904.d59f20e-2.1.noarch
obs-service-obs_scm-common-0.10.28.1632141620.a8837d3-1.1.noarch
obs-service-tar-0.10.28.1632141620.a8837d3-1.1.noarch
obs-service-verify_file-0.1.1-2.13.noarch
obs-service-tar_scm-0.10.28.1632141620.a8837d3-1.1.noarch
obs-service-set_version-0.5.14-2.1.noarch
obs-service-source_validator-0.21-1.3.noarch
obs-service-download_url-0.1.3-2.1.noarch
obs-service-obs_scm-0.10.28.1632141620.a8837d3-1.1.noarch
obs-service-recompress-0.5.1-2.2.noarch
obs-service-download_files-0.9.1-1.1.noarch
```

**Comment by jengelh** [comment]
```
    def unlock_cache(self):
        if self.lock_file and os.path.isfile(self.lock_file.name):
            fcntl.lockf(self.lock_file, fcntl.LOCK_UN)
            self.lock_file.close()
            self.lock_file = None
```

close. no unlink. bruh.
