### ISSUE TITLE
Sources downloaded multiple times if referenced in multiple spec files

### ISSUE THREAD

**Issue by Vogtinator** [openSUSE/osc#266]
In the breeze package we have a breeze.spec and breeze4.spec which use the same tar.gz as source.
Running ```osc service localrun download_files``` causes the .tar.xz to be downloaded twice.

**Comment by marcus-h** [comment]
On 2017-02-15 11:45:31 -0800, Fabian Vogt wrote:
> In the breeze package we have a breeze.spec and breeze4.spec which use the same tar.gz as source.
> Running ```osc service localrun download_files``` causes the .tar.xz to be downloaded twice.
> 
Hmm this needs to be fixed in the obs-service-download_files package.
Can you please file a bug in the corresponding repo (see
https://github.com/openSUSE/obs-service-download_files)?

**Comment by Vogtinator** [comment]
Done!
