### ISSUE TITLE
404 on running service for non commited package

### ISSUE THREAD

**Issue by k0da** [openSUSE/osc#277]
steps to reproduce:
osc mkpac foo
place some dummy _service into foo
do osc service localrun

> osc service lr
Server returned an error: HTTP Error 404: Not Found

api responds 404 for ?cmd=getprojectservices

I'm not sure if it is not an api issue

**Comment by k0da** [comment]
right.. there is no package yet

**Comment by k0da** [comment]
this fixes it:
https://github.com/openSUSE/osc/pull/278

**Comment by marcus-h** [comment]
On 2017-03-09 07:25:37 -0800, Dinar Valeev wrote:
> this fixes it:
> https://github.com/openSUSE/osc/pull/278
> 
Fixed in commit 9d0725b (see PR#278 for the details).
Thanks for the report!
