### ISSUE TITLE
service disabledrun is not documented

### ISSUE THREAD

**Issue by Ana06** [openSUSE/osc#282]
`osc service disabledrun` is not documented, while the rest COMMANDs for service are documented:
https://github.com/openSUSE/osc/blob/bbd5a922262f9b745551e215fee7b1f77ed5639d/osc/commandline.py#L6501

**Comment by marcus-h** [comment]
On 2017-03-31 00:57:02 -0700, Ana María Martínez Gómez wrote:
> `osc service disabledrun` is not documented, while the rest COMMANDs for service are documented:
> https://github.com/openSUSE/osc/blob/bbd5a922262f9b745551e215fee7b1f77ed5639d/osc/commandline.py#L6501
> 
Fixed in commit ae591a8.

**Comment by jirislaby** [comment]
Why were those commands marked as deprecated when they are favored over server-side runs?

**Comment by marcus-h** [comment]
On 2018-04-01 11:15:05 +0000, Jiri Slaby wrote:
> Why were those commands marked as deprecated when they are favored over server-side runs?
> 
They were deprecated in order to "simplify" the "osc service" command
a bit. For the details, see commit 28c12686b9dabc8011a872faf7f5cfeafdc05789.
