### ISSUE TITLE
get_creator() does not return request creator

### ISSUE THREAD

**Issue by andreasstieger** [openSUSE/osc#286]
`osc/core.py` has the following:

```python
    def get_creator(self):
        """return the creator of the request"""
        if len(self.statehistory):
            return self.statehistory[0].who
        return self.state.who
```

However this does not return the creator of the request, but the last one to change the request state. That is usually a reviewer. 

Case in point: `osc api '/request/487429'`.  The request creator is **leaper** , but `get_creator()` returns **staging-bot** once it performed some reviews.

```xml
<request id="487429" creator="leaper">
  <action type="submit">
   <!-- shortened -->
    <source project="openSUSE:Leap:42.2:Update" package="slrn.6594" rev="a761933975685be4f21679582fabf0de"/>
    <target project="openSUSE:Leap:42.3" package="slrn"/>
  </action>
  <state name="new" who="staging-bot" when="2017-04-11T17:44:58">
    <comment>ready to accept</comment>
  </state>
  <review state="accepted" when="2017-04-11T17:05:24" who="leaper" by_user="leaper">
   <!-- shortened -->
  </review>
   <!-- shortened -->
  <description>Automatic request from openSUSE:Leap:42.2:Update by UpdateCrawler</description>
</request>
```

**Comment by marcus-h** [comment]
On 2017-04-12 01:54:55 -0700, Andreas Stieger wrote:
> `osc/core.py` has the following:
> 
> ```python
>     def get_creator(self):
>         """return the creator of the request"""
>         if len(self.statehistory):
>             return self.statehistory[0].who
>         return self.state.who
> ```
> 
> However this does not return the creator of the request, but the last one to change the request state. That is usually a reviewer. 
> 
Good catch! Fixed in commit d68507f (6965dc5). Now, we
rely on the "creator" attribute, which is part of the <request>
node.

**Comment by marcus-h** [comment]
On 2017-04-12 13:07:28 +0200, Marcus Hüwe wrote:
> On 2017-04-12 01:54:55 -0700, Andreas Stieger wrote:
> > `osc/core.py` has the following:
> > 
> > ```python
> >     def get_creator(self):
> >         """return the creator of the request"""
> >         if len(self.statehistory):
> >             return self.statehistory[0].who
> >         return self.state.who
> > ```
> > 
> > However this does not return the creator of the request, but the last one to change the request state. That is usually a reviewer. 
> > 
> Good catch! Fixed in commit d68507f (6965dc5). Now, we
> rely on the "creator" attribute, which is part of the <request>
> node.

And the "get_creator" method was dropped in favor of a
"creator" attribute.

**Comment by andreasstieger** [comment]
The removal of the `get_creator()` function breaks some [factory bots](https://github.com/search?q=org%3AopenSUSE+get_creator&type=Code)... @lnussel  @DimStar77

**Comment by lnussel** [comment]
so, do we need to fix the code or can we have the function back for compatibility? CC @jberry-suse

**Comment by marcus-h** [comment]
On 2017-04-12 04:30:36 -0700, Andreas Stieger wrote:
> The removal of the `get_creator()` function breaks some [factory bots](https://github.com/search?q=org%3AopenSUSE+get_creator&type=Code)... @lnussel  @DimStar77 
> 
I readded Request.get_creator in commit 164435d. There is no good
reason to break the bots (now)...

**Comment by lnussel** [comment]
thanks!
