### ISSUE TITLE
osr sr -d in a project directory directly creates submit requests

### ISSUE THREAD

**Issue by andreasstieger** [openSUSE/osc#29]
I created a branch project with two packages, based on packages in the same source project, using "osc bco" each.

I modified each package and committed. I went ahead and created a submit request on one package to the parent project.

I issues "osc sr -d" in the directory containing the branch project. I expected a) the project diff or b) the message that this was not yet supported. Instead, submit requests for both packages were issued. This violated the rule of least surprise.

In addition, a submit request was issued when the same one already existed.

**Comment by lethliel** [comment]
Ok. So we can close this now.
