### ISSUE TITLE
how is multibuild_package supposed to work?

### ISSUE THREAD

**Issue by jirislaby** [openSUSE/osc#293]
I am trying to build installation-images which is now multibuild:
```
osc -v build --root=/dev/shm/xxx --no-service --no-verify -j200 --download-api-only --disable-debuginfo --userootforbuild -M openSUSE
```
but -M seems to have no effect:
```
[    0s] init_buildsystem --configdir /usr/lib/build/configs --cachedir /var/cache/build --create-build-binaries --rpmlist /tmp/rpmlist.vQPx52 /suse/jslaby/tmp/home:jirislaby:installation-images-test/installation-images/installation-images.spec ...
...
[   10s] + exec rpmbuild -ba --define '_srcdefattr (-,root,root)' --nosignature /usr/src/packages/SOURCES/installation-images.spec
[   10s] error: Architecture is not included: x86_64
```

Note that there is no `--buildflavor openSUSE` when doing `init_buildsystem`.

```
osc --version
0.157.2
```

And looking into sources, `multibuild_package` is used only if no `.spec` is specified on the commandline AND there are multiple `.spec` files in the directory. So how is one supposed to use this?

**Comment by lethliel** [comment]
can you please provide a link to the project?

**Comment by jirislaby** [comment]
It's OBS and [system:install:head installation-images](https://build.opensuse.org/package/show/system:install:head/installation-images).

**Comment by jirislaby** [comment]
Works for me. Thanks!
