### ISSUE TITLE
`osc rq wipe` not mentioned in `osc rq --help`

### ISSUE THREAD

**Issue by cboltz** [openSUSE/osc#298]
http://openbuildservice.org/2017/05/19/frontend-sprint-report-2// mentions the `osc rq wipe $ID` command. However...

    # osc rq wipe
    Too few arguments.
    # osc rq --help | grep wipe
    #

Please add some information about `osc rq wipe` to the --help output.

(CC @ccboltz)

**Comment by lethliel** [comment]
This is not documented by intention. It is a admin function and is obsoleted furthermore.
