### ISSUE TITLE
osc build - WARNING: package is not existing on server yet

### ISSUE THREAD

**Issue by mmohring** [openSUSE/osc#299]
When running osc build on b.o.o OBS:Server:Unstable obs-server, a local build complains:

WARNING: package is not existing on server yet
WARNING: source service from package or project will not be executed. This may not be the same build as on server!

and does not work. The same works on the server.

**Comment by mmohring** [comment]
$ osc -A https://api.opensuse.org co OBS:Server:Unstable obs-server
$ cd OBS:Server:Unstable/obs-server
$ osc -A https://api.opensuse.org build openSUSE_42.2 x86_64 obs-server.spec
WARNING: package is not existing on server yet
WARNING: source service from package or project will not be executed. This may not be the same build as on server!
Building obs-server.spec for openSUSE_42.2/x86_64
Error: build description file named '/home/martin/co/OBS:Server:Unstable/obs-server/obs-server.spec' does not exist.

**Comment by mmohring** [comment]
This package uses a _service file. I have installed all the services used in this _service file: obs_scm, tar, recompress, set_version, download_url .

**Comment by mmohring** [comment]
If I exchange the first service in the service file from "obs_scm" to "tar_scm" and call:
$ osc -A https://api.opensuse.org build openSUSE_42.2 x86_64 _service:tar_scm:obs-server.spec
the build starts up but stops with:

[   35s] removing nis flags from //etc/nsswitch.conf...
[   35s] now finalizing build dir...
[   35s] SIOCSIFADDR: File exists
[   35s] Running build time source services...
[   35s] ERROR: no .obsinfo file found in directory: '/home/abuild/rpmbuild/SOURCES'
[   35s] service run failed for service 'tar'
[   35s] 
[   35s] neptun failed "build obs-server.spec" at Tue May 23 11:53:12 UTC 2017.
[   35s] 
[   39s] [   27.994731] reboot: Power down

**Comment by adrianschroeter** [comment]
you need to use once "osc service run" and specify the generate spec file then. The one with the _service:.. prefix.
