### ISSUE TITLE
osc ci - cannot handle more than 2 GB file uploads

### ISSUE THREAD

**Issue by mmohring** [openSUSE/osc#304]
if you add a very big file downloaded_files.tar.gz, more than 2 GB to a package working copy with:

$ osc add downloaded_files.tar.gz
$ osc ci -m"added: very big file"

it results in an error trace:

sending    downloaded_files.tar.gz
Transmitting file data .Traceback (most recent call last):
  File "/usr/bin/osc", line 41, in <module>
    r = babysitter.run(osccli)
  File "/usr/lib/python2.7/site-packages/osc/babysitter.py", line 61, in run
    return prg.main(argv)
  File "/usr/lib/python2.7/site-packages/osc/cmdln.py", line 344, in main
    return self.cmd(args)
  File "/usr/lib/python2.7/site-packages/osc/cmdln.py", line 367, in cmd
    retval = self.onecmd(argv)
  File "/usr/lib/python2.7/site-packages/osc/cmdln.py", line 501, in onecmd
    return self._dispatch_cmd(handler, argv)
  File "/usr/lib/python2.7/site-packages/osc/cmdln.py", line 1232, in _dispatch_cmd
    return handler(argv[0], opts, *args)
  File "/usr/lib/python2.7/site-packages/osc/commandline.py", line 4568, in do_commit
    self._commit(subcmd, opts, args)
  File "/usr/lib/python2.7/site-packages/osc/commandline.py", line 4652, in _commit
    prj.commit(packages, msg=msg, files=files, skip_local_service_run=skip_local_service_run, verbose=opts.verbose, can_branch=can_branch, force=opts.force)
  File "/usr/lib/python2.7/site-packages/osc/core.py", line 973, in commit
    p.commit(msg, verbose=verbose, skip_local_service_run=skip_local_service_run, can_branch=can_branch, force=force)
  File "/usr/lib/python2.7/site-packages/osc/core.py", line 1493, in commit
    self.put_source_file(filename, tdir)
  File "/usr/lib/python2.7/site-packages/osc/core.py", line 1341, in put_source_file
    http_PUT(u, file = tfilename)
  File "/usr/lib/python2.7/site-packages/osc/core.py", line 3312, in http_PUT
    def http_PUT(*args, **kwargs):    return http_request('PUT', *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/osc/core.py", line 3299, in http_request
    fd = urlopen(req, data=data)
  File "/usr/lib64/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib64/python2.7/urllib2.py", line 429, in open
    response = self._open(req, data)
  File "/usr/lib64/python2.7/urllib2.py", line 447, in _open
    '_open', req)
  File "/usr/lib64/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/site-packages/osc/oscssl.py", line 220, in https_open
    h.request(req.get_method(), selector, req.data, headers)
  File "/usr/lib64/python2.7/httplib.py", line 1042, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib64/python2.7/httplib.py", line 1082, in _send_request
    self.endheaders(body)
  File "/usr/lib64/python2.7/httplib.py", line 1038, in endheaders
    self._send_output(message_body)
  File "/usr/lib64/python2.7/httplib.py", line 886, in _send_output
    self.send(message_body)
  File "/usr/lib64/python2.7/httplib.py", line 858, in send
    self.sock.sendall(data)
  File "/usr/lib64/python2.7/site-packages/M2Crypto/SSL/Connection.py", line 226, in write
    return self._write_bio(data)
  File "/usr/lib64/python2.7/site-packages/M2Crypto/SSL/Connection.py", line 209, in _write_bio
    return m2.ssl_write(self.ssl, data, self._timeout)
ValueError: object too large

You can upload this very big file with the OBS WebUI without error, and then you can also check out this very big file with:

$ osc up

without error. Also, you can use a Source Service to generate bigger than 2 GB files. But you cannot upload them with osc ci command.

This happens with osc git master. I am using the python version of openSUSE Leap 42.2 and this distro.

**Comment by marcus-h** [comment]
On 2017-07-03 09:19:04 +0000, Martin Mohring wrote:
> if you add a very big file downloaded_files.tar.gz, more than 2 GB to a package working copy with:
> 
> $ osc add downloaded_files.tar.gz
> $ osc ci -m"added: very big file"
> 
> it results in an error trace:
> 
> sending    downloaded_files.tar.gz
> Transmitting file data .Traceback (most recent call last):
>   File "/usr/bin/osc", line 41, in <module>
>     r = babysitter.run(osccli)
>   File "/usr/lib/python2.7/site-packages/osc/babysitter.py", line 61, in run
>     return prg.main(argv)
>   File "/usr/lib/python2.7/site-packages/osc/cmdln.py", line 344, in main
>     return self.cmd(args)
>   File "/usr/lib/python2.7/site-packages/osc/cmdln.py", line 367, in cmd
>     retval = self.onecmd(argv)
>   File "/usr/lib/python2.7/site-packages/osc/cmdln.py", line 501, in onecmd
>     return self._dispatch_cmd(handler, argv)
>   File "/usr/lib/python2.7/site-packages/osc/cmdln.py", line 1232, in _dispatch_cmd
>     return handler(argv[0], opts, *args)
>   File "/usr/lib/python2.7/site-packages/osc/commandline.py", line 4568, in do_commit
>     self._commit(subcmd, opts, args)
>   File "/usr/lib/python2.7/site-packages/osc/commandline.py", line 4652, in _commit
>     prj.commit(packages, msg=msg, files=files, skip_local_service_run=skip_local_service_run, verbose=opts.verbose, can_branch=can_branch, force=opts.force)
>   File "/usr/lib/python2.7/site-packages/osc/core.py", line 973, in commit
>     p.commit(msg, verbose=verbose, skip_local_service_run=skip_local_service_run, can_branch=can_branch, force=force)
>   File "/usr/lib/python2.7/site-packages/osc/core.py", line 1493, in commit
>     self.put_source_file(filename, tdir)
>   File "/usr/lib/python2.7/site-packages/osc/core.py", line 1341, in put_source_file
>     http_PUT(u, file = tfilename)
>   File "/usr/lib/python2.7/site-packages/osc/core.py", line 3312, in http_PUT
>     def http_PUT(*args, **kwargs):    return http_request('PUT', *args, **kwargs)
>   File "/usr/lib/python2.7/site-packages/osc/core.py", line 3299, in http_request
>     fd = urlopen(req, data=data)
>   File "/usr/lib64/python2.7/urllib2.py", line 154, in urlopen
>     return opener.open(url, data, timeout)
>   File "/usr/lib64/python2.7/urllib2.py", line 429, in open
>     response = self._open(req, data)
>   File "/usr/lib64/python2.7/urllib2.py", line 447, in _open
>     '_open', req)
>   File "/usr/lib64/python2.7/urllib2.py", line 407, in _call_chain
>     result = func(*args)
>   File "/usr/lib/python2.7/site-packages/osc/oscssl.py", line 220, in https_open
>     h.request(req.get_method(), selector, req.data, headers)
>   File "/usr/lib64/python2.7/httplib.py", line 1042, in request
>     self._send_request(method, url, body, headers)
>   File "/usr/lib64/python2.7/httplib.py", line 1082, in _send_request
>     self.endheaders(body)
>   File "/usr/lib64/python2.7/httplib.py", line 1038, in endheaders
>     self._send_output(message_body)
>   File "/usr/lib64/python2.7/httplib.py", line 886, in _send_output
>     self.send(message_body)
>   File "/usr/lib64/python2.7/httplib.py", line 858, in send
>     self.sock.sendall(data)
>   File "/usr/lib64/python2.7/site-packages/M2Crypto/SSL/Connection.py", line 226, in write
>     return self._write_bio(data)
>   File "/usr/lib64/python2.7/site-packages/M2Crypto/SSL/Connection.py", line 209, in _write_bio
>     return m2.ssl_write(self.ssl, data, self._timeout)
> ValueError: object too large
> 
Hmm yes, the current implementation of core.http_request is rather
crude... There's a more "clever" way to do this. However, I still need
to check if it breaks on some "ancient" python version.
@adrianschroeter: do you know by chance the oldest python version
that we need to support?

**Comment by adrianschroeter** [comment]
@marcus-h we support down to SLE 11, which comes with python 2.6

Is this a limitation here?

**Comment by marcus-h** [comment]
On 2017-07-05 07:26:34 +0000, Adrian Schröter wrote:
> @marcus-h we support down to SLE 11, which comes with python 2.6
> 
> Is this a limitation here?
> 
No probably not - I just wanted to know, which versions I need to
check for potential issues... Thanks for the info!

**Comment by mcepl** [comment]
> @marcus-h we support down to SLE 11, which comes with python 2.6

M2Crypto (of which I am an upstream maintainer) is tested on RHEL-6 (that's Python 2.6 and OpenSSL 1.0.1e).

**Comment by dsamx** [comment]
Here is a current trace from python 3.6 from a Leap 15.1 system for a 3.5G file during osc ci:

Transmitting file data ......Traceback (most recent call last):
  File "/usr/bin/osc", line 41, in <module>
    r = babysitter.run(osccli)
  File "/usr/lib/python3.6/site-packages/osc/babysitter.py", line 64, in run
    return prg.main(argv)
  File "/usr/lib/python3.6/site-packages/osc/cmdln.py", line 347, in main
    return self.cmd(args)
  File "/usr/lib/python3.6/site-packages/osc/cmdln.py", line 370, in cmd
    retval = self.onecmd(argv)
  File "/usr/lib/python3.6/site-packages/osc/cmdln.py", line 504, in onecmd
    return self._dispatch_cmd(handler, argv)
  File "/usr/lib/python3.6/site-packages/osc/cmdln.py", line 1235, in _dispatch_cmd
    return handler(argv[0], opts, *args)
  File "/usr/lib/python3.6/site-packages/osc/commandline.py", line 4828, in do_commit
    self._commit(subcmd, opts, args)
  File "/usr/lib/python3.6/site-packages/osc/commandline.py", line 4936, in _commit
    prj.commit(packages, msg=msg, files=prj_files, skip_local_service_run=skip_local_service_run, verbose=opts.verbose, can_branch=can_branch, force=opts.force)
  File "/usr/lib/python3.6/site-packages/osc/core.py", line 1016, in commit
    p.commit(msg, verbose=verbose, skip_local_service_run=skip_local_service_run, can_branch=can_branch, force=force)
  File "/usr/lib/python3.6/site-packages/osc/core.py", line 1566, in commit
    self.put_source_file(filename, tdir)
  File "/usr/lib/python3.6/site-packages/osc/core.py", line 1386, in put_source_file
    http_PUT(u, file = tfilename)
  File "/usr/lib/python3.6/site-packages/osc/core.py", line 3404, in http_PUT
    def http_PUT(*args, **kwargs):    return http_request('PUT', *args, **kwargs)
  File "/usr/lib/python3.6/site-packages/osc/core.py", line 3391, in http_request
    fd = urlopen(req, data=data)
  File "/usr/lib64/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib64/python3.6/urllib/request.py", line 526, in open
    response = self._open(req, data)
  File "/usr/lib64/python3.6/urllib/request.py", line 544, in _open
    '_open', req)
  File "/usr/lib64/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.6/site-packages/osc/oscssl.py", line 222, in https_open
    h.request(req.get_method(), request_uri, req.data, headers)
  File "/usr/lib64/python3.6/http/client.py", line 1287, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib64/python3.6/http/client.py", line 1333, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib64/python3.6/http/client.py", line 1282, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib64/python3.6/http/client.py", line 1081, in _send_output
    self.send(chunk)
  File "/usr/lib64/python3.6/http/client.py", line 1002, in send
    self.sock.sendall(data)
  File "/usr/lib64/python3.6/site-packages/M2Crypto/SSL/Connection.py", line 354, in write
    return self._write_bio(data)
  File "/usr/lib64/python3.6/site-packages/M2Crypto/SSL/Connection.py", line 333, in _write_bio
    return m2.ssl_write(self.ssl, data, self._timeout)
ValueError: object too large

**Comment by adrianschroeter** [comment]
On Montag, 25. Januar 2021, 10:08:27 CET dsamx wrote:
> Here is a current trace from python 3.6 from a Leap 15.1 system for a 3.5G file during osc ci:
> 
> Transmitting file data ......Traceback (most recent call last):
>   File "/usr/bin/osc", line 41, in <module>
>     r = babysitter.run(osccli)
>   File "/usr/lib/python3.6/site-packages/osc/babysitter.py", line 64, in run
>     return prg.main(argv)
>   File "/usr/lib/python3.6/site-packages/osc/cmdln.py", line 347, in main
>     return self.cmd(args)
>   File "/usr/lib/python3.6/site-packages/osc/cmdln.py", line 370, in cmd
>     retval = self.onecmd(argv)
>   File "/usr/lib/python3.6/site-packages/osc/cmdln.py", line 504, in onecmd
>     return self._dispatch_cmd(handler, argv)
>   File "/usr/lib/python3.6/site-packages/osc/cmdln.py", line 1235, in _dispatch_cmd
>     return handler(argv[0], opts, *args)
>   File "/usr/lib/python3.6/site-packages/osc/commandline.py", line 4828, in do_commit
>     self._commit(subcmd, opts, args)
>   File "/usr/lib/python3.6/site-packages/osc/commandline.py", line 4936, in _commit
>     prj.commit(packages, msg=msg, files=prj_files, skip_local_service_run=skip_local_service_run, verbose=opts.verbose, can_branch=can_branch, force=opts.force)
>   File "/usr/lib/python3.6/site-packages/osc/core.py", line 1016, in commit
>     p.commit(msg, verbose=verbose, skip_local_service_run=skip_local_service_run, can_branch=can_branch, force=force)
>   File "/usr/lib/python3.6/site-packages/osc/core.py", line 1566, in commit
>     self.put_source_file(filename, tdir)
>   File "/usr/lib/python3.6/site-packages/osc/core.py", line 1386, in put_source_file
>     http_PUT(u, file = tfilename)
>   File "/usr/lib/python3.6/site-packages/osc/core.py", line 3404, in http_PUT
>     def http_PUT(*args, **kwargs):    return http_request('PUT', *args, **kwargs)
>   File "/usr/lib/python3.6/site-packages/osc/core.py", line 3391, in http_request
>     fd = urlopen(req, data=data)
>   File "/usr/lib64/python3.6/urllib/request.py", line 223, in urlopen
>     return opener.open(url, data, timeout)
>   File "/usr/lib64/python3.6/urllib/request.py", line 526, in open
>     response = self._open(req, data)
>   File "/usr/lib64/python3.6/urllib/request.py", line 544, in _open
>     '_open', req)
>   File "/usr/lib64/python3.6/urllib/request.py", line 504, in _call_chain
>     result = func(*args)
>   File "/usr/lib/python3.6/site-packages/osc/oscssl.py", line 222, in https_open
>     h.request(req.get_method(), request_uri, req.data, headers)
>   File "/usr/lib64/python3.6/http/client.py", line 1287, in request
>     self._send_request(method, url, body, headers, encode_chunked)
>   File "/usr/lib64/python3.6/http/client.py", line 1333, in _send_request
>     self.endheaders(body, encode_chunked=encode_chunked)
>   File "/usr/lib64/python3.6/http/client.py", line 1282, in endheaders
>     self._send_output(message_body, encode_chunked=encode_chunked)
>   File "/usr/lib64/python3.6/http/client.py", line 1081, in _send_output
>     self.send(chunk)
>   File "/usr/lib64/python3.6/http/client.py", line 1002, in send
>     self.sock.sendall(data)
>   File "/usr/lib64/python3.6/site-packages/M2Crypto/SSL/Connection.py", line 354, in write
>     return self._write_bio(data)
>   File "/usr/lib64/python3.6/site-packages/M2Crypto/SSL/Connection.py", line 333, in _write_bio
>     return m2.ssl_write(self.ssl, data, self._timeout)
> ValueError: object too large

can we keep this limit (at least for non .obspcio files) but give a proper error message instead

-- 

Adrian Schroeter <adrian@suse.de>
Build Infrastructure Project Manager

SUSE Software Solutions Germany GmbH,  Maxfeldstr. 5, 90409 Nuernberg, Germany
(HRB 247165, AG München), Geschäftsführer: Felix Imendörffer

**Comment by marcus-h** [comment]
On 2021-01-25 01:08:27 -0800, dsamx wrote:
...
>   File "/usr/lib/python3.6/site-packages/osc/oscssl.py", line 222, in https_open
>     h.request(req.get_method(), request_uri, req.data, headers)
>   File "/usr/lib64/python3.6/http/client.py", line 1287, in request
>     self._send_request(method, url, body, headers, encode_chunked)
>   File "/usr/lib64/python3.6/http/client.py", line 1333, in _send_request
>     self.endheaders(body, encode_chunked=encode_chunked)
>   File "/usr/lib64/python3.6/http/client.py", line 1282, in endheaders
>     self._send_output(message_body, encode_chunked=encode_chunked)
>   File "/usr/lib64/python3.6/http/client.py", line 1081, in _send_output
>     self.send(chunk)
>   File "/usr/lib64/python3.6/http/client.py", line 1002, in send
>     self.sock.sendall(data)
>   File "/usr/lib64/python3.6/site-packages/M2Crypto/SSL/Connection.py", line 354, in write
>     return self._write_bio(data)
>   File "/usr/lib64/python3.6/site-packages/M2Crypto/SSL/Connection.py", line 333, in _write_bio
>     return m2.ssl_write(self.ssl, data, self._timeout)
> ValueError: object too large
>
Hmm yes, due to our memoryview dance in core.http_request, it tries to
write the whole data in chunk (which exceeds INT_MAX and hence the
ValueError). Writing it in one chunk is completely insane. This part
needs a rewrite. The last time I tried to "fix" it, I broke local
OBS instances (see issue [1] and commit [2]). I'll have a look at it
again.

[1] https://github.com/openSUSE/osc/issues/202
[2] c53a7681ef289181b03e1077efbfd246bf1247f6

**Comment by matwey** [comment]
Are there any known workarounds for this issue?

**Comment by mcepl** [comment]
> Are there any known workarounds for this issue?

Use Python 3? Would it help?

**Comment by matwey** [comment]
I am not sure. Currently I see that `osc` uses python 3. At least it does at Leap 15.3. And there is the issue.

**Comment by matwey** [comment]
I've uploaded the file via WebUI and I am afraid I've broken something:
![image](https://user-images.githubusercontent.com/156627/113868005-e1eac180-97b7-11eb-99d3-95221e87b02a.png)
Mind the file size.

**Comment by mcepl** [comment]
So, are we 100% certain that the fault is on the client side or on the server one?

**Comment by marcus-h** [comment]
On 2021-04-07 08:38:41 -0700, Matěj Cepl wrote:
> So, are we 100% certain that the fault is on the client side or on the server one?
>
Yes, it is an osc issue - see [1].

[1] https://github.com/openSUSE/osc/issues/304#issuecomment-767189316

**Comment by mcepl** [comment]
I was looking at this yesterday, and without any buck-passing attitude, I have to say, that creating gigabytes-sized PyObjects in memory and pushing them to wire is truly insane. The only thing I can do in M2Crypto is perhaps to add some diagnostics, so the error message would include the size of the requested object, but that’s probably it (and I am not sure it is worth the effort).

**Comment by marcus-h** [comment]
On 2021-04-09 00:14:46 -0700, Matěj Cepl wrote:
> I was looking at this yesterday, and without any buck-passing attitude, I have to say, that creating gigabytes-sized PyObjects in memory and pushing them to wire is truly insane.

Yes, definitely! It should fixed in PR #910 ("Support an arbitrary
sized file in core.http_request") [1].

> The only thing I can do in M2Crypto is perhaps to add some diagnostics, so the error message would include the size of the requested object, but that’s probably it (and I am not sure it is worth the effort).
>
Personally, I'm fine with the error message:)

[1] https://github.com/openSUSE/osc/pull/910
