### ISSUE TITLE
mageia build failure osc local

### ISSUE THREAD

**Issue by bill-auger** [openSUSE/osc#307]
```
[   57s] [1/365] installing augeas-lenses-1.8.0-1.mga6
[   57s] error: Failed to dlopen /usr/lib64/rpm-plugins/systemd_inhibit.so libdbus-1.so.3: cannot open shared object file: No such file or directory
[   57s] error: error reading from file .init_b_cache/augeas-lenses.rpm
[   57s] exit ...
```

**Comment by Conan-Kudo** [comment]
Which Mageia target is this? Mageia 6 or Mageia Cauldron?

**Comment by bill-auger** [comment]
sry - this was over a month ago - all i can remember is that is was Mageia Cauldron - i have this building successfully now but i dont remember how i fixed it or if i did anything at all particularly that fixed it - perhaps my .spec file was NFG or perhaps some broken package got updated since then - i dunno

**Comment by bill-auger** [comment]
one thing i notice is the number of packages shown in the OP (365) - now that it is building correctly the number of packages is 424
