### ISSUE TITLE
Provide github command line workflow compatibility mode

### ISSUE THREAD

**Issue by celan** [openSUSE/osc#308]
Many people are used to the git/github workflow for every day use. When switching between osc and git commands it's annyoing and you tend to make mistakes or you are simply slower. Therefore I suggest a compatibility mode like bash has for line editing where you can switch between vi and emacs mode.

**Comment by marcus-h** [comment]
On 2017-07-19 08:08:38 -0700, Stephan Barth wrote:
> Many people are used to the git/github workflow for every day use. When switching between osc and git commands it's annyoing and you tend to make mistakes or you are simply slower. Therefore I suggest a compatibility mode like bash has for line editing where you can switch between vi and emacs mode.
> 
Hmm this description is quite "vague". Can you give a few examples
of the to be added git-like commands + their effects?

**Comment by dmach** [comment]
Closing for insufficient details.
If you still want this change, please open a new issue with examples and ideally a list of actionable items to be implemented.
