### ISSUE TITLE
osc results --xml PROJECT PACKAGE hangs 

### ISSUE THREAD

**Issue by mimi1vx** [openSUSE/osc#315]
```
osc results --xml openSUSE:Factory gcc
Traceback (most recent call last):
  File "/usr/bin/osc", line 41, in <module>
    r = babysitter.run(osccli)
  File "/usr/lib/python2.7/site-packages/osc/babysitter.py", line 61, in run
    return prg.main(argv)
  File "/usr/lib/python2.7/site-packages/osc/cmdln.py", line 343, in main
    return self.cmd(args)
  File "/usr/lib/python2.7/site-packages/osc/cmdln.py", line 366, in cmd
    retval = self.onecmd(argv)
  File "/usr/lib/python2.7/site-packages/osc/cmdln.py", line 500, in onecmd
    return self._dispatch_cmd(handler, argv)
  File "/usr/lib/python2.7/site-packages/osc/cmdln.py", line 1230, in _dispatch_cmd
    return handler(argv[0], opts, *args)
  File "/usr/lib/python2.7/site-packages/osc/commandline.py", line 5056, in do_results
    for xml in get_package_results(**kwargs):
  File "/usr/lib/python2.7/site-packages/osc/core.py", line 5609, in get_package_results
    xml = ''.join(show_results_meta(apiurl, project, package, *args, **kwargs))
TypeError: show_results_meta() got an unexpected keyword argument 'showexcl'

```

boo#1053384

**Comment by marcus-h** [comment]
On 2017-08-11 09:21:12 +0000, Ondřej Súkup wrote:
>  ```
> osc results --xml openSUSE:Factory gcc
> Traceback (most recent call last):
>   File "/usr/bin/osc", line 41, in <module>
>     r = babysitter.run(osccli)
>   File "/usr/lib/python2.7/site-packages/osc/babysitter.py", line 61, in run
>     return prg.main(argv)
>   File "/usr/lib/python2.7/site-packages/osc/cmdln.py", line 343, in main
>     return self.cmd(args)
>   File "/usr/lib/python2.7/site-packages/osc/cmdln.py", line 366, in cmd
>     retval = self.onecmd(argv)
>   File "/usr/lib/python2.7/site-packages/osc/cmdln.py", line 500, in onecmd
>     return self._dispatch_cmd(handler, argv)
>   File "/usr/lib/python2.7/site-packages/osc/cmdln.py", line 1230, in _dispatch_cmd
>     return handler(argv[0], opts, *args)
>   File "/usr/lib/python2.7/site-packages/osc/commandline.py", line 5056, in do_results
>     for xml in get_package_results(**kwargs):
>   File "/usr/lib/python2.7/site-packages/osc/core.py", line 5609, in get_package_results
>     xml = ''.join(show_results_meta(apiurl, project, package, *args, **kwargs))
> TypeError: show_results_meta() got an unexpected keyword argument 'showexcl'
> 
> ```
Already fixed in commit 900ee88b. The recent osc package in the
openSUSE:Tools project should have this fix.
