### ISSUE TITLE
osc always says 100% cache miss when building debian packages with spec files

### ISSUE THREAD

**Issue by Conan-Kudo** [openSUSE/osc#321]
Whenever doing `osc build` for building Debian packages that use a spec file as a source, it always has a 100% cache miss and redownloads everything unnecessarily.

For example, when building `cscript` for Debian 9.0 from `home:Pharaoh_Atem:cscript`, it always returns this message:
```
100.0% cache miss. 0/153 dependencies cached.
```

It can be reproduced by doing the following:
```
$ osc co home:Pharaoh_Atem:cscript
$ cd home:Pharaoh_Atem:cscript/cscript
$ osc build Debian_9.0 x86_64
....
$ osc build Debian_9.0 x86_64
```
Each run will always have a 100% cache miss.

I believe it has to do with [how package suffixes](https://github.com/openSUSE/osc/blob/master/osc/build.py#L124-L134) are determined, but I'm not sure how this can be fixed properly.

**Comment by marcus-h** [comment]
On 2017-08-21 18:48:26 +0000, Neal Gompa (ニール・ゴンパ) wrote:
> I believe it has to do with [how package suffixes](https://github.com/openSUSE/osc/blob/master/osc/build.py#L124-L134) are determined, but I'm not sure how this can be fixed properly.
> 
Hmm yes this "guessing" is wrong. Actually, we need to take the
buildconfig's binarytype into account.

**Comment by Conan-Kudo** [comment]
@marcus-h Do we have any code anywhere in osc for parsing the buildconfig? It doesn't look like we do...
