### ISSUE TITLE
osc submitreq TARGETPROJ fails with a syntax error

### ISSUE THREAD

**Issue by jnweiger** [openSUSE/osc#328]
With osc-0.159 and also git master:
osc submitreq TARGETPROJ
bails out with unbound variable t.

**Comment by jnweiger** [comment]
Trivially fixed https://github.com/openSUSE/osc/pull/327

The variable should be 'target_project', not 't'.
Am I the first user to try that feature? :-)

**Comment by marcus-h** [comment]
Fixed in commit 2e6c838d662e281868fa4d7b7d96347be5e2012b.
Thanks again for the fix!
