### ISSUE TITLE
`osc rq show --interactive $ID`  doesn't show the comments

### ISSUE THREAD

**Issue by FelixZhang** [openSUSE/osc#330]
The comments show in the non-interactive mode though. This could bring confusions to the reviewers sometimes.

**Comment by marcus-h** [comment]
On 2017-09-04 08:59:22 +0000, Felix Zhang wrote:
> The comments show in the non-interactive mode though. This could bring confusions to the reviewers sometimes.
> 
Marco already fixed it in commit 7804a8c.
