### ISSUE TITLE
osc build -M requires flavor to have been commited first

### ISSUE THREAD

**Issue by nmorey** [openSUSE/osc#334]
Trying to run `osc build -M new_flavour` fails with an error 400 if the flavor has not been commited to OBS.

Although not blocking, this means it is necessary to first update the _multibuild file, commit and only afterward test it.
Plus the error message is unclear:
```
$ osc build -M tutu
Building openmpi.spec for openSUSE_Factory/x86_64
Getting buildinfo from server and store to /work1/nmorey/workspace/alternates/EnvMod/openmpi/.osc/_buildinfo-openSUSE_Factory-x86_64.xml
Server returned an error: HTTP Error 400: Bad Request
remote error: did not get project back from src server
```

**Comment by dmach** [comment]
I have successfully built a test package with a flavor that did not exist on server.
It must have been fixed in the meantime... Closing.
