### ISSUE TITLE
Missing explanation for status 'R'

### ISSUE THREAD

**Issue by sebix** [openSUSE/osc#336]
I modified a package locally (without committing) and then updated (updated contained the same modifications). I now have this `osc status` output:
```
R    pymisp-2.4.80.tar.gz
```

The status `R` is not mentioned in the help for `osc status`. This is osc 0.159 on TW.

**Comment by mbluemer** [comment]
For reference the value of `R` is returned from here: [https://github.com/openSUSE/osc/blob/master/osc/core.py#L1874-L1875](https://github.com/openSUSE/osc/blob/master/osc/core.py#L1874-L1875)
If I'm reading this correctly the changes exists both locally and in the store but are still marked to be added?

**Comment by sebix** [comment]
>  If I'm reading this correctly the changes exists both locally and in the store but are still marked to be added?

Yes, sounds reasonable

**Comment by marcus-h** [comment]
On 2017-10-03 09:56:43 -0700, Mark Bluemer wrote:
> For reference the value of `R` is returned from here: [https://github.com/openSUSE/osc/blob/master/osc/core.py#L1874-L1875](https://github.com/openSUSE/osc/blob/master/osc/core.py#L1874-L1875)
> If I'm reading this correctly the changes exists both locally and in the store but are still marked to be added?
> 
Yes. An "R" state can be produced as follows:
- osc rm file
- echo foo > file
- osc add file

=> the former file was "replaced". I updated the "osc st --help" text
in commit aea395a.

**Comment by sebix** [comment]
Thanks!
