### ISSUE TITLE
Fix anonymous, /public, build experience

### ISSUE THREAD

**Issue by jberry-suse** [openSUSE/osc#342]
Currently, `osc-plugin-factory` does a build and deploy from travisci to obs. The build is done manually via rpm commands and such, while the deploy is done using `osc`. It would be preferred to use `osc build` in some cases and my first thought on setting it up that way, but it has it's downsides and currently does not work out-of-the-box. Some of this may require tweaks to the permissions on OBS side to make the calls available for `osc` to use.

The OBS credentials for a user are stored using a travisci secret variable which means it is only exposed on the main project branches and not on pull requests to avoid people being able to get a hold of the value. The problem of course is that one wants to run builds to see that `.spec` changes to not causes failures, but that does not work properly for an anonymous user. One could setup a throw-away account, but that is rather ugly as there would appear to be no reason for this not to work anonymously.

The steps involved:

1. `osc checkout`
2. point `_service` file at local clone
3. run `osc service disabledrun`
4. run `osc build`

The last two steps do not work properly. The third step can be fixed so long as there are not server-side services by change `raise` in `osc.core.getProjectGlobalServices()` to a `pass` so that it simple ignores a failure to `getprojectservices`. Seems like a similar fallback is likely alright in most cases, but exposing that API would seem to have no downsides as the rest of the files are already downloaded.

The issues with `osc build` are the calls to get `_buildinfo`. This shares the fact that it is a `POST` call like `getprojectservices` which is likely why it is permissioned differently.

I would expect that I should be able to perform a local build of a package without needing an OBS account and the CI usecase is a very solid one.

Unless there are clear ways to workaround this, it may make sense to just create issues against OBS, but I'd like input from someone more familiar with these bits.

**Comment by jcvenegas** [comment]
Hi @jberry-suse, what is the final solution for this?. I am willing to do something similar to test our automation to generate obs packages but want to build local packages to make sure the automation works properly in a CI (jenkins) .

Are you still using a secret from travisci?

Here are the results I got.
```
osc co home:katacontainers:release/runtime -o /tmp/update.sh.TE5fPVJATjC
A    /tmp/update.sh.TE5fPVJATjC
A    /tmp/update.sh.TE5fPVJATjC/_service
A    /tmp/update.sh.TE5fPVJATjC/debian.changelog
A    /tmp/update.sh.TE5fPVJATjC/debian.compat
A    /tmp/update.sh.TE5fPVJATjC/debian.control
A    /tmp/update.sh.TE5fPVJATjC/debian.rules
A    /tmp/update.sh.TE5fPVJATjC/kata-runtime.dsc
A    /tmp/update.sh.TE5fPVJATjC/kata-runtime.spec
A    /tmp/update.sh.TE5fPVJATjC/source_cc-runtime.py
osc service run
Server returned an error: HTTP Error 404: Not Found
```
Am I missing to do a local build without a obs account? ( I dont want to expose those credentials in the CI).

**Comment by jberry-suse** [comment]
I have some further cleanup locally that I haven't got around to pushing, but everything is working in our travis-ci setup.

Secret is used for deploying to OBS from master branch, and unfortunately after talking with OBS team and such the best I could come up with was a throwaway account used for merge request runs.

https://github.com/openSUSE/openSUSE-release-tools/blob/2550cb4240c93b904f09167d662747c4e46f2ba7/.travis.yml#L10-L13

https://github.com/openSUSE/openSUSE-release-tools/blob/dc1dc370a6860a349c02760b0b26faef06831e3a/dist/ci/obs-build-target

The deploying also takes care of making a request to Factory if no exists and since we have cron enabled on travis-ci to run once daily it will catch-up even if development stops.

https://github.com/openSUSE/openSUSE-release-tools/commit/944a7720f7f18b61cdae325813ae93c9f645255f

I would like to extract these bits and put in a separate repo as a template for others, but I haven't gotten around to it. Presumably this should be enough for you to go on. If you have trouble or questsions, let me know.

**Comment by hramrach** [comment]
what's the problem with local builds without an account?

**Comment by marcus-h** [comment]
On 2021-07-02 10:21:38 -0700, Michal Suchánek wrote:
> what's the problem with local builds without an account?
>
There is currently no (supported) route in the OBS API for
this (AFAIK, this is done on purpose).

**Comment by hramrach** [comment]
what's the purpose of not allowing local builds without an account?

**Comment by hennevogel** [comment]
> what's the purpose of not allowing local builds without an account?

Being able to "rate limit" people.

**Comment by hramrach** [comment]
Why is rate-limiting users' local builds useful?

Sounds a bit arbitrary.

**Comment by hennevogel** [comment]
> Why is rate-limiting users' local builds useful?

Local builds also use resources on the API, especially network.

**Comment by hramrach** [comment]
So do many other actions some of which you can do anonymously.

**Comment by hennevogel** [comment]
> So do many other actions some of which you can do anonymously.

Erm, the API, that osc is using, requires authentication for everything. Don't shoot the messenger, I'm just telling you how things are 😃

**Comment by dmach** [comment]
This is something we can't fix in osc directly, the OBS API is authenticated. Closing.
