### ISSUE TITLE
'osc sr --yes ...' doesn't supersede existing requests as promised

### ISSUE THREAD

**Issue by wfeldt** [openSUSE/osc#343]
`osc help sr` says:

`--yes               proceed without asking.`

But it assumes 'no'.

It would be nice to have osc do the right thing here to avoid old requests piling up in auto-submissions.

**Comment by marcus-h** [comment]
On 2017-10-06 08:27:41 +0000, Steffen Winterfeldt wrote:
> 'osc help sr' says:
> 
> `--yes               proceed without asking.`
> 
> But it assumes 'no'.
> 
Yep, see also https://github.com/openSUSE/osc/pull/269.

> It would be nice to have osc do the right thing here to avoid old requests piling up in auto-submissions.
> 
Fixed in commit 760d4d6.
