### ISSUE TITLE
'osc ci' exit code doesn't take source service results into account

### ISSUE THREAD

**Issue by wfeldt** [openSUSE/osc#344]
`osc ci ...` returns with exit code 0 even if a source service reports an error and the actual check-in fails.

Please have osc exit with nonzero exit code in this case so the condition can be handled in scripts.

**Comment by marcus-h** [comment]
On 2017-10-06 08:33:02 +0000, Steffen Winterfeldt wrote:
> `osc ci ...` returns with exit code 0 even if a source service reports an error and the actual check-in fails.
> 
> Please have osc exit with nonzero exit code in this case so the condition can be handled in scripts.
> 
Hmm are you talking about local service runs or remote service runs?
If the former fails, osc commit exits with status 1. If the latter
fails, osc exits with status 0, because the actual commit was
successful.

**Comment by wfeldt** [comment]
Local; it exits with 0 for me:

# osc ci -m "xxx"
- package has check-build.sh: (unchanged)
- package has installation-images-rpmlintrc: (unchanged)
changelog not in sequence:
[...]
Please fix with your own tools or try /usr/lib/obs/service/source_validators/helpers/fix_changelog
Aborting: service call failed:  /usr/lib/obs/service/source_validator --outdir /wrk1/obs/home:snwint/installation-images/tmpVnY_x7.source_validator.service
A service failed with error: 1
# echo $?
0

**Comment by marcus-h** [comment]
On 2017-10-06 11:12:03 +0000, Steffen Winterfeldt wrote:
> Local; it exits with 0 for me:
> 
Ugh... right. Fixed in commit 6acc90d.
