### ISSUE TITLE
subprocess.check_output() not in Python 2.6

### ISSUE THREAD

**Issue by birkenfeld** [openSUSE/osc#355]
Is osc supposed to be still Python 2.6/RHEL6 compatible? If yes, `check_output` used [here](https://github.com/openSUSE/osc/blob/master/osc/core.py#L7575) needs to be replaced, as it's new in 2.7.

**Comment by lethliel** [comment]
I created a PR to make it 2.6 compatible.

**Comment by birkenfeld** [comment]
Thanks, that was fast :)
