### ISSUE TITLE
osc getbinaries ignores API setting

### ISSUE THREAD

**Issue by olafhering** [openSUSE/osc#359]
osc 0.161.1 was instructed to talk to OBS. Instead it pokes at files in $PWD:

````
olaf@latitude:~/work/pbs/Multimedia/kodi $  bash -x obs getbinaries openSUSE:Factory/mariadb
+ export OSC_CONFIG=/home/olaf/.osc/oscrc
+ OSC_CONFIG=/home/olaf/.osc/oscrc
+ exec /usr/bin/osc --config=/home/olaf/.osc/oscrc -A https://api.opensuse.org getbinaries openSUSE:Factory/mariadb
Server returned an error: HTTP Error 404: Not Found
Multimedia
````

**Comment by lethliel** [comment]
is `~/work/pbs/Multimedia/kodi` a valid working copy? 

Please try `getbinaries openSUSE:Factory/mariadb <repo> <arch>`
`osc getbinaries openSUSE:Factory/mariadb standard x86_64`

**Comment by olafhering** [comment]
Yes, it is a working copy. But why would it matter? It should probably error out right away because <repo> <arch> are missing.

**Comment by lethliel** [comment]
No it shouldn't. It tries to determine valid repo/arch combinations to present to the user. And it uses the actual working directory.

It tries to get the metadata of https://api.opensuse.org/source/Multimedia/, but this does not exists. 

```
marco@linux:~> osc api https://api.opensuse.org/source/Multimedia/_meta
Server returned an error: HTTP Error 404: Not Found
Multimedia
```

**Comment by olafhering** [comment]
In some sense your are probably right that the single 'project/path' option could be translated into the supported 'repository arch' options. I do not know the internals.

**Comment by lethliel** [comment]
This works as intended.
