### ISSUE TITLE
osc build -p ../rpms/tw doesnt send recommends to the server which makes client side build behave differently to server side build

### ISSUE THREAD

**Issue by darix** [openSUSE/osc#363]
osc build -p ../rpms/tw doesnt send recommends to the server which makes client side build behave differently to server side build

**Comment by marcus-h** [comment]
On 2017-12-14 18:37:26 +0000, darix wrote:
> osc build -p ../rpms/tw doesnt send recommends to the server which makes client side build behave differently to server side build
> 
Fixed in commit 0b241a9 ('Consider "recommends" and "supplements"
in build.create_deps').
