### ISSUE TITLE
cannot build sample AppImage with osc on ubuntu 16.04

### ISSUE THREAD

**Issue by slowphil** [openSUSE/osc#365]
when trying "osc build AppImage x86_64 appimage.yml" on the sample app home:probono/QtQuickApp listed on[ this page](https://github.com/AppImage/AppImageKit/wiki/Using-Open-Build-Service) I get the following error:

...
[    3s] now finalizing build dir...
[    3s] cp: omitting directory '/home/phil/home:probono/QtQuickApp/QtQuickApp'
[    3s] Unpacking QtQuickApp.obscpio ...
[    3s] 72 blocks
[    3s] Running build time source services...
[    3s] -----------------------------------------------------------------
[    3s] ----- building appimage.yml (user abuild)
[    3s] -----------------------------------------------------------------
[    3s] -----------------------------------------------------------------
[    3s] bash: dpkg-architecture: command not found
[    3s] 
[    3s] mylinuxpc failed "build appimage.yml" at Wed Jan  3 21:33:56 UTC 2018

Note that my system does have dpkg-architecture installed.
I also tried running the osc AppImage (instead of the one taken from OBS) and it immediatly fails with :
ImportError: No module named site

**Comment by marcus-h** [comment]
On 2018-01-03 22:40:34 +0000, slowphil wrote:
> when trying "osc build AppImage x86_64 appimage.yml" on the sample app home:probono/QtQuickApp listed on[ this page](https://github.com/AppImage/AppImageKit/wiki/Using-Open-Build-Service) I get the following error:
> 
> ...
> [    3s] now finalizing build dir...
> [    3s] cp: omitting directory '/home/phil/home:probono/QtQuickApp/QtQuickApp'
> [    3s] Unpacking QtQuickApp.obscpio ...
> [    3s] 72 blocks
> [    3s] Running build time source services...
> [    3s] -----------------------------------------------------------------
> [    3s] ----- building appimage.yml (user abuild)
> [    3s] -----------------------------------------------------------------
> [    3s] -----------------------------------------------------------------
> [    3s] bash: dpkg-architecture: command not found
> [    3s] 
> [    3s] mylinuxpc failed "build appimage.yml" at Wed Jan  3 21:33:56 UTC 2018
> 
Are you doing a chroot based build? If so, can try it again with
"osc build --clean AppImage x86_64 appimage.yml" (which nukes the
old buildroot)?

> Note that my system does have dpkg-architecture installed.

Your system binaries are not considered at this point.

**Comment by slowphil** [comment]
Yes, I guess it is a usual chroot build (I did nothing special), and I am a bit surprised it looks for dpkg-architecture, I was more expecting something rpm-based. 
The output I posted earlier was not resulting from the first run of the command that's why it took only 3 seconds to fail. With the --clean option, it re-downloads all the packages , but still fails all the same after 38 seconds... 
(osc version is 0.162.1, the lastest available on the [repo](https://download.opensuse.org/repositories/openSUSE:/Tools/xUbuntu_16.04/all/osc_0.162.1_all.deb))

**Comment by marcus-h** [comment]
On 2018-01-04 07:48:31 +0000, slowphil wrote:
> Yes, I guess it is a usual chroot build (I did nothing special), and I am a bit surprised it looks for dpkg-architecture, I was more expecting something rpm-based. 

Hmm yes... it seems to be a bug in the build script (not osc).
I just created a PR [1] that should fix it. As a hacky
workaround you could create a dummy /bin/rpm file
(touch /bin/rpm; chmod +x /bin/rpm - do not forget to remove
this file afterwards...)

[1] https://github.com/openSUSE/obs-build/pull/418

**Comment by marcus-h** [comment]
On 2018-01-05 00:02:20 +0100, Marcus Hüwe wrote:
> On 2018-01-04 07:48:31 +0000, slowphil wrote:
> > Yes, I guess it is a usual chroot build (I did nothing special), and I am a bit surprised it looks for dpkg-architecture, I was more expecting something rpm-based. 
> 
> Hmm yes... it seems to be a bug in the build script (not osc).
> I just created a PR [1] that should fix it.

Superseded by PR https://github.com/openSUSE/obs-build/pull/419.

> As a hacky
> workaround you could create a dummy /bin/rpm file
> (touch /bin/rpm; chmod +x /bin/rpm - do not forget to remove
> this file afterwards...)
> 
Please ignore this... this will most likely not work, because in
this case it tries to call createrepo, which probably does not
exist in your host system.

> [1] https://github.com/openSUSE/obs-build/pull/418
