### ISSUE TITLE
only unmount filesystems inside a buildroot if there are no other processes still inside

### ISSUE THREAD

**Issue by darix** [openSUSE/osc#367]
1. shell 1: osc build ... 
2. watch  build and see some weird warning
3. shell 2: osc chroot ...
4. investigate that weird warning while the build is still running. (this is especially interesting for big packages with C++ where the build takes ages.)
5. leave the osc chroot. this leads to all file systems being unmounted and later down the road failing the build. (e.g. brp scripts requiring /dev/null)

# expected behavior

step 5 wont unmount the file systems.

**Comment by dmach** [comment]
@darix I'm unable to reproduce it, could you check if you still can?

**Comment by dmach** [comment]
Closing for lack of reproducibility.
