### ISSUE TITLE
osc build should pass '--jobs=' to build only if explicitly specified

### ISSUE THREAD

**Issue by StefanBruens** [openSUSE/osc#371]
osc currently gets the number of jobs from
1. the commandline
2. the user config
3. the default config, i.e. sysconf SC_NPROCESSORS_ONLN

and always passes a --jobs=N argument to build.

In case 'build' finds a --jobs option, it will replace the default _smp_mflags rpm macro. This breaks e.g. usage of _smp_ncpus_max to limit the number of jobs from inside the build script.

The default definition of _smp_mflags is:
```
%_smp_mflags %([ -z "$RPM_BUILD_NCPUS" ] \\\
        && RPM_BUILD_NCPUS="`/usr/bin/getconf _NPROCESSORS_ONLN`"; \\\
        ncpus_max=%{?_smp_ncpus_max}; \\\
        if [ -n "$ncpus_max" ] && [ "$ncpus_max" -gt 0 ] && [ "$RPM_BUILD_NCPUS" -gt "$ncpus_max" ]; then RPM_BUILD_NCPUS="$ncpus_max"; fi; \\\
        if [ "$RPM_BUILD_NCPUS" -gt 1 ]; then echo "-j$RPM_BUILD_NCPUS"; fi)
```
so rpm will limit the number of jobs if not specified explicitly

**Comment by marcus-h** [comment]
On 2018-01-22 21:47:34 +0000, StefanBruens wrote:
> osc currently gets the number of jobs from
> 1. the commandline
> 2. the user config
> 3. the default config, i.e. sysconf SC_NPROCESSORS_ONLN
> 
> and always passes a --jobs=N argument to build.
> 
You can work around it by setting the "build-jobs" option to 1
(or any other integer <= 1). In this case, no --jobs option is
passed to the build script. (Note that this requires commit 1a92c8b
("The 'build-jobs' config option should be an integer").)

If you are doing a kvm build, the absence of the --jobs has an impact
on the number of CPUs in the VM (no "-smp ..." option is passed to the
qemu-kvm binary).

Is this "workaround" ok for you?

**Comment by dmach** [comment]
I've decided to change the code that if `build_jobs > 0` then pass it to the build tool.
Sometimes it makes sense to keep the build jobs at 1.
The change is documented in the configuration (which also gets rendered as oscrc man page).
