### ISSUE TITLE
Disable non-secure connection warning for non-https connections

### ISSUE THREAD

**Issue by jberry-suse** [openSUSE/osc#373]
Unless I am missing something, the whole point of the following warning is in relation to checking ssl certificates and warning you about a self-signed certificates.

https://github.com/openSUSE/osc/blob/5e3fe8ba08d7625140f06441c804e82790ea7db0/osc/conf.py#L563

When running against local OBS instance using their provided docker method there is not an `https` connection, not even a self-signed `https`. I would expect an `apiurl` configured to `http` to not print this message since the user in-fact had to specify the `apiurl` and chose without `https`. Clearly there is no certificate to check so a message indicating certificate check is disabled does not make a lot of sense. Instances should disallow non-https connections as desired, but to have the tool complain _all_ the time is just silly.

If there is some push-back at least provide an option that can be set in config to hide the warning.

When running tests one is inundated with these messages.

```
nosetests --with-coverage --cover-package=. --cover-inclusive
WARNING: SSL certificate checks disabled. Connection is insecure!
WARNING: SSL certificate checks disabled. Connection is insecure!
.WARNING: SSL certificate checks disabled. Connection is insecure!
WARNING: SSL certificate checks disabled. Connection is insecure!
.WARNING: SSL certificate checks disabled. Connection is insecure!
WARNING: SSL certificate checks disabled. Connection is insecure!
.WARNING: SSL certificate checks disabled. Connection is insecure!
WARNING: SSL certificate checks disabled. Connection is insecure!
.WARNING: SSL certificate checks disabled. Connection is insecure!
WARNING: SSL certificate checks disabled. Connection is insecure!
.WARNING: SSL certificate checks disabled. Connection is insecure!
...S..........................WARNING: SSL certificate checks disabled. Connection is insecure!
WARNING: SSL certificate checks disabled. Connection is insecure!
.WARNING: SSL certificate checks disabled. Connection is insecure!
WARNING: SSL certificate checks disabled. Connection is insecure!
WARNING: SSL certificate checks disabled. Connection is insecure!
WARNING: SSL certificate checks disabled. Connection is insecure!
.WARNING: SSL certificate checks disabled. Connection is insecure!
WARNING: SSL certificate checks disabled. Connection is insecure!
...WARNING: SSL certificate checks disabled. Connection is insecure!
..WARNING: SSL certificate checks disabled. Connection is insecure!
.WARNING: SSL certificate checks disabled. Connection is insecure!
.WARNING: SSL certificate checks disabled. Connection is insecure!
.......WARNING: SSL certificate checks disabled. Connection is insecure!
..................
```

https://travis-ci.org/openSUSE/osc-plugin-factory/jobs/333524860

And running any command against the instance you get this message as well.

**Comment by marcus-h** [comment]
On 2018-01-26 16:17:22 +0000, Jimmy Berry wrote:
> Unless I am missing something, the whole point of the following warning is in relation to checking ssl certificates and warning you about a self-signed certificates.
> 
> https://github.com/openSUSE/osc/blob/5e3fe8ba08d7625140f06441c804e82790ea7db0/osc/conf.py#L563
> 
It sole purpose is to "warn" the user if the sslcertk is explicitly disabled
or if http is used.

> When running against local OBS instance using their provided docker method there is not an https connection, not even a self-signed https. I would expect an `apiurl` configured to `http` to not print this message since the user in-fact had to specify the `apiurl` and choose without `https`. Instances should disallow non-https connections as desired, but to have the tool complain _all_ the time is just silly.
> 
> If there is some push-back at least provide an option that can be set in config to hide the warning.
> 
What we could do is the following: if the sslcertk is globally disabled
or disabled for the particular apiurl, then no warning is displayed. Would
this work for you?

> When running tests one is inundated with these messages.
> 
(The warnings could be filtered.)

**Comment by jberry-suse** [comment]
> What we could do is the following: if the sslcertk is globally disabled
> or disabled for the particular apiurl, then no warning is displayed. Would
> this work for you?

Yes, any sort of configuration option to hide them would be appreciated.

**Comment by dmach** [comment]
We have decided not to fix this in the current code base, because we'll be moving to a new urllib3 based code in #1000 shortly.
We'll no longer support plain http (we don't want to send passwords in plain text over the network & it's always possible to create a self-signed cert for testing purposes).

**Comment by hennevogel** [comment]
> We'll no longer support plain http

Hm, but *we* (as in OBS) support running on HTTP... 

There is also the case of development environments that is in wide usage (as you can see in this issue) by many people.

> we don't want to send passwords in plain text over the network

There is not necessarily a network involved that needs protection. Can you leave this decision http/https up to the people setting things up please?
