### ISSUE TITLE
Need a way to tweak qemu-kvm arguments in oscrc

### ISSUE THREAD

**Issue by matwey** [openSUSE/osc#379]
Hello,

I am running osc on ARMv8 SBC. Unfortunately, to run `qemu-kvm` correctly `-M virt,gic-version=2` should be appended in my case. It would be great to have a way to specify additional options in `.oscrc`.

This option use-case would be not limited only to ARM-based systems. For instance, due to specific bugs in qemu/kvm, I have to use  `-cpu host,-tsc-deadline,pmu=off` at ESXi-hosted x86_64 guest. Currently, there is no way to run `osc` on any of such hosts.

Recent versions of `build` script have `-vm-custom-opt` argument to pass additional options to the hypervisor.

**Comment by matwey** [comment]
Well, it would be great to have an opportunity not to write build-opt every time, but store this for every-day usage.

**Comment by dmach** [comment]
I don't think we should extend osc to support options per build type.
Please use an alias or write a shell wrapper script instead.
