### ISSUE TITLE
copypac/branch option for automatically set the revision

### ISSUE THREAD

**Issue by Ana06** [openSUSE/osc#382]
As you can see in our [OBS release documentation] we many times need to run `copypath` follow by `setlinkrev`, for example:

```
osc copypac OBS:Server:Unstable $PACKAGE OBS:Server:$VERSION:Staging
osc setlinkrev OBS:Server:$VERSION:Staging $PACKAGE
```

It would be nice to have an option in `copypac` and `branch` to set the revision instead. :bowtie:

**Comment by marcus-h** [comment]
On 2018-02-14 15:07:40 +0000, Ana María Martínez Gómez wrote:
> As you can see in our [OBS release documentation] we many times need to run `copypath` follow by `setlinkrev`, for example:
> 
(Do you have link to the docs?)

> ```
> osc copypac OBS:Server:Unstable $PACKAGE OBS:Server:$VERSION:Staging
> osc setlinkrev OBS:Server:$VERSION:Staging $PACKAGE
> ```
> 
Would "osc copypac -e ..." work for you? (I don't know the exact
purpose/workflows of the staging project.)

Alternatively, the two commands can be encapsulated in an own
"staging-copypac" via an osc plugin.

> It would be nice to have an option in `copypac` and `branch` to set the revision instead. :bowtie:  
> 
Hmm we could add such an option to the branch command (or rather
implement it in the backend?), but adding it to "copypac" doesn't
make too much sense (IMHO).

**Comment by dmach** [comment]
Both `osc copypac` and `osc branch` commands have `-r/--revision` option for a while. Closing.
