### ISSUE TITLE
osc doesn't work with new and/or/with/etc spec file conditional requires

### ISSUE THREAD

**Issue by dmulder** [openSUSE/osc#389]
See here:
http://rpm.org/user_doc/boolean_dependencies.html

When these conditionals are present, osc assumes the and/or/with/etc commands are package names, and splits them onto separate lines.
Like this:

Requires:       krb5-client
Requires:       or
Requires:       or
Requires:       or
Requires:       or
Requires:       or
Requires:       python-dnspython
Requires:       python-ldap
Requires:       python-netifaces
Requires:       python-python-pam
Requires:       python3-dnspython
Requires:       python3-ldap
Requires:       python3-netifaces
Requires:       python3-python-pam
Requires:       samba-client
Requires:       samba-python
Requires:       samba-python3

I'm trying to do conditional packaging so that a package can either accept python3 or python2. Can this be fixed please?

**Comment by marcus-h** [comment]
On 2018-03-06 14:16:54 -0800, David Mulder wrote:
> See here:
> http://rpm.org/user_doc/boolean_dependencies.html
> 
> When these conditionals are present, osc assumes the and/or/with/etc commands are package names, and splits them onto separate lines.
> Like this:
> 
> Requires:       krb5-client
> Requires:       or
> Requires:       or
> Requires:       or
> Requires:       or
> Requires:       or
> Requires:       python-dnspython
> Requires:       python-ldap
> Requires:       python-netifaces
> Requires:       python-python-pam
> Requires:       python3-dnspython
> Requires:       python3-ldap
> Requires:       python3-netifaces
> Requires:       python3-python-pam
> Requires:       samba-client
> Requires:       samba-python
> Requires:       samba-python3
> 
> I'm trying to do conditional packaging so that a package can either accept python3 or python2. Can this be fixed please?
> 
Where do you see this behavior?
Which osc command did you execute?

**Comment by adrianschroeter** [comment]
this is most likely a problem of the obs-service-format_spec_file service. osc is not touching the spec file...

**Comment by dmulder** [comment]
It seems this has been report against obs-service-format_spec_file [here](https://github.com/openSUSE/obs-service-format_spec_file/issues/23).

**Comment by dmulder** [comment]
Code to fix this is in this [MR](https://github.com/openSUSE/obs-service-format_spec_file/pull/32).

**Comment by lethliel** [comment]
So this can be closed. Thanks for the report.
