### ISSUE TITLE
symlinked $HOME/.oscrc gets replaced with a ordinary file

### ISSUE THREAD

**Issue by HeikoSchlittermann** [openSUSE/osc#390]
For privacy reasons I had `~/.oscrc` linked from NFS mounted home directory to a directory on local storage. When _osc_ added something to my `~/.oscrc`, it replaced the symlink with an ordinary file, thus exposing my obs login credentials to the machines mounting the NFS share.

**Comment by logological** [comment]
It should follow the symlink and write to the real file.  A lot of people (myself included) manage their dotfiles across machines using a Git repository and GNU Stow to create a symlink farm.  Having `osc` remove the symlink breaks this setup.

**Comment by HeikoSchlittermann** [comment]
Thans for fixing this!

**Comment by marcus-h** [comment]
On 2021-12-08 09:36:33 +0000, Heiko Schlittermann wrote:
> Thanks for fixing this!
>
Kudos go to @dmach:)
