### ISSUE TITLE
osc diff should have "ignore whitespace" support

### ISSUE THREAD

**Issue by lrupp** [openSUSE/osc#396]
Like here on [Github](https://blog.github.com/2011-10-21-github-secrets/), "osc diff" should provide an additional option to ignore whitespace changes in the diff. ( Add '-w1' or '--whitespace=1' to the URL to see the diff with whitespace ignored...)

**Comment by dmach** [comment]
Osc uses `difflib.diff_bytes()` that doesn't support ignoring whitespaces.
So it is not doable without redoing diffing completely (use another lib? call the `diff` command?).
Also, it would work only locally because OBS doesn't support ignoring whitespaces in diffs.
