### ISSUE TITLE
Feature: command to download new source and delete old source

### ISSUE THREAD

**Issue by guoyunhe** [openSUSE/osc#397]
For example, if I want to just update an software from 3.1.4 to 3.1.5, no build configuration changes, I have to manually:

1. Modify version in spec file.
2. Find the download link, download tar.gz from website/github and copy to project.
3. Delete old tar.gz file.
4. osc ar

to prepare new source.

I am thinking if osc can automatically download source tar.gz if I have specified download URL in spec file.

```
Source:         https://github.com/slacka/%{name}/archive/v%{version}/%{name}-%{version}.tar.gz
```
The steps will be:

1. Modify version in spec file
2. osc downloadsource
3. Delete old tar.gz file
4. osc ar

It will save some clicks in web browser and file manager.

**Comment by marcus-h** [comment]
On 2018-03-28 23:18:53 -0700, Guo Yunhe wrote:
> For example, if I want to just update an software from 3.1.4 to 3.1.5, no build configuration changes, I have to manually:
> 
> 1. Modify version in spec file.
> 2. Find the download link, download tar.gz from website/github and copy to project.
> 3. Delete old tar.gz file.
> 4. osc ar
> 
> to prepare new source.
> 
You can automate this via so-called source services [1]. Hence,
I'm closing this issue (if you have further questions, just ask:) ).

[1] http://openbuildservice.org/help/manuals/obs-user-guide/cha.obs.source_service.html
