### ISSUE TITLE
tarball with tar_scm service fetch from github ends up almost empty

### ISSUE THREAD

**Issue by frispete** [openSUSE/osc#399]
Hi, 

today, I tried to update my [FreeRDP](https://build.opensuse.org/package/show/home:frispete:RemoteDesktop/freerdp2) build as always in a checked out copy:
```
$ osc service disabledrun
Cloning into bare repository '/var/cache/obs/tar_scm/56b4eb933fa2e77b484bad0ce4fb93a994aa647426be674d3f66f69a6b033de0/FreeRDP'...
a9ecd6a6ccc71130805a6bf3214c169fc42746ba
Cloning into '/home/hp/src/obs/home:frispete:RemoteDesktop/freerdp2/FreeRDP'...
a9ecd6a6ccc71130805a6bf3214c169fc42746ba
Compressed freerdp-2.0.0~git.1522916443.a9ecd6a6c.tar to freerdp-2.0.0~git.1522916443.a9ecd6a6c.tar.xz
```
I already removed the cached repo from /var/cache/obs/tar_scm, just in case, but the resulting tarball is almost empty (second tar.xz file):
```
$ l
drwxrwxr-x  3 hp lisa      18  5. Apr 20:21 FreeRDP/
-rw-rw-r--  1 hp lisa 4335868 14. Feb 11:55 freerdp-2.0.0~git.1518601944.ed4f54ab4.tar.xz
-rw-rw-r--  1 hp lisa     200  5. Apr 20:21 freerdp-2.0.0~git.1522916443.a9ecd6a6c.tar.xz
-rw-r--r--  1 hp lisa   66170  5. Apr 20:21 freerdp.changes
-rw-rw-r--  1 hp lisa    3943  5. Apr 20:21 freerdp.spec
drwxrwxr-x  2 hp lisa    4096 14. Feb 11:58 .osc/
-rw-rw-r--  1 hp lisa     562 26. Jan 2017  _service
-rw-rw-r--  1 hp lisa     236  5. Apr 20:21 _servicedata
$ tar tvf freerdp-2.0.0~git.1522916443.a9ecd6a6c.tar.xz
drwxrwxr-x root/root         0 2018-04-05 10:20 freerdp-2.0.0~git.1522916443.a9ecd6a6c/
```
The checked out FreeRDP dir just contains the .git folder:
```
$ l FreeRDP/
insgesamt 0
drwxrwxr-x 3 hp lisa  18  5. Apr 20:46 ./
drwxrwxr-x 4 hp lisa 275  5. Apr 20:47 ../
drwxrwxr-x 8 hp lisa 180  5. Apr 20:46 .git/
```

My versions are:
```
$ git --version
git version 2.14.1
$ osc --version
0.162.1
```
Content of _service:
```
<services>
  <service name="tar_scm" mode="disabled">
    <param name="scm">git</param>
    <param name="url">https://github.com/FreeRDP/FreeRDP.git</param>
    <param name="filename">freerdp</param>
    <param name="versionprefix">2.0.0~git</param>
    <param name="changesgenerate">enable</param>
    <param name="revision">refs/heads/master</param>
  </service>
  <service name="recompress" mode="disabled">
    <param name="file">*.tar</param>
    <param name="compression">xz</param>
  </service>
  <service name="set_version" mode="disabled"/>
</services>
```

Something more to know? Any idea,, what's going on here? 
The branch names of the FreeRDP github project didn't change to my knowledge. A normal git clone succeeds as usual.

**Comment by marcus-h** [comment]
On 2018-04-05 11:51:07 -0700, Hans-Peter Jansen wrote:
> ```
> $ l
> drwxrwxr-x  3 hp lisa      18  5. Apr 20:21 FreeRDP/
> -rw-rw-r--  1 hp lisa 4335868 14. Feb 11:55 freerdp-2.0.0~git.1518601944.ed4f54ab4.tar.xz
> -rw-rw-r--  1 hp lisa     200  5. Apr 20:21 freerdp-2.0.0~git.1522916443.a9ecd6a6c.tar.xz
> -rw-r--r--  1 hp lisa   66170  5. Apr 20:21 freerdp.changes
> -rw-rw-r--  1 hp lisa    3943  5. Apr 20:21 freerdp.spec
> drwxrwxr-x  2 hp lisa    4096 14. Feb 11:58 .osc/
> -rw-rw-r--  1 hp lisa     562 26. Jan 2017  _service
> -rw-rw-r--  1 hp lisa     236  5. Apr 20:21 _servicedata
> $ tar tvf freerdp-2.0.0~git.1522916443.a9ecd6a6c.tar.xz
> drwxrwxr-x root/root         0 2018-04-05 10:20 freerdp-2.0.0~git.1522916443.a9ecd6a6c/
> ```

Hmm works for me:

marcus@linux:~/home:frispete:RemoteDesktop/freerdp2> osc st
M    _servicedata
?    freerdp-2.0.0~git.1522916443.a9ecd6a6c.tar.xz
M    freerdp.changes
M    freerdp.spec
marcus@linux:~/home:frispete:RemoteDesktop/freerdp2> ls -la freerdp-2.0.0~git.1522916443.a9ecd6a6c.tar.xz
-rw-r--r-- 1 marcus users 4339968 Apr  5 20:58 freerdp-2.0.0~git.1522916443.a9ecd6a6c.tar.xz
marcus@linux:~/home:frispete:RemoteDesktop/freerdp2>

This is probably no osc issue. Which tar_scm version are you using?
Can you try to remove/rename the FreeRDP directory? (Just a wild
guess...)

**Comment by marcus-h** [comment]
On 2018-04-05 21:20:24 +0000, Hans-Peter Jansen wrote:
> Hm, interesting. I'm using obs-service-tar_scm-0.8.0.1520581079.e26b0ae-198.1.noarch here.

That's what I'm also using (I've no obs-service-tar_scm package installed,
because I'm directly working on the sources, but this shouldn't make a
difference).

> Of course, I removed the FreeRDP directory. In fact, it's part of my workflow, because tar_scm complains and fails, if it exists. Which git version do you use?
> 
marcus@linux:~> git --version
git version 2.16.1
marcus@linux:~>

You can also run "osc -d service dr" to see how osc calls the
tar_scm service (maybe this helps to further debug it).

**Comment by frispete** [comment]
Okay, slowly getting to the bottom of it now.

I relocated this issue to [tar_scm](https://github.com/openSUSE/obs-service-tar_scm/issues/22) where it belongs.

Thank you, Marcus, for your support.
