### ISSUE TITLE
remote osc_hotshot.py

### ISSUE THREAD

**Issue by sleep-walker** [openSUSE/osc#400]
It seems that osc_hotshot.py is long time dead and noone cared. Let's just remove it from GIT and setup.py.

**Comment by marcus-h** [comment]
On 2018-04-10 04:11:02 +0000, Tomáš Čech wrote:
> It seems that osc_hotshot.py is long time dead and noone cared. Let's just remove it from GIT and setup.py.
> 
Let it RIP...
Thanks for the issue + PR!

**Comment by lethliel** [comment]
removed.
