### ISSUE TITLE
Get statistics after osc build?

### ISSUE THREAD

**Issue by ggardet** [openSUSE/osc#411]
Is there a mean to get statistics about max memory and disk usages from build run locally?

Such as in OBS: https://build.opensuse.org/package/statistics/openSUSE:Factory/gcc/standard/x86_64

**Comment by adrianschroeter** [comment]
On Freitag, 27. April 2018, 14:41:06 CEST wrote ggardet:
> Is there a mean to get statistics about max memory and disk usages from build run locally?
> 
> Such as in OBS: https://build.opensuse.org/package/statistics/openSUSE:Factory/gcc/standard/x86_64

Just download the _statistics file, it is part of the build result

-- 

Adrian Schroeter
email: adrian@suse.de

SUSE Linux GmbH, GF: Felix Imendörffer, Jane Smithard, Graham Norton, HRB 21284 (AG Nürnberg) 
 
Maxfeldstraße 5                         
90409 Nürnberg 
Germany

**Comment by ggardet** [comment]
I mean, if I build locally with ```osc build XXX --vm-type=kvm``` how can I get the stats?
I cannot find any _statistics file.

**Comment by adrianschroeter** [comment]
On Freitag, 27. April 2018, 14:48:25 CEST wrote ggardet:
> I mean, if I build locally with ```osc build XXX --vm-type=kvm``` how can I get the stats?
> I cannot find any _statistics file.

 --vm-type=kvm --statistics

should produce it

-- 

Adrian Schroeter
email: adrian@suse.de

SUSE Linux GmbH, GF: Felix Imendörffer, Jane Smithard, Graham Norton, HRB 21284 (AG Nürnberg) 
 
Maxfeldstraße 5                         
90409 Nürnberg 
Germany

**Comment by ggardet** [comment]
No such option:
```osc build: no such option: --statistics```

**Comment by adrianschroeter** [comment]
On Freitag, 27. April 2018, 14:55:30 CEST wrote ggardet:
> No such option:
> ```osc build: no such option: --statistics```

osc does not know it indeed:

 https://github.com/openSUSE/osc/pull/412

> 
> 


-- 

Adrian Schroeter
email: adrian@suse.de

SUSE Linux GmbH, GF: Felix Imendörffer, Jane Smithard, Graham Norton, HRB 21284 (AG Nürnberg) 
 
Maxfeldstraße 5                         
90409 Nürnberg 
Germany

**Comment by mlschroe** [comment]
Try `osc --build-opt=--statistics`.

**Comment by lethliel** [comment]
was fixed in #412
