### ISSUE TITLE
unable to build using osc build Error: build ('/usr/bin/build') command not found 

### ISSUE THREAD

**Issue by hackertron** [openSUSE/osc#417]
Hello i am trying to build a package ( rclone ) for s390x. i have installed osc using zypper install osc . 

when i  execute osc build i get following error 
`Error: build ('/usr/bin/build') command not found
Install the build package from http://download.opensuse.org/repositories/openSUSE:/Tools/`

I did visisted the link and downloaded every RPM in that directory : http://download.opensuse.org/repositories/openSUSE:/Tools/SLE_12_SP3/s390x/

I am using s390x which is built on SLES12 SP3. I have also tried same thing on my OpenSUSE LEAP it works absolutely fine there .

**Comment by adrianschroeter** [comment]
the build package is in noarch/ directory.
