### ISSUE TITLE
Could we have colorized diff, please?

### ISSUE THREAD

**Issue by mcepl** [openSUSE/osc#420]
Something like parameter ``--color`` for ``git diff``, or at least an equivalent of running the output of ``osc diff`` through ``colordiff(1)`` filter.
![screenshot from 2018-05-21 14-41-11](https://user-images.githubusercontent.com/198999/40308023-15ba9850-5d05-11e8-97c7-0e7d0dff9505.png)

**Comment by mcepl** [comment]
Except it doesn't work any more. We should probably really bit the bullet and use Pygments or something of that sort.

**Comment by marcus-h** [comment]
On 2021-07-16 10:03:12 -0700, Matěj Cepl wrote:
> Except it doesn't work any more. We should probably really bit the bullet and use Pygments or something of that sort.
>
What about introducing a diff-cmd config option?

**Comment by mcepl** [comment]
I have for now this:
```diff
diff --git a/osc/core.py b/osc/core.py
index 6146508a..198ae970 100644
--- a/osc/core.py
+++ b/osc/core.py
@@ -25,6 +25,14 @@ import shlex
 import hashlib
 import platform
 
+# Poor man's colorama
+GREEN=b'\x1b[32m'
+RED=b'\x1b[31m'
+BLUE=b'\x1b[34m'
+RESET=b'\x1b[39m'
+
+COLORIZE = True
+
 
 try:
     import distro
@@ -4762,6 +4770,19 @@ def binary_file(fn):
     return binary(open(fn, 'rb').read(4096))
 
 
+# From the snippet on https://chezsoi.org/lucas/blog/colored-diff-output-with-python.html
+def color_diff(diff):
+    for line in diff:
+        if line.startswith(b'+'):
+            yield GREEN + line + RESET
+        elif line.startswith(b'-'):
+            yield RED + line + RESET
+        elif line.startswith(b'^'):
+            yield BLUE + line + RESET
+        else:
+            yield line
+
+
 def get_source_file_diff(dir, filename, rev, oldfilename = None, olddir = None, origfilename = None):
     """
     This methods diffs oldfilename against filename (so filename will
@@ -4827,7 +4848,11 @@ def get_source_file_diff(dir, filename, rev, oldfilename = None, olddir = None,
             d[i] += b'\n\\ No newline at end of file'
             if i+1 != len(d):
                 d[i] += b'\n'
-    return d
+
+    if COLORIZE:
+        return color_diff(d)
+    else:
+        return d
 
 def server_diff(apiurl,
                 old_project, old_package, old_revision,
```
Which somehow works, it doesn't any new dependencies, but it is obviously not finished.

  * [ ] ``COLORIZE`` is hard-coded constant, it should be an option (probably in the config file, or in both places)
  * [ ] it works for ``osc diff`` but not for ``osc sr -d`` for example
  * [ ] it works when it shouldn't (e.g., in the included diff in ``osc ci`` commit message editor)

Would anybody be able to finish it to the shippable state?

**Comment by avindra** [comment]
```sh
osc diff | colordiff | less
```

happily using `colordiff` and `less`
