### ISSUE TITLE
osc commit fails when uri get's to long (eg. commit message exceeds certain limit)

### ISSUE THREAD

**Issue by bgeuken** [openSUSE/osc#426]
I added some missing changelog entries and ran osc commit afterwards. Since all changes are added as proposed commit message I ended up with a long message.
After sending this failed.

I know it's an edgecase but I would expect osc to shorten the message or warn me.

```bash
> osc commit
Sending    obs-server.changes
Server returned an error: HTTP Error 414: Request-URI Too Long
```

**Comment by marcus-h** [comment]
On 2018-06-06 08:11:13 +0000, Björn Geuken wrote:
> I know it's an edgecase but I would expect osc to shorten the message or warn me.
> 
IMHO, this points out a general design "flaw": passing arbitrary data
via query parameters. Unfortunately, I've no idea atm how to fix it
without changing the api code as well. Even if we would adjust the api
code, we would end up with compat code in osc... :/

> `
> > osc commit
> Sending    obs-server.changes
> Server returned an error: HTTP Error 414: Request-URI Too Long
> `
> 
(Automatically) shortening the commit message is not an option, IMHO.

**Comment by bgeuken** [comment]
Could we tell users about this limitation or make this visible, eg. in the editor that pops up when calling osc commit?

**Comment by marcus-h** [comment]
On 2018-06-12 00:08:13 -0700, Björn Geuken wrote:
> Could we tell users about this limitation or make this visible, eg. in the editor that pops up when calling osc commit?
> 
Hmm the limit is server specific. If a 414 occurs during osc commit,
we could print a message that it might be due to a "too long" commit
message (but it could be also due to a combination of ridicuously
long project + package names + a long commit message...).

**Comment by dmach** [comment]
This doesn't seem to be a frequent issue, probably not something that requires a fix. Closing.
