### ISSUE TITLE
Dependencies missing in setup.py

### ISSUE THREAD

**Issue by crazyscientist** [openSUSE/osc#439]
Hey developers,

when attempting to install the osc package in a fresh virtualenv I noticed, that the `setup.py` does not define any dependencies?! How about adding the following:

- urlgrabber
- pycurl

**Comment by marcus-h** [comment]
On 2018-08-23 01:46:21 -0700, Andreas Hasenkopf wrote:
> when attempting to install the osc package in a fresh virtualenv I noticed, that the `setup.py` does not define any dependencies?! How about adding the following:
> 
> - urlgrabber
> - pycurl
> 
The urlgrabber dependency makes sense (however, we are currently
trying to get rid of urlgrabber (see [1])). osc does not depend
on "pycurl" (probably urlgrabber misses this dependency).


[1] https://github.com/openSUSE/osc/pull/410

**Comment by dmach** [comment]
I think this is no longer relevant because the latest osc doesn't depend on neither urlgrabber or pycurl. Closing.
