### ISSUE TITLE
mailaddr environment variable is not properly parsed anymore

### ISSUE THREAD

**Issue by lemmy04** [openSUSE/osc#440]
running osc 0.163.0 on openSUSE LEap 42.3.
I've been using the mailaddr environment variable to control the email address that "osc vc" would put in the .changes files successfully for ages, but since a few days (I'm guessing: update to 0.163), what I get now in my changes files when I set mailaddr is a line with my real name, and no mail address at all.

To reproduce:

```
export mailaddr=foo@bar.org
osc vc

```
expected outcome: a .changes file with a line with the date, time, and "foo@bar.org"
actual outcome: a .changes file with a line with the current date and time, and the realname of the user followed by <>

**Comment by marcus-h** [comment]
On 2018-08-23 23:06:05 -0700, Mathias Homann wrote:
> 
> ```
> export mailaddr=foo@bar.org
> osc vc
> 
> ```
> expected outcome: a .changes file with a line with the date, time, and "foo@bar.org"
> actual outcome: a .changes file with a line with the current date and time, and the realname of the user followed by <>
> 
As a workaround, you can set the VC_MAILADDR env variable. The
question is if we should fix this in osc or vc...

**Comment by lemmy04** [comment]
hm... that still prefixes the mail address with my realname from OBS or .oscrc, what if i do not what that in there at all, and only have the mail address from the variable?

**Comment by marcus-h** [comment]
On 2018-08-26 13:46:14 -0700, Mathias Homann wrote:
> hm... that still prefixes the mail address with my realname from OBS or .oscrc, what if i do not what that in there at all, and only have the mail address from the variable?
> 
That's not possible anymore (see [1]). If your realname should
not end up in the final rpm package, you can define the
%fullname_in_changelog macro in the project config.

[1] https://github.com/openSUSE/obs-build/pull/214

**Comment by lemmy04** [comment]
what do I put in there?

**Comment by marcus-h** [comment]
On 2018-08-26 15:09:39 -0700, Mathias Homann wrote:
> what do I put in there?
> 
Whatever you like - just its existence matters. For instance,

Macros:
%fullname_in_changelog %nil
:Macros

should do the trick.

**Comment by marcus-h** [comment]
On 2018-08-23 23:06:05 -0700, Mathias Homann wrote:
> ```
> export mailaddr=foo@bar.org
> osc vc
> 
> ```
This is now fixed with commit 3c5b27f ("Fall back to $mailaddr
if $VC_MAILADDR is unset/null") in obs-build.

**Comment by adrianschroeter** [comment]
On Mittwoch, 29. August 2018, 16:06:07 CEST wrote Marcus Hüwe:
> On 2018-08-23 23:06:05 -0700, Mathias Homann wrote:
> > ```
> > export mailaddr=foo@bar.org
> > osc vc
> > 
> > ```
> This is now fixed with commit 3c5b27f ("Fall back to $mailaddr
> if $VC_MAILADDR is unset/null") in obs-build.

also a new build package release is available in openSUSE:Tools already and Factory soon

-- 

Adrian Schroeter
email: adrian@suse.de

SUSE Linux GmbH, GF: Felix Imendörffer, Jane Smithard, Graham Norton, HRB 21284 (AG Nürnberg) 
 
Maxfeldstraße 5                         
90409 Nürnberg 
Germany

**Comment by lemmy04** [comment]
> On 2018-08-26 15:09:39 -0700, Mathias Homann wrote: what do I put in there?
> Whatever you like - just its existence matters. For instance, Macros: %fullname_in_changelog %nil :Macros should do the trick.

...does not work. Or i got the format wrong. https://build.opensuse.org/project/prjconf/home:lemmy04:snowglobe is my project where I need that., please have a look and suggest.

**Comment by marcus-h** [comment]
On 2018-09-15 00:17:49 -0700, Mathias Homann wrote:
> > On 2018-08-26 15:09:39 -0700, Mathias Homann wrote: what do I put in there?
> > Whatever you like - just its existence matters. For instance, Macros: %fullname_in_changelog %nil :Macros should do the trick.
> 
> ...does not work. Or i got the format wrong. https://build.opensuse.org/project/prjconf/home:lemmy04:snowglobe is my project where I need that., please have a look and suggest.
> 
Ah sorry, I got the macro definition wrong (you can use the
%fullname_in_changelog macro only to _enable_ the new feature
for sles builds). There is no way to disable it.
