### ISSUE TITLE
osc should error out if keyring is to be used, but python-keyring is not installed

### ISSUE THREAD

**Issue by johanneskastl** [openSUSE/osc#441]
Hi all,

openSUSE Tumbleweed
20180829

osc has been installed via `zypper in osc` from the openSUSE:Tools repository, but it is missing the packages needed to use my system's kwallet.

from .oscrc
>[general]
> use_keyring = 1
> [...]
> [https://api.opensuse.org]
> keyring=1
> 

This resulted in getting `401 Unauthorized` errors, until I installed `python2-keyring` and the following packages:

`python2-appdirs python2-asn1crypto python2-backports python2-cffi python2-configparser python2-cryptography python2-entrypoints python2-idna python2-keyring python2-packaging   python2-pyasn1 python2-pycparser python2-pyparsing python2-SecretStorage python2-setuptools python-enum34 python-ipaddress`

> # rpm -qa|grep osc
> osc-0.163.0-237.2.noarch
> # rpm -qa|grep keyring
> python3-keyring-13.2.1-1.1.noarch
> python2-keyring-13.2.1-1.1.noarch
> #

Not sure if those packages would have been suggested or recommended during installation of osc.

If you need further input, more details etc., please just reach out to me.

Kind Regards,
Johannes

**Comment by marcus-h** [comment]
On 2018-09-02 05:59:23 -0700, Johannes Kastl wrote:
> osc has been installed via `zypper in osc` from the openSUSE:Tools repository, but it is missing the packages needed to use my system's kwallet.
> 
> from .oscrc
> >[general]
> > use_keyring = 1
> > [...]
> > [https://api.opensuse.org]
> > keyring=1

There is no "keyring" config option (but that's unrelated).

> > 
> 
> This resulted in getting `401 Unauthorized` errors, until I installed `python2-keyring` and the following packages:
> 
> `python2-appdirs python2-asn1crypto python2-backports python2-cffi python2-configparser python2-cryptography python2-entrypoints python2-idna python2-keyring python2-packaging   python2-pyasn1 python2-pycparser python2-pyparsing python2-SecretStorage python2-setuptools python-enum34 python-ipaddress`
> 
> > # rpm -qa|grep osc
> > osc-0.163.0-237.2.noarch
> > # rpm -qa|grep keyring
> > python3-keyring-13.2.1-1.1.noarch
> > python2-keyring-13.2.1-1.1.noarch
> > kastl@laptop:/home/kastl>
> 
> Not sure if those packages would have been suggested or recommended during installation of osc.
> 
Hmm osc recommends python-keyring. Any chance that you used
"zypper in --no-recommends osc" or something like that?

Maybe osc should error out if "use_keyring" is enabled but no
python-keyring is available.

**Comment by johanneskastl** [comment]
Hi Marcus,

you are right, I did disable the installation of recommended packages. So it seems the dependencies of the RPM are correct.

I would really appreciate more feedback from osc and erroring out, if it is asked to get the password from keyring and cannot do so. Simply having a 401 error does not seem to be a good indicator of the real problem.

I changed the issue title accordingly.

**Comment by lethliel** [comment]
This is solved with the new password handling backend in https://github.com/openSUSE/osc/commit/e8d9fb52f6b18926ed20fb7712916e9e63070cba
