### ISSUE TITLE
Ubuntu 17.04, osc from AppImage ImportError: No module named site

### ISSUE THREAD

**Issue by ok2cqr** [openSUSE/osc#453]
Hi,

I just registered to build service, downloaded osc as AppImage, followed step by step instructions published here: 
https://openbuildservice.org/help/manuals/obs-beginners-guide/#sec.obsbg.uc.setuphome

but osc always returns ImportError: No module named site

Thanks for help!

Petr

**Comment by marcus-h** [comment]
On 2018-10-12 22:17:57 -0700, Petr Hlozek wrote:
> I just registered to build service, downloaded osc as AppImage, followed step by step instructions published here: 
> https://openbuildservice.org/help/manuals/obs-beginners-guide/#sec.obsbg.uc.setuphome
> 
> but osc always returns ImportError: No module named site
> 
I cannot say much about the appimage stuff, but can you post the
complete traceback?

**Comment by ok2cqr** [comment]
I'm sorry, I don't know what you mean. The error message I've sent is the only one error message I get when run the osc from appimage, nothing more. The error message is still the same even when trying to add any prameter to the osc.

**Comment by ok2cqr** [comment]
I'm sorry for the typo in the subject, I'm using Ubuntu 18.04, not 17.04.

**Comment by adrianschroeter** [comment]
should work now with latest version from openSUSE:Tools
