### ISSUE TITLE
setting cipherlist will prevent osc from using TLS 1.3

### ISSUE THREAD

**Issue by crrodriguez** [openSUSE/osc#455]
https://github.com/openSUSE/osc/blob/f12c7747d0697a718e20a698a1816a20e299d897/osc/oscssl.py#L169

This will break TLS 1.3 support, as that cipherlist only includes tls 1.2 or earlier ciphers, since openssl has been fixed long time ago not use or prefer insecure ciphers I suggest just removing this line and everything will work.

**Comment by dmach** [comment]
We have decided not to fix this in the current code base, because we'll be moving away from m2crypto in https://github.com/openSUSE/osc/pull/1000 shortly.
The new code doesn't explicitly set any ciphers, it only disables weaker crypto and relies on urllib3 defaults otherwise.
