### ISSUE TITLE
osc sr in project checkout drips over not source-linked packages

### ISSUE THREAD

**Issue by DimStar77** [openSUSE/osc#46]
Having a checkout of a project (e.g GNOME:Factory) and issuing
  osc sr
in there fails / aborts at the first occurence of a non-linked package:

osc/GNOME/Factory> osc sr
Submitting package  ModemManager
Submitting package  NetworkManager
Submitting package  NetworkManager-gnome
Package  NetworkManager-iodine  is not a source link and no target specified.
This is currently not supported.

**Comment by lethliel** [comment]
This sould also be solved with https://github.com/openSUSE/osc/commit/3da7b9b3d8d2f46ae0ce1d9f84bd8c1666335603 and the fix will be released with 0.166.0
