### ISSUE TITLE
osc sr --seperate-requests in prj checkout fails on packages without diff

### ISSUE THREAD

**Issue by DimStar77** [openSUSE/osc#47]
Trying to do osc sr --seperate-requests on a prj fails / aborts on first occurrence of a package without a diff against the parent:

osc/GNOME/Factory> osc sr --seperate-requests
Submitting package  ModemManager
Server returned an error: HTTP Error 400: Bad Request
The request contains no actions. Submit requests without source changes may have skipped!

**Comment by lethliel** [comment]
Finally this is solved in https://github.com/openSUSE/osc/commit/3da7b9b3d8d2f46ae0ce1d9f84bd8c1666335603 and will be released with 0.166.0
