### ISSUE TITLE
osc build with buildtime service keeps running even if outside service fails

### ISSUE THREAD

**Issue by darix** [openSUSE/osc#478]
found while obs_scm was broken ...

the outside service that should create the obscpio file failed ... but osc started the build anyway, and then the part inside the build env complained about the missing cpio file.

expected would be that OSC stops after the outside part failed.

**Comment by marcus-h** [comment]
(Ah I just saw that it was already assigned to @lethliel - sorry
for intefering (it would be nice if github would send a notification... ;) ))

**Comment by dmach** [comment]
This is a really dated issue and we don't have a clear reproducer. Closing.
