### ISSUE TITLE
feature: osc rq list prj --incoming

### ISSUE THREAD

**Issue by DimStar77** [openSUSE/osc#48]
A feature that could be helpful would be an extension to osc rq list, showing only 'incoming' requests.

Example:
osc rq list GNOME:Factory --incoming
would show me only SRs with GNOME:Factory as target.

Currently, one can work around this missing feature by 'excluding known targets' (--exclude-target-project openSUSE:Factory).

Would just be a small 'help' in daily review jobs.

**Comment by lethliel** [comment]
This is kind of old. But the function would be nice nevertheless.

**Comment by lethliel** [comment]
implemented in git master. Will be part of 0.166.0
