### ISSUE TITLE
osc deleterequest $project should refuse to send deleterequest for nonempty projects

### ISSUE THREAD

**Issue by dirkmueller** [openSUSE/osc#508]
osc rdelete is refusing to delete nonempty products, however osc deleterequest happy does so (even without --recursive/--all/--force) given. Given how easy it is to accidentally create a deleterequest against a project rather than a package inside the project, we should be a bit more cautious here and reject it similarly to rdelete.

**Comment by lethliel** [comment]
fixed in https://github.com/openSUSE/osc/pull/509
