### ISSUE TITLE
osc build with a kiwi image leaves the buildroot in an inconsistent state

### ISSUE THREAD

**Issue by dcermak** [openSUSE/osc#511]
I am building kiwi images for various openSUSE distribution versions and often switch between e.g. Leap 15 and Leap 42.3. Running `osc build` consistently fails the first time after I switch to a different distro version. This typically manifests with outputs like this:
```
[   10s] rpm: error while loading shared libraries: liblua.so.5.1: cannot open shared object file: No such file or directory
[   10s] deleting libmpfr4
[   10s] rpm: error while loading shared libraries: liblua.so.5.1: cannot open shared object file: No such file or directory
[   10s] deleting libncurses5
[   10s] rpm: error while loading shared libraries: liblua.so.5.1: cannot open shared object file: No such file or directory
[   10s] deleting libnettle4
[   10s] rpm: error while loading shared libraries: liblua.so.5.1: cannot open shared object file: No such file or directory
[   10s] deleting libogg0
[   10s] rpm: error while loading shared libraries: liblua.so.5.1: cannot open shared object file: No such file or directory
[   10s] deleting libopenssl1_0_0
[   10s] rpm: error while loading shared libraries: liblua.so.5.1: cannot open shared object file: No such file or directory
[   10s] deleting libpango-1_0-0
[   10s] rpm: error while loading shared libraries: liblua.so.5.1: cannot open shared object file: No such file or directory
[   10s] deleting libpciaccess0
[   10s] rpm: error while loading shared libraries: liblua.so.5.1: cannot open shared object file: No such file or directory
[   10s] deleting libpixman-1-0
```
(and the same 20 times again)

For completeness: I am performing builds in a kvm VM.

A very simple workaround is to `rm -rf ` the buildroot before running `osc build`. Maybe this should be the default?

**Comment by marcus-h** [comment]
On 2019-02-06 13:27:18 +0000, Dan Čermák wrote:
> I am building kiwi images for various openSUSE distribution versions and often switch between e.g. Leap 15 and Leap 42.3. Running `osc build` consistently fails the first time after I switch to a different distro version. This typically manifests with outputs like this:
> ```
> [   10s] rpm: error while loading shared libraries: liblua.so.5.1: cannot open shared object file: No such file or directory
> [   10s] deleting libmpfr4
> [   10s] rpm: error while loading shared libraries: liblua.so.5.1: cannot open shared object file: No such file or directory
> [   10s] deleting libncurses5
> [   10s] rpm: error while loading shared libraries: liblua.so.5.1: cannot open shared object file: No such file or directory
> [   10s] deleting libnettle4
> [   10s] rpm: error while loading shared libraries: liblua.so.5.1: cannot open shared object file: No such file or directory
> [   10s] deleting libogg0
> [   10s] rpm: error while loading shared libraries: liblua.so.5.1: cannot open shared object file: No such file or directory
> [   10s] deleting libopenssl1_0_0
> [   10s] rpm: error while loading shared libraries: liblua.so.5.1: cannot open shared object file: No such file or directory
> [   10s] deleting libpango-1_0-0
> [   10s] rpm: error while loading shared libraries: liblua.so.5.1: cannot open shared object file: No such file or directory
> [   10s] deleting libpciaccess0
> [   10s] rpm: error while loading shared libraries: liblua.so.5.1: cannot open shared object file: No such file or directory
> [   10s] deleting libpixman-1-0
> ```
> (and the same 20 times again)
> 
> For completeness: I am performing builds in a kvm VM.
> 
Are you sure that you are doing a vm build? (Or are you just doing a
"osc build ..." in a kvm VM?)

> A very simple workaround is to `rm -rf ` the buildroot before running `osc build`.
> 
osc build --clean ...
How is your build root configured? (osc config general build-root)
You can use different build roots per project/package/repo/arch
For instance,
osc config general build-root \
    /var/tmp/build-root/%(project)s-%(package)s-%(repo)s-%(arch)s

> Maybe this should be the default?

Hmm this does not sound like a good default to me:)
Maybe we could introduce a config option for this...

**Comment by dcermak** [comment]
Marcus Hüwe <notifications@github.com> writes:

> On 2019-02-06 13:27:18 +0000, Dan Čermák wrote:
>> I am building kiwi images for various openSUSE distribution versions and often switch between e.g. Leap 15 and Leap 42.3. Running `osc build` consistently fails the first time after I switch to a different distro version. This typically manifests with outputs like this:
>> ```
>> [   10s] rpm: error while loading shared libraries: liblua.so.5.1: cannot open shared object file: No such file or directory
>> [   10s] deleting libmpfr4
>> [   10s] rpm: error while loading shared libraries: liblua.so.5.1: cannot open shared object file: No such file or directory
>> [   10s] deleting libncurses5
>> [   10s] rpm: error while loading shared libraries: liblua.so.5.1: cannot open shared object file: No such file or directory
>> [   10s] deleting libnettle4
>> [   10s] rpm: error while loading shared libraries: liblua.so.5.1: cannot open shared object file: No such file or directory
>> [   10s] deleting libogg0
>> [   10s] rpm: error while loading shared libraries: liblua.so.5.1: cannot open shared object file: No such file or directory
>> [   10s] deleting libopenssl1_0_0
>> [   10s] rpm: error while loading shared libraries: liblua.so.5.1: cannot open shared object file: No such file or directory
>> [   10s] deleting libpango-1_0-0
>> [   10s] rpm: error while loading shared libraries: liblua.so.5.1: cannot open shared object file: No such file or directory
>> [   10s] deleting libpciaccess0
>> [   10s] rpm: error while loading shared libraries: liblua.so.5.1: cannot open shared object file: No such file or directory
>> [   10s] deleting libpixman-1-0
>> ```
>> (and the same 20 times again)
>> 
>> For completeness: I am performing builds in a kvm VM.
>> 
> Are you sure that you are doing a vm build? (Or are you just doing a
> "osc build ..." in a kvm VM?)

I have configured osc to build in a kvm, i.e. `build-type = kvm` in .oscrc

>
>> A very simple workaround is to `rm -rf ` the buildroot before running `osc build`.
>> 
> osc build --clean ...
> How is your build root configured? (osc config general build-root)

$ osc config general build-root
'general': 'build-root' is set to '/var/tmp/build-root/%(repo)s-%(arch)s'

> You can use different build roots per project/package/repo/arch
> For instance,
> osc config general build-root \
>     /var/tmp/build-root/%(project)s-%(package)s-%(repo)s-%(arch)s

That would solve the issue, but my drive is not large enough for this,
each kiwi build root takes up well over 10 GB.

**Comment by dmach** [comment]
This happened to me even with normal rpm builds.
Wiping the build root is probably the right thing to do.
Fixing this properly would lead to consuming much more disk space as stated in an earlier comment.
