### ISSUE TITLE
osc diff -r... file is not limited to that file

### ISSUE THREAD

**Issue by AdamMajer** [openSUSE/osc#515]
I would like to diff only one file in between revisions, not the entire revision's all files.

How to Reproduce
----------------

osc co server:proxy squid
cd server:proxy/squid
osc diff -r177:178 squid.changes

The .spec file changes are also listed

**Comment by AdamMajer** [comment]
Previously reported against OBS, but looks like it's a client issue - https://github.com/openSUSE/open-build-service/issues/6996

**Comment by StayPirate** [comment]
that would be a very useful feature
