### ISSUE TITLE
osc package tracking moves files into old project

### ISSUE THREAD

**Issue by coogor** [openSUSE/osc#53]
Problem...I have a project home:DocB:python_packages which I wanted to branch (completely) into home:DocB:Tryton:3.0. Ideally in one step (see http://forums.opensuse.org/english/other-forums/development/open-build-service-obs/491382-osc-copy-all-packages-one-project-another-project.html )

As this did not work, and I detected the package tracking functionality http://en.opensuse.org/openSUSE:OSC#Package_tracking
I created a local copy accordingly.

As the attempt with 
osc add home:DocB:python_packages
did not work out, I copied the local files from the source to the target directory.

Made changes to one package, added the changed files to the version control, and checked in:
docb@T520:~/home:DocB:Tryton:3.0/trytond> osc ar
A    trytond.changes
docb@T520:~/home:DocB:Tryton:3.0/trytond> osc ci
Sending    trytond.spec
Sending    trytond.changes
Transmitting file data ..
Committed revision 50.
Waiting for server side source service run
...
At revision 50.

As a result, the files were changed in  home:DocB:python_packages/trytond/ instead of /home:DocB:Tryton:3.0/trytond/.

Tried detaching:
docb@T520:~/home:DocB:Tryton:3.0> osc detachbranch
Error: '/home/docb/home:DocB:Tryton:3.0' is not an osc package working copy

..whats wrong? Is there a way to clone a whole project?

**Comment by dmach** [comment]
I'm not sure if there's still something to be done after long 9 years...

> Is there a way to clone a whole project?

`$ osc co <project>` works out of the box so does the package tracking feature mentioned above.

If you believe there's still something to be fixed, please open a new issue and provide a new, fresh reproducer.
