### ISSUE TITLE
Not able to delete password after initial keyring setup.

### ISSUE THREAD

**Issue by SchoolGuy** [openSUSE/osc#535]
I setup up the keyring usage when using osc for the first time. Since my credentials have changed I thought I was able to delete the entry in my KWallet.

When looking into the KWallet I was not able to see the entry. Neither was the case with the root KWallet. I also attempted to reinstall the `python-keyring` but that didn't help. Seahorse is not installed and never was. I am running a Leap 15.0 and have KDE as the Desktop Environment of Choice. The osc version is `0.165.git`

Using the osc command with a plaintext password works. So the client is able to authenticate against the api when using the correct credentials.

**Comment by SchoolGuy** [comment]
So a solution for this is to manually install `python3-keyring` and then to look if there is an entry for `keyring get api.opensuse.org <USERNAME>` if there is you can use `keyring set api.opensuse.org <USERNAME>` to set your password.

**Comment by lethliel** [comment]
This is solved in https://github.com/openSUSE/osc/commit/e8d9fb52f6b18926ed20fb7712916e9e63070cba 

A password change will be possible using `osc conig <apiurl> --change-password`
