### ISSUE TITLE
request: make osc branch|detachbranch|copypac work on project level

### ISSUE THREAD

**Issue by coogor** [openSUSE/osc#54]
I have a project with some 30+ packages in it.
Now I want to create a branch for a new major release for that project, while keeping the original project, as this release is still maintained.
Unfortunately I have to call 'osc branch' for each package...which is a PITA.

Please make osc branch|detachbranch|copypac work on project-level as well.
Thanks

**Comment by lethliel** [comment]
This will not work as branching is always on package level.
