### ISSUE TITLE
[py3] select/unselect cmd fails to update status comments

### ISSUE THREAD

**Issue by nilxam** [openSUSE/osc#544]
Since osc moved to python3, I got a type error below when runs `staging select`, I guess having the same issue for `staging unselect`.

<pre>
Traceback (most recent call last):
  File "/usr/bin/osc", line 41, in <module>
    r = babysitter.run(osccli)
  File "/usr/lib/python3.6/site-packages/osc/babysitter.py", line 61, in run
    return prg.main(argv)
  File "/usr/lib/python3.6/site-packages/osc/cmdln.py", line 344, in main
    return self.cmd(args)
  File "/usr/lib/python3.6/site-packages/osc/cmdln.py", line 367, in cmd
    retval = self.onecmd(argv)
  File "/usr/lib/python3.6/site-packages/osc/cmdln.py", line 501, in onecmd
    return self._dispatch_cmd(handler, argv)
  File "/usr/lib/python3.6/site-packages/osc/cmdln.py", line 1232, in _dispatch_cmd
    return handler(argv[0], opts, *args)
  File "/home/maxlin_factory/.osc-plugins/osc-staging.py", line 668, in do_staging
    filter_from, opts.no_freeze)
  File "/home/maxlin_factory/.osc-plugins/osclib/select_command.py", line 143, in perform
    self.api.update_status_or_deactivate(self.target_project, 'select')
  File "/home/maxlin_factory/.osc-plugins/osclib/stagingapi.py", line 1472, in update_status_or_deactivate
    self.update_status_comments(project, command)
  File "/home/maxlin_factory/.osc-plugins/osclib/stagingapi.py", line 1541, in update_status_comments
    meta['requests_comment'] = self.get_prj_meta_revision(project)
  File "/home/maxlin_factory/.osc-plugins/osclib/stagingapi.py", line 692, in get_prj_meta_revision
    log = get_commitlog(self.apiurl, project, '_project', None, format='xml', meta=True)
  File "/usr/lib/python3.6/site-packages/osc/core.py", line 6340, in get_commitlog
    comment.replace('&', '&amp;').replace('<', '&gt;').replace('>', '&lt;'))
TypeError: a bytes-like object is required, not 'str'
</pre>

**Comment by coolo** [comment]
get_commitlog is buggy and mixes bytes and strings in case of `b'<no message/>'`

**Comment by coolo** [comment]
this is quite a blocker for using 0.165

**Comment by jberry-suse** [comment]
blocks openSUSE/openSUSE-release-tools#1758

**Comment by lethliel** [comment]
Will fix this when i am back from vacation (Wednesday)

**Comment by coolo** [comment]
would be awesome if it doesn't take a week

**Comment by lethliel** [comment]
@coolo: This is fixed in commit https://github.com/openSUSE/osc/pull/550/commits/03777b7e4d43521089e5fcc6d8a8315b9b758ded

Sorry for the delay. I had an appointment in the eye clinic last week also.

**Comment by lethliel** [comment]
> More or less the same error occurs when running `osc add $directory` in a project:
> 
> ```
> $ osc add root
> root is a directory, do you want to archive it for submission? (y/n) y
> Traceback (most recent call last):
>   File "/usr/bin/osc", line 41, in <module>
>     r = babysitter.run(osccli)
>   File "/usr/lib/python3.7/site-packages/osc/babysitter.py", line 61, in run
>     return prg.main(argv)
>   File "/usr/lib/python3.7/site-packages/osc/cmdln.py", line 344, in main
>     return self.cmd(args)
>   File "/usr/lib/python3.7/site-packages/osc/cmdln.py", line 367, in cmd
>     retval = self.onecmd(argv)
>   File "/usr/lib/python3.7/site-packages/osc/cmdln.py", line 501, in onecmd
>     return self._dispatch_cmd(handler, argv)
>   File "/usr/lib/python3.7/site-packages/osc/cmdln.py", line 1232, in _dispatch_cmd
>     return handler(argv[0], opts, *args)
>   File "/usr/lib/python3.7/site-packages/osc/commandline.py", line 4588, in do_add
>     addFiles([arg])
>   File "/usr/lib/python3.7/site-packages/osc/core.py", line 7148, in addFiles
>     cpio_proc.communicate('\0'.join(todo))
>   File "/usr/lib64/python3.7/subprocess.py", line 924, in communicate
>     self._stdin_write(input)
>   File "/usr/lib64/python3.7/subprocess.py", line 873, in _stdin_write
>     self.stdin.write(input)
> TypeError: a bytes-like object is required, not 'str'
> 1 block
> ```

This is handled in https://github.com/openSUSE/osc/issues/543
