### ISSUE TITLE
multibuild misses dependencies

### ISSUE THREAD

**Issue by bmwiedemann** [openSUSE/osc#547]
Reproducer:
```bash
osc co openSUSE:Factory/pg_cron && cd $_
osc build --noservice --clean -M postgresql95 --local-package
osc build --noservice --clean -M postgresql95 --alternative-project $PRJ
```

Such a build misses the `postgresql95-server-devel` dependency and thus the build fails with
`make: pg_config: Command not found`

A workaround is to patch the spec file to work without -M

other affected packages might be imb, kicad-doc, mvapich2 and tensorflow

**Comment by bmwiedemann** [comment]
I captured debug output from
```bash
osc -d build --noservice --clean -M openmpi --local-package > /tmp/osc.debug.bad 2>&1
osc -d build --noservice --clean -M openmpi > /tmp/osc.debug.good 2>&1
```

and the only diff in API calls was
```diff
-POST https://api.opensuse.org/build/openSUSE:Factory/standard/x86_64/_repository/_buildinfo
+POST https://api.opensuse.org/build/openSUSE:Factory/standard/x86_64/imb:openmpi/_buildinfo
```

**Comment by dmach** [comment]
@bmwiedemann is it still reproducible?

**Comment by bmwiedemann** [comment]
No.
I think, this has been solved a while ago, so I am using local multibuilds with --alternative-project now.
