### ISSUE TITLE
Flag name inconsistency --noservice for build and commit

### ISSUE THREAD

**Issue by msirringhaus** [openSUSE/osc#548]
I just noticed that `osc build` has the option-alternatives `--no-service` and `--noservice`, while `osc commit` only knows `--noservice`.
Would it not be more consistent if `--no-service` would also work for `osc commit`?

**Comment by dmach** [comment]
You're right that they should behave consistently.
I've extended this also to `--skip-local-service-run` command-line option and `local_service_run` config option.
