### ISSUE TITLE
update of project - osc hangs after 2nd change

### ISSUE THREAD

**Issue by coogor** [openSUSE/osc#55]
I've done some mass changes to many packages within a project, and want to check it in all in one run. Latest at the 2nd change osc hangs with 'Transmitting file data ':

docb@T520:~/home:DocB:Tryton:3.0> osc ci
nothing to do for package trytond
nothing to do for package tryton
nothing to do for package neso
nothing to do for package trytond_country
nothing to do for package trytond_crm_activities
Sending    trytond_currency/trytond_currency.spec
Transmitting file data .
Committed revision 2.
Waiting for server side source service run
....
At revision 2.
Sending    trytond_party/trytond_party.spec
Transmitting file data .

only CRTL-C helps, and restart of the check in.

osc is osc-0.139.1-1.1.1.noarch

**Comment by lethliel** [comment]
This is 6 years old now. I can not reproduce this. Please re-open if this is still an issue.

**Comment by sriemer** [comment]
I just hit this issue today actually on Leap 15.2 with `osc-0.170.0-lp152.2.3.1`. This is still an issue.

**Workaround**: Kill the hanging osc and retry. Then it usually works. Definitely timing related.

Will try to gather a `tcpdump` next time this happens and will reopen if I have more information.
