### ISSUE TITLE
osc meta -e pkg <name> returns bytes as output

### ISSUE THREAD

**Issue by lethliel** [openSUSE/osc#569]
When running into an error using osc meta the return text is bytes: 

```
Try again? ([y/N]): y
Sending meta data...
BuildService API error: validation_failed (400)
b'package validation error: 4:0: ERROR: Element package has extra content: disable'
```

**Comment by marcus-h** [comment]
On 2019-05-28 04:59:36 -0700, Marco Strigl wrote:
> When running into an error using osc meta the return text is bytes:
>
> ```
> Try again? ([y/N]): y
> Sending meta data...
> BuildService API error: validation_failed (400)
> b'package validation error: 4:0: ERROR: Element package has extra content: disable'
> ```
>
Fixed via PR#571 ("Properly parse error message in metafile.edit").
