### ISSUE TITLE
osc build --local-package does not work with master

### ISSUE THREAD

**Issue by Conan-Kudo** [openSUSE/osc#572]
With 0.165.1 and master, when I try to use `osc build --alternative-project=home:Pharaoh_Atem CentOS_7 x86_64 --no-verify --local-package`, it does not work.

I get messages like the following:
```
Error: "/home/ngompa/Sources/package-backports/bcc" is not an osc package working copy.
```

With 0.164.2, this worked. My guess is that https://github.com/openSUSE/osc/commit/c39c3b8cae826723c23e5115e5c051438d7aa8ba broke it, but I'm not sure.

**Comment by dmach** [comment]
I tried to reproduce using the following steps:
```
$ osc co openSUSE:Factory bcc
$ rm -rf openSUSE:Factory/.osc
$ rm -rf openSUSE:Factory/bcc/.osc
$ cd openSUSE:Factory/bcc
$ osc build --alternative-project=openSUSE:Factory standard x86_64 --no-verify --local-package
```
And it works just fine.
Closing, let me know if it's still broken for you.
