### ISSUE TITLE
osc linkpac copies 'locked' state from source package

### ISSUE THREAD

**Issue by susematz** [openSUSE/osc#574]
I just tried to linkpac a package from SUSE:Maintenance to a home project of mine so
that I can test building with my own updates to other packages.  The linkpac creates the
target package in a locked state (copied from the SUSE:Maintenance package meta).
That means it couldn't even create the _link file, i.e. the linkpac itself already failed.

It did create the target container already, though (empty). Just that, because it's locked I can't
even remove it anymore.  The webapp doesn't even allow me to change the Meta info to remove
the locked state.  Until I learned about 'osc unlock' I was at a loss how to remove or do anything
else with this container.

I would say that linkpacing something into my own projects (where I must be able to write to
for the linkpac to succeed at all), should not copy the locked state; it just doesn't make much
sense to me; especially if it causes the linkpac itself to not even succeed.

**Comment by adrianschroeter** [comment]
On Montag, 3. Juni 2019, 17:18:07 CEST susematz wrote:
> I just tried to linkpac a package from SUSE:Maintenance to a home project of
> mine so that I can test building with my own updates to other packages. 
> The linkpac creates the target package in a locked state (copied from the
> SUSE:Maintenance package meta). That means it couldn't even create the
> _link file, i.e. the linkpac itself already failed.
> 
> It did create the target container already, though (empty). Just that,
> because it's locked I can't even remove it anymore.  The webapp doesn't
> even allow me to change the Meta info to remove the locked state.  Until I
> learned about 'osc unlock' I was at a loss how to remove or do anything
> else with this container.
> 
> I would say that linkpacing something into my own projects (where I must be
> able to write to for the linkpac to succeed at all), should not copy the
> locked state; it just doesn't make much sense to me; especially if it
> causes the linkpac itself to not even succeed.

yes, it shouldn't be copied .... on the other hand, "osc linkpac" should not
be used anymore these days (at least in 99,9% of the cases you want "osc 
branch")

-- 

Adrian Schroeter
SUSE Linux Products GmbH,  Maxfeldstr. 5, 90409 Nuernberg, Germany
email: adrian@suse.de

**Comment by susematz** [comment]
Maybe, if branch doesn't exhibit the same behaviour (does it?) that's good already.  But there are a couple cases
where linkpac is exactly right.  In the case above for instance, or if I'm adding a new .spec file and
want the build service to start picking it up and building it (because the links for other .spec files are only created automatically when completely creating a new package container, not when adding a new .spec
file).  The branch is even wrong, as those links shouldn't be to a specific version, but really follow it,
and also never should have additional patches than the base container.

**Comment by adrianschroeter** [comment]
On Montag, 3. Juni 2019, 17:34:55 CEST susematz wrote:
> Maybe, if branch doesn't exhibit the same behaviour (does it?) that's good
> already.  But there are a couple cases where linkpac is exactly right.  In
> the case above for instance, or if I'm adding a new .spec file

we propose to use _multibuild there these days ... this avoids any manual 
setup steps like linkpac

> and want the
> build service to start picking it up and building it (because the links for
> other .spec files are only created automatically when completely creating a
> new package container, not when adding a new .spec file).  The branch is
> even wrong, as those links shouldn't be to a specific version, but really
> follow it, and also never should have additional patches than the base
> container.

the branch is also following, it even helps you to merge conflicts better


-- 

Adrian Schroeter
SUSE Linux Products GmbH,  Maxfeldstr. 5, 90409 Nuernberg, Germany
email: adrian@suse.de

**Comment by susematz** [comment]
AFAIK _multibuild still has problems when trying to build only a subset of the packages in a staging project?  In any case, I'm not trying to argue for or against linkpac, but I do argue for it being fixed,
no matter if there are alternatives.
