### ISSUE TITLE
Provide a command to see failing packages in a project

### ISSUE THREAD

**Issue by ismail** [openSUSE/osc#581]
Currently, what I do is:

```
osc results --xml openSUSE:Backports:SLE-15-SP1 | xpath -q -e "//status[@code='failed']/@package" 
```

There should be an osc command for this, probably with a selection option for the architechture and repository.

**Comment by mlschroe** [comment]
It should support a `-f` option, like with `osc rebuild`.

(Actually a --code=XXX option would also be nice)

**Comment by lethliel** [comment]
@ismail: There is already a arch/repo selector 

`--repo / --arch`

@mlschroe: That was what I am thinking about. `--code` for "random" code like scheduled and additionally the `-f` for the failed packages.

**Comment by lethliel** [comment]
I am working on this atm.
