### ISSUE TITLE
[help] osc dependson is not the same as osc whatdependson

### ISSUE THREAD

**Issue by mcepl** [openSUSE/osc#582]
``osc whatdependson`` is a very useful command to find out how relevant the package is and whether it couldn't be removed. Unfortunately, even after studying ``osc help`` I haven't found that it exists, because it is enlisted only as an alias of ``osc dependson``, which it isn't, these are exact opposites of each other. Please fix ``osc help``.

**Comment by lethliel** [comment]
You are right. The help needs to improved here. Although whatdependson calls the same function only with a reserve flag there needs to be an own help text in osc help.
