### ISSUE TITLE
Bad decoding of server_diff output

### ISSUE THREAD

**Issue by andreas-schwab** [openSUSE/osc#589]
osc rq show -d 711052 contains mojibake.

**Comment by lethliel** [comment]
This is related to https://github.com/openSUSE/osc/issues/540 and discussed in https://github.com/openSUSE/osc/pull/554

**Comment by lethliel** [comment]
fixed with https://github.com/openSUSE/osc/commit/2b47be6b1e1eeb17957aba1f45c1af4433b6bdec
