### ISSUE TITLE
rebase from the remote project

### ISSUE THREAD

**Issue by mcepl** [openSUSE/osc#594]
The scenario is this:

I have a development project (let’s say https://build.opensuse.org/package/show/devel:languages:python:Factory/python3, hereinafter devel project) and I branch it into my home project (https://build.opensuse.org/package/show/home:mcepl:work/python3, hereinafter home project). Now, there is a long couple of months process when Python 3.8 goes through alpha versions. I don't want to push this build even into devel project until it is out of alphas and it is at least beta1. Meanwhile, CVEs happen and devel project gets some additional patches.
When Python 3.8 finally turns beta, I would like to push my home project into devel project (and start testing other Python packages on it). However, if just push my home project into devel project, I remove all those patches I have meantime pushed there. I would need a command (e.g., ``osc rebase``) to rebase home project to be sitting on the top of the current devel project.

Is there a way how to do it?

**Comment by Vogtinator** [comment]
Branched packages are automatically rebased (unless explicitly disabled by the "stay on current revision" option). To resolve any conflicts you need to run `osc pull`.

**Comment by mcepl** [comment]
It certainly didn't work that way for me. I have never checked any option like "stay on current revision" and yet push from my home project to devel project suggested removal of those patches.

**Comment by mcepl** [comment]
This is probably PEBKAC. Let's close it for now.
