### ISSUE TITLE
Better error message on failing submitrequest for mutliple packages

### ISSUE THREAD

**Issue by jonsger** [openSUSE/osc#605]
I wanted to make a single SR for some 20 packages, but it failed and I didn't noticed why.

```
home:jbrielmaier:branches:X11:MATE:Factory> osc submitrequest X11:MATE:Factory -m "Update MATE to 1.23"
Submitting package  atril
[...]
Submitting package  python-caja
The request contains no actions. Submit requests without source changes may have skipped!
```

The actual problem was that I didn't check in the changes in the `mate-applets` package, so in this package there was no source change.

It would be nice to have a error message leading you to the actual problem like
```
The request contains no actions. The following packages didn't contain a source change:
* mate-applets
Submit request may have skipped!
```

~Jonathan

**Comment by lethliel** [comment]
as discussed in IRC we will have a look at this together tomorrow

**Comment by adrianschroeter** [comment]
this is an api side message in first place

**Comment by adrianschroeter** [comment]
but the message should only come when in _no_ package is no change. It should proceed if in at least one package is a change. The other packages will just not be part of the request action list.

**Comment by lethliel** [comment]
@adrianschroeter 

The api returns a 400 Bad Request error and no sr is created. 
I will open an issue for the API.

**Comment by lethliel** [comment]
This is solved in https://github.com/openSUSE/osc/pull/618/commits/3da7b9b3d8d2f46ae0ce1d9f84bd8c1666335603
