### ISSUE TITLE
osc build does not produce a re-usable package cache

### ISSUE THREAD

**Issue by m-grant-prg** [openSUSE/osc#613]
I have been using OBS and osc for some time at a basic user level. I
build projects locally using osc before committing to OBS. All works
fine for Leap 15.0 and 15.1, Fedora 29 & 30 and Debian_9.0.

I have just started building for Debian_10, all I did was
osc build --ccache Debian_10
and whilst the projects build successfully with osc, each time I build
I get the message:- 100.0% cache miss. 0/180 dependencies cached. and
all packages are downloaded again. On inspection in the Debian_10
package cache directory the filenames are odd, they all have b'
prepended and inserted. For example:- b'adduser'_b'3.118'_b'all'.deb As
opposed to the same package in the Debian_9.0 directory of:-
adduser_3.115_all.deb

I have now experimented by deleting the working Debian_9.0 package
cache and re-building the project and the same thing happens, project
builds OK but all the package names are now corrupted. 

The package cache directory has correct ownership.

osc --version is 0.165.1

Distribution is Leap 15.1

I posted this on the openSUSE OBS mailing list where I received the suggestion that it may be a python3 bug and to report it here.

Regards,
Mark Grant

**Comment by jonsger** [comment]
Which package or in which project are you building with `osc build --ccache Debian_10`?

**Comment by marcus-h** [comment]
On 2019-07-25 03:41:34 -0700, jonsger wrote:
> Which package or in which project are you building with `osc build --ccache Debian_10`?
>
This does not depend on the project or package. It is a bug in
osc.util.debquery.DebQuery.filename (it should return a bytes
instead of a str...).

**Comment by lethliel** [comment]
Yes. I am already working on the fix.
