### ISSUE TITLE
`osc --changesauthor ...` option does not exist (?)

### ISSUE THREAD

**Issue by ghost** [openSUSE/osc#619]
While trying to update an obscpio file using a service, osc had this output:

```
$ osc service disabledrun
[...]
No changesauthor defined!
You can define it by:
 * configure 'email=' in ~/.config/osc/oscrc in your default api section
 * configure <param name="changesauthor">...</param> in your _service file
 * using '--changesauthor' on the cli
```

Herr co-worker and I tried all three options, and only the second one really worked for us. Otherwise:

* `email=` in `~/.oscrc` was not recognized (I know, the config file should apparently be moved to the new path but `~/.oscrc` appears to still be recognized for other purposes

* `--changesauthor` is apparently not a recognized osc option. We tried it both as an option to the `service` subcommand and as an option to the main `osc` command, neither worked.

In addition, I don't even know why osc is asking for an e-mail in this case -- doesn't it usually know one's e-mail address from the user account?

**Comment by marcus-h** [comment]
On 2019-08-05 06:30:33 -0700, Stefan Knorr wrote:
> While trying to update an obscpio file using a service, osc had this output:
>
> ```
> $ osc service disabledrun
> [...]
> No changesauthor defined!
> You can define it by:
>  * configure 'email=' in ~/.config/osc/oscrc in your default api section
>  * configure <param name="changesauthor">...</param> in your _service file
>  * using '--changesauthor' on the cli
> ```
>
> Herr co-worker and I tried all three options, and only the second one really worked for us. Otherwise:
>
> * `email=` in `~/.oscrc` was not recognized (I know, the config file should apparently be moved to the new path but `~/.oscrc` appears to still be recognized for other purposes
>
Which osc version are you using? What's the output of
"osc config <apiurl> email"?

> * `--changesauthor` is apparently not a recognized osc option, we tried it both as an option to the `service` subcommand and as an option to the main `osc` command.
>
The --changesauthor option refers to the tar_scm script (it is not an
osc option).

**Comment by dmpop** [comment]
When I run `osc config https://api.suse.de email` I get this:

    'https://api.suse.de': 'email' is set to 'xxxx@xxxx.com'

where _xxxx@xxxx.com_ is my correct email address.

**Comment by sknorr** [comment]
> The --changesauthor option refers to the tar_scm script (it is not an
osc option).

Oh! That makes some sense. However, it is really unfortunate that this is just shown among the messages from `osc` itself then. Is there some way this could be made clearer?

**Comment by dmach** [comment]
I couldn't come up with a proper fix that would completely eliminate the confusion,
so I ended up printing running services.
At least the errors no longer seem to be popping up from nowhere.
