### ISSUE TITLE
UTF-8 wrongly displayed

### ISSUE THREAD

**Issue by jengelh** [openSUSE/osc#633]
osc-0.165.4 (Tumbleweed)

`osc rq show -d` displays UTF-8 sequences wrongly. (Maybe related to https://github.com/openSUSE/open-build-service/issues/8349 , but the mojibake is different).

Observed:
```
» osc rq show -d 730703 | grep --text 10204
-            i.e. decode "������\x{10204}"
+            i.e. decode "�� ����\x{10204}"
```
Expected:
```
» osc rdiff -r49:50 devel:languages:perl/perl-Cpanel-JSON-XS | grep --text 10204
-            i.e. decode "��\x{10204}"
+            i.e. decode "í í°\x{10204}"
```

**Comment by lethliel** [comment]
I think this is more an issue in tempfile.NamedTemporaryFile().write(). 

because before we give the bytes-like object to the write method it looks like this:
```
b'\nchanges files:\n--------------\n--- perl-Cpanel-JSON-XS.changes\n+++ perl-Cpanel-JSON-XS.changes\n@@ -302 +302 @@\n-            i.e. decode "\xef\xbf\xbd\xef\xbf\xbd\xef\xbf\xbd\xef\xbf\xbd\xef\xbf\xbd\xef\xbf\xbd\\x{10204}"\n+            i.e. decode "\xef\xbf\xbd\xef\xbf\xbd \xef\xbf\xbd\xef\xbf\xbd\xef\xbf\xbd\xef\xbf\xbd\\x{10204}"\n'
```

and `tmpfile.write(message)` changes it to:

```
changes files:
--------------
--- perl-Cpanel-JSON-XS.changes
+++ perl-Cpanel-JSON-XS.changes
@@ -302 +302 @@
-            i.e. decode "������\x{10204}"
+            i.e. decode "�� ����\x{10204}"

```

**Comment by marcus-h** [comment]
On 2019-09-13 08:22:21 -0700, jengelh wrote:
> `osc rq show -d` displays UTF-8 sequences wrongly. (Maybe related to https://github.com/openSUSE/open-build-service/issues/8349 , but the mojibake is different).
>
> Observed:
> ```
> » osc rq show -d 730703 | grep --text 10204
> -            i.e. decode "������\x{10204}"
> +            i.e. decode "�� ����\x{10204}"
> ```

It seems that the API provides a broken diff:

marcus@linux:~> curl -u Marcus_H -X POST -d '' https://api.opensuse.org/request/730703?cmd=diff | hexdump -C
Enter host password for user 'Marcus_H':
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   222    0   222    0     0    204      0 --:--:--  0:00:01 --:--:--   204
00000000  0a 63 68 61 6e 67 65 73  20 66 69 6c 65 73 3a 0a  |.changes files:.|
00000010  2d 2d 2d 2d 2d 2d 2d 2d  2d 2d 2d 2d 2d 2d 0a 2d  |--------------.-|
00000020  2d 2d 20 70 65 72 6c 2d  43 70 61 6e 65 6c 2d 4a  |-- perl-Cpanel-J|
00000030  53 4f 4e 2d 58 53 2e 63  68 61 6e 67 65 73 0a 2b  |SON-XS.changes.+|
00000040  2b 2b 20 70 65 72 6c 2d  43 70 61 6e 65 6c 2d 4a  |++ perl-Cpanel-J|
00000050  53 4f 4e 2d 58 53 2e 63  68 61 6e 67 65 73 0a 40  |SON-XS.changes.@|
00000060  40 20 2d 33 30 32 20 2b  33 30 32 20 40 40 0a 2d  |@ -302 +302 @@.-|
00000070  20 20 20 20 20 20 20 20  20 20 20 20 69 2e 65 2e  |            i.e.|
00000080  20 64 65 63 6f 64 65 20  22 ef bf bd ef bf bd ef  | decode ".......|
00000090  bf bd ef bf bd ef bf bd  ef bf bd 5c 78 7b 31 30  |...........\x{10|
000000a0  32 30 34 7d 22 0a 2b 20  20 20 20 20 20 20 20 20  |204}".+         |
000000b0  20 20 20 69 2e 65 2e 20  64 65 63 6f 64 65 20 22  |   i.e. decode "|
000000c0  ef bf bd ef bf bd 20 ef  bf bd ef bf bd ef bf bd  |...... .........|

          ^^ ^^ ^^ This is the unicode replacement character (U+FFFD).

My guess is that the API tries to utf-8 decode the diff data that it receives
from the backend, which does not work in general.

000000d0  ef bf bd 5c 78 7b 31 30  32 30 34 7d 22 0a        |...\x{10204}".|
000000de
marcus@linux:~>


> Expected:
> ```
> » osc rdiff -r49:50 devel:languages:perl/perl-Cpanel-JSON-XS | grep --text 10204
> -            i.e. decode "��\x{10204}"
> +            i.e. decode "í í°\x{10204}"
> ```
>

marcus@linux:~> curl -u Marcus_H -X POST -d '' 'https://api.opensuse.org/source/devel%3Alanguages%3Aperl/perl-Cpanel-JSON-XS?cmd=diff&oproject=openSUSE%3AFactory' | hexdump -C
Enter host password for user 'Marcus_H':
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   198    0   198    0     0    167      0 --:--:--  0:00:01 --:--:--   167
00000000  0a 63 68 61 6e 67 65 73  20 66 69 6c 65 73 3a 0a  |.changes files:.|
00000010  2d 2d 2d 2d 2d 2d 2d 2d  2d 2d 2d 2d 2d 2d 0a 2d  |--------------.-|
00000020  2d 2d 20 70 65 72 6c 2d  43 70 61 6e 65 6c 2d 4a  |-- perl-Cpanel-J|
00000030  53 4f 4e 2d 58 53 2e 63  68 61 6e 67 65 73 0a 2b  |SON-XS.changes.+|
00000040  2b 2b 20 70 65 72 6c 2d  43 70 61 6e 65 6c 2d 4a  |++ perl-Cpanel-J|
00000050  53 4f 4e 2d 58 53 2e 63  68 61 6e 67 65 73 0a 40  |SON-XS.changes.@|
00000060  40 20 2d 33 30 32 20 2b  33 30 32 20 40 40 0a 2d  |@ -302 +302 @@.-|
00000070  20 20 20 20 20 20 20 20  20 20 20 20 69 2e 65 2e  |            i.e.|
00000080  20 64 65 63 6f 64 65 20  22 ed a0 81 ed b0 82 5c  | decode "......\|

                                      ^^ first illegal utf-8 sequence.

00000090  78 7b 31 30 32 30 34 7d  22 0a 2b 20 20 20 20 20  |x{10204}".+     |
000000a0  20 20 20 20 20 20 20 69  2e 65 2e 20 64 65 63 6f  |       i.e. deco|
000000b0  64 65 20 22 c3 ad 20 c3  ad c2 b0 5c 78 7b 31 30  |de ".. ....\x{10|
000000c0  32 30 34 7d 22 0a                                 |204}".|
000000c6
marcus@linux:~>


Hence, this seems to be an API bug in the POST /request/:id?cmd=diff route.

**Comment by marcus-h** [comment]
Hmm if you view my previous reply in a browser, it looks a bit broken...

On 2019-09-18 16:20:41 +0200, Marcus Hüwe wrote:
```
> 000000b0  20 20 20 69 2e 65 2e 20  64 65 63 6f 64 65 20 22  |   i.e. decode "|
> 000000c0  ef bf bd ef bf bd 20 ef  bf bd ef bf bd ef bf bd  |...... .........|
>
>           ^^ ^^ ^^ This is the unicode replacement character (U+FFFD).
>
```

<SNIP>

```
> 00000060  40 20 2d 33 30 32 20 2b  33 30 32 20 40 40 0a 2d  |@ -302 +302 @@.-|
> 00000070  20 20 20 20 20 20 20 20  20 20 20 20 69 2e 65 2e  |            i.e.|
> 00000080  20 64 65 63 6f 64 65 20  22 ed a0 81 ed b0 82 5c  | decode "......\|
>
>                                       ^^ first illegal utf-8 sequence.
>
```

**Comment by marcus-h** [comment]
On 2019-09-18 16:24:50 +0200, Marcus Hüwe wrote:
> Hmm if you view my previous reply in a browser, it looks a bit broken...
>
Hmm my fixup failed as well:/ But I guess it is obvious what I wanted to
"highlight":)

**Comment by dmach** [comment]
This seems to be fixed in OBS already. Closing.

**Comment by jengelh** [comment]
osc-0.182.0-2.1.noarch still shows the Observed block and not the Expected block.

**Comment by dmach** [comment]
> osc-0.182.0-2.1.noarch still shows the Observed block and not the Expected block.

Ah, correct. I re-tested this (properly this time) and it seems that the API returns garbage.
I've created an OBS issue for that: https://github.com/openSUSE/open-build-service/issues/13537
