### ISSUE TITLE
"osc vc -F ..." interprets strings from infile containing backslashes as escape characters

### ISSUE THREAD

**Issue by M0ses** [openSUSE/osc#637]
If the infile for ```osc vc -F <infile> <changesfile>``` contains backslashes, e.g. `\b`, the corresponding control character (in this case backspace) is added to the changesfile

oneliner to reproduce:

```
echo -n > test.changes;echo "\b" > tmp.changes;osc vc -F tmp.changes test.changes; hexdump test.changes -C
```

**Comment by M0ses** [comment]
same happens with

```
osc vc -m "\b"
```

**Comment by marcus-h** [comment]
On 2019-09-17 09:28:05 -0700, Frank Schreiner wrote:
> same happens with
>
> ```
> osc vc -m "\b"
> ```
That's expected because "vc" itself calls "echo -e". In the
"osc vc -F <file> ..." case, the problem is that osc just passes the
file's content to "vc" via the its "-m" option. Actually, osc should
pass the filename to "vc" (but then, osc has to "calculate" the
changes file name on its own...).

**Comment by M0ses** [comment]
I already stumble over https://github.com/openSUSE/obs-build/blob/master/vc#L137.
I guess this is the ```echo -e``` you are referring to?
I`m coming from a problem in cpanspec which is passing the changes to an ```osc vc -F``` and wondering what would be the best/cleanest approach to solve this issue.

IMHO:
 * the opportunity to pass escape sequences to ```osc vc -m "..."``` is absolutly valuable
 * lines taken from a file with option "-F" should not be changed

maybe in case of reading from an input file via "-F" option the backslash should be substituted by "\\".

**Comment by M0ses** [comment]
To illustrate the issue, taken as an example, a line of changelog of perl-POE (generate from the git commit messages):

```
      "C:\opt\perl-5.20.1\bin\perl.exe" mylib/gen-tests.perl lib/POE.pm
```

the

```
...\bin\
```
gets an

```
...<backspace>in
```
in the changelog (created by cpanspec), 
which will break with new version of createrepo_c

and I think this not an  uncommon comment for autogenerated changelogs in languages which also are available on Windows.

**Comment by lethliel** [comment]
This is fixed.
