### ISSUE TITLE
Automatical dos2unix for *.spec files when building

### ISSUE THREAD

**Issue by guoyunhe** [openSUSE/osc#647]
I sometimes copied some build commands from GitHub or websites. The copied text may contains `\r` and some editors don't convert it (vim). When I run `osc build`, it will throw an error at `\r` position.

**Comment by jayvdb** [comment]
Does `spec-cleaner` fix this?  If not, the same issue should be raised there, and probably fixed there first as it is easier and has less risk associated with the change.

**Comment by guoyunhe** [comment]
Yes, spec-cleaner does fixed this.

**Comment by marcus-h** [comment]
On 2019-10-02 04:15:58 -0700, Guo Yunhe wrote:
> I sometimes copied some build commands from GitHub or websites. The copied text may contains `\r` and some editors don't convert it (vim). When I run `osc build`, it will throw an error at `\r` position.
>
IMHO, osc should not touch the spec file/build description.

**Comment by jayvdb** [comment]
osc build runs some obs service plugins, and I think the one which is touching the spec files is https://github.com/openSUSE/obs-service-format_spec_file/blob/master/prepare_spec , so that might be the next place to add dos2unix-ish behaviour.

**Comment by dmach** [comment]
As discussed above, osc shouldn't modify the specs directly,
the modifications are done via plugins/services.
This change is out of scope of osc, closing.
