### ISSUE TITLE
osc should not assume a default instance when multiple configurations are present

### ISSUE THREAD

**Issue by Firstyear** [openSUSE/osc#649]
It's possible for osc to have multiple instances configured, however it uses one as a "default". This can lead to surprising behaviour, where when you re-branch or change content, osc will silently swap from a private instance to it's default public one. This may lead to disclosure of content that is not legally meant to be public.

Suggesting to the user to use aliases like iosc or eosc etc is not the answer - these workarounds exist because osc has a surprising behavior (which violates the psychology design principle of consistency), and even as work arounds fail to account for mistakes where the user could type osc which again, will faill back to the surprising behaviour. 

Instead, when an action would "fall back" to the default the user should be informed to make a decision (similar to when you ask to trust gpg keys). This process would look like:

```
osc branch ..... 
> Which instance would you like to use?
1) url
2) url
choice [default: 1] #
```

Not only is this now a constraint that will prevent human mistakes from occurring, it adds consistency and predictability to the tool, eliminating the need for aliases, and actually being safer to use in these cases. 

Thanks,

**Comment by marcus-h** [comment]
On 2019-10-08 16:15:31 -0700, Firstyear wrote:
> It's possible for osc to have multiple instances configured, however it uses one as a "default". This can lead to surprising behaviour, where when you re-branch or change content, osc will silently swap from a private instance to it's default public one. This may lead to disclosure of content that is not legally meant to be public.
>
Hmm about which command are you talking? osc commit uses the apiurl that is
associated with the project/package working copy.

> Suggesting to the user to use aliases like iosc or eosc etc is not the answer - these workarounds exist because osc has a surprising behavior (which violates the psychology design principle of consistency), and even as work arounds fail to account for mistakes where the user could type osc which again, will faill back to the surprising behaviour.
>
Yes, osc's UI is super inconsistent.

> Instead, when an action would "fall back" to the default the user should be informed to make a decision (similar to when you ask to trust gpg keys). This process would look like:
>
> ```
> osc branch .....
> > Which instance would you like to use?
> 1) url
> 2) url
> choice [default: 1] #
> ```
>
Hmm this would break scripts (we could work around that, though).

We outlined a new UI in [1]. Long story short: the idea is that the
user _explicitly_ has to specify the apiurl/alias for all "remote"
commands (that is, commands that are not "context sensitive"/do not read the
missing information (like the apiurl) from the working copy/CWD).

Would this help in your case?


[1] https://lizards.opensuse.org/2011/05/23/gsoc-new-osc-user-interface-proposal/

**Comment by Firstyear** [comment]
I have a lot of potential feedback on good cli design - I led the redesign of the 389-ds cli tools, and its been really good, so where would I comment on the new ui ideas? 

Anyway, "for now" prompting on ambiguity would help a lot here, even at the risk of breaking things IMO.

**Comment by dmach** [comment]
I don't think we should introduce any new interactive prompt, especially with all existing scripts relying on the current behavior. I'm not saying we won't redesign osc in the future, but I'd keep the current behavior for now.
