### ISSUE TITLE
Publish `osc` on PyPI?

### ISSUE THREAD

**Issue by crazyscientist** [openSUSE/osc#658]
Hi there,

I was wondering, if we should publish `osc` also as a package on PyPI?

**Comment by adrianschroeter** [comment]
On Mittwoch, 23. Oktober 2019, 17:17:12 CEST Andreas Hasenkopf wrote:
> Hi there,
> 
> I was wondering, if we should publish `osc` also as a package on PyPI?

depends on who "we" is... Feel free to do so, if you like.

-- 

Adrian Schroeter <adrian@suse.de>
Build Infrastructure Project Manager

SUSE Software Solutions Germany GmbH,  Maxfeldstr. 5, 90409 Nuernberg, Germany
(HRB 247165, AG München), Geschäftsführer: Felix Imendörffer

**Comment by crazyscientist** [comment]
@adrianschroeter Thanks for the thumbs up. And yes, I'm kind of volunteering to set this up.

So, how would I do it? By setting up a Travis CI pipeline that automatically builds the Python package and submits it to PyPI once a tag is set on the master branch. That would basically be an identical setup as for [OSC Tiny](https://github.com/crazyscientist/osc-tiny).

It looks like @toabctl already created an [osc project on PyPI](https://pypi.org/project/osc/). Would you mind adding me as maintainer to the PyPI project or supply the credentials that I can use in the Travis CI configuration?

**Comment by toabctl** [comment]
@crazyscientist sure. what's your pypi username?
Does installing `osc` via pip works nowadays? I tried ~1-2 years ago and not all requiremennts were installable (eg.` urlgrabber` but that should be fixed).

**Comment by crazyscientist** [comment]
> Does installing osc via pip works nowadays?

Yes, like a charm :smile: 

> what's your pypi username?

It's `crazyphd`

**Comment by lethliel** [comment]
> @adrianschroeter Thanks for the thumbs up. And yes, I'm kind of volunteering to set this up.
> 

@crazyscientist Thanks for volunteering. That is one thing I wanted to do anyway but never had the time.

**Comment by adrianschroeter** [comment]
please note that you may should consider to package also the "build" script as part of the pip. Since an osc without to test your changes local is way less useful...

**Comment by crazyscientist** [comment]
@toabctl Would you mind adding `crazyphd` as maintainer on PyPI?

**Comment by toabctl** [comment]
@crazyscientist added you as owner now.
