### ISSUE TITLE
complete.sh breaks systems's TAB completion

### ISSUE THREAD

**Issue by rudimeier** [openSUSE/osc#66]
In 08a95050 the line
COMP_WORDBREAKS="${COMP_WORDBREAKS//:}"
was added to complete.sh. This may override and break well choosen system settings.

Please remove this line again or make sure that packagers don't install it into /etc/profile.d or bashrc.
The real bug is that colon was choosen for OBS subproject separator. This should not be "fixed" by making things even worse.

See also,
https://bugzilla.novell.com/show_bug.cgi?id=851908#c12
(comments 12 - 15)

**Comment by lethliel** [comment]
The line was removed long ago.
