### ISSUE TITLE
osc fails to migrate credential config

### ISSUE THREAD

**Issue by andreas-schwab** [openSUSE/osc#665]
osc always asks for credentials instead of retrieving them from the keyring.  You cannot even run osc config or osc help without being asked for credentials.

$ osc help
No password found in section https://api.opensuse.org
Please enter new credentials.
Username:

**Comment by lethliel** [comment]
Can you do a osc config --change-password and set it to the keyring manager?

**Comment by andreas-schwab** [comment]
$ osc config --change-password
--change-password only needs the apiurl

**Comment by lethliel** [comment]
Yes. You need to do:
osc config https://api.opensuse.org -- change-password

**Comment by andreas-schwab** [comment]
$ osc config https://api.opensuse.org -- change-password
No password found in section https://api.opensuse.org
Please enter new credentials.
Username:

**Comment by lethliel** [comment]
So you would need to provide your credentials and select the appropriate keyring manager then.

**Comment by lethliel** [comment]
fixed by https://github.com/openSUSE/osc/commit/5227e357bcd681e0cc4fc10bce868a44775841b8
