### ISSUE TITLE
check in huge shell archives is insanely slow

### ISSUE THREAD

**Issue by frispete** [openSUSE/osc#669]
osc 0.166.1 as of TW 20191101 is insanely slow in checking in huge shell archives like the nvidia G05 driver, that comes as a 135 MiB shell archive.

After switching to Python 3, osc's diff handling used to be broken for anything, it cannot decode. Now, it does handle those cases again, but..

Example of checking in a new driver 440.31 of nvidia-gfxG05 to a local OBS (client and server running on decent hardware):
```
$ time oscl ci
Default log message was not changed. Press 'c' to continue.
a)bort, c)ontinue, e)dit: a
aborted.

real    31m10,899s
user    31m1,173s
sys     0m1,694s
```

Compare with osc 0.162.1 (Leap 15.0):
```
$ time oscl ci
Deleting    NVIDIA-Linux-x86_64-440.26.run
Sending    NVIDIA-Linux-x86_64-440.31.run
Transmitting file data .
Committed revision 18.

real    0m29,472s
user    0m10,212s
sys     0m2,851s
```

It took me less than 2 seconds to edit and decline the first operation and to accept the second.

Steps to reproduce:
```
osc branch X11:Drivers:Video/nvidia-gfxG05
osc co home:USERNAME:branches:X11:Drivers:Video/nvidia-gfxG05
osc service dr # fetches NVIDIA-Linux-x86_64-440.31.run
osc ar
osc ci # just cancel this operation
```

**Comment by marcus-h** [comment]
On 2019-11-04 16:47:07 +0000, Hans-Peter Jansen wrote:
> osc 0.166.1 as of TW 20191101 is insanely slow in checking in huge shell archives like the nvidia G05 driver, that comes as a 135 MiB shell archive.
>
> After switching to Python 3, osc's diff handling used to be broken for anything, it cannot decode. Now, it does handle those cases again, but..
>
> Example of checking in a new driver 440.31 of nvidia-gfxG05 to a local OBS (client and server running on decent hardware):
> ```
> $ time oscl ci
> Default log message was not changed. Press 'c' to continue.
> a)bort, c)ontinue, e)dit: a
> aborted.
>
> real    31m10,899s
> user    31m1,173s
> sys     0m1,694s
> ```
>
> Compare with osc 0.162.1 (Leap 15.0):
> ```
> $ time oscl ci
> Deleting    NVIDIA-Linux-x86_64-440.26.run
> Sending    NVIDIA-Linux-x86_64-440.31.run
> Transmitting file data .
> Committed revision 18.
>
> real    0m29,472s
> user    0m10,212s
> sys     0m2,851s
> ```
>
On python3, osc uses chardet to "decode" the bytes diff (the shell archive
is considered as a text file, hence, the diff is performed), which takes
a "lot" of time (it tries several encodings).
osc's get_commit_msg function should probably return a list of bytes but
this is a bit more involved...
Maybe we should simply get rid of the chardet module and simply perform
"either utf-8 or latin-1" decode heuristic (having an "inaccurate" [1]
diff might be OK for the purpose of a commit message).

[1] https://github.com/openSUSE/osc/pull/554#issuecomment-493755780

**Comment by frispete** [comment]
> On python3, osc uses chardet to "decode" the bytes diff (the shell archive
is considered as a text file, hence, the diff is performed), which takes
a "lot" of time (it tries several encodings).

Trying all different encodings on a 1.3 MB binary chunk, that will not encode into any valid encoding, is obviously a worst case scenario here.

> osc's get_commit_msg function should probably return a list of bytes but this is a bit more involved...
> Maybe we should simply get rid of the chardet module and simply perform
> "either utf-8 or latin-1" decode heuristic (having an "inaccurate" [1]
> diff might be OK for the purpose of a commit message).

+1. Since the diff is a commit message hint only and thrown away anyway, even utf-8 only should be fine (or do we deal with **that** much archaic latin1 data, still?).

**Comment by frispete** [comment]
Just to give you a heads up, today, I was bitten from this issue again (kernel transition from 5.4.14 to 5.5.1, that requires a new nvidia release). 

Since my environment is either TW or 15.1+, I had no choice anymore, but suffer. Well, no...

During the hanging osc, I linked osc into a 15.1 dedicated project, forced `_without_python3 1` by prjconf, built it, waited for OBS to publish it, installed it, killed the osc process, checked it in with the python2 based osc, and the driver build finished before py3 based osc would have finished the check in.

Oh, well...
