### ISSUE TITLE
osc with python-keyring stores multiple account passwords in same secret

### ISSUE THREAD

**Issue by seife** [openSUSE/osc#674]
I'm using osc on openSUSE Leap 15.1 with XFCE. gnome-keyring-daemon is running.
Today I updated to latest osc from openSUSE:Tools and discovered `osc config --change-password`.

I stored my password in the keyring and it worked. Unfortunately, I have multiple OBS accounts and OSC stores all the passwords in the same "secret storage bucket".

Investigating the stored password with the `seahorse` tool, I see that it is named `password for 'USER' on 'osc'` which is the first strange thing. Going into the details it shows

    username: USER
    application: osc
    service: osc

IMVHO, service: should be the hostname of the obs server or something like that.

osc version is 0.166.1

**Comment by seife** [comment]
my setup is using `class KeyringCredentialsManager(AbstractCredentialsManager)` from osc/credentials.py.
I'll come up with a patch soon.

**Comment by seife** [comment]
I see this is fixed with

    commit 5227e357bcd681e0cc4fc10bce868a44775841b8
    Author: Andreas Schwab <schwab@linux-m68k.org>
    Date:   Sun Nov 3 12:33:17 2019 +0100
    
        Don't enforce password reuse

can we get a new release, please? ;-)

**Comment by lethliel** [comment]
0.166.2 was released to openSUSE:Tools a few hours ago and a SR to Factory is created
