### ISSUE TITLE
Feature request: run _service first when called with 'osc build'

### ISSUE THREAD

**Issue by lrupp** [openSUSE/osc#686]
I moved all my package sources to Github, keeping only a _service file in my package directory.

Now, if I run ```osc build```, I get an error that there is neither a spec-file nor anything else that osc could use to build the package. I have to run ```osc service run``` first to extract the spec file out of the (upstream) Github repository.

Feature request: run ```osc service run```, if osc detects only a _service file in the directory.

**Comment by marcus-h** [comment]
On 2019-11-25 03:07:15 -0800, Lars Vogdt wrote:
> I moved all my package sources to Github, keeping only a _service file in my package directory.
>
> Now, if I run ```osc build```, I get an error that there is neither a spec-file nor anything else that osc could use to build the package. I have to run ```osc service run``` first to extract the spec file out of the (upstream) Github repository.
>
> Feature request: run ```osc service run```, if osc detects only a _service file in the directory.
>
If there's a _service file, osc will automatically execute the services.
Currently, this is done after "parsing" the commandline args... so this
can be considered as a bug. (The only drawback, if we change the current
behavior, is that we do not have the "fail fast" behavior anymore. That
is, we can only recognize missing/wrong arguments after running the
(expensive) services.)

**Comment by mmohring** [comment]
This is a new behavior. A while ago, osc build automatically ran the source service first. So when I had a package which generates also a .spec file, I was runnung osc build a.spec, a.spec not existing to run a build and let it fail. This now does not work anymore. So a bug or not, this worked before. What is also inconsistent is that if you know the name of the generated .spec file, a osc build <known.spec> will run the source service. So the new behavior is in any case not intuitive. What also happens is that lets say I have the build package, and it generates a .spec file. But running osc build build.spec now causes an error, before the change it detected that build.spec is in reality <prefix from sources services>:build.spec and ran that instead. Now it fails with an error complaining the .spec file is missing.
Example:

OBS:Server:Unstable/obs-server

In the past you could run:

osc build obs-server.spec 

in a checked out copy. Now you have to run

osc build _service:obs_scm:obs-server.spec

after running osc service run. If you just run osc build obs-server.spec without osc service run it says that it cannot find a spec file.

**Comment by mmohring** [comment]
To bring back the old behaviour, I have just commented out the following line in the code:

Line 587 in "osc/build.py":

    if not os.path.isfile(build_descr):
        raise oscerr.WrongArgs('Error: build description file named \'%s\' does not exist.' % build_descr)

This is just a workaround of course, I had not time to investigate all the changes made recently which lead to the new behaviour.

**Comment by adrianschroeter** [comment]
On Dienstag, 7. Januar 2020, 15:46:16 CET Martin Mohring wrote:
> This is a new behavior. A while ago, osc build automatically ran the source service first. So when I had a package which generates also a .spec file, I was runnung osc build a.spec, a.spec not existing to run a build and let it fail. This now does not work anymore. So a bug or not, this worked before. What is also inconsistent is that if you know the name of the generated .spec file, a osc build <known.spec> will run the source service. So the new behavior is in any case not intuitive. What also happens is that lets say I have the build package, and it generates a .spec file. But running osc build build.spec now causes an error, before the change it detected that build.spec is in reality <prefix from sources services>:build.spec and ran that instead. Now it fails with an error complaining the .spec file is missing.
> Example:
> 
> OBS:Server:Unstable/obs-server
> 
> In the past you could run:
> 
> osc build obs-server.spec 
> 
> in a checked out copy. Now you have to run
> 
> osc build _service:obs_scm:obs-server.spec
> 
> after running osc service run. If you just run osc build obs-server.spec without osc service run it says that it cannot find a spec file.

I agree that it would be nice that you don't have to do that, but it was that way since years ...

-- 

Adrian Schroeter <adrian@suse.de>
Build Infrastructure Project Manager

SUSE Software Solutions Germany GmbH,  Maxfeldstr. 5, 90409 Nuernberg, Germany
(HRB 247165, AG München), Geschäftsführer: Felix Imendörffer

**Comment by dmach** [comment]
I tried to narrow down the autodetection of which spec file to select by adding the following code which accepts `_service:*:` prefix:
```
                if len(cands) > 1:
                    pac_cands = [i for i in cands if fnmatch.fnmatch(i, f"*:{pac}.{recipe}")]
                    if pac_cands:
                        cands = pac_cands
```

I ended up with this:
```
Multiple build description files found: _service:obs_scm:obs-server.spec, _service:set_version:_service:obs_scm:obs-server.spec
```

It is not clear which one to use.
I don't think osc should be guessing any further -> let's keep the current behavior.
