### ISSUE TITLE
diffs returned by osc ci are no longer in color (0.165.1 -> 0.166.2)

### ISSUE THREAD

**Issue by Conan-Kudo** [openSUSE/osc#688]
I upgraded from osc-0.165.1 to osc-0.166.2, and now diffs for `osc ci` are no longer colored.

This is on Fedora 31, using the `osc` package provided by Fedora.

The version where this worked: `osc-0.165.1-255.1.2.fc31.1`. ([Dist-Git packaging tree](https://src.fedoraproject.org/rpms/osc/tree/ed6d95a792f613ae2da28cb4f9670af9fa039d09))

The version where this breaks: `osc-0.166.2-272.1.2.fc31` ([Dist-Git packaging tree](https://src.fedoraproject.org/rpms/osc/tree/9ab882fd5d41b5b844d137296e2d860f16f52d72))

Note that `osc diff` has _never_ returned color diffs, only `osc ci`.

**Comment by dmach** [comment]
`osc ci` seems to be showing color diffs - osc-0.177.0 on Tumbleweed.
It was either fixed in the meantime or it did not work due to something in Fedora.
