### ISSUE TITLE
KeyError on fetching CentOS8 package python2-rpm-macros

### ISSUE THREAD

**Issue by wagner-certat** [openSUSE/osc#700]
Hello,

I repeatedly get an KeyError exception on trying to build a CentOS 8 package locally:
```
$ osc build CentOS_8
Building python3-six.spec for CentOS_8/x86_64
Getting buildinfo from server and store to /home/sebastianw/packaging/home:sebix:intelmq/python-six/.osc/_buildinfo-CentOS_8-x86_64.xml
Getting buildconfig from server and store to /home/sebastianw/packaging/home:sebix:intelmq/python-six/.osc/_buildconfig-CentOS_8-x86_64
Updating cache of required packages
0.3% cache miss. 376/377 dependencies cached.

CentOS:CentOS-8/python2-rpm-macros: attempting download from api, since not found
fetching packages for 'CentOS:CentOS-8': | Elapsed Time: 0:00:00                                                                                                                                                                              
Traceback (most recent call last):
  File "/usr/bin/osc", line 41, in <module>
    r = babysitter.run(osccli)
  File "/usr/lib/python3.7/site-packages/osc/babysitter.py", line 62, in run
    return prg.main(argv)
  File "/usr/lib/python3.7/site-packages/osc/cmdln.py", line 344, in main
    return self.cmd(args)
  File "/usr/lib/python3.7/site-packages/osc/cmdln.py", line 367, in cmd
    retval = self.onecmd(argv)
  File "/usr/lib/python3.7/site-packages/osc/cmdln.py", line 501, in onecmd
    return self._dispatch_cmd(handler, argv)
  File "/usr/lib/python3.7/site-packages/osc/cmdln.py", line 1232, in _dispatch_cmd
    return handler(argv[0], opts, *args)
  File "/usr/lib/python3.7/site-packages/osc/commandline.py", line 6449, in do_build
    return osc.build.main(self.get_api_url(), opts, args)
  File "/usr/lib/python3.7/site-packages/osc/build.py", line 948, in main
    fetcher.run(bi)
  File "/usr/lib/python3.7/site-packages/osc/fetch.py", line 253, in run
    self.__fetch_cpio(buildinfo.apiurl)
  File "/usr/lib/python3.7/site-packages/osc/fetch.py", line 128, in __fetch_cpio
    self.__download_cpio_archive(apiurl, project, repo, arch, package, **pkgs)
  File "/usr/lib/python3.7/site-packages/osc/fetch.py", line 87, in __download_cpio_archive
    pac = pkgs[decode_it(n.rsplit(b'.', 1)[0])]
KeyError: ''
```
```
$ osc --version
0.166.2
```
current TW version

**Comment by adrianschroeter** [comment]
On Sonntag, 8. Dezember 2019, 14:02:32 CET Wagner wrote:
> Hello,
> 
> I repeatedly get an KeyError exception on trying to build a CentOS 8 package locally:
> ```
> $ osc build CentOS_8
> Building python3-six.spec for CentOS_8/x86_64
> Getting buildinfo from server and store to /home/sebastianw/packaging/home:sebix:intelmq/python-six/.osc/_buildinfo-CentOS_8-x86_64.xml
> Getting buildconfig from server and store to /home/sebastianw/packaging/home:sebix:intelmq/python-six/.osc/_buildconfig-CentOS_8-x86_64
> Updating cache of required packages
> 0.3% cache miss. 376/377 dependencies cached.
> 
> CentOS:CentOS-8/python2-rpm-macros: attempting download from api, since not found
> fetching packages for 'CentOS:CentOS-8': | Elapsed Time: 0:00:00                                                                                                                                                                              
> Traceback (most recent call last):
>   File "/usr/bin/osc", line 41, in <module>
>     r = babysitter.run(osccli)
>   File "/usr/lib/python3.7/site-packages/osc/babysitter.py", line 62, in run
>     return prg.main(argv)
>   File "/usr/lib/python3.7/site-packages/osc/cmdln.py", line 344, in main
>     return self.cmd(args)
>   File "/usr/lib/python3.7/site-packages/osc/cmdln.py", line 367, in cmd
>     retval = self.onecmd(argv)
>   File "/usr/lib/python3.7/site-packages/osc/cmdln.py", line 501, in onecmd
>     return self._dispatch_cmd(handler, argv)
>   File "/usr/lib/python3.7/site-packages/osc/cmdln.py", line 1232, in _dispatch_cmd
>     return handler(argv[0], opts, *args)
>   File "/usr/lib/python3.7/site-packages/osc/commandline.py", line 6449, in do_build
>     return osc.build.main(self.get_api_url(), opts, args)
>   File "/usr/lib/python3.7/site-packages/osc/build.py", line 948, in main
>     fetcher.run(bi)
>   File "/usr/lib/python3.7/site-packages/osc/fetch.py", line 253, in run
>     self.__fetch_cpio(buildinfo.apiurl)
>   File "/usr/lib/python3.7/site-packages/osc/fetch.py", line 128, in __fetch_cpio
>     self.__download_cpio_archive(apiurl, project, repo, arch, package, **pkgs)
>   File "/usr/lib/python3.7/site-packages/osc/fetch.py", line 87, in __download_cpio_archive
>     pac = pkgs[decode_it(n.rsplit(b'.', 1)[0])]
> KeyError: ''
> ```
> ```
> $ osc --version
> 0.166.2

I think you need osc 0.167 version, which support RedHat module rpm packages download.

You can find it in openSUSE:Tools project.


-- 

Adrian Schroeter <adrian@suse.de>
Build Infrastructure Project Manager

SUSE Software Solutions Germany GmbH,  Maxfeldstr. 5, 90409 Nuernberg, Germany
(HRB 247165, AG München), Geschäftsführer: Felix Imendörffer

**Comment by wagner-certat** [comment]
Ok, thanks for the quick answer!

Note to myself: The Submit Request for TW is https://build.opensuse.org/request/show/754708
