### ISSUE TITLE
osc build requires running in a checked out directory even with --alternative-project

### ISSUE THREAD

**Issue by jirislaby** [openSUSE/osc#703]
This was originally reported at:
https://bugzilla.suse.com/show_bug.cgi?id=1136584

And it got no attention for half a year.

Given it is a serious regression which blocks updating osc on all development machines, let's open a dup of that here.

> (In reply to Michal Kubeček from comment #0)
> > According to Jiří Slabý, 0.164.2 also works.
> 
> Yes, osc 0.165 now needs .osc dir and _project, _package and (empty) _files in it for to me unknown reason. So this is a regression preventing use of osc as we use it for the kernel maintenance. See:
> https://kernel.opensuse.org/cgit/kernel-source/tree/scripts/osc_wrapper?h=scripts#n286
> 
> >	rm -rf "$(dirname "$spec")/.osc"
> >	osc build --local-package --alternative-project="$PROJECT" \
> >		"${osc_args[@]}" standard "$spec"

**Comment by lethliel** [comment]
You need to specify the --no-service flag.

**Comment by lethliel** [comment]
@jirislaby Or do you need the local service run before building?

**Comment by jirislaby** [comment]
We don't need services, so I added the option to the script. Now it dies due to missing `./.osc/_last_buildroot.new`. If I create the dir and touch the file, it works. But it should need the file the same as it does not necessarily need .osc/_project etc. Any other flag needed?
```
Traceback (most recent call last):
  File "/usr/bin/osc", line 41, in <module>
    r = babysitter.run(osccli)
  File "/usr/lib/python3.7/site-packages/osc/babysitter.py", line 62, in run
    return prg.main(argv)
  File "/usr/lib/python3.7/site-packages/osc/cmdln.py", line 344, in main
    return self.cmd(args)
  File "/usr/lib/python3.7/site-packages/osc/cmdln.py", line 367, in cmd
    retval = self.onecmd(argv)
  File "/usr/lib/python3.7/site-packages/osc/cmdln.py", line 501, in onecmd
    return self._dispatch_cmd(handler, argv)
  File "/usr/lib/python3.7/site-packages/osc/cmdln.py", line 1232, in _dispatch_cmd
    return handler(argv[0], opts, *args)
  File "/usr/lib/python3.7/site-packages/osc/commandline.py", line 6491, in do_build
    return osc.build.main(self.get_api_url(), opts, args)
  File "/usr/lib/python3.7/site-packages/osc/build.py", line 1298, in main
    osc.core.store_write_last_buildroot(os.curdir, repo, arch, vm_type)
  File "/usr/lib/python3.7/site-packages/osc/core.py", line 6549, in store_write_last_buildroot
    store_write_string(dir, '_last_buildroot', repo + '\n' + arch + '\n' + vm_type + '\n')
  File "/usr/lib/python3.7/site-packages/osc/core.py", line 6531, in store_write_string
    f = open(fname + '.new', 'w')
FileNotFoundError: [Errno 2] No such file or directory: './.osc/_last_buildroot.new'
```

**Comment by jirislaby** [comment]
ade9baba52afead490085779c8408761f080a5cf fixes the above?

**Comment by lethliel** [comment]
@jirislaby This is fixed in https://github.com/openSUSE/osc/commit/ade9baba52afead490085779c8408761f080a5cf

I will release the new version 0.167.1 which inlcudes this fix today (latest tomorrow)

**Comment by lethliel** [comment]
@jirislaby 0.167.1 is released to openSUSE:Tools. SR to Factory pending.

**Comment by jirislaby** [comment]
We are done here.
