### ISSUE TITLE
osc aborts if files beside _apiurl, _project and _packages are in .osc

### ISSUE THREAD

**Issue by dcermak** [openSUSE/osc#705]
`osc` will not accept projects where there are files beside `_apiurl`, `_project` and `_packages` in the `.osc/` directory. This is caused by the function `wc_check`:
https://github.com/openSUSE/osc/blob/32ec356bad032c61fe7fab42f44eef00c06564e9/osc/core.py#L706

Could this behavior be changed, so that other tools could add additional data into `.osc/` for caching without killing `osc`?

**Comment by marcus-h** [comment]
On 2019-12-10 05:09:38 -0800, Dan Čermák wrote:
> `osc` will not accept projects where there are files beside `_apiurl`, `_project` and `_packages` in the `.osc/` directory. This is caused by the function `wc_check`:
> https://github.com/openSUSE/osc/blob/32ec356bad032c61fe7fab42f44eef00c06564e9/osc/core.py#L706
>
> Could this behavior be changed, so that other tools could add additional data into `.osc/` for caching without killing `osc`?
>
This would make osc's wc management code a bit more complicated (osc's
working copy handling is already quite fragile (osc2 is a bit better in this
regard)). What about using a separate directory/file for your plugin (for
instance, .osc_plugin_XXX)?

**Comment by dcermak** [comment]
> What about using a separate directory/file for your plugin (for instance, .osc_plugin_XXX)?

Sometimes the obvious solution is the best one (and I was too blind to see it). Thanks!
