### ISSUE TITLE
Make osc update to recover on failed updates of packages while working on large project

### ISSUE THREAD

**Issue by mcepl** [openSUSE/osc#707]
I have checked out ``devel:languages:python`` (that’s 1825 packages) and when I try to update it it always fails on some package for one reason or another. That unfortunately means when I remove the offending package (to be freshly downloaded from the source), I have to restart the whole process again and wait until it fails somewhere else.

Would it be possible for ``osc up`` on a project just to list in the end all packages where it failed to refresh their content properly instead of failing on each of them?

**Comment by lethliel** [comment]
@mcepl I finally have time to work through some issues. What is the reason they are failing to update? 
I am currently checking out devel:languages:python and need some hints on how to reproduce the failing updates.

**Comment by mcepl** [comment]
I am not completely certain how to reliably reproduce, but it seems to me that this works:

1. ``osc co <project>``

2. create new package in the project by some other means … accepted SR from a home project, for example.

3. in impatience include the new package in the project via ``osc co -c name-of-package``.

4. run ``osc up`` on whole project

**Comment by lethliel** [comment]
That does not work for me. But copying .osc/_files from Package A to Package B results in an inconsistent working copy for Package B. 

Is this one of the errors you are talking about?

**Comment by mcepl** [comment]
I am sure, I have never touched ``.osc/`` directly, but the error is usually something like ``want to add python-foo/, but it already exists``.

**Comment by lethliel** [comment]
Ah I found it. Thanks.

**Comment by mcepl** [comment]
This seems to somehow go away. At least, I haven’t seen it for a long time.
