### ISSUE TITLE
List the Python dependencies

### ISSUE THREAD

**Issue by crazyscientist** [openSUSE/osc#708]
Hi there,

while working on a derived package I noticed that `osc` actually has some dependencies, e.g. `M2Crypto`. These dependencies should me mentioned in a `requirements.txt` and/or as `install_requires` in `setup.py`.

Having this dependencies defined outside OBS would also be helpful for #658.

**Comment by Conan-Kudo** [comment]
The dependencies for `osc` are not defined in any meaningful way because that requires changing `osc` to use `setuptools`, which they have been reluctant to do.

The dependencies are as follows:
* `distro`
* `lxml`
* `progressbar2`
* `rpm`
* `M2Crypto`

**Comment by marcus-h** [comment]
On 2019-12-17 18:19:48 -0800, Neal Gompa (ニール・ゴンパ) wrote:
> The dependencies are as follows:
> * `distro`

Optional.

> * `lxml`

No.

> * `progressbar2`

Optional.

> * `rpm`

Optional.

> * `M2Crypto`
>
Optional, but recommended.

**Comment by crazyscientist** [comment]
>  `M2Crypto`

Given the fact the OBS API is only accessible via HTTPS, M2Crypto has to be considered a requirement!

**Comment by marcus-h** [comment]
On 2020-02-13 06:18:37 -0800, Andreas Hasenkopf wrote:
> >  `M2Crypto`
>
> Given the fact the OBS API is only accessible via HTTPS, M2Crypto has to be considered a requirement!
>
Hmm well... you can setup your own OBS instance (for instance, for testing
purposes) that supports only http. Of course, for the sake of "security",
https is recommended (but not required:) ).

**Comment by crazyscientist** [comment]
> Hmm well... you can setup your own OBS instance (for instance, for testing
purposes) that supports only http. Of course, for the sake of "security",
https is recommended (but not required:) ).

@marcus-h Let's consider this a very hypothetical scenario. As Python packages can only list required packages, not recommended ones, I consider having M2Crypto installed automatically a good thing. Even the RPM package lists it as a requirement :wink:

**Comment by nickbroon** [comment]
setup.py appears to be used as part of the debian/ubuntu package build:
https://build.opensuse.org/package/live_build_log/openSUSE:Tools/osc/xUbuntu_19.10/x86_64

So having `install_requires` populated in setup.py would be useful. This would allow the debian packaging auto-populate the `python3:Depends` in https://build.opensuse.org/package/view_file/openSUSE:Tools/osc/debian.control?expand=1

**Comment by nickbroon** [comment]
regarding m2crypto I believe this is optional (though see #743 for where it might not be fully optionally)
https://build.opensuse.org/request/show/772679 was merged recently specifically regarding this, so that osc could be installed on older debian/ubuntu releases.

**Comment by Conan-Kudo** [comment]
Same is true in the rpm side, as there's a dependency generator for that now.

**Comment by crazyscientist** [comment]
> regarding m2crypto I believe this is optional (though see #743 for where it might not be fully optionally)
> https://build.opensuse.org/request/show/772679 was merged recently specifically regarding this, so that osc could be installed on older debian/ubuntu releases.

As a xUbuntu 18.04 user I kindly like to point out a few things:

* the public openSUSE OBS instance as well as the internal SUSE OBS instance **require** SSL encryption. No encryption, no joy.
* What's the point in having a piece of client software installed with an optional requirement/dependency, when the server side enforces the use of this dependency?

**Conclusion** If the current xUbuntu repos do not supply M2Crypto, it should be backported or osc should continue to rely in Python2 until this requirement can be met. Otherwise the DEB package will be no help at all for Ubuntu users.

**Comment by lethliel** [comment]
@crazyscientist You are right. And setting sslcertck=0 could be considered a security issue. 

I have opened a bug for bionic backports to backport python3-m2crypto from focal. 
https://bugs.launchpad.net/bionic-backports/+bug/1863863

**Comment by nickbroon** [comment]
Good point. So while from technical perspective M2Crypto is optional, as client does not strictly require it if the server supports non ssl connections (or `sslcertck`=0 is used), given that single most commonly used server uses ssl (and rightly most people will not want to use `sslcertck=0`) it's probably reasonable to want to have python3-m2crypto available. Getting backported to 1804 would great (and I notice that debian 10 already has a backport).
