### ISSUE TITLE
Regression: osc chroot --wipe does not work with --root

### ISSUE THREAD

**Issue by nickbroon** [openSUSE/osc#709]
```
~$ cd ~
~$ osc chroot --wipe --root=/var/lib/jenkins/workspace/job/build-root/project-standard-x86_64
Error: '/home/user' is not an osc project dir or working copy
```

**Comment by nickbroon** [comment]
See also #706 for related issue when using --force

**Comment by lethliel** [comment]
@nickbroon Are you issuing this command outside the package directory? 

When I use it inside an package working copy it just works fine. 
If I use it outside I get:
`Missing argument: build description (for example a spec, dsc or kiwi file)`

**Comment by nickbroon** [comment]
Yes, It's being used from a user home directory, that is not a package working copy.

**Comment by lethliel** [comment]
You are right. This is a regression. I am working on the fix at the moment.

**Comment by nickbroon** [comment]
Fab, thanks. I watch for a new release with this fix appearing in openSUSE:Tools on OBS.

**Comment by nickbroon** [comment]
@lethliel Did you get a chance to publish a new version to https://build.opensuse.org/package/show/openSUSE:Tools/osc ?

**Comment by lethliel** [comment]
I will release a new version today. But it also needs the new version of the build script to work. But that will be released today as well.
