### ISSUE TITLE
osc shell ignores --no-init

### ISSUE THREAD

**Issue by andreas-schwab** [openSUSE/osc#711]
$ osc shell --no-init r riscv64
Building llvm10.spec for r/riscv64
Use local '/space/osc/home:Andreas_Schwab:Factory/llvm10/.osc/_buildinfo-r-riscv64.xml' file as buildinfo
Use local '/space/osc/home:Andreas_Schwab:Factory/llvm10/.osc/_buildconfig-r-riscv64' file as buildconfig
Updating cache of required packages
4.7% cache miss. 162/170 dependencies cached.

Missing '/var/tmp/schwab/osbuild-packagecache/home:Andreas_Schwab:Factory/r/riscv64/glibc-2.30-2034.1.riscv64.rpm' in cache: --offline not possible.

**Comment by lethliel** [comment]
fixed with https://github.com/openSUSE/osc/pull/710
