### ISSUE TITLE
.osc/_files contains weird values for revision and srcmd5

### ISSUE THREAD

**Issue by dcermak** [openSUSE/osc#714]
I have been trying to read in checked out packages, but I am currently struggling to understand where osc takes the values for `rev` and `srcmd5` in the xml file `.osc/_files`? The file looks more or less like the file list as returned by the OBS API via `GET /source/<project>/<package>`, however that API call results in completely different values for `rev` and `srcmd5`.

For example:
``` ShellSession
$ osc co devel:libraries:c_c++/notmuch
$ cd devel\:libraries\:c_c++/notmuch/
$ head -1 .osc/_files
<directory name="notmuch" rev="f09e79714356e8e29f4802de8f723a2c" srcmd5="f09e79714356e8e29f4802de8f723a2c">
```

On the other hand:
``` ShellSession
$ curl --user $OBS_USERNAME:$OBS_PASSWORD 'https://api.opensuse.org/source/devel:libraries:c_c++/notmuch'
<directory name="notmuch" rev="52" vrev="55" srcmd5="eabaae50ec84ed2f3e8ee2dac292a390">
```

Where does osc get the `srcmd5` value from and why is it equal to the revision?

**Comment by marcus-h** [comment]
On 2020-01-07 07:06:16 -0800, Dan Čermák wrote:
> I have been trying to read in checked out packages, but I am currently struggling to understand where osc takes the values for `rev` and `srcmd5` in the xml file `.osc/_files`? The file looks more or less like the file list as returned by the OBS API via `GET /source/<project>/<package>`, however that API call results in completely different values for `rev` and `srcmd5`.
>
Yep, in essence, it is the result of the /source/project/package?query route.
The devel:libraries:c_c++/notmuch is a _link. In this case, we have to
distinguish between expanded and unexpanded sources (for a very brief
overview, [1] might be helpful).

> For example:
> ``` ShellSession
> $ osc co devel:libraries:c_c++/notmuch
> $ cd devel\:libraries\:c_c++/notmuch/
> $ head -1 .osc/_files
> <directory name="notmuch" rev="f09e79714356e8e29f4802de8f723a2c" srcmd5="f09e79714356e8e29f4802de8f723a2c">
> ```
>
These are "the"/some expanded sources.

> On the other hand:
> ``` ShellSession
> $ curl --user $OBS_USERNAME:$OBS_PASSWORD 'https://api.opensuse.org/source/devel:libraries:c_c++/notmuch'
> <directory name="notmuch" rev="52" vrev="55" srcmd5="eabaae50ec84ed2f3e8ee2dac292a390">
> ```
>
These are the unexpanded sources. The xsrcmd5 attribute in the linkinfo element
represents "the" expanded sources.

Example:

```
marcus@linux:~> curl -u Marcus_H https://api.opensuse.org/source/devel:libraries:c_c++/notmuch
Enter host password for user 'Marcus_H':
<directory name="notmuch" rev="54" vrev="57" srcmd5="230b02edd1c26728721ae0b03d5b5283">
  <linkinfo project="openSUSE:Factory" package="notmuch" srcmd5="9e47261dc1fd93ce2744131619671fbc" baserev="9e47261dc1fd93ce2744131619671fbc" xsrcmd5="f516416f687b247b04d3c313a5b70e6c" lsrcmd5="230b02edd1c26728721ae0b03d5b5283"/>
  <entry name="_link" md5="c69b492d162910ea13be95b90b21d675" size="124" mtime="1578437805"/>
  <entry name="database-v1.tar.xz" md5="934228459565fbd7956a2eb2d0f64c53" size="204876" mtime="1551092319"/>

  ...

</directory>
marcus@linux:~> curl -u Marcus_H https://api.opensuse.org/source/devel:libraries:c_c++/notmuch?rev=f516416f687b247b04d3c313a5b70e6c
Enter host password for user 'Marcus_H':
<directory name="notmuch" rev="f516416f687b247b04d3c313a5b70e6c" srcmd5="f516416f687b247b04d3c313a5b70e6c">
  <linkinfo project="openSUSE:Factory" package="notmuch" srcmd5="9e47261dc1fd93ce2744131619671fbc" baserev="9e47261dc1fd93ce2744131619671fbc" lsrcmd5="230b02edd1c26728721ae0b03d5b5283"/>
  <entry name="database-v1.tar.xz" md5="934228459565fbd7956a2eb2d0f64c53" size="204876" mtime="1551092319"/>

  ...

</directory>
marcus@linux:~> curl -u Marcus_H https://api.opensuse.org/source/devel:libraries:c_c++/notmuch?expand=1
Enter host password for user 'Marcus_H':
<directory name="notmuch" rev="f516416f687b247b04d3c313a5b70e6c" vrev="59" srcmd5="f516416f687b247b04d3c313a5b70e6c">
  <linkinfo project="openSUSE:Factory" package="notmuch" srcmd5="9e47261dc1fd93ce2744131619671fbc" baserev="9e47261dc1fd93ce2744131619671fbc" lsrcmd5="230b02edd1c26728721ae0b03d5b5283"/>
  <entry name="database-v1.tar.xz" md5="934228459565fbd7956a2eb2d0f64c53" size="204876" mtime="1551092319"/>

  ...

</directory>
marcus@linux:~>
```

**Comment by marcus-h** [comment]
On 2020-01-08 14:18:29 +0100, Marcus Hüwe wrote:
> On 2020-01-07 07:06:16 -0800, Dan Čermák wrote:
> > I have been trying to read in checked out packages, but I am currently struggling to understand where osc takes the values for `rev` and `srcmd5` in the xml file `.osc/_files`? The file looks more or less like the file list as returned by the OBS API via `GET /source/<project>/<package>`, however that API call results in completely different values for `rev` and `srcmd5`.
> >
> Yep, in essence, it is the result of the /source/project/package?query route.
> The devel:libraries:c_c++/notmuch is a _link. In this case, we have to
> distinguish between expanded and unexpanded sources (for a very brief
> overview, [1] might be helpful).
>

Arghs... here's the missing reference.

[1] https://github.com/openSUSE/osc/issues/468#issuecomment-439895612

**Comment by dcermak** [comment]
Marcus Hüwe <notifications@github.com> writes:

> On 2020-01-07 07:06:16 -0800, Dan Čermák wrote:
>> I have been trying to read in checked out packages, but I am currently struggling to understand where osc takes the values for `rev` and `srcmd5` in the xml file `.osc/_files`? The file looks more or less like the file list as returned by the OBS API via `GET /source/<project>/<package>`, however that API call results in completely different values for `rev` and `srcmd5`.
>>
> Yep, in essence, it is the result of the /source/project/package?query route.
> The devel:libraries:c_c++/notmuch is a _link. In this case, we have to
> distinguish between expanded and unexpanded sources (for a very brief
> overview, [1] might be helpful).

So essentially osc fetches the list of files with the parameter
`expand=1` so that any _link files are not present in the checked out
directory?

And you obtain the number of the checked out state from the lsrcmd5
entry in the <linkinfo>?

**Comment by marcus-h** [comment]
On 2020-01-08 06:42:42 -0800, Dan Čermák wrote:
> Marcus Hüwe <notifications@github.com> writes:
> > On 2020-01-07 07:06:16 -0800, Dan Čermák wrote:
> >> I have been trying to read in checked out packages, but I am currently struggling to understand where osc takes the values for `rev` and `srcmd5` in the xml file `.osc/_files`? The file looks more or less like the file list as returned by the OBS API via `GET /source/<project>/<package>`, however that API call results in completely different values for `rev` and `srcmd5`.
> >>
> > Yep, in essence, it is the result of the /source/project/package?query route.
> > The devel:libraries:c_c++/notmuch is a _link. In this case, we have to
> > distinguish between expanded and unexpanded sources (for a very brief
> > overview, [1] might be helpful).
>
> So essentially osc fetches the list of files with the parameter
> `expand=1` so that any _link files are not present in the checked out
> directory?
>
It depends if you request the expanded or unexpanded sources (for instance,
"osc up -e" vs. "osc up -u"). (expand=1 is only used if the user wants to
checkout the server-side generated _service files.)

> And you obtain the number of the checked out state from the lsrcmd5
> entry in the <linkinfo>?
>
Hmm which number?

**Comment by dcermak** [comment]
Marcus Hüwe <notifications@github.com> writes:

> On 2020-01-08 06:42:42 -0800, Dan Čermák wrote:
>> Marcus Hüwe <notifications@github.com> writes:
>> > On 2020-01-07 07:06:16 -0800, Dan Čermák wrote:
>> >> I have been trying to read in checked out packages, but I am currently struggling to understand where osc takes the values for `rev` and `srcmd5` in the xml file `.osc/_files`? The file looks more or less like the file list as returned by the OBS API via `GET /source/<project>/<package>`, however that API call results in completely different values for `rev` and `srcmd5`.
>> >>
>> > Yep, in essence, it is the result of the /source/project/package?query route.
>> > The devel:libraries:c_c++/notmuch is a _link. In this case, we have to
>> > distinguish between expanded and unexpanded sources (for a very brief
>> > overview, [1] might be helpful).
>>
>> So essentially osc fetches the list of files with the parameter
>> `expand=1` so that any _link files are not present in the checked out
>> directory?
>>
> It depends if you request the expanded or unexpanded sources (for instance,
> "osc up -e" vs. "osc up -u"). (expand=1 is only used if the user wants to
> checkout the server-side generated _service files.)

Ah, I see. Judging from the docs of `osc co` expand link is the default,
is that the same for `osc up`?

>
>> And you obtain the number of the checked out state from the lsrcmd5
>> entry in the <linkinfo>?
>>
> Hmm which number?

The revision number (e.g. r45 and not the md5hash).

**Comment by dmach** [comment]
There doesn't seem to be any change in osc needed, closing.
Please reopen or let me know if you think otherwise.
