### ISSUE TITLE
osc cat [FAILS to 'cat' uploaded file whilst running service]

### ISSUE THREAD

**Issue by byteduty** [openSUSE/osc#722]
osc cat <PROJECT> <PACKAGE> _service

Returns the following whilst the service is running:

$ osc cat Project package _service
Server returned an error: HTTP Error 400: service in progress
service in progress

I don't think this makes any sense, as the _service is an uploaded file, not a file generated from the service run. As a consequence, if you need to query a file, you need to cache your request till after the service has completed.

**Comment by adrianschroeter** [comment]
On Donnerstag, 16. Januar 2020, 14:23:43 CET Colin Docherty wrote:
> osc cat <PROJECT> <PACKAGE> _service
> 
> Returns the following whilst the service is running:
> 
> $ osc cat Project package _service
> Server returned an error: HTTP Error 400: service in progress
> service in progress
> 
> I don't think this makes any sense, as the _service is an uploaded file, not a file generated from the service run. As a consequence, if you need to query a file, you need to cache your request till after the service has completed.

well, you can always request unexpanded sources so it would never give you that error.

osc cat -u ....



-- 

Adrian Schroeter <adrian@suse.de>
Build Infrastructure Project Manager

SUSE Software Solutions Germany GmbH,  Maxfeldstr. 5, 90409 Nuernberg, Germany
(HRB 247165, AG München), Geschäftsführer: Felix Imendörffer

**Comment by byteduty** [comment]
> On Donnerstag, 16. Januar 2020, 14:23:43 CET Colin Docherty wrote: osc cat <PROJECT> <PACKAGE> _service Returns the following whilst the service is running: $ osc cat Project package _service Server returned an error: HTTP Error 400: service in progress service in progress I don't think this makes any sense, as the _service is an uploaded file, not a file generated from the service run. As a consequence, if you need to query a file, you need to cache your request till after the service has completed.
> well, you can always request unexpanded sources so it would never give you that error. osc cat -u ....
> […](#)

This might be sufficient to get me round my current problem, although it still doesn't address the fact that I don't think it makes sense for uploaded files like _service.

Mind you maybe the _service and _contraints files should be more integrated into the project, ad have their own REST API a bit like the prj or conf META presently as their kind of special cases.

**Comment by adrianschroeter** [comment]
On Donnerstag, 16. Januar 2020, 15:06:12 CET Colin Docherty wrote:
> > On Donnerstag, 16. Januar 2020, 14:23:43 CET Colin Docherty wrote: osc cat <PROJECT> <PACKAGE> _service Returns the following whilst the service is running: $ osc cat Project package _service Server returned an error: HTTP Error 400: service in progress service in progress I don't think this makes any sense, as the _service is an uploaded file, not a file generated from the service run. As a consequence, if you need to query a file, you need to cache your request till after the service has completed.
> > well, you can always request unexpanded sources so it would never give you that error. osc cat -u ....
> > […](#)
> 
> This might be sufficient to get me round my current problem, although it still doesn't address the fact that I don't think it makes sense for uploaded files like _service.
> 
> Mind you maybe the _service and _contraints files should be more integrated into the project, ad have their own REST API a bit like the prj or conf META presently as their kind of special cases.

you can have modified _service files in your branch. Or the target of the branch has
modified it in between.

So you need to merge it to see the actual result.

one could extend the api to support a ignore-all-service-result-files .... but that would
be kind of a special feature.

-- 

Adrian Schroeter <adrian@suse.de>
Build Infrastructure Project Manager

SUSE Software Solutions Germany GmbH,  Maxfeldstr. 5, 90409 Nuernberg, Germany
(HRB 247165, AG München), Geschäftsführer: Felix Imendörffer

**Comment by dmach** [comment]
#1306 mitigates the problem by retrying on receiving 400 HTTP status code.
