### ISSUE TITLE
'osc build --vm-type=qemu' fails by default if host has > 8 cores on aarch64

### ISSUE THREAD

**Issue by bubbleguuum** [openSUSE/osc#728]
osc version: 0.167.2

qemu aarch64 can handle a maximum of 8 cores.

On a host with more cores than 8, qemu will fail to launch with error below.
It can be trivially fixed by passing '-j 8' to build argument or 'setting build-jobs = 8' in oscrc (however the latter that will apply to all builds).

The fix for this error was not immediately obvious to me and osc could be a bit smarter about it and use a maximum of 8 cores to pass to qemu (-smp option)

///////////////////

$osc build --vm-type=qemu openSUSE_Factory_ARM aarch64
...
[    1s] setting hostarch to aarch64
[    1s] booting qemu...
[    1s] /usr/bin/qemu-system-aarch64 -nodefaults -no-reboot -nographic -vga none -cpu cortex-a72 -M virt -object rng-random,filename=/dev/hwrng,id=rng0 -device virtio-rng-device,rng=rng0 -runas qemu -net none -kernel /home/bobbie/tmp/build-root/openSUSE_Factory_ARM-aarch64/.mount/boot/kernel -initrd /home/bobbie/tmp/build-root/openSUSE_Factory_ARM-aarch64/.mount/boot/initrd -append root=/dev/disk/by-id/virtio-0 rootfstype=ext4 rootflags=noatime ext4.allow_unsupported=1 kpti=off pti=off spectre_v2=off panic=1 quiet no-kvmclock elevator=noop nmi_watchdog=0 rw rd.driver.pre=binfmt_misc console=ttyAMA0 init=/.build/build -m 512 -drive file=/home/bobbie/tmp/build-root/openSUSE_Factory_ARM-aarch64/img,format=raw,if=none,id=disk,cache=unsafe -device virtio-blk-device,drive=disk,serial=0 -drive file=/home/bobbie/tmp/build-root/openSUSE_Factory_ARM-aarch64/swap,format=raw,if=none,id=swap,cache=unsafe -device virtio-blk-device,drive=swap,serial=1 -serial stdio -chardev socket,id=monitor,server,nowait,path=/home/bobbie/tmp/build-root/openSUSE_Factory_ARM-aarch64/img.qemu/monitor -mon chardev=monitor,mode=readline -smp 12
[    1s] qemu-system-aarch64: Number of SMP CPUs requested (12) exceeds max CPUs supported by machine 'mach-virt' (8)
[    1s] No buildstatus set, either the base system is broken (kernel/initrd/udev/glibc/bash/perl)
[    1s] or the build host has a kernel or hardware problem...

**Comment by ggardet** [comment]
You can use `-j 8` to use only 8 cores.

**Comment by lethliel** [comment]
as @ggardet already stated this can be fixed by adding -j <max_cores>
