### ISSUE TITLE
Glob-based "trust packages from foo project"

### ISSUE THREAD

**Issue by mcepl** [openSUSE/osc#730]
I maintain all Python packages, so I have tendency to branch from many different projects. And in every other project when building the package I am confronted with this dialogue:
```
The build root needs packages from project 'devel:kubic'.
Note that malicious packages can compromise the build result or even your system.
Would you like to ...
0 - quit (default)
1 - always trust packages from 'devel:kubic'
2 - trust packages just this time
?
```
And neither choice is much appealing to me. Of course, I need the package to be built, so ``0`` is out of the window. Always trusting packages from that project just leads to bizarrely large section in ``~/.config/osc/oscrc``. So, I usually press ``2``, but it gets quite old after the fifth attempt to build the package.

Could we get this option package-wide only, so that whenever I build this particular package, I get all packages from that project, but this choice would be written in the local ``.osc/`` file, not the system-wide?

What do you think?

**Comment by Conan-Kudo** [comment]
This would be great for me too! It's a pain when I do similar things across Factory or internal projects.

**Comment by adrianschroeter** [comment]
the security issue does not depend on the package you build, but the binaries you download. They can change at any time.

You need to use kvm for a secure build in dependend of the binaries, if that is what you want.

**Comment by mcepl** [comment]
OK, so @adrianschroeter claims it is nonsense, and he is mostly like right. Just have a giant `~/.config/osc/oscrc`.

**Comment by mcepl** [comment]
Actually, after a lot of thinking, I believe what I need is not limiting trust to one package, but just the contrary: could I get some kind of glob parsing, so I can trust more? Let’s say I am willing to trust ``openSUSE:*`` or ``devel:languages:*`` projects. Would it be possible?

**Comment by dmach** [comment]
The requested feature sounds reasonable to me.
@lethliel mind if I steal this issue from you?
