### ISSUE TITLE
osc api command without arguments throws traceback

### ISSUE THREAD

**Issue by mimi1vx** [openSUSE/osc#735]
```
~/g/mtui ❯❯❯ osc api                                                                                   ✘ 130 comment ✭
Traceback (most recent call last):
  File "/usr/bin/osc", line 41, in <module>
    r = babysitter.run(osccli)
  File "/usr/lib/python3.7/site-packages/osc/babysitter.py", line 62, in run
    return prg.main(argv)
  File "/usr/lib/python3.7/site-packages/osc/cmdln.py", line 344, in main
    return self.cmd(args)
  File "/usr/lib/python3.7/site-packages/osc/cmdln.py", line 367, in cmd
    retval = self.onecmd(argv)
  File "/usr/lib/python3.7/site-packages/osc/cmdln.py", line 501, in onecmd
    return self._dispatch_cmd(handler, argv)
  File "/usr/lib/python3.7/site-packages/osc/cmdln.py", line 1232, in _dispatch_cmd
    return handler(argv[0], opts, *args)
TypeError: do_api() missing 1 required positional argument: 'url'
```

better will be help for api command

**Comment by marcus-h** [comment]
On 2020-02-07 03:18:34 -0800, Ondřej Súkup wrote:
> ```
> ~/g/mtui ❯❯❯ osc api                                                                                   ✘ 130 comment ✭
> Traceback (most recent call last):
>   File "/usr/bin/osc", line 41, in <module>
>     r = babysitter.run(osccli)
>   File "/usr/lib/python3.7/site-packages/osc/babysitter.py", line 62, in run
>     return prg.main(argv)
>   File "/usr/lib/python3.7/site-packages/osc/cmdln.py", line 344, in main
>     return self.cmd(args)
>   File "/usr/lib/python3.7/site-packages/osc/cmdln.py", line 367, in cmd
>     retval = self.onecmd(argv)
>   File "/usr/lib/python3.7/site-packages/osc/cmdln.py", line 501, in onecmd
>     return self._dispatch_cmd(handler, argv)
>   File "/usr/lib/python3.7/site-packages/osc/cmdln.py", line 1232, in _dispatch_cmd
>     return handler(argv[0], opts, *args)
> TypeError: do_api() missing 1 required positional argument: 'url'
> ```
>
> better will be help for api command
>
Hmm yes, _INCORRECT_NUM_ARGS_RE in cmdln.py does not take the python3
error message(s) into account.
