### ISSUE TITLE
IncompleteRead(0 bytes read)

### ISSUE THREAD

**Issue by ignatenkobrain** [openSUSE/osc#742]
This is happening on Fedora Rawhide (33):

```
~/Projects/home:ignatenkobrain:rust 
✦ ❯ osc up
/usr/lib/python3.8/site-packages/osc/core.py:1453: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if r is not 0:
IncompleteRead(0 bytes read)
```

I've tried to debug it a bit and found that the problem is happening around `if options['sslcertck']` in osc/conf.py.

When I removed that part of condition which checks SSL things, everything started to work just fine.

* `osc-0.167.1-281.1.4.fc32.noarch`
* `python3-3.8.2~rc1-1.fc33.x86_64`

**Comment by lethliel** [comment]
Thanks for the report. I will look into it.

**Comment by lethliel** [comment]
Seems to be related to the size of the project (packages count) and if sslcertck is 1: 

This works with sslcertck=1(package count 11):

```
osc api /source/home:mstrigl
<directory count="11">
  <entry name="build"/>
  <entry name="glibmm2"/>
  <entry name="helloSUSE"/>
  <entry name="hellooSC2"/>
  <entry name="hellooSC_docker"/>
  <entry name="mediagoblin"/>
  <entry name="osc"/>
  <entry name="osc-py2"/>
  <entry name="product-builder"/>
  <entry name="test"/>
  <entry name="test-osc"/>
</directory>
```

This works not with sslcertck=1 (package count=274):

```
osc -d api /source/home:ignatenkobrain:rust
GET https://api.opensuse.org/source/home:ignatenkobrain:rust
IncompleteRead(0 bytes read)
```

If I disable sslcertck in the api section it works: 

```
[https://api.opensuse.org]
sslcertck=0
```

```
<directory count="274">
  <entry name="rust-adler32"/>
  <entry name="rust-aho-corasick"/>
  <entry name="rust-ansi_term"/>
  <entry name="rust-approx"/>
  <entry name="rust-arc-swap"/>
  <entry name="rust-arrayref"/>
  <entry name="rust-arrayvec"/>
  <entry name="rust-atty"/>
...

```

**Comment by lethliel** [comment]
The error is raised in http/client.py in function:

```
def _safe_readinto(self, b):
        """Same as _safe_read, but for reading into a buffer."""
        amt = len(b)
        n = self.fp.readinto(b)
        if n < amt:
            raise IncompleteRead(bytes(b[:n]), amt-n)
        return n
```

because amt = 8192 (size of buffer), but n = is 7202. So he did not read the complete buffer.
But until now I have no clue how this can happen. 

This is gonna be fun. Will investigate further.

**Comment by marcus-h** [comment]
On 2020-02-18 02:10:58 -0800, Marco Strigl wrote:
> The error is raised in http/client.py in function:
>
> ```
> def _safe_readinto(self, b):
>         """Same as _safe_read, but for reading into a buffer."""
>         amt = len(b)
>         n = self.fp.readinto(b)
>         if n < amt:
>             raise IncompleteRead(bytes(b[:n]), amt-n)
>         return n
> ```
>
> because amt = 8192 (size of buffer), but n = is 7202. So he did not read the complete buffer.
> But until now I have no clue how this can happen.
>
> This is gonna be fun. Will investigate further.
>
Assumption: we are talking about python3.8 (hard to tell without a
traceback:) )
From a very quick glance this seems to be an issue with m2crypto. python3.8
"expects"/assumes that fp is wrapped into a BufferedReader (or any other reader
that reads _exact_ amt bytes).
self.fp is a obtained by invoking SSL.Connection.makefile, which returns
a socket.SocketIO, which does no buffering. Wrapping this in a
io.BufferedReader should do the trick.
The attached m2crypto patch should fix this (completely UNTESTED, though).

```
diff --git a/M2Crypto/SSL/Connection.py b/M2Crypto/SSL/Connection.py
index 7053aa6..e24003a 100644
--- a/M2Crypto/SSL/Connection.py
+++ b/M2Crypto/SSL/Connection.py
@@ -12,6 +12,7 @@ Copyright 2008 Heikki Toivonen. All rights reserved.

 import logging
 import socket
+import io

 from M2Crypto import BIO, Err, X509, m2, py27plus, six, util  # noqa
 from M2Crypto.SSL import Checker, Context, timeout  # noqa
@@ -584,7 +585,8 @@ class Connection(object):
     def makefile(self, mode='rb', bufsize=-1):
         # type: (AnyStr, int) -> socket._fileobject
         if six.PY3:
-            return socket.SocketIO(self, mode)
+            return io.BufferedReader(socket.SocketIO(self, mode),
+                                     io.DEFAULT_BUFFER_SIZE)
         else:
             return socket._fileobject(self, mode, bufsize)

```

**Comment by lethliel** [comment]
Yes. It is python 3.8. And your patch worked. Thanks. 
I submitted a PR to M2Crypto. (https://gitlab.com/m2crypto/m2crypto/-/merge_requests/242)

**Comment by lethliel** [comment]
Had to use this: 

```
if six.PY3:
    raw = socket.SocketIO(self, mode)
    if 'rw' in mode:
        return io.BufferedRWPair(raw, raw)
    return io.BufferedReader(raw, io.DEFAULT_BUFFER_SIZE)
```

Otherwise SocketIO with mode rw would fail.

**Comment by lethliel** [comment]
fixed in python-M2Crypto now.
