### ISSUE TITLE
[python3.8] Testsuite fails

### ISSUE THREAD

**Issue by lethliel** [openSUSE/osc#751]
The testsuite for python 3.8 fails. From the first quick glance there are three reasons:

* encoding issues when opening exp_file in __mock_PUT
* order problem of XML attributes using ET.

[osc_python38_testsuite_fail.log](https://github.com/openSUSE/osc/files/4229531/osc_python38_testsuite_fail.log)

But I have to take a closer look.

**Comment by OlegGirko** [comment]
Fedora 32 with Python 3.8 has been already released, so solving this issue becomes quite urgent.
Any ideas how to fix it?

**Comment by marcus-h** [comment]
On 2020-05-17 13:44:00 -0700, Oleg Girko wrote:
> Fedora 32 with Python 3.8 has been already released, so solving this issue becomes quite urgent.
> Any ideas how to fix it?
>
Yes, at least some ideas for workarounds. I'll come up with a patch within
the next few days.

**Comment by OlegGirko** [comment]
@marcus-h: Thank you! I'll be waiting for new release with this change included.
