### ISSUE TITLE
zst detection fails

### ISSUE THREAD

**Issue by houz** [openSUSE/osc#756]
The magic number check in https://github.com/openSUSE/osc/blob/master/osc/util/packagequery.py#L76 is wrong. The ZST part should be `magic[:4] == b'\x28\xb5\x2f\xfd'`.

See https://tools.ietf.org/html/rfc8478#section-3.1.1 for reference.

**Comment by marcus-h** [comment]
Fixed in commit 4e8e0492e8dc0aaf036794df2a5cc6dd53d91d49 ("Fix arch zst
magic in util.packagequery").

Thanks a lot!
