### ISSUE TITLE
exception storm during initial setup if kdewallet not set up yet

### ISSUE THREAD

**Issue by rindeal** [openSUSE/osc#757]
Steps to reproduce:

1. `$ rm -rf ~/.config/osc/ ~/.local/share/kwallet* ~/.config/kwallet*`
2. `$ osc`
3. kdewallet window pops up prompting you to set up a new wallet (keyring)
4. wait a minute or so
5. observe `osc` throwing exceptions

```plain
Creating osc configuration file /home/foo/.config/osc/oscrc ...
Username: foo
Password: 
1) chainer ChainerBackend (Backend provided by python-keyring)
2) fail Keyring (Backend provided by python-keyring)
3) kwallet DBusKeyring (Backend provided by python-keyring)
4) Config file credentials manager (Store the credentials in the config file (plain text))
5) Obfuscated Config file credentials manager (Store the credentials in the config file (obfuscated))
6) Transient password store (Do not store the password and always ask for the password)
Select credentials manager: 3
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/osc/commandline.py", line 145, in postoptparse
    override_verbose = self.options.verbose)
  File "/usr/lib/python3.7/site-packages/osc/conf.py", line 840, in get_config
    account_not_configured_text % conffile)
osc.oscerr.NoConfigfile

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/keyring/backends/kwallet.py", line 88, in connected
    self.iface.networkWallet(), wId, self.appid)
  File "/usr/lib/python3.7/site-packages/dbus/proxies.py", line 72, in __call__
    return self._proxy_method(*args, **keywords)
  File "/usr/lib/python3.7/site-packages/dbus/proxies.py", line 147, in __call__
    **keywords)
  File "/usr/lib/python3.7/site-packages/dbus/connection.py", line 653, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NoReply: Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/osc", line 41, in <module>
    r = babysitter.run(osccli)
  File "/usr/lib/python3.7/site-packages/osc/babysitter.py", line 62, in run
    return prg.main(argv)
  File "/usr/lib/python3.7/site-packages/osc/cmdln.py", line 336, in main
    self.postoptparse()
  File "/usr/lib/python3.7/site-packages/osc/commandline.py", line 152, in postoptparse
    conf.interactive_config_setup(e.file, apiurl)
  File "/usr/lib/python3.7/site-packages/osc/conf.py", line 1021, in interactive_config_setup
    write_initial_config(conffile, config, creds_mgr_descriptor=creds_mgr_descr)
  File "/usr/lib/python3.7/site-packages/osc/conf.py", line 769, in write_initial_config
    creds_mgr.set_password(config['apiurl'], config['user'], config['pass'])
  File "/usr/lib/python3.7/site-packages/osc/credentials.py", line 188, in set_password
    keyring.set_password(urlsplit(url)[1], user, password)
  File "/usr/lib/python3.7/site-packages/keyring/core.py", line 63, in set_password
    _keyring_backend.set_password(service_name, username, password)
  File "/usr/lib/python3.7/site-packages/keyring/backends/kwallet.py", line 112, in set_password
    if not self.connected(service):
  File "/usr/lib/python3.7/site-packages/keyring/backends/kwallet.py", line 90, in connected
    raise InitError('Failed to open keyring: %s.' % e)
keyring.errors.InitError: Failed to open keyring: org.freedesktop.DBus.Error.NoReply: Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken..
```

**Comment by marcus-h** [comment]
On 2020-02-28 15:16:23 -0800, Jan Chren wrote:
> Steps to reproduce:
>
> 1. `$ rm -rf ~/.config/osc/ ~/.local/share/kwallet* ~/.config/kwallet*`
> 2. `$ osc`
> 3. kdewallet window pops up prompting you to set up a new wallet (keyring)
> 4. wait a minute or so
> 5. observe `osc` to throw exceptions
>
> ```plain
> Creating osc configuration file /home/foo/.config/osc/oscrc ...
> Username: foo
> Password:
> 1) chainer ChainerBackend (Backend provided by python-keyring)
> 2) fail Keyring (Backend provided by python-keyring)
> 3) kwallet DBusKeyring (Backend provided by python-keyring)
> 4) Config file credentials manager (Store the credentials in the config file (plain text))
> 5) Obfuscated Config file credentials manager (Store the credentials in the config file (obfuscated))
> 6) Transient password store (Do not store the password and always ask for the password)
> Select credentials manager: 3
> Traceback (most recent call last):
>   File "/usr/lib/python3.7/site-packages/osc/commandline.py", line 145, in postoptparse
>     override_verbose = self.options.verbose)
>   File "/usr/lib/python3.7/site-packages/osc/conf.py", line 840, in get_config
>     account_not_configured_text % conffile)
> osc.oscerr.NoConfigfile
>

<SNIP>

> During handling of the above exception, another exception occurred:
>
> Traceback (most recent call last):
>   File "/usr/bin/osc", line 41, in <module>
>     r = babysitter.run(osccli)
>   File "/usr/lib/python3.7/site-packages/osc/babysitter.py", line 62, in run
>     return prg.main(argv)
>   File "/usr/lib/python3.7/site-packages/osc/cmdln.py", line 336, in main
>     self.postoptparse()
>   File "/usr/lib/python3.7/site-packages/osc/commandline.py", line 152, in postoptparse
>     conf.interactive_config_setup(e.file, apiurl)
>   File "/usr/lib/python3.7/site-packages/osc/conf.py", line 1021, in interactive_config_setup
>     write_initial_config(conffile, config, creds_mgr_descriptor=creds_mgr_descr)
>   File "/usr/lib/python3.7/site-packages/osc/conf.py", line 769, in write_initial_config
>     creds_mgr.set_password(config['apiurl'], config['user'], config['pass'])
>   File "/usr/lib/python3.7/site-packages/osc/credentials.py", line 188, in set_password
>     keyring.set_password(urlsplit(url)[1], user, password)
>   File "/usr/lib/python3.7/site-packages/keyring/core.py", line 63, in set_password
>     _keyring_backend.set_password(service_name, username, password)
>   File "/usr/lib/python3.7/site-packages/keyring/backends/kwallet.py", line 112, in set_password
>     if not self.connected(service):
>   File "/usr/lib/python3.7/site-packages/keyring/backends/kwallet.py", line 90, in connected
>     raise InitError('Failed to open keyring: %s.' % e)
> keyring.errors.InitError: Failed to open keyring: org.freedesktop.DBus.Error.NoReply: Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken..
> ```
Hmm there is not much we can do from the osc side about this (except
handling the exception more gracefully). Though, I'm not sure if the
plain error message is more helpful than the traceback in this case.

**Comment by rindeal** [comment]
> Hmm there is not much we can do from the osc side about this (except handling the exception more gracefully). Though, I'm not sure if the plain error message is more helpful than the traceback in this case.

That might certainly help, but I'm more in favour of fixing the underlying bug(s), which I suspect will be somewhere in the python-keyring's implementation of kwallet's DBus API or in kwallet's DBus API itself. This is more of a Level 1 report with the goal of forwarding it to appropriate places at your discretion.

**Comment by dmach** [comment]
Now it raises the following exception:
```
  File "/usr/lib/python3.10/site-packages/keyring/backends/kwallet.py", line 111, in get_password
    raise KeyringLocked("Failed to unlock the keyring!")
```
