### ISSUE TITLE
osc submitrequest should support multiple packages

### ISSUE THREAD

**Issue by JanZerebecki** [openSUSE/osc#772]
`osc submitrequest` should support multiple packages, like the api https://build.opensuse.org/apidocs/index#81 does.

Also document what it will do when it is called in a local project that only has some of its modified packages checked out.

**Comment by adrianschroeter** [comment]
it does, just submit the entire project and you will get a request where all modified packages are included.

You can also construct individual requests with multiple actions using

 # osc createrequest --help

**Comment by JanZerebecki** [comment]
createrequest is what I was looking for. Thank you. No idea how I missed it.
