### ISSUE TITLE
suggest correct m2crypto package when missing

### ISSUE THREAD

**Issue by jnweiger** [openSUSE/osc#774]
When running with old python2, the suggestion to install package 'python-m2crypto' was correct.
With modern python3 these days, the suggestion should be 'python3-m2crypto'
Also mention "pip3 install M2Crypto" as an alternative, when no such package is available. E.g. Ubuntu 18.04 and up only have python-m2crypto but no pyhton3-m2crypto

PR #773 fixes this.

**Comment by dmach** [comment]
We have decided not to fix this in the current code base, because we'll be moving away from m2crypto in https://github.com/openSUSE/osc/pull/1000 shortly.
