### ISSUE TITLE
Allow default ENV variables in .oscrc

### ISSUE THREAD

**Issue by marxin** [openSUSE/osc#777]
I always repeat the following steps:
```
$ osc chroot
$ export TERM=xterm
```

would it  be possible to always export desired ENV variables after chroot?

**Comment by marxin** [comment]
Quite simple workaround is:
`TERM=xterm osc chroot`

**Comment by dmach** [comment]
@marxin I find the described behavior ok.
`osc shell` inherits any exported or explicitly specified variables.
What exactly do you want to change?

**Comment by marxin** [comment]
The current behavior is sufficient as the env variables are inherited.
