### ISSUE TITLE
IncompleteRead(0 bytes read) on every action

### ISSUE THREAD

**Issue by norbusan** [openSUSE/osc#783]
After some days of perfectly working, suddenly I receive permanently `IncompleteRead(0 bytes read)` on every action.

This is with Debian/unstable, ocs 0.168.2

Running with full debugging I see (replacing some hex strings with HEXID, not sure which carries sensitive information):
```
$ osc --traceback --http-full-debug up


-- GET https://api.opensuse.org/source/home:npreining:debian-plasma
send: b'GET /source/home:npreining:debian-plasma HTTP/1.1\r\nAccept-Encoding: identity\r\nHost: api.opensuse.org\r\nUser-agent: osc/0.168.2\r\nCookie: openSUSE_session=<HEXID>\r\nConnection: close\r\n\r\n'
reply: 'HTTP/1.1 200 OK\r\n'
header: Date: Wed, 22 Apr 2020 08:34:27 GMT
header: Server: Apache/2.4.23 (Linux/SUSE)
header: Strict-Transport-Security: max-age=31536000
header: cache-control: max-age=0, private, must-revalidate
header: vary: Accept-Encoding
header: referrer-policy: strict-origin-when-cross-origin
header: x-permitted-cross-domain-policies: none
header: x-xss-protection: 1; mode=block
header: x-opensuse-runtimes: {"view":7.638589013367891,"db":12.455468298867345,"backend":0}
header: x-request-id: HEXID
header: x-opensuse-apiversion: 2.11~alpha.20200421T190532.c447e49ec8
header: x-download-options: noopen
header: x-frame-options: SAMEORIGIN
header: x-runtime: 0.056401
header: x-content-type-options: nosniff
header: x-powered-by: Phusion Passenger 6.0.4
header: etag: W/"HEXID"
header: status: 200 OK
header: content-type: application/xml; charset=utf-8
header: Connection: close
header: Transfer-Encoding: chunked
Traceback (most recent call last):
  File "/usr/lib/python3.8/http/client.py", line 593, in _readinto_chunked
    n = self._safe_readinto(temp_mvb)
  File "/usr/lib/python3.8/http/client.py", line 618, in _safe_readinto
    raise IncompleteRead(bytes(b[:n]), amt-n)
http.client.IncompleteRead: IncompleteRead(7201 bytes read, 576 more expected)
```

Is this something temporarily or is there an error on my side?

Thanks

Norbert

**Comment by marcus-h** [comment]
On 2020-04-22 01:36:42 -0700, Norbert Preining wrote:
> After some days of perfectly working, suddenly I receive permanently `IncompleteRead(0 bytes read)` on every action.
>
> This is with Debian/unstable, ocs 0.168.2
>
> Running with full debugging I see (replacing some hex strings with HEXID, not sure which carries sensitive information):

(osc --http-debug is mostly sufficient, which filters Authorization and
Cookie headers)

<SNIP>

> Is this something temporarily or is there an error on my side?
>
This is an m2crypto issue, which is already fixed [1].


[1] https://gitlab.com/m2crypto/m2crypto/-/merge_requests/242

**Comment by norbusan** [comment]
Great to hear, thanks a lot!

**Comment by norbusan** [comment]
Hi @marcus-h 
hmm, contemplating a bit I am surprised. python3-m2crypto on Debian is still at 0.31.0 from back then, and nothing has changed in the last week in Debian.

So something else must have triggered this, because it was working even today in the morning (Japan Standard Time), and during the day it stopped.

Can you imagine an explanation for that?

**Comment by marcus-h** [comment]
On 2020-04-22 03:06:45 -0700, Norbert Preining wrote:
> Hi @marcus-h
> hmm, contemplating a bit I am surprised. python3-m2crypto on Debian is still at 0.31.0 from back then, and nothing has changed in the last week in Debian.
>
The issue is a combination of an old python3-m2crypto (without the fix)
and python3.8.

> So something else must have triggered this, because it was working even today in the morning (Japan Standard Time), and during the day it stopped.
>
> Can you imagine an explanation for that?
>
The bug can only happen if the http response is chunked
("Transfer-Encoding: chunked"). Hence, not all API calls are affected.
More precisely, the bug only happens in case of a chunked response in
combination with a "short" read (we request more data than available,
the available data is returned, and since it is less than the requested
data, the IncompleteRead error is raised).
The reasons for a short read are manifold, for instance, a "slower"
internet connection, network "issues", more load on the API server
etc. (note: the short read itself is nothing to worry about - it is
just that the python3.8 http.client module expects that m2crypto
"handles" the short read).

**Comment by norbusan** [comment]
Thanks a lot!
I can confirm that applying the patch to the version in Debian (which is still 0.31) fixes the issue.

I have opened a [bug report](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=958496) and attached a debdiff to update the package in Debian.

Thanks again for your explanation, and patience, I am closing this issue now.
