### ISSUE TITLE
Support for building via systemd-nspawn?

### ISSUE THREAD

**Issue by dcermak** [openSUSE/osc#804]
Does osc support using systemd-nspawn to build packages? obs-build does: https://github.com/openSUSE/obs-build/blob/master/build-vm-nspawn, but I couldn't find any mention of nspawn in this repository.

**Comment by marcus-h** [comment]
On 2020-06-05 07:28:18 -0700, Dan Čermák wrote:
> Does osc support using systemd-nspawn to build packages? obs-build does: https://github.com/openSUSE/obs-build/blob/master/build-vm-nspawn, but I couldn't find any mention of nspawn in this repository.
>
You can specify it via the "--vm-type nspawn" config option.
osc build --vm-type nspawn ...

**Comment by dcermak** [comment]
Marcus Hüwe <notifications@github.com> writes:

> On 2020-06-05 07:28:18 -0700, Dan Čermák wrote:
>> Does osc support using systemd-nspawn to build packages? obs-build does: https://github.com/openSUSE/obs-build/blob/master/build-vm-nspawn, but I couldn't find any mention of nspawn in this repository.
>>
> You can specify it via the "--vm-type nspawn" config option.
> osc build --vm-type nspawn ...

That seems to work, but unfortunately the container never launches, I
keep getting the following error:
```
[    4s] booting nspawn...
[    4s] Invalid machine name: obsbuild..mount
```

**Comment by OlegGirko** [comment]
Hold on, I have a solution. Please stand by for a pull request.

**Comment by OlegGirko** [comment]
OK, PR created. See #867 for details.
