### ISSUE TITLE
OBS misses minimal UTF-8 locales for build

### ISSUE THREAD

**Issue by ItachiSan** [openSUSE/osc#806]
As in title.

## Situation
I use OBS for releasing a few ArchLinux packages.

## Problem
When building one of my packages (*telegram-desktop-dev*) I have an issue within the internal `bsdtar` call made from `makepkg`.
(There are other few small issues within the logs too)

## Expected
`makepkg` works as intended.

## Log
https://build.opensuse.org/package/live_build_log/home:ItachiSan:archlinux/telegram-desktop-dev/standard/x86_64

## Extra
Please let me know if I can provide any additional information for aiding in troubleshooting.

**Comment by marcus-h** [comment]
On 2020-06-08 10:37:18 -0700, Giovanni Santini wrote:
>
Hmm your description (subject line) is pretty sparse. If locales
are missing, then it is most likely an issue with the project config
(or maybe the buildrequires). This does not seem to be an osc issue.

**Comment by ItachiSan** [comment]
I agree the issue does not lie within `osc` *per se*, but with the chroots used from the `build` command.
I am however not sure where to report it though, I thought here was the correct place.

**Comment by lethliel** [comment]
@ItachiSan Try the build service mailing list.
