### ISSUE TITLE
Updating a previously branched and deleted package results in a backtrace

### ISSUE THREAD

**Issue by dcermak** [openSUSE/osc#807]
I have run into the following issue:
I have branched `utilities/jtc` and played around with it locally, maybe even making a commit (can't remember honestly). Then I deleted the branched project `home:dancermak:branches:utilities` and branched `utilities/jtc` again. Running `osc up` in the previously checked out copy resultis in the following backtrace:
``` ShellSession
dan@Boreas > osc up
Updating jtc
A    jtc/_link
U    jtc/jtc.changes
Traceback (most recent call last):
  File "/usr/bin/osc", line 41, in <module>
    r = babysitter.run(osccli)
  File "/usr/lib/python3.8/site-packages/osc/babysitter.py", line 64, in run
    return prg.main(argv)
  File "/usr/lib/python3.8/site-packages/osc/cmdln.py", line 347, in main
    return self.cmd(args)
  File "/usr/lib/python3.8/site-packages/osc/cmdln.py", line 370, in cmd
    retval = self.onecmd(argv)
  File "/usr/lib/python3.8/site-packages/osc/cmdln.py", line 504, in onecmd
    return self._dispatch_cmd(handler, argv)
  File "/usr/lib/python3.8/site-packages/osc/cmdln.py", line 1235, in _dispatch_cmd
    return handler(argv[0], opts, *args)
  File "/usr/lib/python3.8/site-packages/osc/commandline.py", line 4973, in do_update
    prj.update(expand_link=opts.expand_link,
  File "/usr/lib/python3.8/site-packages/osc/core.py", line 971, in update
    p.update(rev, service_files)
  File "/usr/lib/python3.8/site-packages/osc/core.py", line 2352, in update
    self.__update(kept, added, deleted, services, fm, root.get('rev'))
  File "/usr/lib/python3.8/site-packages/osc/core.py", line 2393, in __update
    merge_status = self.mergefile(f.name, rev, f.mtime)
  File "/usr/lib/python3.8/site-packages/osc/core.py", line 1668, in mergefile
    upfilename = os.path.join(self.dir, n + '.r' + self.rev)
TypeError: can only concatenate str (not "NoneType") to str
```

**Comment by marcus-h** [comment]
On 2020-06-10 01:08:48 -0700, Dan Čermák wrote:
> Traceback (most recent call last):
>   File "/usr/bin/osc", line 41, in <module>
>     r = babysitter.run(osccli)
>   File "/usr/lib/python3.8/site-packages/osc/babysitter.py", line 64, in run
>     return prg.main(argv)
>   File "/usr/lib/python3.8/site-packages/osc/cmdln.py", line 347, in main
>     return self.cmd(args)
>   File "/usr/lib/python3.8/site-packages/osc/cmdln.py", line 370, in cmd
>     retval = self.onecmd(argv)
>   File "/usr/lib/python3.8/site-packages/osc/cmdln.py", line 504, in onecmd
>     return self._dispatch_cmd(handler, argv)
>   File "/usr/lib/python3.8/site-packages/osc/cmdln.py", line 1235, in _dispatch_cmd
>     return handler(argv[0], opts, *args)
>   File "/usr/lib/python3.8/site-packages/osc/commandline.py", line 4973, in do_update
>     prj.update(expand_link=opts.expand_link,
>   File "/usr/lib/python3.8/site-packages/osc/core.py", line 971, in update
>     p.update(rev, service_files)
>   File "/usr/lib/python3.8/site-packages/osc/core.py", line 2352, in update
>     self.__update(kept, added, deleted, services, fm, root.get('rev'))
>   File "/usr/lib/python3.8/site-packages/osc/core.py", line 2393, in __update
>     merge_status = self.mergefile(f.name, rev, f.mtime)
>   File "/usr/lib/python3.8/site-packages/osc/core.py", line 1668, in mergefile
>     upfilename = os.path.join(self.dir, n + '.r' + self.rev)
> TypeError: can only concatenate str (not "NoneType") to str
> ```
Hmm this looks fishy (self.rev seems to be None). Can you post the output
of
- cat .osc/_files
- cat .osc/_in_update/_files (if existing)

**Comment by dcermak** [comment]
Marcus Hüwe <notifications@github.com> writes:

> On 2020-06-10 01:08:48 -0700, Dan Čermák wrote:
>> Traceback (most recent call last):
>>   File "/usr/bin/osc", line 41, in <module>
>>     r = babysitter.run(osccli)
>>   File "/usr/lib/python3.8/site-packages/osc/babysitter.py", line 64, in run
>>     return prg.main(argv)
>>   File "/usr/lib/python3.8/site-packages/osc/cmdln.py", line 347, in main
>>     return self.cmd(args)
>>   File "/usr/lib/python3.8/site-packages/osc/cmdln.py", line 370, in cmd
>>     retval = self.onecmd(argv)
>>   File "/usr/lib/python3.8/site-packages/osc/cmdln.py", line 504, in onecmd
>>     return self._dispatch_cmd(handler, argv)
>>   File "/usr/lib/python3.8/site-packages/osc/cmdln.py", line 1235, in _dispatch_cmd
>>     return handler(argv[0], opts, *args)
>>   File "/usr/lib/python3.8/site-packages/osc/commandline.py", line 4973, in do_update
>>     prj.update(expand_link=opts.expand_link,
>>   File "/usr/lib/python3.8/site-packages/osc/core.py", line 971, in update
>>     p.update(rev, service_files)
>>   File "/usr/lib/python3.8/site-packages/osc/core.py", line 2352, in update
>>     self.__update(kept, added, deleted, services, fm, root.get('rev'))
>>   File "/usr/lib/python3.8/site-packages/osc/core.py", line 2393, in __update
>>     merge_status = self.mergefile(f.name, rev, f.mtime)
>>   File "/usr/lib/python3.8/site-packages/osc/core.py", line 1668, in mergefile
>>     upfilename = os.path.join(self.dir, n + '.r' + self.rev)
>> TypeError: can only concatenate str (not "NoneType") to str
>> ```
> Hmm this looks fishy (self.rev seems to be None). Can you post the output
> of
> - cat .osc/_files

$ cat jtc/.osc/_files
<directory name="jtc" srcmd5="c80453afcf97cc7312750d91c758b031">
  <entry name="jtc.spec" size="1802" md5="849a145326178dce1db188facb37a5b9" mtime="1590422915"/>
  <entry name="jtc.changes" size="6254" md5="07475f3a5da108af43541fecf811a6aa" mtime="1590422915"/>
  <entry name="jtc-1.76d.tar.gz" size="221123" md5="5bd9d920da1a6feb9ee441ac32043dbc" mtime="1589993283"/>
</directory>

> - cat .osc/_in_update/_files (if existing)

$ cat jtc/.osc/_in_update/_files
<directory name="jtc" rev="1" vrev="1" srcmd5="6e583406346b7de5937707917bae9f4a">
  <linkinfo project="utilities" package="jtc" srcmd5="5c42a7b49474bc618fc31fc9297821af" baserev="5c42a7b49474bc618fc31fc9297821af" xsrcmd5="1215042b526a050d4a875a123681c345" lsrcmd5="6e583406346b7de5937707917bae9f4a" />
  <entry name="_link" md5="389c088f2bb764bae574ac11d9b4a1c2" size="117" mtime="1590396656" />
  <entry name="jtc-1.76d.tar.gz" md5="5bd9d920da1a6feb9ee441ac32043dbc" size="221123" mtime="1589993283" />
  <entry name="jtc.changes" md5="55d57b3e429dc909dfd7a9ec2f01b7ec" size="6089" mtime="1589993284" />
  <entry name="jtc.spec" md5="0cf3115ce16b3e4799adfb88bc03f5dc" size="1772" mtime="1589993285" />
</directory>

The files don't exist in the .osc directory of the project though.

**Comment by marcus-h** [comment]
On 2020-06-10 01:41:01 -0700, Dan Čermák wrote:
> Marcus Hüwe <notifications@github.com> writes:
>
> > On 2020-06-10 01:08:48 -0700, Dan Čermák wrote:
> >> Traceback (most recent call last):
> >>   File "/usr/bin/osc", line 41, in <module>
> >>     r = babysitter.run(osccli)
> >>   File "/usr/lib/python3.8/site-packages/osc/babysitter.py", line 64, in run
> >>     return prg.main(argv)
> >>   File "/usr/lib/python3.8/site-packages/osc/cmdln.py", line 347, in main
> >>     return self.cmd(args)
> >>   File "/usr/lib/python3.8/site-packages/osc/cmdln.py", line 370, in cmd
> >>     retval = self.onecmd(argv)
> >>   File "/usr/lib/python3.8/site-packages/osc/cmdln.py", line 504, in onecmd
> >>     return self._dispatch_cmd(handler, argv)
> >>   File "/usr/lib/python3.8/site-packages/osc/cmdln.py", line 1235, in _dispatch_cmd
> >>     return handler(argv[0], opts, *args)
> >>   File "/usr/lib/python3.8/site-packages/osc/commandline.py", line 4973, in do_update
> >>     prj.update(expand_link=opts.expand_link,
> >>   File "/usr/lib/python3.8/site-packages/osc/core.py", line 971, in update
> >>     p.update(rev, service_files)
> >>   File "/usr/lib/python3.8/site-packages/osc/core.py", line 2352, in update
> >>     self.__update(kept, added, deleted, services, fm, root.get('rev'))
> >>   File "/usr/lib/python3.8/site-packages/osc/core.py", line 2393, in __update
> >>     merge_status = self.mergefile(f.name, rev, f.mtime)
> >>   File "/usr/lib/python3.8/site-packages/osc/core.py", line 1668, in mergefile
> >>     upfilename = os.path.join(self.dir, n + '.r' + self.rev)
> >> TypeError: can only concatenate str (not "NoneType") to str
> >> ```
> > Hmm this looks fishy (self.rev seems to be None). Can you post the output
> > of
> > - cat .osc/_files
>
> $ cat jtc/.osc/_files
> <directory name="jtc" srcmd5="c80453afcf97cc7312750d91c758b031">
>   <entry name="jtc.spec" size="1802" md5="849a145326178dce1db188facb37a5b9" mtime="1590422915"/>
>   <entry name="jtc.changes" size="6254" md5="07475f3a5da108af43541fecf811a6aa" mtime="1590422915"/>
>   <entry name="jtc-1.76d.tar.gz" size="221123" md5="5bd9d920da1a6feb9ee441ac32043dbc" mtime="1589993283"/>
> </directory>
>
The "rev" attribute is missing. Is it possible that you manually modified
this file? There are cases where the "rev" attribute can be omitted but
in this case it should be present. Also, a linkinfo element should be
present in case of a branch/link.

(Side note: the home:dancermak:branches:utilities project does not exist
anymore)

<SNIP>

> The files don't exist in the .osc directory of the project though.
>
Yes, that's expected.

**Comment by dcermak** [comment]
Marcus Hüwe <notifications@github.com> writes:

> On 2020-06-10 01:41:01 -0700, Dan Čermák wrote:
>> Marcus Hüwe <notifications@github.com> writes:
>>
>> > On 2020-06-10 01:08:48 -0700, Dan Čermák wrote:
>> >> Traceback (most recent call last):
>> >>   File "/usr/bin/osc", line 41, in <module>
>> >>     r = babysitter.run(osccli)
>> >>   File "/usr/lib/python3.8/site-packages/osc/babysitter.py", line 64, in run
>> >>     return prg.main(argv)
>> >>   File "/usr/lib/python3.8/site-packages/osc/cmdln.py", line 347, in main
>> >>     return self.cmd(args)
>> >>   File "/usr/lib/python3.8/site-packages/osc/cmdln.py", line 370, in cmd
>> >>     retval = self.onecmd(argv)
>> >>   File "/usr/lib/python3.8/site-packages/osc/cmdln.py", line 504, in onecmd
>> >>     return self._dispatch_cmd(handler, argv)
>> >>   File "/usr/lib/python3.8/site-packages/osc/cmdln.py", line 1235, in _dispatch_cmd
>> >>     return handler(argv[0], opts, *args)
>> >>   File "/usr/lib/python3.8/site-packages/osc/commandline.py", line 4973, in do_update
>> >>     prj.update(expand_link=opts.expand_link,
>> >>   File "/usr/lib/python3.8/site-packages/osc/core.py", line 971, in update
>> >>     p.update(rev, service_files)
>> >>   File "/usr/lib/python3.8/site-packages/osc/core.py", line 2352, in update
>> >>     self.__update(kept, added, deleted, services, fm, root.get('rev'))
>> >>   File "/usr/lib/python3.8/site-packages/osc/core.py", line 2393, in __update
>> >>     merge_status = self.mergefile(f.name, rev, f.mtime)
>> >>   File "/usr/lib/python3.8/site-packages/osc/core.py", line 1668, in mergefile
>> >>     upfilename = os.path.join(self.dir, n + '.r' + self.rev)
>> >> TypeError: can only concatenate str (not "NoneType") to str
>> >> ```
>> > Hmm this looks fishy (self.rev seems to be None). Can you post the output
>> > of
>> > - cat .osc/_files
>>
>> $ cat jtc/.osc/_files
>> <directory name="jtc" srcmd5="c80453afcf97cc7312750d91c758b031">
>>   <entry name="jtc.spec" size="1802" md5="849a145326178dce1db188facb37a5b9" mtime="1590422915"/>
>>   <entry name="jtc.changes" size="6254" md5="07475f3a5da108af43541fecf811a6aa" mtime="1590422915"/>
>>   <entry name="jtc-1.76d.tar.gz" size="221123" md5="5bd9d920da1a6feb9ee441ac32043dbc" mtime="1589993283"/>
>> </directory>
>>
> The "rev" attribute is missing. Is it possible that you manually modified
> this file? There are cases where the "rev" attribute can be omitted but
> in this case it should be present. Also, a linkinfo element should be
> present in case of a branch/link.

Yes, this package was checked out via the vscode extension for OBS
(https://github.com/SUSE/open-build-service-connector). So osc needs the
rev= attribute in the directory element?

>
> (Side note: the home:dancermak:branches:utilities project does not exist
> anymore)

Yes, I already made the SR and it got deleted.

**Comment by marcus-h** [comment]
On 2020-06-15 02:50:33 -0700, Dan Čermák wrote:
> Marcus Hüwe <notifications@github.com> writes:
>
> > On 2020-06-10 01:41:01 -0700, Dan Čermák wrote:
> >> Marcus Hüwe <notifications@github.com> writes:
> >>
> >> > On 2020-06-10 01:08:48 -0700, Dan Čermák wrote:
> >> >> Traceback (most recent call last):
> >> >>   File "/usr/bin/osc", line 41, in <module>
> >> >>     r = babysitter.run(osccli)
> >> >>   File "/usr/lib/python3.8/site-packages/osc/babysitter.py", line 64, in run
> >> >>     return prg.main(argv)
> >> >>   File "/usr/lib/python3.8/site-packages/osc/cmdln.py", line 347, in main
> >> >>     return self.cmd(args)
> >> >>   File "/usr/lib/python3.8/site-packages/osc/cmdln.py", line 370, in cmd
> >> >>     retval = self.onecmd(argv)
> >> >>   File "/usr/lib/python3.8/site-packages/osc/cmdln.py", line 504, in onecmd
> >> >>     return self._dispatch_cmd(handler, argv)
> >> >>   File "/usr/lib/python3.8/site-packages/osc/cmdln.py", line 1235, in _dispatch_cmd
> >> >>     return handler(argv[0], opts, *args)
> >> >>   File "/usr/lib/python3.8/site-packages/osc/commandline.py", line 4973, in do_update
> >> >>     prj.update(expand_link=opts.expand_link,
> >> >>   File "/usr/lib/python3.8/site-packages/osc/core.py", line 971, in update
> >> >>     p.update(rev, service_files)
> >> >>   File "/usr/lib/python3.8/site-packages/osc/core.py", line 2352, in update
> >> >>     self.__update(kept, added, deleted, services, fm, root.get('rev'))
> >> >>   File "/usr/lib/python3.8/site-packages/osc/core.py", line 2393, in __update
> >> >>     merge_status = self.mergefile(f.name, rev, f.mtime)
> >> >>   File "/usr/lib/python3.8/site-packages/osc/core.py", line 1668, in mergefile
> >> >>     upfilename = os.path.join(self.dir, n + '.r' + self.rev)
> >> >> TypeError: can only concatenate str (not "NoneType") to str
> >> >> ```
> >> > Hmm this looks fishy (self.rev seems to be None). Can you post the output
> >> > of
> >> > - cat .osc/_files
> >>
> >> $ cat jtc/.osc/_files
> >> <directory name="jtc" srcmd5="c80453afcf97cc7312750d91c758b031">
> >>   <entry name="jtc.spec" size="1802" md5="849a145326178dce1db188facb37a5b9" mtime="1590422915"/>
> >>   <entry name="jtc.changes" size="6254" md5="07475f3a5da108af43541fecf811a6aa" mtime="1590422915"/>
> >>   <entry name="jtc-1.76d.tar.gz" size="221123" md5="5bd9d920da1a6feb9ee441ac32043dbc" mtime="1589993283"/>
> >> </directory>
> >>
> > The "rev" attribute is missing. Is it possible that you manually modified
> > this file? There are cases where the "rev" attribute can be omitted but
> > in this case it should be present. Also, a linkinfo element should be
> > present in case of a branch/link.
>
> Yes, this package was checked out via the vscode extension for OBS
> (https://github.com/SUSE/open-build-service-connector). So osc needs the
> rev= attribute in the directory element?
>
Yes, the current osc code expects the presence of a rev attribute. We
could change the code, though. In general, if you modify the osc metadata
(the .osc/ dir(s)) with a different tool than osc itself, things can go
wrong... Hence, no osc bug:)
