### ISSUE TITLE
[RFE] osc reset

### ISSUE THREAD

**Issue by mcepl** [openSUSE/osc#808]
(edited log of the IRC conversation with @lethliel to have it recorded here):

That's comething completely different … what I mean is something like ``git reset --hard``: I sent something wrong to my devel project, and then I decide that it was stupid and I would like to get rid off it, but it is already on OBS.

>       So you want to switch to a former revision and submit that to your devel project?

Yes, basically roll back the project to some previous revision or (because I couldn't rewrite the history), to continue the project as if some previous revisions never happened.

>       You will get a osc reset command for that.

My current version of the shell script is:
```sh
#!/bin/bash
set -eu

function usage() {
    echo "usage: osc_reset -r REVNO" >&2
    exit 1
}

function die() {
    echo "$1" >&2
    exit 2
}

[[ "$#" -eq 2 ]] || usage
ls .osc/ >/dev/null 2>&1 || die "Command must be run from OSC package checkout."

REVNO=$2
PRJ=$(cat .osc/_project)
PKG=$(cat .osc/_package)

SR_OUT=$(osc sr -m 'revert' -r 6 "$PRJ" "$PKG" "$PRJ" "$PKG")
REQ_ID=$(echo "$SR_OUT"|awk '/created request id/ { print $4 }')
[[ -n "$REQ_ID" ]] || die "Submit request has not been created properly."

osc request accept -m ok $SR_OUT
```

**Comment by lethliel** [comment]
Thanks for putting this in an issue. 
Will start to work on thins next monday.

**Comment by marcus-h** [comment]
On 2020-06-12 05:23:27 -0700, Matěj Cepl wrote:
> (edited log of the IRC conversation to have it recorded here):
>
> That's comething completely different ... what I mean is
> something like git reset --hard I sent something wrong to my
> devel project and then decide that it is a stupid and I would
> like to get rid off it, but it is already on OBS.
>
> >       So you want to switch to a former revision and submit
> >       that to your devel project?
>
> yes, basically roll back the project to some previous revision or
> (because I couldn't rewrite the history), to continue the project
> as if some previous revisions never happened.
>
Hmm what should happen if your link target evolved in the meantime?

> >       You will get a osc reset command for that.
>
Hmm we maybe we could reuse the existing "osc revert" command.

**Comment by mcepl** [comment]
> Hmm what should happen if your link target evolved in the meantime?

I don’t understand.

> Hmm we maybe we could reuse the existing "``osc revert``" command.

We were talking about it: ``osc revert`` is something completely different:

* ``osc reset`` should require revision number (OK, it could default to zero, which would the equivalent of ``osc revert``), but
* ``osc revert`` requires filename, ``osc reset`` should work always on the complete checkout, so it should indiscriminately wipe out everything and replace it with new (respectively, old) content.

**Comment by andreas-schwab** [comment]
osc copypac $PRJ $PKG -r $REV

**Comment by marcus-h** [comment]
On 2020-06-12 07:15:00 -0700, Matěj Cepl wrote:
> > Hmm what should happen if your link target evolved in the meantime?
>
> I don’t understand.
>
Sorry for the late response...
If I understand your example/script correctly your "reset workflow" would
look like this:

- select revision from osc log home:xyz:branches:origin pkg
- cd home:xyz:branches:origin/pkg
- osc reset <selected revision>

The "problem" is that if you select your revision like this, it is not
obvious how the new file set should look like (after the reset). For this,
let's consider the following scenario.

$> commit(origin, pkg, foo << EOF);
This is
file
foo
#
#
end of file
EOF
$>

origin/pkg is at revision 1.

$> branch(origin, pkg, prj, pkg);

prj/pkg is a branch (at revision 1) of origin/pkg.

$> commit(prj, pkg, foo << EOF);
This is
file
foo
#
#
end of file
New content from the branch.
EOF
$>

prj/pkg is at revision 2

The "expanded" prj/pkg/foo file looks like this

$> cat_expand(prj, pkg, foo);
This is
file
foo
#
#
end of file
New content from the branch.
$>

(That is, the file that you just committed.)

Next, the origin package evolves:

$> commit(origin, pkg, foo << EOF);
New content from the origin.
This is
file
foo
#
#
end of file
$>

origin/pkg is at revision 2.

Now, the "expanded" prj/pkg/foo file looks like this

$> cat_expand(prj, pkg, foo);
New content from the origin.
This is
file
foo
#
#
end of file
New content from the branch.
$>

Note that prj/pkg is still at revision 2.

Next, the prj/pkg/foo file is changed.

$> commit(prj, pkg, foo << EOF);
New content from the origin.
This is
file
foo
#
#
end of file
Oops, I did a mistake...
$>

prj/pkg is at revision 3.

Now, the "expanded" prj/pkg/foo file looks like this

$> cat_expand(prj, pkg, foo);
New content from the origin.
This is
file
foo
#
#
end of file
Oops, I did a mistake...
$>

Finally, the origin/pkg/foo file is changed.

$> commit(origin, pkg, foo << EOF);
New content from the origin.
And even more content here.
This is
file
foo
#
#
end of file
$>

origin/pkg is at revision 3.

The revision "timeline" looks like this

origin/pkg: @rev1                @rev2         @rev3
prj/pkg:           @rev1  @rev2         @rev3

Now, you want to "reset" prj/pkg to revision 2 (@rev2).

$> reset(prj, pkg, @rev2);

Question: how does the "expanded" prj/pkg/foo file look like? That is,
what's the (expected) output of

$> cat_expand(prj, pkg, foo);

?

Potential outputs:

#
# (a) Exactly what you committed in @rev2
#

$> cat_expand(prj, pkg, foo);
This is
file
foo
#
#
end of file
New content from the branch.
$>

#
# (b) Expand @rev2 against origin/pkg@rev2 (this is the state you
#     actually "saw" before you committed your changes in prj/pkg@rev3)
#

$> cat_expand(prj, pkg, foo);
New content from the origin.
This is
file
foo
#
#
end of file
New content from the branch.
$>

#
# (c) Expand @rev2 against origin/pkg@rev3 (that is, expand it against
#     the latest revision of the origin/pkg)
#

$> cat_expand(prj, pkg, foo);
New content from the origin.
And even more content here.
This is
file
foo
#
#
end of file
New content from the branch.
$>

**Comment by mcepl** [comment]
> origin/pkg: @rev1 @Rev2 @Rev3
> prj/pkg: @rev1 @Rev2 @Rev3

I understand, that osc is not as correct VCS as git or mercurial is, so I understand when I say ``osc reset @Rev2`` here, it means actually “get the checkout to the state as it was when @Rev2 was current and create new commit with this semi-new state”.

**Comment by Rev2** [comment]
Please stop spamming me

**Comment by lethliel** [comment]
Sorry. We were talking about Revisions here. Would not have thought that someone with that username exists.

**Comment by adrianschroeter** [comment]
keep in mind to use "linkrev=base" to ensure that newer changes from the linked package do not get taken.

(this has nothing to do with being "exact", the functionality of on request merging multiple repositories simply does not exist in git/svn/...)

**Comment by marcus-h** [comment]
(Note: I removed all AT signs from the quoted mail (sorry for that))

On 2020-07-07 15:55:50 +0000, Matěj Cepl wrote:
> > origin/pkg: rev1 Rev2 Rev3
> > prj/pkg: rev1 Rev2 Rev3
>
> I understand, that osc is not as correct VCS as git or mercurial is, so I understand when I say ``osc reset Rev2`` here, it means actually “get the checkout to the state as it was when Rev2 was current and create new commit with this semi-new state”.
>
Hmm this does not really answer my question:) As the example
demonstrates/should demonstrate, one can only relate rev2 with a set of
expanded revs. From this set of expanded revs, osc reset should pick
one. The question is which one:)

**Comment by marcus-h** [comment]
On 2020-07-07 23:33:54 -0700, Adrian Schröter wrote:
> keep in mind to use "linkrev=base" to ensure that newer changes from the linked package do not get taken.
>
That is, you prefer option (a)?
If so, why/what's wrong with the other options?

(I'm just trying to understand what behavior our users expect)

**Comment by adrianschroeter** [comment]
My expecation would be that I get the state which was there on commit time.

If you want anything different you would need eg. go to the build history and use any expanded version.

IMHO these are the only two ways were you do not risk to run into source conflicts or have anyway a complete different state as referenced.

**Comment by mcepl** [comment]
I think, especially with switch to git this is not relevant any more.
