### ISSUE TITLE
osc -p should accept a list of repos

### ISSUE THREAD

**Issue by mslacken** [openSUSE/osc#811]
The ' --prefer-pkgs' options is great when using obs in conjunction with difficult packages like CUDA.  Now the problem is, that not multiple repositories can be added via -p.
As workaround one can download several repositories and create one big local one  like described in https://news.opensuse.org/2020/06/19/build-tensorflow-with-cuda/, but it would be more consistent to have the option to add multiple packages via the -p switch.

**Comment by marcus-h** [comment]
On 2020-06-22 04:36:50 -0700, Christian Goll wrote:
> The ' --prefer-pkgs' options is great when using obs in conjunction with difficult packages like CUDA.  Now the problem is, that not multiple repositories can be added via -p.
> As workaround one can download several repositories and create one big local one  like described in https://news.opensuse.org/2020/06/19/build-tensorflow-with-cuda/, but it would be more consistent to have the option to add multiple packages via the -p switch.
>
You can specify the -p option multiple times:
osc build -p /path/to/repo1 -p /path/to/repo2 -p /path/to/rpms ...

**Comment by mslacken** [comment]
Right, this working must have had a typo when trying it the first time.
Sorry for the inconvenience.
