### ISSUE TITLE
'osc co' requires a login

### ISSUE THREAD

**Issue by mslacken** [openSUSE/osc#812]
It is not possible to checkout a repository/package on the commandline without a login, although it is possible to get all the information about a repository/package via the webinterface. 
All other major collaboration platforms like github or gitlab allow anonymous code checkout.

**Comment by marcus-h** [comment]
On 2020-06-22 04:39:13 -0700, Christian Goll wrote:
> It is not possible to checkout a repository/package on the commandline without a login, although it is possible to get all the information about a repository/package via the webinterface.

Hmm there is nothing we do from the osc POV because the API routes that
are used by osc require authentication (there are "no" "official" routes
that do not require authentication).

**Comment by lethliel** [comment]
There is the public route path which do not require authentication. But those are marked as "not safe for production use" because they are not stable and can be changed any time without notification. 

@marcus-h What do you think of implementing a anonymous interface? 
@adrianschroeter Your opinion is welcome here too :-)

**Comment by marcus-h** [comment]
On 2020-06-25 17:48:54 +0000, Marco Strigl wrote:
> There is the public route path which do not require authentication. But those are marked as "not safe for production use" because they are not stable and can be changed any time without notification.
>
> @marcus-h What do you think of implementing a anonymous interface?

From the osc side, "almost" no changes are required (or well... it
depends how it is eventually implemented in the API). Hence, no
objections from my side:)

**Comment by lethliel** [comment]
I am sorry. There is nothing we can do. The public routes (without authentication) are part of the reference system (build.opensuse.org) and may not exist on other (private / public) instance of the Buildservice.

**Comment by abitrolly** [comment]
@lethliel may I ask to consider reopening this request? I want to create CI script for BleachBit that validates that packaging files committed to BleackBit repo match the ones in OBS. It should also be easy for contributors to check this without creating accounts etc. 

The reference system can support anonymous user that is used by default. This user will need to be configured explicitly. Will this work?
