### ISSUE TITLE
ArchLinux build fails

### ISSUE THREAD

**Issue by PerryWerneck** [openSUSE/osc#824]
When trying to build an ArchLinux version of a package osc ends with a python traceback (below). the RPM and DEB builds are ok for the same package.

```
Arch:Core/libsecret: attempting download from api, since not found
fetching packages for 'Arch:Core': | Elapsed Time: 0:00:27                                                                                            
Traceback (most recent call last):
  File "/usr/bin/osc", line 41, in <module>
    r = babysitter.run(osccli)
  File "/usr/lib/python3.6/site-packages/osc/babysitter.py", line 64, in run
    return prg.main(argv)
  File "/usr/lib/python3.6/site-packages/osc/cmdln.py", line 347, in main
    return self.cmd(args)
  File "/usr/lib/python3.6/site-packages/osc/cmdln.py", line 370, in cmd
    retval = self.onecmd(argv)
  File "/usr/lib/python3.6/site-packages/osc/cmdln.py", line 504, in onecmd
    return self._dispatch_cmd(handler, argv)
  File "/usr/lib/python3.6/site-packages/osc/cmdln.py", line 1235, in _dispatch_cmd
    return handler(argv[0], opts, *args)
  File "/usr/lib/python3.6/site-packages/osc/commandline.py", line 6559, in do_build
    return osc.build.main(self.get_api_url(), opts, args)
  File "/usr/lib/python3.6/site-packages/osc/build.py", line 998, in main
    fetcher.run(bi)
  File "/usr/lib/python3.6/site-packages/osc/fetch.py", line 260, in run
    self.__fetch_cpio(buildinfo.apiurl)
  File "/usr/lib/python3.6/site-packages/osc/fetch.py", line 132, in __fetch_cpio
    self.__download_cpio_archive(apiurl, project, repo, arch, package, **pkgs)
  File "/usr/lib/python3.6/site-packages/osc/fetch.py", line 102, in __download_cpio_archive
    self.move_package(tmpfile, pac.localdir, pac)
  File "/usr/lib/python3.6/site-packages/osc/fetch.py", line 174, in move_package
    pkgq = packagequery.PackageQuery.query(tmpfile, extra_rpmtags=(1044, 1051, 1052))
  File "/usr/lib/python3.6/site-packages/osc/util/packagequery.py", line 81, in query
    pkgqueryresult = pkgquery.read(all_tags, self_provides, *extra_tags)
  File "/usr/lib/python3.6/site-packages/osc/util/archquery.py", line 36, in read
    prv = b'%s = %s' % (self.name(), self.fields['pkgver'][0])
KeyError: 'pkgver'

```

**Comment by marcus-h** [comment]
On 2020-07-07 17:40:15 +0000, Perry Werneck wrote:
> ```
> Arch:Core/libsecret: attempting download from api, since not found

You have to install the "zstd" package (otherwise the tar call fails,
which osc does not expect...)

> Traceback (most recent call last):

<SNIP>

>   File "/usr/lib/python3.6/site-packages/osc/util/archquery.py", line 36, in read
>     prv = b'%s = %s' % (self.name(), self.fields['pkgver'][0])
> KeyError: 'pkgver'
>
osc should handle this more gracefully...

**Comment by PerryWerneck** [comment]
Hi,

Already installed; still failing. 

```
root@thinkpad:~ # LANG=C zypper in zstd
Loading repository data...
Reading installed packages...
'zstd' is already installed.
No update candidate for 'zstd-1.4.4-lp151.3.6.1.x86_64'. The highest available version is already installed.
Resolving package dependencies...

Nothing to do.

```

**Comment by marcus-h** [comment]
On 2020-07-07 14:51:43 -0700, Perry Werneck wrote:
> ```
> root@thinkpad:~ # LANG=C zypper in zstd
> Loading repository data...
> Reading installed packages...
> 'zstd' is already installed.
> No update candidate for 'zstd-1.4.4-lp151.3.6.1.x86_64'. The highest available version is already installed.
> Resolving package dependencies...
>
> Nothing to do.
>
> ```
Does the following work for you?

- fetch the libsecret cpio archive:
curl -u Marcus_H -o out.cpio \
    'https://api.opensuse.org/build/Arch:Core/standard/x86_64/_repository?view=cpio&binary=libsecret'

- extract the cpio archive
cpio -i < out.cpio

- print the .PKGINFO to stdout
tar -O -xf libsecret.pkg.tar.zst .PKGINFO

What's the output of the tar command?

**Comment by marcus-h** [comment]
On 2020-07-08 00:08:55 +0200, Marcus Hüwe wrote:
> - fetch the libsecret cpio archive:
> curl -u Marcus_H -o out.cpio \
>     'https://api.opensuse.org/build/Arch:Core/standard/x86_64/_repository?view=cpio&binary=libsecret'
>
Replace "Marcus_H" with your obs username:)

**Comment by PerryWerneck** [comment]
The tar has failed:

```
perry@thinkpad:~/tmp $ LANG=C tar -O -xf libsecret.pkg.tar.zst .PKGINFO
tar: This does not look like a tar archive
tar: Skipping to next header
tar: .PKGINFO: Not found in archive
tar: Exiting with failure status due to previous errors

```

After adjusting the compress program ...

```
perry@thinkpad:~/tmp $ LANG=C tar -O --use-compress-program=/usr/bin/zstd -xf libsecret.pkg.tar.zst .PKGINFO
# Generated by makepkg 5.2.1
# using fakeroot version 1.24
pkgname = libsecret
pkgbase = libsecret
pkgver = 0.20.3-1
pkgdesc = Library for storing and retrieving passwords and other secrets
url = https://wiki.gnome.org/Projects/Libsecret
builddate = 1586886594
packager = Jan Alexander Steffens (heftig) <jan.steffens@gmail.com>
size = 2270835
arch = x86_64
license = LGPL
provides = libsecret-1.so=0-64
depend = glib2
depend = libgcrypt
optdepend = org.freedesktop.secrets: secret storage backend
makedepend = docbook-xsl
makedepend = gobject-introspection
makedepend = vala
makedepend = git
makedepend = gtk-doc
makedepend = meson
makedepend = valgrind
checkdepend = python-dbus
checkdepend = dbus-glib
checkdepend = python-gobject
checkdepend = gjs

```

**Comment by adrianschroeter** [comment]
I suppose Arch Linux has no support for zstd in tar.

However, not an osc issue, but a distro issue.

**Comment by marcus-h** [comment]
On 2020-07-07 23:46:32 -0700, Adrian Schröter wrote:
> I suppose Arch Linux has no support for zstd in tar.
>
It seems it is about Leap15.1 (according to the zypper output). I just
checked Leap15.2 and it also has no zstd suffix detection (see src/suffix.c).

> However, not an osc issue, but a distro issue.
>
The question is whether osc should account for that.

**Comment by adrianschroeter** [comment]
well, in build script we have a fallback wrapper using zstdcat . osc could do the same.

**Comment by PerryWerneck** [comment]
Updating tar on OpenSUSE (https://build.opensuse.org/package/show/home:PerryWerneck/tar) fixed this problem but it still failing.

```
[    5s] [38/38] preinstalling pacman...
[    5s] bsdtar: Error opening archive: Unrecognized archive format

```

**Comment by marcus-h** [comment]
On 2020-07-08 15:13:42 +0000, Perry Werneck wrote:
> Updating tar on OpenSUSE (https://build.opensuse.org/package/show/home:PerryWerneck/tar) fixed this problem but it still failing.
>
> ```
> [    5s] [38/38] preinstalling pacman...
> [    5s] bsdtar: Error opening archive: Unrecognized archive format
>
> ```
It seems that your bsdtar package is also too "old".

**Comment by PerryWerneck** [comment]
After updating bsdtar (https://build.opensuse.org/package/show/home:PerryWerneck/libarchive) the build process completed. It works for me but I think it's not the best way for osc.

**Comment by dmach** [comment]
This issue has been open for 4 years, I believe zstd is supported everywhere now.
Please let me know if this is still an issue.
