### ISSUE TITLE
IncompleteRead(0 bytes read)

### ISSUE THREAD

**Issue by peti** [openSUSE/osc#832]
I'm getting lots of

    IncompleteRead(0 bytes read)

errors when I use `osc-0.170.0` on NixOS. This used to work fine a while ago, so I reckon that some Python library was updated and that this update breaks osc in some way. I have look at the debug output, but I cannot see what might be causing this issue:

~~~
$ osc --debug --http-full-debug update


-- GET https://api.opensuse.org/source/devel:languages:haskell
GET https://api.opensuse.org/source/devel:languages:haskell
send: b'GET /source/devel:languages:haskell HTTP/1.1\r\nAccept-Encoding: identity\r\nHost: api.opensuse.org\r\nUser-agent: osc/0.170.0\r\nCookie: openSUSE_session=65e0cf1a33f9d2fdbe043a664520383b\r\nConnection: close\r\n\r\n'
reply: 'HTTP/1.1 200 OK\r\n'
header: Date: Wed, 19 Aug 2020 16:08:49 GMT
header: Server: Apache/2.4.33 (Linux/SUSE)
header: Strict-Transport-Security: max-age=31536000
header: cache-control: max-age=0, private, must-revalidate
header: vary: Accept-Encoding
header: referrer-policy: strict-origin-when-cross-origin
header: x-permitted-cross-domain-policies: none
header: x-xss-protection: 1; mode=block
header: x-opensuse-runtimes: {"view":13.464858056977391,"db":15.041946899145842,"backend":0}
header: x-request-id: 570a13ea-1bce-43e5-a42d-bb4d84b998f8
header: x-opensuse-apiversion: 2.11~alpha.20200819T094511.323084bc2e
header: x-download-options: noopen
header: x-frame-options: SAMEORIGIN
header: x-runtime: 0.058264
header: x-content-type-options: nosniff
header: x-powered-by: Phusion Passenger 6.0.4
header: etag: W/"6349149c39a9ac0e8d30dc63b8ac91ec"
header: status: 200 OK
header: content-type: application/xml; charset=utf-8
header: Connection: close
header: Transfer-Encoding: chunked
IncompleteRead(0 bytes read)
~~~

Running the same command on Tumbleweed succeeds every time.

**Comment by marcus-h** [comment]
On 2020-08-19 16:12:08 +0000, Peter Simons wrote:
> I'm getting lots of
>
>     IncompleteRead(0 bytes read)
>
> errors when I use `osc-0.170.0` on NixOS. This used to work fine a while ago, so I reckon that some Python library was updated and that this update breaks osc in some way. I have look at the debug output, but I cannot see what might be causing this issue:
>
I guess you are using python38. Then, this is probably [1] (that is, you
need a recent python3-M2Crypto).

> $ osc --debug --http-full-debug update
>
--http-full-debug includes headers like "Cookie", which is used
for authorization. So you might want to change your password now:/

[1] https://gitlab.com/m2crypto/m2crypto/-/merge_requests/242

**Comment by nickbroon** [comment]
https://github.com/openSUSE/osc/issues/771#issuecomment-668556447 is a work around for this.

**Comment by dmach** [comment]
Upgrading m2crypto worked. No need to change code for this.
