### ISSUE TITLE
osc service run doesn't match documentation

### ISSUE THREAD

**Issue by dannysauer** [openSUSE/osc#835]
The help / docs for `osc service run` indicates that parameters will be pulled from _service if the service is defined.

```plaintext
    COMMAND can be:
    run         r  run defined services locally, it takes an optional parameter to run only a
                   specified source service. In case parameters exist for this one in _service file
                   they are used.
```

However, that does not appear to be the case, unless I'm doing something wrong. :)  The services below work fine with runall or similar, both locally and server-side. So I'm pretty sure they're properly defined, but I it's entirely plausible that I'm doing something wrong. 

Here are a couple of commands with their error messages, complaining about missing parameters, and the _service file which contains those parameters:

```plaintext
sauer@macdanny:~/dev/obs/home:dannysauer:owntracks/ot-recorder> osc service run obs_scm
Please specify valid --scm=... options
Aborting: service call failed:  /usr/lib/obs/service/obs_scm --outdir /home/sauer/dev/osc/home:dannysauer:owntracks/ot-recorder/tmpqsulo8oi.obs_scm.service

sauer@macdanny:~/dev/obs/home:dannysauer:owntracks/ot-recorder> osc service run recompress
ERROR: no inputs files are given via --file parameter!
Aborting: service call failed:  /usr/lib/obs/service/recompress --outdir /home/sauer/dev/osc/home:dannysauer:owntracks/ot-recorder/tmpk1apmoms.recompress.service

sauer@macdanny:~/dev/obs/home:dannysauer:owntracks/ot-recorder> osc --version
0.170.0
```

```xml
<!-- vi: set ft=xml: -->
<services>
  <service name="obs_scm">
    <param name="url">https://github.com/dannysauer/recorder.git</param>
    <param name="scm">git</param>
    <param name="exclude">.git</param>
    <param name="versionformat">@PARENT_TAG@</param>
    <param name="revision">@PARENT_TAG@</param>
    <param name="changesgenerate">enable</param>
    <param name="extract">etc/rpm/ot-recorder.spec</param>
  </service>
  <service name="format_spec_file" mode="buildtime" />
  <service name="set_version" mode="buildtime" />
  <service name="tar" mode="buildtime" />
  <service name="recompress" mode="buildtime">
    <param name="file">*.tar</param>
    <param name="compression">gz</param>
  </service>
</services>
```

**Comment by marcus-h** [comment]
On 2020-09-03 16:12:01 +0000, Danny Sauer wrote:
> The help / docs for `osc service run` indicates that parameters will be pulled from _service if the service is defined.
>
> ```plaintext
>     COMMAND can be:
>     run         r  run defined services locally, it takes an optional parameter to run only a
>                    specified source service. In case parameters exist for this one in _service file
>                    they are used.
> ```
>
> However, that does not appear to be the case, unless I'm doing something wrong. :)  The services below work fine with runall or similar, both locally and server-side. So I'm pretty sure they're properly defined, but I it's entirely plausible that I'm doing something wrong.
>
No, you did nothing wrong:) This was recently fixed in commit
cb6eaf3720fdd5206c2bc06d7bf444c6fdd14ecb ("Fix single service disabled run").

**Comment by dannysauer** [comment]
Then I searched wrong. :D 
Thanks!
