### ISSUE TITLE
Avoid duplicates due to a second OBS instance

### ISSUE THREAD

**Issue by jobermayr** [openSUSE/osc#84]
"osc build" should know that PROJECT on api.opensuse.org and openSUSE.org:PROJECT on pmbs-api.links2linux.de (https://pmbs.links2linux.de/project/show/openSUSE.org) are the same ...

Btw. if packages from openSUSE.org:PROJECT get fetched via api.opensuse.org->pmbs-api.opensuse.org->MYHOST it should also go directly (api.opensuse.org->MYHOST) to avoid unnecessary traffic on second OBS instance ...

**Comment by dmach** [comment]
The linked PR was rejected and it seems that this cannot be easily implemented without hardcoding values in osc, which wouldn't work in a general case. Closing.
