### ISSUE TITLE
osc sr superseede prompt does not accept 'c' as an entry

### ISSUE THREAD

**Issue by dcermak** [openSUSE/osc#840]
I have just tried to create a submitrequest and osc prompted me whether I want to supersede the old one. I opted to cancel (I assume that's what `c` is for?), but that didn't work:
```ShellSession
$ osc sr -m "add constraint on the childprocess version"
The following submit request is already open: 833723.
Supersede the old request? (y/n/c) c
c is not a valid option.to work on x86 & arm
Supersede the old request? (y/n/c) ^Cinterrupted!
```

I guess that's a bug?

**Comment by lethliel** [comment]
I cannot reproduce this:

```
The following submit request is already open: 834226.
Supersede the old request? (y/n/c) c
Aborting
aborted.
```

Which osc version are you using?

**Comment by dcermak** [comment]
> Which osc version are you using?

0.170.0

**Comment by marcus-h** [comment]
On 2020-09-14 00:40:34 -0700, Dan Čermák wrote:
> I have just tried to create a submitrequest and osc prompted me whether I want to supersede the old one. I opted to cancel (I assume that's what `c` is for?), but that didn't work:
> ```ShellSession
> $ osc sr -m "add constraint on the childprocess version"
> The following submit request is already open: 833723.
> Supersede the old request? (y/n/c) c
> c is not a valid option.to work on x86 & arm

This looks pretty strange (especially, the "to work on x86 & arm" part).

Is this reproducible (in a "fresh" terminal)?

**Comment by dcermak** [comment]
> Is this reproducible (in a "fresh" terminal)?

For some reason it is no longer reproducible. Sorry for the noise.
