### ISSUE TITLE
move service generated files to .old instead of deleting them

### ISSUE THREAD

**Issue by lnussel** [openSUSE/osc#845]
Before running services, obs moves all generated files to a `.old` directory:
https://github.com/openSUSE/open-build-service/blob/66eedd78b4ca65439b96be271b04347cfc21f248/src/backend/bs_service#L135

while osc just deletes them:
https://github.com/openSUSE/osc/blob/7b5d10552352295ebdd21193b6dfbf830e7d236a/osc/core.py#L415

So I guess osc should be fixed to be have like the server side in that case.

**Comment by dmach** [comment]
This is fixed already in
 - https://github.com/openSUSE/osc/pull/847
