### ISSUE TITLE
osc co ignores the --revision flag

### ISSUE THREAD

**Issue by dcermak** [openSUSE/osc#852]
I have tried to use the `--revision` option when checking out a project, but it appears that `osc co --revision=9 devel:languages:ruby:extensions rubygem-vagrant_cloud` always checks out `HEAD` and not revision 9. Is this a bug or am I using osc wrong?

**Comment by marcus-h** [comment]
On 2020-10-08 01:20:02 -0700, Dan Čermák wrote:
> I have tried to use the `--revision` option when checking out a project,

When checking out a whole project, the revision is currently ignored (see
"osc co --help").

> but it appears that `osc co --revision=9 devel:languages:ruby:extensions rubygem-vagrant_cloud` always checks out `HEAD` and not revision 9. Is this a bug or am I using osc wrong?
>
Well, devel:languages:ruby:extensions/rubygem-vagrant_cloud is a branch.
That is, if you specify "--revision=9", the fileset from revision 9 is
still expanded against openSUSE:Factory/rubygem-vagrant_cloud HEAD. You
are probably interested in --revision=55598009832170312963bf64e32926f0.

**Comment by dcermak** [comment]
Marcus Hüwe <notifications@github.com> writes:

> On 2020-10-08 01:20:02 -0700, Dan Čermák wrote:
>> I have tried to use the `--revision` option when checking out a project,
>
> When checking out a whole project, the revision is currently ignored (see
> "osc co --help").

My bad, I actually meant to write "package" instead of "project".

>
>> but it appears that `osc co --revision=9 devel:languages:ruby:extensions rubygem-vagrant_cloud` always checks out `HEAD` and not revision 9. Is this a bug or am I using osc wrong?
>>
> Well, devel:languages:ruby:extensions/rubygem-vagrant_cloud is a branch.
> That is, if you specify "--revision=9", the fileset from revision 9 is
> still expanded against openSUSE:Factory/rubygem-vagrant_cloud HEAD. You
> are probably interested in --revision=55598009832170312963bf64e32926f0.

That does not work unfortunately:
$ osc co --revision=55598009832170312963bf64e32926f0 devel:languages:ruby:extensions rubygem-vagrant_cloud
$ cd /tmp/devel\:languages\:ruby\:extensions/rubygem-vagrant_cloud/
$ osc log |head -2
----------------------------------------------------------------------------
r13 | buildservice-autocommit | 2020-10-08 11:14:27 | ad6e521c6e46c3a82540ea570335c72a | unknown | rq840197

**Comment by lethliel** [comment]
osc log comes from the server. 
use osc info to check on which revision you are.

**Comment by dcermak** [comment]
> osc log comes from the server.

Oh!

> use osc info to check on which revision you are.

At the correct one. Sorry for the noise.
