### ISSUE TITLE
osc with uses USERID and ignores .oscrc

### ISSUE THREAD

**Issue by osynge** [openSUSE/osc#86]
Dear OSC guys.

I am running OSC with an .oscrc config file that is ignored by osc and my user ID is used rather than what is configured in the oscrc file.

as unix user ID oms101 I can checkout 

isc co home:osynge:branches:Devel:Storage:Ceph ceph

but on committing I get the error:

Server returned an error: HTTP Error 403: Forbidden
no permission to modify package ceph in project home:osynge:branches:Devel:Storage:Ceph
Transmitting file data

If I make a new unix user and change userID I can successfully do this task with the same config file.

My config file is shown below:
# grep -v '#' .oscrc | sed 's/pass = .*/pass = password/g'

[general]
apiurl = https://api.opensuse.org
su-wrapper = sudo
build-root =  /usr/local/share/build-root/%(repo)s-%(arch)s

[https://api.suse.de]
user = osynge
pass = password
trusted_prj=SUSE:Factory:Head Devel:Storage:Ceph

[https://api.opensuse.org]
user = oms101
pass = password
trusted_prj=CentOS:CentOS-5 CentOS:CentOS-6 openSUSE:Factory filesystems

**Comment by jberry-suse** [comment]
Ran into this today when using a second obs account for the first time.

**Comment by marcus-h** [comment]
On 2016-10-25 12:03:40 -0700, Jimmy Berry wrote:
> Ran into this today when using a second obs account for the first time.
> 
Fixed in commit 05ad9efae3460003ee5f6e12915efbee661a5a7c.
