### ISSUE TITLE
Tutorial - please explain distribution/project/repository

### ISSUE THREAD

**Issue by abitrolly** [openSUSE/osc#862]
In https://en.opensuse.org/openSUSE:Build_Service_Tutorial#Step_Three.C2.A0.E2.80.93_Choose_build_targets it is said that `osc ls` command lists available repositories.

> ### Step Three – Choose build targets
>
> Now you have to select for which distributions (e.g. openSUSE 13.1, Ubuntu 14.04 etc.) your packages should get built.
>
> * **Command line**: first get a list of available repositories
> ```
> osc ls
> ```

But `osc ls` lists projects. How to get the list of distributions and their repos?

**Comment by marcus-h** [comment]
On 2020-11-13 04:17:27 -0800, Anatoli Babenia wrote:
> In https://en.opensuse.org/openSUSE:Build_Service_Tutorial#Step_Three.C2.A0.E2.80.93_Choose_build_targets it is said that `osc ls` command lists available repositories.
>
> > ### Step Three – Choose build targets
> >
> > Now you have to select for which distributions (e.g. openSUSE 13.1, Ubuntu 14.04 etc.) your packages should get built.
> >
> > * **Command line**: first get a list of available repositories
> > ```
> > osc ls
> > ```
>
> But `osc ls` lists projects. How to get the list of distributions and their repos?
>
"osc repos <project>" lists the (repo, arch) pairs for the specified
project.

**Comment by abitrolly** [comment]
@marcus-h the project in tutorial is empty, and the command `osc repos` lists only configured repositories. How to get a list of distro repos for selecting build targets for an empty project?

**Comment by marcus-h** [comment]
On 2020-11-13 06:43:36 -0800, Anatoli Babenia wrote:
> @marcus-h the project in tutorial is empty, and the command `osc repos` lists only configured repositories. How to get a list of distro repos for selecting build targets for an empty project?
>
osc ls -> list all projects
A "distribution" is also a project. For instance, "osc ls" prints, among
others, "openSUSE:Leap:15.3". In order to figure out all potential repos
of the openSUSE:Leap:15.3 project, run "osc repos openSUSE:Leap:15.3".

**Comment by abitrolly** [comment]
@marcus-h but the list is huge! How do I know which of the repos are official Linux distributives to build for?

How to get this list of supported distro repos from command line?
https://build.opensuse.org/project/add_repository_from_default_list/home:abitrolly

![image](https://user-images.githubusercontent.com/8781107/99141628-369d6c80-265e-11eb-8795-eb03f4d1d8eb.png)

**Comment by marcus-h** [comment]
On 2020-11-13 22:46:32 -0800, Anatoli Babenia wrote:
> @marcus-h but the list is huge! How do I know which of the repos are official Linux distributives to build for?
>
You can build against all these projects.

> How to get this list of supported distro repos from command line?
> https://build.opensuse.org/project/add_repository_from_default_list/home:abitrolly
>
You are probably looking for "osc distributions".

**Comment by abitrolly** [comment]
> You can build against all these projects.

Not sure what does mean to build against random projects. Up to this point I build packages only for Ubuntu and Fedora.

> You are probably looking for "osc distributions".

Thanks! Although I've already discovered how to query available distributions with repositories through authenticated API. )
```
osc api "/distributions" | xpath -q -e "//distribution/reponame/text()"
```

**Comment by abitrolly** [comment]
I edited the tutorial to replace confusing `osc ls` with proper `osc dists` https://en.opensuse.org/index.php?title=openSUSE:Build_Service_Tutorial&diff=149209&oldid=148213

Should be clear now that project is not a distribution and not a repository.
