### ISSUE TITLE
`osc repo add` or scripted repo addition

### ISSUE THREAD

**Issue by abitrolly** [openSUSE/osc#864]
It is good when CLI tools can be used in shell scripts to automate workflows. With `osc` I don't see how to add repository without manually editing XML file with `osc meta prjconf -e`.

How about adding a set of `osc repo` commands that will make `osc` interface more or less consistent with what `git remote` provides?

 * `osc repo ls` - list repos configured for the current project
 * `osd repo add` - add repo to the project

**Comment by dmach** [comment]
I'm working on something like this right now.
I'm not sure about the `osc repo ls` command, you can always check the meta.
On the other hand we should also add `osc repo rm`.
