### ISSUE TITLE
osc --debug status outputs no debugging information

### ISSUE THREAD

**Issue by roman-neuhauser** [openSUSE/osc#87]
```
% time osc --debug st
M    haskell-hslogger/PKGBUILD
M    ttf-hanazono/PKGBUILD
M    vim-project/PKGBUILD
M    vim-workspace/PKGBUILD
osc --debug st  140.87s user 26.18s system 49% cpu 5:36.52 total
```

i would expect _something_ to look at while it's going through the project.

**Comment by lethliel** [comment]
This is not what --debug is used for. 
If you want detailed information about what files are opened and what is done on OS level please use strace
