### ISSUE TITLE
How to install `osc` service?

### ISSUE THREAD

**Issue by abitrolly** [openSUSE/osc#881]
Can't commit to my branch of `openSUSE:Tools/build`.
```bash
$ osc commit
ERROR: please install obs-service-format_spec_file or use the --noservice option
```
Commiting without .spec formatting might be possible, but I'd like to try this feature. However, I could not find any info how to install those services. This info is absent from wiki, man pages and this repo.

**Comment by marcus-h** [comment]
On 2020-12-10 03:01:06 -0800, Anatoli Babenia wrote:
> Can't commit to my branch of `obs-tools`.
> ```bash
> $ osc commit
> ERROR: please install obs-service-format_spec_file or use the --noservice option
> ```
> Commiting without .spec formatting might be possible, but I'd like to try this feature. However, I could not find any info how to install those services. This info is absent from wiki, man pages and this repo.
>
This particular service is part of the openSUSE:Tools project [1].
The package is called obs-service-format_spec_file.

[1] https://download.opensuse.org/repositories/openSUSE:/Tools/

**Comment by abitrolly** [comment]
I see, I thought there is some `osc service install` command.

I also discovered https://openbuildservice.org/help/manuals/obs-user-guide/cha.obs.source_service.html which says,

> Services are safe. A source checkout and service run never harms the system of a user.

That source format service wants to be run on my side. How is that security enforced?

**Comment by marcus-h** [comment]
On 2020-12-11 03:36:43 -0800, Anatoli Babenia wrote:
> I see, I thought there is some `osc service install` command.
>
No, that's the "job" of, for instance, the package manager.

> I also discovered https://openbuildservice.org/help/manuals/obs-user-guide/cha.obs.source_service.html which says,
>
> > Services are safe. A source checkout and service run never harms the system of a user.
>
> That source format service wants to be run on my side. How is that security enforced?
>
Whether a service is "safe" or not probably depends on the service. For
instance, a local OBS might support "custom", "unsafe" services.

Eventually, the user decides whether a service is run on its system
or not (if you don't want to run it, simply do not install the particular
service or pass the corresponding options to osc).

**Comment by abitrolly** [comment]
@marcus-h but if I clone (branch) other project, `osc` doesn't ask my permission to execute the code that the user of this project has configured, right?

**Comment by marcus-h** [comment]
On 2020-12-11 12:49:51 +0000, Anatoli Babenia wrote:
> @marcus-h but if I clone (branch) other project, `osc` doesn't ask my permission to execute the code that the user of this project has configured, right?
>
Examples:
osc checkout does not run source services unless you explicitly
specify the --source-service-option.
osc commit runs services by default unless you specify the
--noservice option. That is, in the commit case the services are
executed by default if they are installed on your system.

**Comment by abitrolly** [comment]
The doc [About Source Service](https://openbuildservice.org/help/manuals/obs-user-guide/cha.obs.source_service.html#sec.obs.sserv.about) says this

> The service is a script that is stored in the /usr/lib/obs/service directory

I am not sure what else could be done to this. Maybe adding a link to `osc help` command.
