### ISSUE TITLE
osc pypi artifact is not up to date

### ISSUE THREAD

**Issue by chenrui333** [openSUSE/osc#884]
👋  looks like the latest release in here is `v0.171.0`, but the pypi artifact is still with `v0.167.2`.

**Comment by marcus-h** [comment]
On 2020-12-25 20:48:11 -0800, chenrui wrote:
> 👋  looks like the latest release in here is `v0.171.0`, but the pypi artifact is still with `v0.167.2`.
>
Hmm maybe our automatic deployment on pypi via travis does not "work"
anymore. @crazyscientist and @toabctl worked on this some time ago.
Do you have any ideas what could be wrong?:)
