### ISSUE TITLE
'osc sr' does not ask me whether to supersede past requests

### ISSUE THREAD

**Issue by MeggyCal** [openSUSE/osc#889]
I am using osc 0.171.0. Previously 'osc sr', when there were some open request with the same source and target, asked if I want to supersede them. I got quite used to this behavior and find it useful. But now it does not do this anymore, which could IMO bite us badly (for example, somebody creates some request, then fixes it and *does not supersede* the old one and after that some maintainer reviews requests from the oldest and accepts the wrong request). Is it bug, feature or am I just confused?

**Comment by MeggyCal** [comment]
looks like I am just confused :) sorry for false alarm

**Comment by marcus-h** [comment]
On 2021-01-13 03:14:26 -0800, MeggyCal wrote:
> I am using osc 0.171.0. Previously 'osc sr', when there were some open request with the same source and target, asked if I want to supersede them. I got quite used to this behavior and find it useful. But now it does not do this anymore, which could IMO bite us badly (for example, somebody creates some request, then fixes it and *does not supersede* the old one and after that some maintainer reviews requests from the oldest and accepts the wrong request). Is it bug, feature or am I just confused?
>
Unfortunately, this depends a bit on how you invoke osc:/ For instance,
if you run "osc sr" in a project working copy, the superseding behavior
differs compared to "osc sr" in a package working copy.
How did you invoke it and is CWD a project/package wc or just a "plain"
directory?

**Comment by MeggyCal** [comment]
Thanks for handling this, I later found out I probably invoked the sr via buildservice API (I did not remember this) and maintainer option "Forward submit request to upper-project / anything", so this does not fully apply. The request forwarding does not care about another hanging requests (and I think I see why, it would be mostly pain for the maintainers), so it was only expected. Thanks and sorry for false alarm!
