### ISSUE TITLE
osc bco: disable build and save the world

### ISSUE THREAD

**Issue by AdamMajer** [openSUSE/osc#894]
Whenever one does an `osc bco`, and this creates a new project, the parent project configuration is copied. This then starts to rebuild the package on all aches. In most cases, this is not what is wanted.

There should be a way of editing the config of the created project before the branch operation is complete. For example,

 1. create project and copy repository template from parent to new project
 2. allow user to edit `meta prj` and commit this
 3. then branch the package when prj meta is committed

maybe something like,

`osc bco --edit-prj osc`

and a .oscrc config where this can be set true in all cases where a branch to new project happens

As-is, we are rebuilding the world every time one branches to make a change before even that change is done. And in most cases, the change does not even have to be compiled on all arches to validate it.

**Comment by adrianschroeter** [comment]
On Donnerstag, 28. Januar 2021, 10:03:21 CET Adam Majer wrote:
> Whenever one does an `osc bco`, and this creates a new project, the parent project configuration is copied. This then starts to rebuild the package on all aches. In most cases, this is not what is wanted.

I would say in most cases it is wanted or one can not see regressions on submissions back...

> 
> There should be a way of editing the config of the created project before the branch operation is complete. For example,
> 
>  1. create project and copy repository template from parent to new project
>  2. allow user to edit `meta prj` and commit this
>  3. then branch the package when prj meta is committed
> 
> maybe something like,
> 
> `osc bco --edit-prj osc`
> 
> and a .oscrc config where this can be set true in all cases where a branch to new project happens
> 
> As-is, we are rebuilding the world every time one branches to make a change before even that change is done. And in most cases, the change does not even have to be compiled on all arches to validate it.
> 
> 
> 


-- 

Adrian Schroeter <adrian@suse.de>
Build Infrastructure Project Manager

SUSE Software Solutions Germany GmbH,  Maxfeldstr. 5, 90409 Nuernberg, Germany
(HRB 247165, AG München), Geschäftsführer: Felix Imendörffer

**Comment by dmach** [comment]
@AdamMajer could you test if https://github.com/openSUSE/osc/pull/1191 (`osc branch --disable-build`) works as expected?
It disables build right after the branch is created, but hopefully it's ok even if it's not entirely atomic.
