### ISSUE TITLE
obs_scm instead of download_url being generated

### ISSUE THREAD

**Issue by z3ntu** [openSUSE/osc#905]
osc generates me this `_service` file now with `osc add https://github.com/openrazer/openrazer/releases/download/v2.9.0/openrazer-2.9.0.tar.xz`:
```xml
<services>
  <service name="obs_scm">
    <param name="url">https://github.com/openrazer/openrazer/releases/download/v2.9.0/openrazer-2.9.0.tar.xz</param>
    <param name="scm">git</param>
  </service>
  <service name="tar" mode="buildtime" />
  <service name="recompress" mode="buildtime">
    <param name="file">*.tar</param>
    <param name="compression">xz</param>
  </service>
  <service name="set_version" mode="buildtime" />
</services>
```
instead of what was generated previously:
```xml
<services>
  <service name="download_url">
    <param name="protocol">https</param>
    <param name="host">github.com</param>
    <param name="path">/openrazer/openrazer/releases/download/v2.9.0/openrazer-2.9.0.tar.xz</param>
  </service>
  <service name="verify_file">
    <param name="file">_service:download_url:openrazer-2.9.0.tar.xz</param>
    <param name="verifier">sha256</param>
    <param name="checksum">c2b52debfd16ae1f319720c1db294f1d8a274b4a5736ac8a3eb27a680180254b</param>
  </service>
</services>
```
I last generated the download_url one on 2020-12-17, so probably with osc 0.171.0, instead of osc 0.172.0 now.

edit: downgraded to 0.171.0 and applied #904, still doesn't work. I'm going to write the _service file manually now to get the release onto OBS

**Comment by marcus-h** [comment]
On 2021-03-22 01:27:29 -0700, Luca Weiss wrote:
> osc generates me this `_service` file now with `osc add https://github.com/openrazer/openrazer/releases/download/v2.9.0/openrazer-2.9.0.tar.xz`:
> ```xml
> <services>
>   <service name="obs_scm">
>     <param name="url">https://github.com/openrazer/openrazer/releases/download/v2.9.0/openrazer-2.9.0.tar.xz</param>
>     <param name="scm">git</param>
>   </service>
>   <service name="tar" mode="buildtime" />
>   <service name="recompress" mode="buildtime">
>     <param name="file">*.tar</param>
>     <param name="compression">xz</param>
>   </service>
>   <service name="set_version" mode="buildtime" />
> </services>
> ```
> instead of what was generated previously:
> ```xml
> <services>
>   <service name="download_url">
>     <param name="protocol">https</param>
>     <param name="host">github.com</param>
>     <param name="path">/openrazer/openrazer/releases/download/v2.9.0/openrazer-2.9.0.tar.xz</param>
>   </service>
>   <service name="verify_file">
>     <param name="file">_service:download_url:openrazer-2.9.0.tar.xz</param>
>     <param name="verifier">sha256</param>
>     <param name="checksum">c2b52debfd16ae1f319720c1db294f1d8a274b4a5736ac8a3eb27a680180254b</param>
>   </service>
> </services>
> ```
> I last generated the download_url one on 2020-12-17, so probably with osc 0.171.0, instead of osc 0.172.0 now.
>
Yes, that's caused by commit 9b245db2244e785fe0d6829a03dba6577c567f07
("catch URLs to github.com and gitlab.com as git repos") :/ See also
the discussion in [1].

[1] https://github.com/openSUSE/osc/pull/834

**Comment by z3ntu** [comment]
Any way to work around this (or get this fixed)? Writing the _service file manually is a bit tedious

**Comment by marcus-h** [comment]
On 2021-04-10 02:31:15 -0700, Luca Weiss wrote:
> Any way to work around this (or get this fixed)? Writing the _service file manually is a bit tedious
>
Hmm we could add a new option (maybe --raw-url or something
like that) so that the URL is not interpreted as a git repo.
Reverting the commit is probably a bad idea because people
could already "rely" on the new behavior...

@adrianschroeter: any opinion?

**Comment by z3ntu** [comment]
Generally github only serves git repos with these urls I believe:
* https://github.com/user/repo
* https://github.com/user/repo/
* https://github.com/user/repo.git
* https://github.com/user/repo.git/

So the other urls should be archives or other forms of non-git repos. For archives there are several paths that can be used (there's also some super legacy paths that still work), so I would kind of make git repos be a special match instead of archives.

I'm actually surprised nobody complained before about this new behavior because that is exactly the way I use osc to publish new releases for my project and this is now broken :)

**Comment by z3ntu** [comment]
Any update on this? This is quite annoying for my release workflow.

Is for doing a release `osc add https://example.org/foo-1.0.tar.gz` the normal way to use it? I'm not aware of any other way to do this.

**Comment by z3ntu** [comment]
@marcus-h @adrianschroeter bump

**Comment by adrianschroeter** [comment]
we could add a github.com specific check for /releases/ path element.

(However, it is anyway better to use a git repo then a tar ball when it exists for a secured source trust chain in general)

**Comment by adrianschroeter** [comment]
https://github.com/openSUSE/osc/pull/1027

**Comment by z3ntu** [comment]
I can confirm it works again with osc 0.181.0, thanks for fixing!
