### ISSUE TITLE
No submitter name in the changelog on debian

### ISSUE THREAD

**Issue by lgbaldoni** [openSUSE/osc#911]
Running osc from openSUSE:Tools on debian 10: `osc vc` doesn't add my name to the header but only the email address.

The configuration file is almost untouched and as I understand, osc should get those informations from the API if not specified in `oscrc`.

**Comment by marcus-h** [comment]
On 2021-04-14 12:40:23 +0000, Luigi Baldoni wrote:
> Running osc from openSUSE:Tools on debian 10: `osc vc` doesn't add my name to the header but only the email address.
>
> The configuration file is almost untouched and as I understand, osc should get those informations from the API if not specified in `oscrc`.
>
Yes, the lookup order is as follows:
- config
- environment variable(s)
- api

What's the output of "osc api /person/<YOUR_USERNAME>"?

**Comment by lgbaldoni** [comment]
> What's the output of "osc api /person/<YOUR_USERNAME>"?

<person>
  <login>MY_USERNAME</login>
  <email>MY_EMAIL</email>
  <realname>MY_REALNAME</realname>
  <state>confirmed</state>
  <watchlist/>
</person>

**Comment by marcus-h** [comment]
On 2021-04-14 08:47:55 -0700, Luigi Baldoni wrote:
> > What's the output of "osc api /person/<YOUR_USERNAME>"?
>
> <person>
>   <login>MY_USERNAME</login>
>   <email>MY_EMAIL</email>
>   <realname>MY_REALNAME</realname>
>   <state>confirmed</state>
>   <watchlist/>
> </person>
>
Ok. What's the output of "osc config <APIURL> realname"? (Where
<APIURL> is the apiurl provided by "osc info".) Is the VC_REALNAME
env variable set? Which version of the "build" (or "obs-build")
package are you using?

**Comment by lgbaldoni** [comment]
> Ok. What's the output of "osc config <APIURL> realname"?

```
$ osc config https://api.opensuse.org realname
'https://api.opensuse.org': 'realname' is not set
```

> Is the VC_REALNAME env variable set?

It is not.

> Which version of the "build" (or "obs-build") package are you using?

```
ii  build                             20170320                              all          A script to build SUSE Linux RPMs
```
But I don't build anything locally on this machine.

**Comment by marcus-h** [comment]
On 2021-04-14 10:24:20 -0700, Luigi Baldoni wrote:
> > Which version of the "build" (or "obs-build") package are you using?
>
> ```
> ii  build                             20170320                              all          A script to build SUSE Linux RPMs
> ```
> But I don't build anything locally on this machine.
>
That's horribly out of date. The vc tool is part of the build package.
Support for a realname was added in 2018. If you update your build
package, it should work:) (an updated build version should be available
in the openSUSE:Tools project, too)

**Comment by lgbaldoni** [comment]
Installing obs-build fixed the problem, TYVM.
