### ISSUE TITLE
osc service disabledrun download_files does not rewrite files

### ISSUE THREAD

**Issue by MeggyCal** [openSUSE/osc#917]
I am using osc 0.172.0. I was fixing some requests Factory bots did not like, some were declined because the committed tarball was different from the upstream one. When I called `osc service disabledrun download_files` or `osc service runall download_files` and committed, nothing happened because the tarball did not change. I had to remove the tarball to download the correct upstream tarball, after that I was able to commit the changed tarball. Is it a bug or a feature?

**Comment by marcus-h** [comment]
On 2021-05-11 05:50:27 -0700, MeggyCal wrote:
> I am using osc 0.172.0. I was fixing some requests Factory bots did not like, some were declined because the committed tarball was different from the upstream one. When I called `osc service disabledrun download_files` or `osc service runall download_files` and committed, nothing happened because the tarball did not change. I had to remove the tarball to download the correct upstream tarball, after that I was able to commit the changed tarball. Is it a bug or a feature?
>
Which version of the obs-service-download_files package are you
using? Recently, there were some changes in the obs-service-download_files
that *could* cause this behavior.

Just to be sure: you did
- osc service disabledrun download_files -> no local changes
- rm <downloaded filename>
- osc service disabledrun download_files -> local changes

If so, then you should probably file a bug against the download_files
service [1].

[1] https://github.com/openSUSE/obs-service-download_files

**Comment by MeggyCal** [comment]
Hi, thanks, I will file an issue against obs-service-download_files as soon as there is the newest version available in standard repos, so I could try it again (I had 0.7.1, but 0.8.0 is already out). Sorry for bothering you :) .

**Comment by dmach** [comment]
This doesn't seem to require any change directly in osc. Closing.
