### ISSUE TITLE
osc service does nothing

### ISSUE THREAD

**Issue by AdamMajer** [openSUSE/osc#922]
On new install of TW,

zypper in osc

```
osc co home:DocB:branches:devel:languages:python/tryton-sao
cd home:DocB:branches:devel:languages:python/tryton-sao
osc service lr
```

and there is no output.

installing node_modules service from my home directory,

```
osc getbinaries home:adamm:branches:OBS:Server:Unstable/obs-service-node_modules openSUSE_Factory x86_64
zypper in ...
osc service lr
... nothing ...
```

I would at least expect a reason why it's not running

```
> ls /usr/lib/obs/service/
node_modules  node_modules.service
```

**Comment by AdamMajer** [comment]
Just for the record, this service runs fine on my Leap workstation. Just on a new TW install, seems some dependencies that we take for granted are not there and `osc` seems to just go for no-op instead of reporting an issue.

**Comment by marcus-h** [comment]
On 2021-06-16 15:10:28 +0000, Adam Majer wrote:
> ```
> osc co home:DocB:branches:devel:languages:python/tryton-sao
> cd home:DocB:branches:devel:languages:python/tryton-sao
> osc service lr
> ```
>
> and there is no output.
>

In the _service file, you have
...
    <service name="node_modules" mode="manual">
...

That is, you have to run "osc service manualrun".

**Comment by AdamMajer** [comment]
Great, so, there was a change that changed behaviour and it's in Maintenance too now :tada: 

```
Status         : out-of-date (version 0.170.0-lp152.2.3.1 installed)                           
```

with this the localrun runs the manual services. And then updated to `osc-0.172.0-lp152.2.6.1.noarch.rpm` and suddenly that stops working. There seems nothing about it in .changes file either. But the help did indeed change, from,

```
   localrun    lr run all services except the ones with mode "buildtime", "disabled", or
                   "serveronly" (deprecated)
```

to

```
    localrun    lr the same as "run" but services with mode "serveronly" are also executed

    run         r  run defined services with modes "trylocal", "localonly", or no mode set locally, may take an optional parameter to run only a
                   specified source service. In case parameters exist for this one in _service file
                   they are used.
```

If I may suggest, please don't change behaviour of various modes and parameters. It's better to remove them and use something else instead than change what the options do.

**Comment by avindra** [comment]
Ran into this.  Seems that this no longer works:

```sh
osc service manual recompress
```

Now it needs to be:

```sh
osc service localrun recompress
```

**Comment by marcus-h** [comment]
On 2021-08-10 19:08:19 -0700, Avindra Goolcharan wrote:
> Ran into this.  Seems that this no longer works:
>
> ```sh
> osc service manual recompress
> ```
>
> Now it needs to be:
>
> ```sh
> osc service localrun recompress
> ```
>
What's the content of your _service file?
