### ISSUE TITLE
Transmitting file data There is no sha256 sum for file

### ISSUE THREAD

**Issue by hramrach** [openSUSE/osc#924]
`osc ci` reports:

> Transmitting file data There is no sha256 sum for file `<somefile>`

Why is there no checksum for the file?

Can't `osc` recreate checksums it has misplaced?

it says:

> This could be due to an outdated working copy.
> Please update your working copy with osc update and
> commit again afterwards.

but updating the checkout does not help at all.

osc version 0.173

**Comment by marcus-h** [comment]
On 2021-07-02 10:30:49 -0700, Michal Suchánek wrote:
> `osc ci` reports:
>
> > Transmitting file data There is no sha256 sum for file `<somefile>`
>
About which project/package are you talking? What's the local state
of <somefile> (you can check it with "osc st")?

**Comment by hramrach** [comment]
osc st <somefile>

returns no output and the exit code is 0

This happens intermittently with random package checkouts, sometimes fresh checkout fixes it.

**Comment by hramrach** [comment]
Looks like the package link is broken but there is no diagnostic for the failure

**Comment by marcus-h** [comment]
On 2021-07-02 11:06:45 -0700, Michal Suchánek wrote:
> Looks like the package link is broken but there is no diagnostic for the failure
>
About which project/package are you talking?

**Comment by hramrach** [comment]
I did try:

osc co home:michals dunst
touch dunst-1.5.0.tar.gz
touch test
osc ar
osc ci

And got the incomprehensible message about missing checksum.

Doing

osc co home:michals dunst
osc pull

fixed the problem but it's not clear from the message that this problem exists.

The problem is reported only on `osc co`, and for existing checkouts it's never reported.

**Comment by marcus-h** [comment]
On 2021-07-02 11:36:56 -0700, Michal Suchánek wrote:
> I did try:
>
> osc co home:michals dunst
> touch dunst-1.5.0.tar.gz
> touch test
> osc ar
> osc ci
>
> And got the incomprehensible message about missing checksum.
>
Hmm I cannot reproduce it. About which file does it complain?
Can you still reproduce it?

> Doing
>
> osc co home:michals dunst
> osc pull
>
Hmm from a very quick glance I cannot see why a "osc pull" is required
(all revs from r2 to r6 can be currently expanded).

Which osc version are you using?

> fixed the problem but it's not clear from the message that this problem exists.
>
> The problem is reported only on `osc co`, and for existing checkouts it's never reported.
>

**Comment by hramrach** [comment]
On Fri, Jul 02, 2021 at 12:55:28PM -0700, Marcus Hüwe wrote:
> On 2021-07-02 11:36:56 -0700, Michal Suchánek wrote:
> > I did try:
> >
> > osc co home:michals dunst
> > touch dunst-1.5.0.tar.gz
> > touch test
> > osc ar
> > osc ci
> >
> > And got the incomprehensible message about missing checksum.
> >
> Hmm I cannot reproduce it. About which file does it complain?

dunst-1.5.0.tar.gz

> Can you still reproduce it?

No, I committed the pull in r3

> 
> > Doing
> >
> > osc co home:michals dunst
> > osc pull
> >
> Hmm from a very quick glance I cannot see why a "osc pull" is required
> (all revs from r2 to r6 can be currently expanded).

It would 'checkout last expandable sources' or somesuch so it expands
even broken revisions.

***@***.***:~/home:michals> osc co dunst
A    dunst

The link in this package ("dunst") is currently broken. Checking
out the last working version instead; please use 'osc pull'
to merge the conflicts.

A    dunst/dunst-1.5.0.tar.gz
A    dunst/dunst.changes
A    dunst/dunst.spec
A    dunst/makefile.patch
At revision 7bbfe1a2d20a1f34a89aea78c29a5cb5.
~/home:michals> cd dunst
~/home:michals/dunst> cp ../dunst.broken/* .
cp: -r not specified; omitting directory '../dunst.broken/BUILDROOT'
cp: -r not specified; omitting directory '../dunst.broken/dunst'
cp: -r not specified; omitting directory '../dunst.broken/dunst-1.5.0'
cp: -r not specified; omitting directory '../dunst.broken/RPMS'
~/home:michals/dunst> osc ar
A    dunst-Flush-stdout-when-using-print.patch
A    dunst-xdg-open-can-open-URLs-don-t-rely-on-specific-hardco.patch
~/home:michals/dunst> osc ci
Sending    dunst.changes
Sending    dunst.spec
Sending    dunst-Flush-stdout-when-using-print.patch
Sending
dunst-xdg-open-can-open-URLs-don-t-rely-on-specific-hardco.patch
Transmitting file data There is no sha256 sum for file
dunst-1.5.0.tar.gz.
This could be due to an outdated working copy.
Please update your working copy with osc update and
commit again afterwards.

> Which osc version are you using?

it's in the description 0.173

**Comment by marcus-h** [comment]
On 2021-07-02 13:07:11 -0700, Michal Suchánek wrote:
> On Fri, Jul 02, 2021 at 12:55:28PM -0700, Marcus Hüwe wrote:
> > On 2021-07-02 11:36:56 -0700, Michal Suchánek wrote:

<SNIP>

> > > Doing
> > >
> > > osc co home:michals dunst
> > > osc pull
> > >
> > Hmm from a very quick glance I cannot see why a "osc pull" is required
> > (all revs from r2 to r6 can be currently expanded).
>
My bad... I used the wrong option for "osc ls" (I used "-r" instead of
"-R" /o\ *sigh*). Indeed, r2 cannot be expanded.

> It would 'checkout last expandable sources' or somesuch so it expands
> even broken revisions.
>
> ***@***.***:~/home:michals> osc co dunst
> A    dunst
>
> The link in this package ("dunst") is currently broken. Checking
> out the last working version instead; please use 'osc pull'
> to merge the conflicts.
>
> A    dunst/dunst-1.5.0.tar.gz
> A    dunst/dunst.changes
> A    dunst/dunst.spec
> A    dunst/makefile.patch
> At revision 7bbfe1a2d20a1f34a89aea78c29a5cb5.
> ~/home:michals> cd dunst
> ~/home:michals/dunst> cp ../dunst.broken/* .
> cp: -r not specified; omitting directory '../dunst.broken/BUILDROOT'
> cp: -r not specified; omitting directory '../dunst.broken/dunst'
> cp: -r not specified; omitting directory '../dunst.broken/dunst-1.5.0'
> cp: -r not specified; omitting directory '../dunst.broken/RPMS'
> ~/home:michals/dunst> osc ar
> A    dunst-Flush-stdout-when-using-print.patch
> A    dunst-xdg-open-can-open-URLs-don-t-rely-on-specific-hardco.patch
> ~/home:michals/dunst> osc ci
> Sending    dunst.changes
> Sending    dunst.spec
> Sending    dunst-Flush-stdout-when-using-print.patch
> Sending
> dunst-xdg-open-can-open-URLs-don-t-rely-on-specific-hardco.patch
> Transmitting file data There is no sha256 sum for file
> dunst-1.5.0.tar.gz.
> This could be due to an outdated working copy.
> Please update your working copy with osc update and
> commit again afterwards.
>
Thanks for the detailed report! Awesome!

PR #925 [1] should fix it.

> > Which osc version are you using?
>
> it's in the description 0.173
>
Ah... I missed that because you edited your first post (in this case
github sends no email...).

[1] https://github.com/openSUSE/osc/pull/925

**Comment by hramrach** [comment]
Thanks for the fix. I have not seen the problem for a while so I assume it was addressed successfully.
