### ISSUE TITLE
OpenSUSE TW: Osc configuration problem

### ISSUE THREAD

**Issue by pandom79** [openSUSE/osc#927]
The first time that i create the osc configuration, i don't see this option to save the credentials:

`kwallet DBusKeyring (Backend provided by python-keyring)
`

I checked that kwallet is installed.
What is missing?

**Comment by marcus-h** [comment]
On 2021-07-08 09:30:10 -0700, pandom79 wrote:
> The first time that i create the osc configuration, i don't see this option to save the credentials:
>
> `kwallet DBusKeyring (Backend provided by python-keyring)
> `
>
> I checked that kwallet is installed.
> What is missing?
>
Did you install the python-keyring module? For instance, on openSUSE
it is called python38-keyring/python39-keyring.

**Comment by pandom79** [comment]
Yes, both are installed but I still have the problem.
 These are the options that i see:

```
1) SecretService Keyring (Backend provided by python-keyring)
2) chainer ChainerBackend (Backend provided by python-keyring)
3) fail Keyring (Backend provided by python-keyring)
4) file PlaintextKeyring (Backend provided by python-keyring)
5) Config file credentials manager (Store the credentials in the config file (plain text))
6) Obfuscated Config file credentials manager (Store the credentials in the config file (obfuscated))
7) Transient password store (Do not store the password and always ask for the password)
```

kwallet DBusKeyring (Backend provided by python-keyring) missing!

**Comment by marcus-h** [comment]
On 2021-07-09 00:12:48 -0700, pandom79 wrote:
> Yes, both are installed but I still have the problem.
>  These are the options that i see:
>
> ```
> 1) SecretService Keyring (Backend provided by python-keyring)
> 2) chainer ChainerBackend (Backend provided by python-keyring)
> 3) fail Keyring (Backend provided by python-keyring)
> 4) file PlaintextKeyring (Backend provided by python-keyring)
> 5) Config file credentials manager (Store the credentials in the config file (plain text))
> 6) Obfuscated Config file credentials manager (Store the credentials in the config file (obfuscated))
> 7) Transient password store (Do not store the password and always ask for the password)
> ```
>
> kwallet DBusKeyring (Backend provided by python-keyring) missing!
>
This indicates that python-keyring cannot load the kwallet backend. osc
just "offers" the keyrings that are provided by the python-keyring
module. You can try to run something like

python3 -c "from keyring import core; core.load_keyring('keyring.backends.kwallet.DBusKeyring')"

in order to find out why the kwallet backend cannot be loaded.

**Comment by pandom79** [comment]
python38/39-dbus-python is missing for some reason.
I installed them and it works.
Thanks so much.
