### ISSUE TITLE
osc se -v -B crash

### ISSUE THREAD

**Issue by arvidjaar** [openSUSE/osc#933]
Ubuntu 20.04, package installed from openSUSE:Tools

```
$ osc se -v -B openSUSE:Leap:15.3 NetworkManager-pptp
Traceback (most recent call last):
  File "/usr/bin/osc", line 45, in <module>
    r = babysitter.run(osccli)
  File "/usr/lib/python3/dist-packages/osc/babysitter.py", line 69, in run
    return prg.main(argv)
  File "/usr/lib/python3/dist-packages/osc/cmdln.py", line 347, in main
    return self.cmd(args)
  File "/usr/lib/python3/dist-packages/osc/cmdln.py", line 370, in cmd
    retval = self.onecmd(argv)
  File "/usr/lib/python3/dist-packages/osc/cmdln.py", line 504, in onecmd
    return self._dispatch_cmd(handler, argv)
  File "/usr/lib/python3/dist-packages/osc/cmdln.py", line 1235, in _dispatch_cmd
    return handler(argv[0], opts, *args)
  File "/usr/lib/python3/dist-packages/osc/commandline.py", line 7963, in do_search
    title = node.findtext('title').strip()
AttributeError: 'NoneType' object has no attribute 'strip'
bor@bor-Latitude-E5450:~/src/binutils$ osc --version
0.174
```

Without `-B` it does not crash.

**Comment by marcus-h** [comment]
On 2021-07-25 21:46:30 -0700, Andrei Borzenkov wrote:
> ```
> $ osc se -v -B openSUSE:Leap:15.3 NetworkManager-pptp
> Traceback (most recent call last):
>   File "/usr/bin/osc", line 45, in <module>
>     r = babysitter.run(osccli)
>   File "/usr/lib/python3/dist-packages/osc/babysitter.py", line 69, in run
>     return prg.main(argv)
>   File "/usr/lib/python3/dist-packages/osc/cmdln.py", line 347, in main
>     return self.cmd(args)
>   File "/usr/lib/python3/dist-packages/osc/cmdln.py", line 370, in cmd
>     retval = self.onecmd(argv)
>   File "/usr/lib/python3/dist-packages/osc/cmdln.py", line 504, in onecmd
>     return self._dispatch_cmd(handler, argv)
>   File "/usr/lib/python3/dist-packages/osc/cmdln.py", line 1235, in _dispatch_cmd
>     return handler(argv[0], opts, *args)
>   File "/usr/lib/python3/dist-packages/osc/commandline.py", line 7963, in do_search
>     title = node.findtext('title').strip()
> AttributeError: 'NoneType' object has no attribute 'strip'
> ***@***.***:~/src/binutils$ osc --version
> 0.174
> ```
>
> Without `-B` it does not crash.
>
In case of the -B option, a search for binaries is performed. If you omit
the -v option, it should also work.
From a user's perspective, what kind of "verbose" information do you expect
in case of a binary search?

**Comment by arvidjaar** [comment]
> If you omit the -v option, it should also work.

I know.

> From a user's perspective, what kind of "verbose" information do you expect in case of a binary search?

I do not know. I am just a user of osc, I am not intimately familiar with implementation details. Binary search returned unexpected result (that is not the point of this issue) and I hoped to get some more details to understand why. I certainly did not expect program crash.
