### ISSUE TITLE
osc commit mangles encoding

### ISSUE THREAD

**Issue by pevik** [openSUSE/osc#934]
I'm pretty sure I didn't broke encoding before running `osc commit`. But after `osc commit` it breaks:
https://build.opensuse.org/request/show/907799
```
-    Vesa Jääskeläinen
+    Vesa JÃ¤Ã¤skelÃ¤inen
```
My locale is:
```
$ locale
LANG=en_GB.utf8
LC_CTYPE=cs_CZ.UTF-8
LC_NUMERIC=cs_CZ.UTF-8
LC_TIME=cs_CZ.UTF-8
LC_COLLATE=cs_CZ.UTF-8
LC_MONETARY=cs_CZ.UTF-8
LC_MESSAGES=C
LC_PAPER=cs_CZ.UTF-8
LC_NAME=cs_CZ.UTF-8
LC_ADDRESS=cs_CZ.UTF-8
LC_TELEPHONE=cs_CZ.UTF-8
LC_MEASUREMENT=cs_CZ.UTF-8
LC_IDENTIFICATION=cs_CZ.UTF-8
```
I suspected `LC_MESSAGES=C` to be problematic, thus I changed it to ;LC_MESSAGES="en_GB.utf8"`, but that didn't help either.
I tried some debugging:
```
$ python3 -c 'import locale; print(locale.getpreferredencoding())'
UTF-8
```
(the same is with `python2`)
Maybe there is a problem with my locale setup. But whole concept of changing something after user committed it sounds really strange to me, but having bug like this is really noop. I'm not able to fix grub2 package just because this issue.
```
$ osc --version
0.174
$ lsb_release -a
LSB Version:	n/a
Distributor ID:	openSUSE
Description:	openSUSE Tumbleweed
Release:	20210721
Codename:	n/a
```

**Comment by marcus-h** [comment]
On 2021-07-26 11:39:27 +0000, Petr Vorel wrote:
> I'm pretty sure I didn't broke encoding before running `osc commit`. But after `osc commit` it breaks:
> https://build.opensuse.org/request/show/907799
> ```
> -    Vesa Jääskeläinen
> +    Vesa JÃ¤Ã¤skelÃ¤inen
> ```

Hmm that could be caused by some source service. osc itself does not
modify files during a commit (which is executed by osc) (you could skip
the services via "osc ci --noservice ...").

Is it reproducable?

**Comment by pevik** [comment]
@marcus-h using `osc ci --noservice` helped, thanks! I suppose we can close the issue as it's OBS specific.
