### ISSUE TITLE
sendsysrq has got a "skipped rebuild" as a result and OBS is showing "succeeded"

### ISSUE THREAD

**Issue by skriesch** [openSUSE/osc#939]
I wanted to debug a failed build because of a kernel issue. Therefore, I triggered a rebuild in the openSUSE Build Service as a first step:
osc rebuild --failed openSUSE:Factory:zSystems/bcc

Then I wanted to use the osc option "sendsysrq" for sending sysrq keys. Therefore, I used following osc command directly after triggering the rebuild:
 osc sendsysrq openSUSE:Factory:zSystems bcc standard s390x 9

The output didn't contain any kernel errors any more, was shorter and created rpm packages.
Finally, there was following statement:
Retried build at Tue Aug 10 13:15:31 2021 returned same result, skipped

The build process has been received the status "Succeeded" in parallel. The build job can not be skipped with the same result (Build failure before) and be succeeded in parallel.

**Comment by marcus-h** [comment]
On 2021-08-10 06:48:02 -0700, Sarah Julia Kriesch wrote:
> I wanted to debug a failed build because of a kernel issue. Therefore, I triggered a rebuild in the openSUSE Build Service as a first step:
> osc rebuild --failed openSUSE:Factory:zSystems/bcc
>
> Then I wanted to use the osc option "sendsysrq" for sending sysrq keys. Therefore, I used following osc command directly after triggering the rebuild:
>  osc sendsysrq openSUSE:Factory:zSystems bcc standard s390x 9
>
> The output didn't contain any kernel errors any more, was shorter and created rpm packages.
> Finally, there was following statement:
> Retried build at Tue Aug 10 13:15:31 2021 returned same result, skipped
>
> The build process has been received the status "Succeeded" in parallel. The build job can not be skipped with the same result (Build failure before) and be succeeded in parallel.
>
The jobhistory looks like this:

***@***.***:~> osc jobhist openSUSE:Factory:zSystems bcc standard s390x | tail -n 3
2021-07-28 18:12:43  bcc                                                source change    succeeded               47m 18s   s390zp25:3
2021-08-04 15:35:51  bcc                                                new build        failed           1d  2h 54m 59s   s390zp21:5
2021-08-10 13:15:31  bcc                                                new build        unchanged                3m 11s   s390zp29:1
***@***.***:~>

The "unchanged" refers to the results of the last successful build (that
is, the one from july). IMHO, this looks correct (if you disagree, the best
is to file a bug against the open-build-service repo (it is not osc related)).

**Comment by skriesch** [comment]
It refers to 2021-07-28 then? The last build has been failed with a kernel error tracing on 2021-08-04. I wanted to retrigger this build via osc. 
Is the output of " Retried build at Tue Aug 10 13:15:31 2021 returned same result, skipped" really correctly then?
I will forward that the OBS tracker, if that is not correct here.

**Comment by adrianschroeter** [comment]
On Dienstag, 10. August 2021, 17:22:32 CEST Sarah Julia Kriesch wrote:
> It refers to 2021-07-28 then? The last build has been failed with a kernel error tracing on 2021-08-04. I wanted to retrigger this build via osc. 
> Is the output of " Retried build at Tue Aug 10 13:15:31 2021 returned same result, skipped" really correctly then?

The tracing only works during the build, if it ends the build we need to debug the KVM handling.

In this particular case it seems the kernel did hangup already and is not
reacting to sysrq anymore. The entire worker screen is frozen, so there is
no way for the build script to inject a sysrq anymore.

But I saved the entire VM state, if that helps you?

> I will forward that the OBS tracker, if that is not correct here.

most likely neither the right place;) Either build script or qemu-kvm topic ...

-- 

Adrian Schroeter ***@***.***>
Build Infrastructure Project Manager

SUSE Software Solutions Germany GmbH,  Maxfeldstr. 5, 90409 Nuernberg, Germany
(HRB 247165, AG München), Geschäftsführer: Felix Imendörffer

**Comment by skriesch** [comment]
> The tracing only works during the build, if it ends the build we need to debug the KVM handling. In this particular case it seems the kernel did hangup already and is not reacting to sysrq anymore. The entire worker screen is frozen, so there is no way for the build script to inject a sysrq anymore. But I saved the entire VM state, if that helps you?

That could be really helpful for all. Can you send me this VM state, please?
Then I can look, how to continue and handle that continuously.
Thank you!

**Comment by adrianschroeter** [comment]
On Mittwoch, 11. August 2021, 10:20:43 CEST Sarah Julia Kriesch wrote:
> > The tracing only works during the build, if it ends the build we need to debug the KVM handling. In this particular case it seems the kernel did hangup already and is not reacting to sysrq anymore. The entire worker screen is frozen, so there is no way for the build script to inject a sysrq anymore. But I saved the entire VM state, if that helps you?
> 
> That could be really helpful for all. Can you send me this VM state, please?
> Then I can look, how to continue and handle that continuously.

I send you a link via personal mail.

-- 

Adrian Schroeter ***@***.***>
Build Infrastructure Project Manager

SUSE Software Solutions Germany GmbH,  Maxfeldstr. 5, 90409 Nuernberg, Germany
(HRB 247165, AG München), Geschäftsführer: Felix Imendörffer

**Comment by skriesch** [comment]
I have tested the vmstate. It seems that it is damaged. I am receiving following output:

```
 qemu-system-s390x -S -kernel boot/image-5.13.4-1-default -m 4G -machine s390-ccw-virtio-5.2 -nodefaults -device sclpconsole,chardev=console -parallel none -net none -chardev stdio,id=console,mux=on -mon chardev=console -nographic -smp 3 -incoming "exec: zcat s390zp23.vmstate.gz" -monitor unix:qemu-monitor-socket,server,nowait --enable-kvm --append 'root=/dev/vda rw console=ttyS0 rdinit=/bin/bash'
qemu-system-s390x: error while loading state section id 2(ram)
qemu-system-s390x: load of migration failed: Input/output error
```

**Comment by skriesch** [comment]
I received the required information with the tool crash now. But that does not solve the sendsysrq issue with osc.

I figured out that this page ( https://crash-utility.github.io/help_pages/irq.html ) is giving the hint, that crash is using the log level 9 within "irq -d". I figured out an issue for s390x:
```
crash> irq -d
irq: -d option is not applicable to S390X architecture
```

How has osc embedded the sendsysrq commands?

**Comment by marcus-h** [comment]
On 2021-08-22 09:11:29 -0700, Sarah Julia Kriesch wrote:

<SNIP>

> How has osc embedded the sendsysrq commands?
>
osc "just" sends an API request, which eventually reaches the corresponding
worker. Then, the worker "just" calls the build script (see the sysrq_job
function in bs_worker). In case of a KVM based build, the build script writes
the sysrq to a socket (see the vm_sysrq_kvm function in the build-vm-kvm
script (which is part of the build package)).

**Comment by adrianschroeter** [comment]
It is sent via

  sendkey alt-print-$SYSRQ

to the qemu monitor console. If that does not work it is a shortcoming of qemu-kvm IMHO.

**Comment by dmach** [comment]
If I understand the previous comments correctly, there's no change needed in osc after all.
Closing, but if if you think that something related still needs a fix, let us know.
