### ISSUE TITLE
Remember buildroot location

### ISSUE THREAD

**Issue by k0da** [openSUSE/osc#94]
We need a mechanism to remember location specified buildroot locaton specified by --root option. Without that it is hard to teach osc chroot to use last used buildroot. 
(chroot option always defaults to /var/tmp/build-root)

**Comment by sebix** [comment]
For debian-builds the build-root also differs: `/var/tmp/build-root/Debian_8.0-x86_64`.

Doing `osc chroot` after a debian-build also chroots to the wrong directory

**Comment by marcus-h** [comment]
On 2016-09-15 07:20:25 -0700, Sebastian wrote:
> For debian-builds the build-root also differs: `/var/tmp/build-root/Debian_8.0-x86_64`.
> 
> Doing `osc chroot` after a debian-build also chroots to the wrong directory
> 
To which dir does it chroot to? And what's the expected dir?

**Comment by sebix** [comment]
> To which dir does it chroot to? And what's the expected dir?

I now looked again and saw that the chroot dir was correctly chosen. But what the confusion caused is that after the command I'm not at the place where the compilation has been executed. I have to manually cd into `/usr/src/packages/`.

**Comment by dmach** [comment]
I've tested this and unless I missed anything, `osc chroot` works as expected - it chroots to the build root used previously (as long as the `osc build` command didn't fail before doing anything with the chroot). Closing, but if the problem still persists, please open a new issue and provide a reproducer.
