### ISSUE TITLE
Windows compatibility

### ISSUE THREAD

**Issue by jayvdb** [openSUSE/osc#948]
Currently `osc` is incompatible with Windows due to use of [`os.sysconf`](https://docs.python.org/3/library/os.html#os.sysconf), but likely others also.  Obviously not all functionality will work, esp `osc build`, but it would be nice if a subset was supported.  I used to use osc on Mac for basic pull/push activity.

**Comment by marcus-h** [comment]
On 2021-09-01 05:35:37 -0700, John Vandenberg wrote:
> Currently `osc` is incompatible with Windows due to use of [`os.sysconf`](https://docs.python.org/3/library/os.html#os.sysconf), but likely others also.  Obviously not all functionality will work, esp `osc build`, but it would be nice if a subset was supported.  I used to use osc on Mac for basic pull/push activity.
>
PR #949 [1] fixes this particular issue.

[1] https://github.com/openSUSE/osc/pull/949
