### ISSUE TITLE
Better diagnostic for domain name issues

### ISSUE THREAD

**Issue by jengelh** [openSUSE/osc#954]
Sometimes, osc spuriously gives me this.

```
» osc getbinaries someprj x86_64
[...workworkwork...]
Failed to reach a server:
 [Errno -2] Name or service not known
```

also

```
Failed to reach a server:
 [Errno -3] Temporary failure in name resolution
```

It should also print the particular name that could not be resolved, and if osc was the one resolving, or if it's an error passed through from the remote OBS server.

**Comment by marcus-h** [comment]
On 2021-09-30 03:16:58 -0700, Jan Engelhardt wrote:
> Sometimes, osc spuriously gives me this.
>
> ```
> » osc getbinaries someprj x86_64
> [...workworkwork...]
> Failed to reach a server:
>  [Errno -2] Name or service not known
> ```

<SNIP>

> It should also print the particular name that could not be resolved, and if osc was the one resolving,
>
I just filed PR #955 ("Improve error message in case of an URLError").
The new error message looks like this:

***@***.***:~> osc ls home:Marcus_H
Failed to reach a server (api.opensuse.org):
 [Errno 111] Connection refused
***@***.***:~>

> or if it's an error passed through from the remote OBS server.

Hmm that's something we cannot "fix" from the osc side (osc just
sees status, for instance, 400 and prints the response).

**Comment by jengelh** [comment]
> Hmm that's something we cannot "fix" from the osc side (osc just sees status, for instance, 400 and prints the response).

I guess it's ok, if one knows that "[Error %d]" is for errors osc encountered, and all other errors show up as something like `HTTP/1.1 500 ...` printed to the console.
