### ISSUE TITLE
osc aggregatepac doesn't handle flavors

### ISSUE THREAD

**Issue by krop** [openSUSE/osc#956]
real life example:

`osc aggregatepac devel:tools:building cmake <destination repo>`

will aggregate the cmake package but not its flavors (cmake:full & cmake:gui)

**Comment by dmach** [comment]
Could you check if the patch from https://github.com/openSUSE/osc/pull/1009 works for you?

**Comment by krop** [comment]
If I understand correctly, flavors would have to be aggregated manually. That's not really what I'd expect.

A typical case is the cmake package:
- cmake contains the binaries
- cmake:mini contains the rpm macros
- cmake:full runs the tests
- cmake:gui contains the Qt GUI

I'd just want to run osc aggregatepac once rather than repeating it for each flavor (at least 2 are required)

**Comment by dmach** [comment]
I see. I need to check if it is possible to do more from osc, because all what osc does is that it writes `_aggregate` file and everything else is done on the server.

**Comment by dmach** [comment]
We'll merge https://github.com/openSUSE/osc/pull/1009 which partially fixes this issue.
I've opened https://github.com/openSUSE/open-build-service/issues/12300 to support all flavors server-side.

**Comment by dmach** [comment]
The osc part of the problem was partially fixed in #1009 already.
When the API changes, we can make further changes in the client.
