### ISSUE TITLE
git checkout fails on Windows

### ISSUE THREAD

**Issue by jayvdb** [openSUSE/osc#960]
The following occurs when doing a clone of this repo on Windows
```
Cloning into 'osc'...
remote: Enumerating objects: 17478, done.
remote: Counting objects: 100% (275/275), done.
remote: Compressing objects: 100% (166/166), done.
Receiving objects: 100% (17478/17478), 11.49 MiB | 1.14 MiB/s, done. 17203

Resolving deltas: 100% (11875/11875), done.
error: invalid path 'tests/prdiff_fixtures/home:user:branches:some:project/.osc/_apiurl'
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'
```

https://stackoverflow.com/questions/5991805/how-do-i-clone-files-with-colons-in-the-filename gives a good overview of this problem, which doesnt appear to be solvable with any git config.

The checkout can be made almost complete by using `git restore --staged --source=HEAD .`
Then `git status` shows

```
On branch master
Your branch is up to date with 'origin/master'.

Changes to be committed:
  (use "git restore --staged <file>..." to unstage)
        deleted:    tests/prdiff_fixtures/home:user:branches:some:project/.osc/_apiurl
        deleted:    tests/prdiff_fixtures/home:user:branches:some:project/.osc/_packages
        deleted:    tests/prdiff_fixtures/home:user:branches:some:project/.osc/_project
        deleted:    tests/prdiff_fixtures/home:user:branches:some:project/common-two
        deleted:    tests/prdiff_fixtures/home:user:branches:some:project/directory
        deleted:    tests/prdiff_fixtures/new:prj/common-two
        deleted:    tests/prdiff_fixtures/new:prj/directory
        deleted:    tests/prdiff_fixtures/old:prj/common-two
        deleted:    tests/prdiff_fixtures/old:prj/directory
        deleted:    tests/prdiff_fixtures/some:project/.osc/_apiurl
        deleted:    tests/prdiff_fixtures/some:project/.osc/_packages
        deleted:    tests/prdiff_fixtures/some:project/.osc/_project
        deleted:    tests/prdiff_fixtures/some:project/common-two
        deleted:    tests/prdiff_fixtures/some:project/directory
        deleted:    tests/update_fixtures/osctest/services/_service:exists
        deleted:    tests/update_fixtures/testUpdateServiceFilesAddDelete__service:bar
        deleted:    tests/update_fixtures/testUpdateServiceFilesAddDelete__service:foo
```

I guess it would be possible to update those tests to use `checkout_no_colon` so that the fixtures could avoid using colon.  Then specific tests without fixtures could be used to test the colon functionality on non-Windows hosts.

**Comment by marcus-h** [comment]
On 2021-10-17 15:52:36 -0700, John Vandenberg wrote:

<SNIP>

> The checkout can be made almost complete by using `git restore --staged --source=HEAD .`
> Then `git status` shows
>
> ```
> On branch master
> Your branch is up to date with 'origin/master'.
>
> Changes to be committed:
>   (use "git restore --staged <file>..." to unstage)
>         deleted:    tests/prdiff_fixtures/home:user:branches:some:project/.osc/_apiurl
>         deleted:    tests/prdiff_fixtures/home:user:branches:some:project/.osc/_packages
>         deleted:    tests/prdiff_fixtures/home:user:branches:some:project/.osc/_project
>         deleted:    tests/prdiff_fixtures/home:user:branches:some:project/common-two
>         deleted:    tests/prdiff_fixtures/home:user:branches:some:project/directory
>         deleted:    tests/prdiff_fixtures/new:prj/common-two
>         deleted:    tests/prdiff_fixtures/new:prj/directory
>         deleted:    tests/prdiff_fixtures/old:prj/common-two
>         deleted:    tests/prdiff_fixtures/old:prj/directory
>         deleted:    tests/prdiff_fixtures/some:project/.osc/_apiurl
>         deleted:    tests/prdiff_fixtures/some:project/.osc/_packages
>         deleted:    tests/prdiff_fixtures/some:project/.osc/_project
>         deleted:    tests/prdiff_fixtures/some:project/common-two
>         deleted:    tests/prdiff_fixtures/some:project/directory
>         deleted:    tests/update_fixtures/osctest/services/_service:exists
>         deleted:    tests/update_fixtures/testUpdateServiceFilesAddDelete__service:bar
>         deleted:    tests/update_fixtures/testUpdateServiceFilesAddDelete__service:foo
> ```
>
> I guess it would be possible to update those tests to use `checkout_no_colon` so that the fixtures could avoid using colon.  Then specific tests without fixtures could be used to test the colon functionality on non-Windows hosts.
>
We could "fix" all filenames except
tests/update_fixtures/osctest/services/_service:exists (that's how a service
file has to be named (as of now)). That said, there are also some testcases,
which checkout _service:xyz files. These testcases would fail on windows
(due to the colon in the filename).

**Comment by dmach** [comment]
Closing as we dropped Windows from supported operating systems (https://github.com/openSUSE/osc/pull/995)
