### ISSUE TITLE
add popt parameter to _link file example

### ISSUE THREAD

**Issue by dsamx** [openSUSE/osc#974]
Please add the popt option to the _link file example, like this:
```
<link project="..." package="...">
<patches>
  <!-- <branch /> for a full copy, default case  -->
  <!-- <apply name="patch" /> apply a patch on the source directory  -->
  <!-- <topadd>%define build_with_feature_x 1</topadd> add a line on the top (spec file only) -->
  <!-- <add name="file.patch" popt="0" /> add a patch to be applied after %setup (spec file only), the popt value is used as "patch -p<popt>" and defaults to 0 -->
  <!-- <delete name="filename" /> delete a file -->
</patches>
</link>
```

Currently it is missing and undocumented. I knew that it was there and searched the obs and osc sources for it until I found it in code.

**Comment by dmach** [comment]
I decided to use `<add name="file.patch" />` rather than `<add name="file.patch" popt="0" />` because it doesn't change the default behavior. The `popt` attribute is explained on the following lines instead.
