### ISSUE TITLE
Speed increase for high latency networks with HTTP connection-pooling (urllib3)

### ISSUE THREAD

**Issue by wfrisch** [openSUSE/osc#976]
### Summary
osc currently establishes and tears down HTTP connections for each individual operation. This imposes a performance penalty, depending on the user's network latency. It is barely noticable when you're close to the build servers, but for example users across the Atlantic will experience significant delays. We can improve this by implementing support for [HTTP persistent connections AKA keep-alive](https://en.wikipedia.org/wiki/HTTP_persistent_connection). 

### Steps to reproduce
Emulate a high latency connection as root:
`# tc qdisc add dev $iface root netem delay 150ms`

Time to checkout with the current implementation:
```
# time osc co openSUSE:Leap:15.2 ImageMagick
real    1m18.104s
```

Time to checkout with HTTP keep-alive:
```
# time osc-keepalive.git/osc-wrapper.py co openSUSE:Leap:15.2 ImageMagick
real    0m31.410s
```

Don't forget to remove the qdisc after testing ;)
`tc qdisc del dev $iface root netem delay 150ms`

### Next steps & challenges
Since openSUSE developers are widely distributed over the globe, a performance improvement of this magnitude justifies an upgrade of osc's HTTP library, in my opinion.

Unfortunately it isn't as easy as flicking a switch to enable HTTP keep-alive because osc operates on a quite low level and is intertwined with the original Python urllib. Suitable candidates for a new HTTP lib would be [urllib3](https://pypi.org/project/urllib3/) or [requests](https://docs.python-requests.org/en/latest/), which is an abstraction of urllib3. Personally I would suggest plain urllib3.

What do you think?

**Comment by wfrisch** [comment]
Here's a [branch with minimal urllib3 support added to osc](https://github.com/wfrisch/osc/tree/urllib3-minimal-test).
Please note that a lot of functionality is missing:

- Proxy support
- SSL certificate error handling (oscssl.py)
- Cookiejar support
- Test suite
- Any HTTP verbs other than GET

**Comment by dmach** [comment]
Thanks for bringing this up, we like the idea!
I've spend couple days writing code that goes beyond your prototype: https://github.com/openSUSE/osc/pull/1000
I decided to use `ConnectionPool` rather than `PoolManager` because that gives us better control over configuring connections per `apiurl`.

Let me know what do you think about my code and if you would do anything differently.
