### ISSUE TITLE
Make osc ci more robust.

### ISSUE THREAD

**Issue by aviau** [openSUSE/osc#98]
Hello!

I have a project of 23 packages. I usualy update them all at a time.

OSC CI fails often and I have to restart the whole checkin.

for example (look at the end): https://s3.amazonaws.com/archive.travis-ci.org/jobs/29921049/log.txt

I wish OSC could catch errors like this and start re-uploading the package.

**Comment by lethliel** [comment]
The attached file is not there anymore and I cannot reproduce this. I think osc ci got a lot more robust since 2014. If you still encounter problems just open a new issue. 

Thanks.
